CREATE TABLE IDS  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(180) ,
  CL_CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;

CREATE TABLE LETTCCMMNCODE (
  CODE_ID varchar(18) NOT NULL,
  CODE_ID_NM varchar(180) ,
  CODE_ID_DC varchar(600) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID)
) ;

CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID varchar(18) NOT NULL,
  CODE varchar(45) NOT NULL,
  CODE_NM varchar(180) ,
  CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE)
) ;

CREATE TABLE LETTNORGNZTINFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(60) NOT NULL,
  ORGNZT_DC varchar(300) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;

CREATE TABLE LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(180) NOT NULL,
  GROUP_CREAT_DE char(60) NOT NULL,
  GROUP_DC varchar(300) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;

CREATE TABLE LETTNAUTHORINFO (
  AUTHOR_CODE varchar(90) DEFAULT '' NOT NULL,
  AUTHOR_NM varchar(180) NOT NULL,
  AUTHOR_DC varchar(600) ,
  AUTHOR_CREAT_DE char(60) NOT NULL,
  CONSTRAINT LETTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;

CREATE TABLE LETTNROLES_HIERARCHY (
  PARNTS_ROLE varchar(90) NOT NULL,
  CHLDRN_ROLE varchar(90) NOT NULL,
  CONSTRAINT LETTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
) ;

CREATE TABLE LETTNROLEINFO (
  ROLE_CODE varchar(150) DEFAULT '' NOT NULL,
  ROLE_NM varchar(180) NOT NULL,
  ROLE_PTTRN varchar(900) ,
  ROLE_DC varchar(600) ,
  ROLE_TY varchar(240) ,
  ROLE_SORT varchar(30) ,
  ROLE_CREAT_DE char(60) NOT NULL,
  CONSTRAINT LETTNROLEINFO_PK PRIMARY KEY (ROLE_CODE)
) ;

CREATE TABLE LETTNAUTHORROLERELATE (
  AUTHOR_CODE varchar(90) NOT NULL,
  ROLE_CODE varchar(150) NOT NULL,
  CREAT_DT DATETIME ,
  CONSTRAINT LETTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
) ;

CREATE TABLE LETTNEMPLYRINFO (
  EMPLYR_ID varchar(60) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(180) NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  EMPL_NO varchar(60) ,
  IHIDNUM varchar(39) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) ,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) ,
  ZIP varchar(18) ,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  OFCPS_NM varchar(180) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(60) ,
  SBSCRB_DE DATETIME ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID)
) ;

CREATE TABLE LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(60) NOT NULL,
  MBER_TY_CODE varchar(45) ,
  AUTHOR_CODE varchar(90) NOT NULL
) ;

CREATE TABLE LETTNTMPLATINFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar(765) ,
  TMPLAT_COURS varchar(6000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;

CREATE TABLE LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(765) NOT NULL,
  BBS_INTRCN varchar(7200) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE LETTNBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID)
) ;

CREATE TABLE LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ varchar(6000) ,
  NTT_CN STRING,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(11) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(60) ,
  NTCR_NM varchar(60) ,
  PASSWORD varchar(600) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID)
) ;

CREATE TABLE LETTCZIP (
  ZIP varchar(18) NOT NULL,
  SN numeric(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar(60) ,
  SIGNGU_NM varchar(60) ,
  EMD_NM varchar(180) ,
  LI_BULD_NM varchar(180) ,
  LNBR_DONG_HO varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCZIP_PK PRIMARY KEY (ZIP,SN)
) ;

CREATE TABLE LETTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar(60) NOT NULL,
  CHANGE_DE char(20) DEFAULT '' NOT NULL,
  ORGNZT_ID char(20) ,
  GROUP_ID char(20) ,
  EMPL_NO varchar(60) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) NOT NULL,
  ZIP varchar(18) NOT NULL,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) ,
  CONSTRAINT LETTHEMPLYRCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
) ;

CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATETIME NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(60) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(30) ,
  JURIRNO varchar(39) ,
  CMPNY_NM varchar(180) NOT NULL,
  CXFC varchar(150) ,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  ENTRPRS_MIDDLE_TELNO varchar(12) ,
  FXNUM varchar(60) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(150) ,
  APPLCNT_IHIDNUM varchar(39) ,
  SBSCRB_DE DATETIME ,
  ENTRPRS_MBER_STTUS varchar(45) ,
  ENTRPRS_MBER_PASSWORD varchar(600) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(300) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(300) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(300) ,
  ENTRPRS_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  APPLCNT_EMAIL_ADRES varchar(150) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID)
) ;

CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;

CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(6000) NOT NULL,
  STRE_FILE_NM varchar(765) NOT NULL,
  ORIGNL_FILE_NM varchar(765) ,
  FILE_EXTSN varchar(60) NOT NULL,
  FILE_CN STRING,
  FILE_SIZE numeric(8,0) ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN)
) ;

CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(60) DEFAULT '' NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  PASSWORD_HINT varchar(300) ,
  PASSWORD_CNSR varchar(300) ,
  IHIDNUM varchar(39) ,
  MBER_NM varchar(150) NOT NULL,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  AREA_NO varchar(12) ,
  MBER_STTUS varchar(45) ,
  DETAIL_ADRES varchar(300) ,
  END_TELNO varchar(12) ,
  MBTLNUM varchar(60) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(60) ,
  MBER_EMAIL_ADRES varchar(150) ,
  MIDDLE_TELNO varchar(12) ,
  SBSCRB_DE DATETIME ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID)
) ;

CREATE TABLE LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(60) ,
  CONECT_IP varchar(69) ,
  CONECT_MTHD char(4) ,
  ERROR_OCCRRNC_AT char(1) ,
  ERROR_CODE char(3) ,
  CREAT_DT DATETIME ,
  CONSTRAINT LETTNLOGINLOG_PK PRIMARY KEY (LOG_ID)
) ;

CREATE TABLE LETTNLOGINPOLICY (
  EMPLYR_ID varchar(60) DEFAULT '' NOT NULL,
  IP_INFO varchar(69) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID)
) ;

CREATE TABLE LETTNPROGRMLIST (
  PROGRM_FILE_NM varchar(180) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar(300) NOT NULL,
  PROGRM_KOREAN_NM varchar(180) ,
  PROGRM_DC varchar(600) ,
  URL varchar(300) NOT NULL,
  CONSTRAINT LETTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;

CREATE TABLE LETTNMENUINFO (
  MENU_NM varchar(180) NOT NULL,
  PROGRM_FILE_NM varchar(180) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) ,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(750) ,
  RELATE_IMAGE_PATH varchar(300) ,
  RELATE_IMAGE_NM varchar(180) ,
  CONSTRAINT LETTNMENUINFO_PK PRIMARY KEY (MENU_NO)
) ;

CREATE TABLE LETTNMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(90) NOT NULL,
  MAPNG_CREAT_ID varchar(90) ,
  CONSTRAINT LETTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE)
) ;

CREATE TABLE LETTNUSERABSNCE (
  EMPLYR_ID varchar(60) DEFAULT '' NOT NULL,
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNUSERABSNCE_PK PRIMARY KEY (EMPLYR_ID)
) ;

CREATE TABLE LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(765) NOT NULL,
  METHOD_NM varchar(180) NOT NULL,
  CREAT_CO numeric(10,0) ,
  UPDT_CO numeric(10,0) ,
  RDCNT numeric(10,0) ,
  DELETE_CO numeric(10,0) ,
  OUTPT_CO numeric(10,0) ,
  ERROR_CO numeric(10,0) ,
  CONSTRAINT LETTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;

-- ============================================================
-- 테이블 및 컬럼 COMMENT (CUBRID 11.3 문법)
-- 테이블: ALTER TABLE table_name COMMENT 'comment';
-- 컬럼: ALTER TABLE table_name COMMENT ON COLUMN col1 = 'comment';
-- gov-std(2025).xlsx 공통표준단어 + eGov 표준 약어 기반
-- ============================================================

-- IDS
ALTER TABLE IDS COMMENT 'ID 시퀀스 관리';
ALTER TABLE IDS COMMENT ON COLUMN TABLE_NAME = '테이블', NEXT_ID = '다음 아이디';

-- LETTCCMMNCLCODE
ALTER TABLE LETTCCMMNCLCODE COMMENT '공통 분류코드';
ALTER TABLE LETTCCMMNCLCODE COMMENT ON COLUMN CL_CODE = '분류 코드', CL_CODE_NM = '분류 코드 명', CL_CODE_DC = '분류 코드 설명', USE_AT = '사용 여부', FRST_REGIST_PNTTM = '최초 등록 시점';
ALTER TABLE LETTCCMMNCLCODE COMMENT ON COLUMN FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점', LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTCCMMNCODE
ALTER TABLE LETTCCMMNCODE COMMENT '공통 코드';
ALTER TABLE LETTCCMMNCODE COMMENT ON COLUMN CODE_ID = '코드 아이디', CODE_ID_NM = '코드 아이디 명', CODE_ID_DC = '코드 아이디 설명', USE_AT = '사용 여부', CL_CODE = '분류 코드';
ALTER TABLE LETTCCMMNCODE COMMENT ON COLUMN FRST_REGIST_PNTTM = '최초 등록 시점', FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점', LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTCCMMNDETAILCODE
ALTER TABLE LETTCCMMNDETAILCODE COMMENT '공통 상세코드';
ALTER TABLE LETTCCMMNDETAILCODE COMMENT ON COLUMN CODE_ID = '코드 아이디', CODE = '코드', CODE_NM = '코드 명', CODE_DC = '코드 설명', USE_AT = '사용 여부';
ALTER TABLE LETTCCMMNDETAILCODE COMMENT ON COLUMN FRST_REGIST_PNTTM = '최초 등록 시점', FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점', LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTNORGNZTINFO
ALTER TABLE LETTNORGNZTINFO COMMENT '조직 정보';
ALTER TABLE LETTNORGNZTINFO COMMENT ON COLUMN ORGNZT_ID = '조직 아이디', ORGNZT_NM = '조직 명', ORGNZT_DC = '조직 설명';

-- LETTNAUTHORGROUPINFO
ALTER TABLE LETTNAUTHORGROUPINFO COMMENT '권한 그룹 정보';
ALTER TABLE LETTNAUTHORGROUPINFO COMMENT ON COLUMN GROUP_ID = '그룹 아이디', GROUP_NM = '그룹 명', GROUP_CREAT_DE = '그룹 생성 일자', GROUP_DC = '그룹 설명';

-- LETTNAUTHORINFO
ALTER TABLE LETTNAUTHORINFO COMMENT '권한 정보';
ALTER TABLE LETTNAUTHORINFO COMMENT ON COLUMN AUTHOR_CODE = '권한 코드', AUTHOR_NM = '권한 명', AUTHOR_DC = '권한 설명', AUTHOR_CREAT_DE = '권한 생성 일자';

-- LETTNROLES_HIERARCHY
ALTER TABLE LETTNROLES_HIERARCHY COMMENT '롤 계층';
ALTER TABLE LETTNROLES_HIERARCHY COMMENT ON COLUMN PARNTS_ROLE = '부모 롤', CHLDRN_ROLE = '자식 롤';

-- LETTNROLEINFO
ALTER TABLE LETTNROLEINFO COMMENT '롤 정보';
ALTER TABLE LETTNROLEINFO COMMENT ON COLUMN ROLE_CODE = '롤 코드', ROLE_NM = '롤 명', ROLE_PTTRN = '롤 패턴', ROLE_DC = '롤 설명', ROLE_TY = '롤 유형';
ALTER TABLE LETTNROLEINFO COMMENT ON COLUMN ROLE_SORT = '롤 정렬', ROLE_CREAT_DE = '롤 생성 일자';

-- LETTNAUTHORROLERELATE
ALTER TABLE LETTNAUTHORROLERELATE COMMENT '권한 롤 관계';
ALTER TABLE LETTNAUTHORROLERELATE COMMENT ON COLUMN AUTHOR_CODE = '권한 코드', ROLE_CODE = '롤 코드', CREAT_DT = '생성 일시';

-- LETTNEMPLYRINFO
ALTER TABLE LETTNEMPLYRINFO COMMENT '업무사용자 정보';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN EMPLYR_ID = '업무사용자 아이디', ORGNZT_ID = '조직 아이디', USER_NM = '사용자 명', PASSWORD = '비밀번호', EMPL_NO = '직원 번호';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN IHIDNUM = '주민등록번호', SEXDSTN_CODE = '성별 코드', BRTHDY = '생년월일', FXNUM = '팩스번호', HOUSE_ADRES = '자택 주소';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN PASSWORD_HINT = '비밀번호 힌트', PASSWORD_CNSR = '비밀번호 정답', HOUSE_END_TELNO = '자택 끝자리 전화번호', AREA_NO = '지역 번호', DETAIL_ADRES = '상세 주소';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN ZIP = '우편번호', OFFM_TELNO = '직장 전화번호', MBTLNUM = '휴대폰번호', EMAIL_ADRES = '이메일 주소', OFCPS_NM = '직위 명';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN HOUSE_MIDDLE_TELNO = '자택 중간 전화번호', GROUP_ID = '그룹 아이디', PSTINST_CODE = '소속기관 코드', EMPLYR_STTUS_CODE = '업무사용자 상태 코드', ESNTL_ID = '고유 아이디';
ALTER TABLE LETTNEMPLYRINFO COMMENT ON COLUMN CRTFC_DN_VALUE = '인증 DN 값', SBSCRB_DE = '가입 일자';

-- LETTNEMPLYRSCRTYESTBS
ALTER TABLE LETTNEMPLYRSCRTYESTBS COMMENT '업무사용자 보안 설정';
ALTER TABLE LETTNEMPLYRSCRTYESTBS COMMENT ON COLUMN SCRTY_DTRMN_TRGET_ID = '보안 결정 대상 아이디', MBER_TY_CODE = '회원 유형 코드', AUTHOR_CODE = '권한 코드';

-- LETTNTMPLATINFO
ALTER TABLE LETTNTMPLATINFO COMMENT '템플릿 정보';
ALTER TABLE LETTNTMPLATINFO COMMENT ON COLUMN TMPLAT_ID = '템플릿 아이디', TMPLAT_NM = '템플릿 명', TMPLAT_COURS = '템플릿 경로', USE_AT = '사용 여부', TMPLAT_SE_CODE = '템플릿 구분 코드';
ALTER TABLE LETTNTMPLATINFO COMMENT ON COLUMN FRST_REGISTER_ID = '최초 등록자 아이디', FRST_REGIST_PNTTM = '최초 등록 시점', LAST_UPDUSR_ID = '최종 수정자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점';

-- LETTNBBSMASTER
ALTER TABLE LETTNBBSMASTER COMMENT '게시판 마스터';
ALTER TABLE LETTNBBSMASTER COMMENT ON COLUMN BBS_ID = '게시판 아이디', BBS_NM = '게시판 명', BBS_INTRCN = '게시판 소개', BBS_TY_CODE = '게시판 유형 코드', BBS_ATTRB_CODE = '게시판 속성 코드';
ALTER TABLE LETTNBBSMASTER COMMENT ON COLUMN REPLY_POSBL_AT = '답글 가능 여부', FILE_ATCH_POSBL_AT = '파일 첨부 가능 여부', ATCH_POSBL_FILE_NUMBER = '첨부 가능 파일 수', ATCH_POSBL_FILE_SIZE = '첨부 가능 파일 크기', USE_AT = '사용 여부';
ALTER TABLE LETTNBBSMASTER COMMENT ON COLUMN TMPLAT_ID = '템플릿 아이디', FRST_REGISTER_ID = '최초 등록자 아이디', FRST_REGIST_PNTTM = '최초 등록 시점', LAST_UPDUSR_ID = '최종 수정자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점';

-- LETTNBBSUSE
ALTER TABLE LETTNBBSUSE COMMENT '게시판 사용';
ALTER TABLE LETTNBBSUSE COMMENT ON COLUMN BBS_ID = '게시판 아이디', TRGET_ID = '대상 아이디', USE_AT = '사용 여부', REGIST_SE_CODE = '등록 구분 코드', FRST_REGIST_PNTTM = '최초 등록 시점';
ALTER TABLE LETTNBBSUSE COMMENT ON COLUMN FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점', LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTNBBS
ALTER TABLE LETTNBBS COMMENT '게시판';
ALTER TABLE LETTNBBS COMMENT ON COLUMN NTT_ID = '게시물 아이디', BBS_ID = '게시판 아이디', NTT_NO = '게시물 번호', NTT_SJ = '게시물 제목', NTT_CN = '게시물 내용';
ALTER TABLE LETTNBBS COMMENT ON COLUMN ANSWER_AT = '답변 여부', PARNTSCTT_NO = '부모글 번호', ANSWER_LC = '답변 레벨', SORT_ORDR = '정렬 순서', RDCNT = '조회수';
ALTER TABLE LETTNBBS COMMENT ON COLUMN USE_AT = '사용 여부', NTCE_BGNDE = '공지 시작일', NTCE_ENDDE = '공지 종료일', NTCR_ID = '게시자 아이디', NTCR_NM = '게시자 명';
ALTER TABLE LETTNBBS COMMENT ON COLUMN PASSWORD = '비밀번호', ATCH_FILE_ID = '첨부 파일 아이디', FRST_REGIST_PNTTM = '최초 등록 시점', FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점';
ALTER TABLE LETTNBBS COMMENT ON COLUMN LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTCZIP
ALTER TABLE LETTCZIP COMMENT '우편번호';
ALTER TABLE LETTCZIP COMMENT ON COLUMN ZIP = '우편번호', SN = '순번', CTPRVN_NM = '시도 명', SIGNGU_NM = '시군구 명', EMD_NM = '읍면동 명';
ALTER TABLE LETTCZIP COMMENT ON COLUMN LI_BULD_NM = '리 건물 명', LNBR_DONG_HO = '번지 동 호', FRST_REGIST_PNTTM = '최초 등록 시점', FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점';
ALTER TABLE LETTCZIP COMMENT ON COLUMN LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTHEMPLYRINFOCHANGEDTLS
ALTER TABLE LETTHEMPLYRINFOCHANGEDTLS COMMENT '업무사용자 정보 변경 내역';
ALTER TABLE LETTHEMPLYRINFOCHANGEDTLS COMMENT ON COLUMN EMPLYR_ID = '업무사용자 아이디', CHANGE_DE = '변경 일자', ORGNZT_ID = '조직 아이디', GROUP_ID = '그룹 아이디', EMPL_NO = '직원 번호';
ALTER TABLE LETTHEMPLYRINFOCHANGEDTLS COMMENT ON COLUMN SEXDSTN_CODE = '성별 코드', BRTHDY = '생년월일', FXNUM = '팩스번호', HOUSE_ADRES = '자택 주소', HOUSE_END_TELNO = '자택 끝자리 전화번호';
ALTER TABLE LETTHEMPLYRINFOCHANGEDTLS COMMENT ON COLUMN AREA_NO = '지역 번호', DETAIL_ADRES = '상세 주소', ZIP = '우편번호', OFFM_TELNO = '직장 전화번호', MBTLNUM = '휴대폰번호';
ALTER TABLE LETTHEMPLYRINFOCHANGEDTLS COMMENT ON COLUMN EMAIL_ADRES = '이메일 주소', HOUSE_MIDDLE_TELNO = '자택 중간 전화번호', PSTINST_CODE = '소속기관 코드', EMPLYR_STTUS_CODE = '업무사용자 상태 코드', ESNTL_ID = '고유 아이디';

-- LETTNBBSMASTEROPTN
ALTER TABLE LETTNBBSMASTEROPTN COMMENT '게시판 마스터 옵션';
ALTER TABLE LETTNBBSMASTEROPTN COMMENT ON COLUMN BBS_ID = '게시판 아이디', ANSWER_AT = '답변 여부', STSFDG_AT = '만족도 여부', FRST_REGIST_PNTTM = '최초 등록 시점', LAST_UPDT_PNTTM = '최종 수정 시점';
ALTER TABLE LETTNBBSMASTEROPTN COMMENT ON COLUMN FRST_REGISTER_ID = '최초 등록자 아이디', LAST_UPDUSR_ID = '최종 수정자 아이디';

-- LETTNENTRPRSMBER
ALTER TABLE LETTNENTRPRSMBER COMMENT '기업 회원';
ALTER TABLE LETTNENTRPRSMBER COMMENT ON COLUMN ENTRPRS_MBER_ID = '기업 회원 아이디', ENTRPRS_SE_CODE = '기업 구분 코드', BIZRNO = '사업자등록번호', JURIRNO = '법인등록번호', CMPNY_NM = '회사 명';
ALTER TABLE LETTNENTRPRSMBER COMMENT ON COLUMN CXFC = '대표자', ZIP = '우편번호', ADRES = '주소', ENTRPRS_MIDDLE_TELNO = '기업 중간 전화번호', FXNUM = '팩스번호';
ALTER TABLE LETTNENTRPRSMBER COMMENT ON COLUMN INDUTY_CODE = '업종 코드', APPLCNT_NM = '신청자 명', APPLCNT_IHIDNUM = '신청자 주민등록번호', SBSCRB_DE = '가입 일자', ENTRPRS_MBER_STTUS = '기업 회원 상태';
ALTER TABLE LETTNENTRPRSMBER COMMENT ON COLUMN ENTRPRS_MBER_PASSWORD = '기업 회원 비밀번호', ENTRPRS_MBER_PASSWORD_HINT = '기업 회원 비밀번호 힌트', ENTRPRS_MBER_PASSWORD_CNSR = '기업 회원 비밀번호 정답', GROUP_ID = '그룹 아이디', DETAIL_ADRES = '상세 주소';
ALTER TABLE LETTNENTRPRSMBER COMMENT ON COLUMN ENTRPRS_END_TELNO = '기업 끝자리 전화번호', AREA_NO = '지역 번호', APPLCNT_EMAIL_ADRES = '신청자 이메일 주소', ESNTL_ID = '고유 아이디';

-- LETTNFILE
ALTER TABLE LETTNFILE COMMENT '파일';
ALTER TABLE LETTNFILE COMMENT ON COLUMN ATCH_FILE_ID = '첨부 파일 아이디', CREAT_DT = '생성 일시', USE_AT = '사용 여부';

-- LETTNFILEDETAIL
ALTER TABLE LETTNFILEDETAIL COMMENT '파일 상세';
ALTER TABLE LETTNFILEDETAIL COMMENT ON COLUMN ATCH_FILE_ID = '첨부 파일 아이디', FILE_SN = '파일 순번', FILE_STRE_COURS = '파일 저장 경로', STRE_FILE_NM = '저장 파일 명', ORIGNL_FILE_NM = '원본 파일 명';
ALTER TABLE LETTNFILEDETAIL COMMENT ON COLUMN FILE_EXTSN = '파일 확장자', FILE_CN = '파일 내용', FILE_SIZE = '파일 크기';

-- LETTNGNRLMBER
ALTER TABLE LETTNGNRLMBER COMMENT '일반 회원';
ALTER TABLE LETTNGNRLMBER COMMENT ON COLUMN MBER_ID = '회원 아이디', PASSWORD = '비밀번호', PASSWORD_HINT = '비밀번호 힌트', PASSWORD_CNSR = '비밀번호 정답', IHIDNUM = '주민등록번호';
ALTER TABLE LETTNGNRLMBER COMMENT ON COLUMN MBER_NM = '회원 명', ZIP = '우편번호', ADRES = '주소', AREA_NO = '지역 번호', MBER_STTUS = '회원 상태';
ALTER TABLE LETTNGNRLMBER COMMENT ON COLUMN DETAIL_ADRES = '상세 주소', END_TELNO = '끝자리 전화번호', MBTLNUM = '휴대폰번호', GROUP_ID = '그룹 아이디', MBER_FXNUM = '회원 팩스번호';
ALTER TABLE LETTNGNRLMBER COMMENT ON COLUMN MBER_EMAIL_ADRES = '회원 이메일 주소', MIDDLE_TELNO = '중간 전화번호', SBSCRB_DE = '가입 일자', SEXDSTN_CODE = '성별 코드', ESNTL_ID = '고유 아이디';

-- LETTNLOGINLOG
ALTER TABLE LETTNLOGINLOG COMMENT '로그인 로그';
ALTER TABLE LETTNLOGINLOG COMMENT ON COLUMN LOG_ID = '로그 아이디', CONECT_ID = '접속 아이디', CONECT_IP = '접속 IP', CONECT_MTHD = '접속 방법', ERROR_OCCRRNC_AT = '오류 발생 여부';
ALTER TABLE LETTNLOGINLOG COMMENT ON COLUMN ERROR_CODE = '오류 코드', CREAT_DT = '생성 일시';

-- LETTNLOGINPOLICY
ALTER TABLE LETTNLOGINPOLICY COMMENT '로그인 정책';
ALTER TABLE LETTNLOGINPOLICY COMMENT ON COLUMN EMPLYR_ID = '업무사용자 아이디', IP_INFO = 'IP 정보', DPLCT_PERM_AT = '중복 허용 여부', LMTT_AT = '제한 여부', FRST_REGISTER_ID = '최초 등록자 아이디';
ALTER TABLE LETTNLOGINPOLICY COMMENT ON COLUMN FRST_REGIST_PNTTM = '최초 등록 시점', LAST_UPDUSR_ID = '최종 수정자 아이디', LAST_UPDT_PNTTM = '최종 수정 시점';

-- LETTNPROGRMLIST
ALTER TABLE LETTNPROGRMLIST COMMENT '프로그램 목록';
ALTER TABLE LETTNPROGRMLIST COMMENT ON COLUMN PROGRM_FILE_NM = '프로그램 파일 명', PROGRM_STRE_PATH = '프로그램 저장 경로', PROGRM_KOREAN_NM = '프로그램 한글 명', PROGRM_DC = '프로그램 설명', URL = 'URL';

-- LETTNMENUINFO
ALTER TABLE LETTNMENUINFO COMMENT '메뉴 정보';
ALTER TABLE LETTNMENUINFO COMMENT ON COLUMN MENU_NM = '메뉴 명', PROGRM_FILE_NM = '프로그램 파일 명', MENU_NO = '메뉴 번호', UPPER_MENU_NO = '상위 메뉴 번호', MENU_ORDR = '메뉴 순서';
ALTER TABLE LETTNMENUINFO COMMENT ON COLUMN MENU_DC = '메뉴 설명', RELATE_IMAGE_PATH = '관계 이미지 경로', RELATE_IMAGE_NM = '관계 이미지 명';

-- LETTNMENUCREATDTLS
ALTER TABLE LETTNMENUCREATDTLS COMMENT '메뉴 생성 내역';
ALTER TABLE LETTNMENUCREATDTLS COMMENT ON COLUMN MENU_NO = '메뉴 번호', AUTHOR_CODE = '권한 코드', MAPNG_CREAT_ID = '매핑 생성 아이디';

-- LETTNUSERABSNCE
ALTER TABLE LETTNUSERABSNCE COMMENT '사용자 부재';
ALTER TABLE LETTNUSERABSNCE COMMENT ON COLUMN EMPLYR_ID = '업무사용자 아이디', USER_ABSNCE_AT = '사용자 부재 여부', FRST_REGISTER_ID = '최초 등록자 아이디', FRST_REGIST_PNTTM = '최초 등록 시점', LAST_UPDUSR_ID = '최종 수정자 아이디';
ALTER TABLE LETTNUSERABSNCE COMMENT ON COLUMN LAST_UPDT_PNTTM = '최종 수정 시점';

-- LETTSSYSLOGSUMMARY
ALTER TABLE LETTSSYSLOGSUMMARY COMMENT '시스템 로그 요약';
ALTER TABLE LETTSSYSLOGSUMMARY COMMENT ON COLUMN OCCRRNC_DE = '발생 일자', SRVC_NM = '서비스 명', METHOD_NM = '메소드 명', CREAT_CO = '생성 건수', UPDT_CO = '수정 건수';
ALTER TABLE LETTSSYSLOGSUMMARY COMMENT ON COLUMN RDCNT = '조회수', DELETE_CO = '삭제 건수', OUTPT_CO = '출력 건수', ERROR_CO = '오류 건수';
