SELECT m.MENU_NM, m.PROGRM_FILE_NM as MENU_PROGRM, p.PROGRM_FILE_NM as LIST_PROGRM, p.URL 
FROM NMENUINFO m 
LEFT JOIN NPROGRMLIST p ON m.PROGRM_FILE_NM = p.PROGRM_FILE_NM 
WHERE m.MENU_NO > 0 
ORDER BY m.MENU_NO
LIMIT 50;
