CREATE SCHEMA IF NOT EXISTS ebt AUTHORIZATION egov;
SET search_path TO ebt;

CREATE TABLE IF NOT EXISTS IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID numeric(30,0) NOT NULL,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS CCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60),
  CL_CODE_DC varchar(200),
  USE_AT char(1),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT CCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
);

CREATE TABLE IF NOT EXISTS CCMMNCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE_ID_NM varchar(60),
  CODE_ID_DC varchar(200),
  USE_AT char(1),
  CL_CODE char(3),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT CCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT CCMMNCODE_FK1 FOREIGN KEY (CL_CODE) REFERENCES CCMMNCLCODE (CL_CODE)
);

CREATE TABLE IF NOT EXISTS CCMMNDETAILCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE varchar(15) NOT NULL,
  CODE_NM varchar(60),
  CODE_DC varchar(200),
  USE_AT char(1),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT CCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT CCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES CCMMNCODE (CODE_ID)
);

CREATE TABLE IF NOT EXISTS NORGNZTINFO (
  ORGNZT_ID char(20) NOT NULL,
  ORGNZT_NM varchar(20) NOT NULL,
  ORGNZT_DC varchar(100),
  CONSTRAINT NORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
);

CREATE TABLE IF NOT EXISTS NAUTHORGROUPINFO (
  GROUP_ID char(20) NOT NULL,
  GROUP_NM varchar(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar(100),
  CONSTRAINT NAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
);

CREATE TABLE IF NOT EXISTS NAUTHORINFO (
  AUTHOR_CODE varchar(30) NOT NULL,
  AUTHOR_NM varchar(60) NOT NULL,
  AUTHOR_DC varchar(200),
  AUTHOR_CREAT_DE char(20) NOT NULL,
  CONSTRAINT NAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
);

CREATE TABLE IF NOT EXISTS NROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  CONSTRAINT NROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT NROLES_HIERARCHY_FK1 FOREIGN KEY (PARNTS_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT NROLES_HIERARCHY_FK2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE)
);

CREATE TABLE IF NOT EXISTS NROLEINFO (
  ROLE_CODE varchar(50) NOT NULL,
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300),
  ROLE_DC varchar(200),
  ROLE_TY varchar(80),
  ROLE_SORT varchar(10),
  ROLE_CREAT_DE char(20) NOT NULL,
  CONSTRAINT NROLEINFO_PK PRIMARY KEY (ROLE_CODE)
);

CREATE TABLE IF NOT EXISTS NAUTHORROLERELATE (
  AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT timestamp,
  CONSTRAINT NAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT NAUTHORROLERELATE_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT NAUTHORROLERELATE_FK2 FOREIGN KEY (ROLE_CODE) REFERENCES NROLEINFO (ROLE_CODE)
);

CREATE TABLE IF NOT EXISTS NEMPLYRINFO (
  EMPLYR_ID varchar(20) NOT NULL,
  ORGNZT_ID char(20),
  USER_NM varchar(60) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  EMPL_NO varchar(20),
  IHIDNUM varchar(200),
  SEXDSTN_CODE char(1),
  BRTHDY char(20),
  FXNUM varchar(20),
  HOUSE_ADRES varchar(100),
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  HOUSE_END_TELNO varchar(4),
  AREA_NO varchar(4),
  DETAIL_ADRES varchar(100),
  ZIP varchar(6),
  OFFM_TELNO varchar(20),
  MBTLNUM varchar(20),
  EMAIL_ADRES varchar(50),
  OFCPS_NM varchar(60),
  HOUSE_MIDDLE_TELNO varchar(4),
  GROUP_ID char(20),
  PSTINST_CODE char(8),
  EMPLYR_STTUS_CODE char(1) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(100),
  SBSCRB_DE timestamp,
  LOCK_AT char(1),
  LOCK_CNT numeric(3,0),
  LOCK_LAST_PNTTM timestamp,
  CHG_PWD_LAST_PNTTM timestamp,
  CONSTRAINT NEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT NEMPLYRINFO_FK1 FOREIGN KEY (ORGNZT_ID) REFERENCES NORGNZTINFO (ORGNZT_ID),
  CONSTRAINT NEMPLYRINFO_FK2 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID)
);

CREATE TABLE IF NOT EXISTS NEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(20) NOT NULL,
  MBER_TY_CODE char(5),
  AUTHOR_CODE varchar(30) NOT NULL,
  CONSTRAINT NEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT NEMPLYRSCRTYESTBS_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE)
);

CREATE TABLE IF NOT EXISTS NTMPLATINFO (
  TMPLAT_ID char(20) NOT NULL,
  TMPLAT_NM varchar(255),
  TMPLAT_COURS varchar(255),
  USE_AT char(1),
  TMPLAT_SE_CODE char(6),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT NTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
);

CREATE TABLE IF NOT EXISTS NBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_INTRCN varchar(2400),
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1),
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0),
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20),
  FRST_REGISTER_ID varchar(20) NOT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  LAST_UPDUSR_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  BLOG_ID char(20),
  BLOG_AT char(2),
  CONSTRAINT NBBSMASTER_PK PRIMARY KEY (BBS_ID),
  CONSTRAINT NBBSMASTER_FK1 FOREIGN KEY (TMPLAT_ID) REFERENCES NTMPLATINFO (TMPLAT_ID)
);

CREATE TABLE IF NOT EXISTS NBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) NOT NULL DEFAULT '',
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT NBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT NBBSUSE_FK1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
);

CREATE TABLE IF NOT EXISTS NBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0),
  NTT_SJ varchar(2000),
  NTT_CN text,
  ANSWER_AT char(1),
  PARNTSCTT_NO numeric(10,0),
  ANSWER_LC numeric(8),
  SORT_ORDR numeric(8),
  RDCNT numeric(10,0),
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20),
  NTCE_ENDDE char(20),
  NTCR_ID varchar(20),
  NTCR_NM varchar(20),
  PASSWORD varchar(200),
  ATCH_FILE_ID char(20),
  NOTICE_AT char(1),
  SJ_BOLD_AT char(1),
  SECRET_AT char(1),
  FRST_REGIST_PNTTM timestamp NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  BLOG_ID char(20),
  CONSTRAINT NBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT NBBS_FK1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
);

CREATE TABLE IF NOT EXISTS CZIP (
  ZIP varchar(6) NOT NULL,
  SN numeric(10,0) NOT NULL,
  CTPRVN_NM varchar(20),
  SIGNGU_NM varchar(20),
  EMD_NM varchar(60),
  LI_BULD_NM varchar(60),
  LNBR_DONG_HO varchar(20),
  FRST_REGIST_PNTTM timestamp,
  FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT CZIP_PK PRIMARY KEY (ZIP,SN)
);

CREATE TABLE IF NOT EXISTS HEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar(20) NOT NULL,
  CHANGE_DE char(20) NOT NULL,
  ORGNZT_ID char(20),
  GROUP_ID char(20),
  EMPL_NO varchar(20),
  SEXDSTN_CODE char(1),
  BRTHDY char(20),
  FXNUM varchar(20),
  HOUSE_ADRES varchar(100),
  HOUSE_END_TELNO varchar(4),
  AREA_NO varchar(4),
  DETAIL_ADRES varchar(100),
  ZIP varchar(6),
  OFFM_TELNO varchar(20),
  MBTNUM varchar(20),
  EMAIL_ADRES varchar(50),
  HOUSE_MIDDLE_TELNO varchar(4),
  PSTINST_CODE char(8),
  EMPLYR_STTUS_CODE char(1),
  ESNTL_ID char(20),
  CHANGE_DE_BEGIN char(20),
  CHANGE_DE_END char(20),
  CONSTRAINT HEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE),
  CONSTRAINT HEMPLYRINFOCHANGEDTLS_FK1 FOREIGN KEY (EMPLYR_ID) REFERENCES NEMPLYRINFO (EMPLYR_ID)
);

CREATE TABLE IF NOT EXISTS NBBSMASTEROPTN (
  BBS_ID char(20) NOT NULL,
  ANSWER_AT char(1) NOT NULL,
  STSFDG_AT char(1) NOT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  CONSTRAINT NBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
);

CREATE TABLE IF NOT EXISTS NENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL,
  ENTRPRS_SE_CODE char(15),
  BIZRNO varchar(10),
  JURIRNO varchar(13),
  CMPNY_NM varchar(60) NOT NULL,
  CXFC varchar(50),
  ZIP varchar(6),
  ADRES varchar(100),
  ENTRPRS_MIDDLE_TELNO varchar(4),
  FXNUM varchar(20),
  INDUTY_CODE char(15),
  APPLCNT_NM varchar(50) NOT NULL,
  APPLCNT_IHIDNUM varchar(200),
  SBSCRB_DE timestamp,
  ENTRPRS_MBER_STTUS varchar(15),
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL,
  GROUP_ID char(20),
  DETAIL_ADRES varchar(100),
  ENTRPRS_END_TELNO varchar(4),
  AREA_NO varchar(4),
  APPLCNT_EMAIL_ADRES varchar(50),
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(100),
  LOCK_AT char(1),
  LOCK_CNT numeric(3,0),
  LOCK_LAST_PNTTM timestamp,
  CHG_PWD_LAST_PNTTM timestamp,
  CONSTRAINT NENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT NENTRPRSMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID)
);

CREATE TABLE IF NOT EXISTS NFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT timestamp NOT NULL,
  USE_AT char(1),
  CONSTRAINT NFILE_PK PRIMARY KEY (ATCH_FILE_ID)
);

CREATE TABLE IF NOT EXISTS NFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255),
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE numeric(8,0),
  CONSTRAINT NFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT NFILEDETAIL_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES NFILE (ATCH_FILE_ID)
);

CREATE TABLE IF NOT EXISTS NGNRLMBER (
  MBER_ID varchar(20) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  IHIDNUM varchar(200),
  MBER_NM varchar(50) NOT NULL,
  ZIP varchar(6),
  ADRES varchar(100),
  AREA_NO varchar(4),
  MBER_STTUS varchar(15),
  DETAIL_ADRES varchar(100),
  END_TELNO varchar(4),
  MBTNUM varchar(20),
  GROUP_ID char(20),
  MBER_FXNUM varchar(20),
  MBER_EMAIL_ADRES varchar(50),
  MIDDLE_TELNO varchar(4),
  SBSCRB_DE timestamp,
  SEXDSTN_CODE char(1),
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(100),
  LOCK_AT char(1),
  LOCK_CNT numeric(3,0),
  LOCK_LAST_PNTTM timestamp,
  CHG_PWD_LAST_PNTTM timestamp,
  CONSTRAINT NGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT NGNRLMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID)
);

CREATE TABLE IF NOT EXISTS NLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20),
  CONECT_IP varchar(23),
  CONECT_MTHD char(4),
  ERROR_OCCRRNC_AT char(1),
  ERROR_CODE char(3),
  CREAT_DT timestamp,
  CONSTRAINT NLOGINLOG_PK PRIMARY KEY (LOG_ID)
);

CREATE TABLE IF NOT EXISTS NLOGINPOLICY (
  EMPLYR_ID varchar(20) NOT NULL,
  IP_INFO varchar(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20),
  FRST_REGIST_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  CONSTRAINT NLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID)
);

CREATE TABLE IF NOT EXISTS NPROGRMLIST (
  PROGRM_FILE_NM varchar(60) NOT NULL,
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60),
  PROGRM_DC varchar(200),
  URL varchar(100) NOT NULL,
  CONSTRAINT NPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
);

CREATE TABLE IF NOT EXISTS NMENUINFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0),
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(250),
  RELATE_IMAGE_PATH varchar(100),
  RELATE_IMAGE_NM varchar(60),
  CONSTRAINT NMENUINFO_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT NMENUINFO_FK2 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES NPROGRMLIST (PROGRM_FILE_NM),
  CONSTRAINT NMENUINFO_FK1 FOREIGN KEY (UPPER_MENU_NO) REFERENCES NMENUINFO (MENU_NO)
);

CREATE TABLE IF NOT EXISTS NMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30),
  CONSTRAINT NMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT NMENUCREATDTLS_FK2 FOREIGN KEY (MENU_NO) REFERENCES NMENUINFO (MENU_NO),
  CONSTRAINT NMENUCREATDTLS_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE)
);

CREATE TABLE IF NOT EXISTS NUSERABSNCE (
  EMPLYR_ID varchar(20) NOT NULL,
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20),
  FRST_REGIST_PNTTM timestamp,
  LAST_UPDUSR_ID varchar(20),
  LAST_UPDT_PNTTM timestamp,
  CONSTRAINT NUSERABSNCE_PK PRIMARY KEY (EMPLYR_ID)
);

CREATE TABLE IF NOT EXISTS SSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO numeric(10,0),
  UPDT_CO numeric(10,0),
  RDCNT numeric(10,0),
  DELETE_CO numeric(10,0),
  OUTPT_CO numeric(10,0),
  ERROR_CO numeric(10,0),
  CONSTRAINT SSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
);

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) AS 
    SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,'','GNR' AS USER_SE, ' '
    FROM NGNRLMBER
    UNION ALL
    SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,'','ENT' AS USER_SE, ' '
    FROM NENTRPRSMBER
    UNION ALL
    SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID,'USR' AS USER_SE, ORGNZT_ID
    FROM NEMPLYRINFO;
