-- [DDL Patch] ID Sequence 테이블 명칭 통일 (COMTECOPSEQ -> ECOPSEQ)
-- 기존에 COMTECOPSEQ가 있을 경우 삭제 후 생성하거나, ECOPSEQ가 없는 경우 생성합니다.

DROP TABLE IF EXISTS ECOPSEQ;

CREATE TABLE ECOPSEQ (
    TABLE_NAME VARCHAR(20) NOT NULL,
    NEXT_ID NUMERIC(30) NULL,
    PRIMARY KEY (TABLE_NAME)
);

COMMENT ON TABLE ECOPSEQ IS 'ID 생성 시퀀스 테이블';
COMMENT ON COLUMN ECOPSEQ.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN ECOPSEQ.NEXT_ID IS '다음 ID';
