-- [DML Patch] 메인 페이지 데이터 노출 및 ID 시퀀스 초기화

-- 1. ID 시퀀스 초기 데이터 (게시판 관련)
INSERT INTO ECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBSID', 1);
INSERT INTO ECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('NTTID', 100);

-- 2. 게시판 마스터 정보 (메인 페이지 연동용 고정 ID)
-- 공지사항 (BBSMSTR_AAAAAAAAAAAA)
INSERT INTO NBBSMASTER (BBS_ID, BBS_NM, BBS_INTRCN, BBS_TY_CODE, REPLY_POSBL_AT, FILE_ATCH_POSBL_AT, ATCH_POSBL_FILE_NUMBER, USE_AT, FRST_REGIST_PNTTM)
VALUES ('BBSMSTR_AAAAAAAAAAAA', '공지사항', '시스템 공지사항 게시판입니다.', 'BBST01', 'N', 'Y', 3, 'Y', NOW());

-- 업무게시판 (BBSMSTR_CCCCCCCCCCCC)
INSERT INTO NBBSMASTER (BBS_ID, BBS_NM, BBS_INTRCN, BBS_TY_CODE, REPLY_POSBL_AT, FILE_ATCH_POSBL_AT, ATCH_POSBL_FILE_NUMBER, USE_AT, FRST_REGIST_PNTTM)
VALUES ('BBSMSTR_CCCCCCCCCCCC', '오늘의 할일', '개인별 업무 할일 게시판입니다.', 'BBST01', 'N', 'Y', 3, 'Y', NOW());

-- 3. 샘플 게시물 데이터 (날짜 형식 yyyyMMdd 준수)
-- 공지사항 샘플
INSERT INTO NBBS (NTT_ID, BBS_ID, NTT_SJ, NTT_CN, ANSWER_AT, PARNTSCTT_NO, ANSWER_LC, SORT_ORDR, RDCNT, USE_AT, NTCE_BGNDE, NTCE_ENDDE, NTCR_ID, NTCR_NM, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
VALUES (1, 'BBSMSTR_AAAAAAAAAAAA', '표준프레임워크 경량환경 오픈', '경량환경 게시판 서비스가 시작되었습니다.', 'N', 0, 0, 1, 0, 'Y', '20250101', '20261231', 'USRCNFRM_00000000001', '관리자', NOW(), 'USRCNFRM_00000000001');

-- 업무게시판 샘플
INSERT INTO NBBS (NTT_ID, BBS_ID, NTT_SJ, NTT_CN, ANSWER_AT, PARNTSCTT_NO, ANSWER_LC, SORT_ORDR, RDCNT, USE_AT, NTCE_BGNDE, NTCE_ENDDE, NTCR_ID, NTCR_NM, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
VALUES (2, 'BBSMSTR_CCCCCCCCCCCC', '메인 페이지 데이터 연동 테스트', '데이터가 정상적으로 출력되는지 확인 중입니다.', 'N', 0, 0, 1, 0, 'Y', '20250101', '20261231', 'USRCNFRM_00000000001', '관리자', NOW(), 'USRCNFRM_00000000001');
