# Testcontainers Configuration
# https://www.testcontainers.org/features/configuration/

# Docker daemon configuration
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy

# For Windows with Docker Desktop
# docker.host=npipe:////./pipe/docker_engine

# Disable remote Docker API
docker.remote-api.enabled=false
