package nuri.migration.adapter;

import nuri.migration.discovery.CatalogObject;
import nuri.migration.discovery.CatalogSnapshot;
import nuri.migration.discovery.DiscoveryRequest;
import nuri.migration.discovery.ObjectKind;
import nuri.migration.discovery.VisibilityStatus;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcMetadataSourceAdapterTest {

    @Test
    void discoversPortableObjectsWithoutWritingToTheSource() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:discovery;DB_CLOSE_DELAY=-1", "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA LEGACY");
            statement.execute("CREATE TABLE LEGACY.PARENT ("
                    + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY, "
                    + "CODE VARCHAR(20) NOT NULL, "
                    + "STATE VARCHAR(1) DEFAULT 'A', "
                    + "CONSTRAINT PK_PARENT PRIMARY KEY (ID), "
                    + "CONSTRAINT UK_PARENT_CODE UNIQUE (CODE))");
            statement.execute("CREATE TABLE LEGACY.CHILD ("
                    + "ID BIGINT, "
                    + "PARENT_ID BIGINT NOT NULL, "
                    + "CONSTRAINT PK_CHILD PRIMARY KEY (ID), "
                    + "CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID) REFERENCES LEGACY.PARENT(ID))");
            statement.execute("CREATE INDEX IX_CHILD_PARENT ON LEGACY.CHILD(PARENT_ID)");
            statement.execute("CREATE VIEW LEGACY.V_PARENT AS SELECT ID, CODE FROM LEGACY.PARENT");

            CatalogSnapshot snapshot = new JdbcMetadataSourceAdapter().discover(
                    connection,
                    DiscoveryRequest.forSchemas(Set.of("LEGACY")));

            assertThat(snapshot.database().productName()).containsIgnoringCase("H2");
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.TABLE, "LEGACY", "PARENT"));
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.VIEW, "LEGACY", "V_PARENT"));
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.PRIMARY_KEY, "LEGACY", "PK_PARENT"));
            assertThat(snapshot.objects())
                    .filteredOn(object -> object.kind() == ObjectKind.UNIQUE_KEY)
                    .anySatisfy(object -> {
                        assertThat(object.schema()).isEqualTo("LEGACY");
                        assertThat(object.attributes()).containsEntry("parentTable", "PARENT");
                        assertThat(object.attributes().get("columns")).contains("CODE");
                    });
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.FOREIGN_KEY, "LEGACY", "FK_CHILD_PARENT"));
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.INDEX, "LEGACY", "IX_CHILD_PARENT"));
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.IDENTITY, "LEGACY", "PARENT.ID"));
            assertThat(snapshot.objects()).anySatisfy(object -> assertObject(
                    object, ObjectKind.DEFAULT_CONSTRAINT, "LEGACY", "PARENT.STATE"));

            assertThat(snapshot.visibilityFindings()).anySatisfy(finding -> {
                assertThat(finding.status()).isEqualTo(VisibilityStatus.UNSUPPORTED);
                assertThat(finding.objectKind()).isEqualTo(ObjectKind.TRIGGER);
            });
        }
    }

    private static void assertObject(
            CatalogObject object,
            ObjectKind kind,
            String schema,
            String name) {
        assertThat(object.kind()).isEqualTo(kind);
        assertThat(object.schema()).isEqualTo(schema);
        assertThat(object.name()).isEqualTo(name);
    }
}
