plugins {
    id 'java-library'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}
 
repositories {
    mavenCentral()
}

// Gradle 5+ 표준 생성 소스 경로를 사용하여 IDE 클래스 중복 오류를 방지합니다.

dependencies {
    api project(':foundation')
    testImplementation testFixtures(project(':foundation'))

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.boot:spring-boot-starter-mail'
    
    // Domain & JPA & QueryDSL
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:5.1.0:jakarta"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"

    // API Docs / MapStruct
    api 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.27'
    api 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'com.h2database:h2'
    testImplementation testFixtures(project(':foundation'))
}

bootJar { enabled = false }
jar { enabled = true }

test {
    useJUnitPlatform()
    exclude '**/ArchitectureTest.class'
}
