CREATE SCHEMA IF NOT EXISTS ebt AUTHORIZATION postgres;

SET search_path TO ebt;

-- IDS
CREATE TABLE IF NOT EXISTS IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID numeric(30,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (TABLE_NAME)
);

-- CCMMNCLCODE
CREATE TABLE IF NOT EXISTS CCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60) DEFAULT NULL,
  CL_CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CL_CODE)
);

-- CCMMNCODE
CREATE TABLE IF NOT EXISTS CCMMNCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE_ID_NM varchar(60) DEFAULT NULL,
  CODE_ID_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  CL_CODE char(3) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID),
  CONSTRAINT CCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES CCMMNCLCODE (CL_CODE)
);
CREATE INDEX IF NOT EXISTS idx_ccmmncode_cl_code ON CCMMNCODE (CL_CODE);

-- CCMMNDETAILCODE
CREATE TABLE IF NOT EXISTS CCMMNDETAILCODE (
  CODE_ID varchar(6) NOT NULL,
  CODE varchar(15) NOT NULL,
  CODE_NM varchar(60) DEFAULT NULL,
  CODE_DC varchar(200) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT CCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES CCMMNCODE (CODE_ID)
);

-- NORGNZTINFO
CREATE TABLE IF NOT EXISTS NORGNZTINFO (
  ORGNZT_ID char(20) NOT NULL DEFAULT '',
  ORGNZT_NM varchar(20) NOT NULL,
  ORGNZT_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (ORGNZT_ID)
);

-- NAUTHORGROUPINFO
CREATE TABLE IF NOT EXISTS NAUTHORGROUPINFO (
  GROUP_ID char(20) NOT NULL DEFAULT '',
  GROUP_NM varchar(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
);

-- NAUTHORINFO
CREATE TABLE IF NOT EXISTS NAUTHORINFO (
  AUTHOR_CODE varchar(30) NOT NULL DEFAULT '',
  AUTHOR_NM varchar(60) NOT NULL,
  AUTHOR_DC varchar(200) DEFAULT NULL,
  AUTHOR_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (AUTHOR_CODE)
);

-- NROLES_HIERARCHY
CREATE TABLE IF NOT EXISTS NROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT NROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT NROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nroles_hierarchy_child ON NROLES_HIERARCHY (CHLDRN_ROLE);

-- NROLEINFO
CREATE TABLE IF NOT EXISTS NROLEINFO (
  ROLE_CODE varchar(50) NOT NULL DEFAULT '',
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300) DEFAULT NULL,
  ROLE_DC varchar(200) DEFAULT NULL,
  ROLE_TY varchar(80) DEFAULT NULL,
  ROLE_SORT varchar(10) DEFAULT NULL,
  ROLE_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);

-- NAUTHORROLERELATE
CREATE TABLE IF NOT EXISTS NAUTHORROLERELATE (
  AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT NAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES NROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT NAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nauthorrolerelate_role ON NAUTHORROLERELATE (ROLE_CODE);

-- NEMPLYRINFO
CREATE TABLE IF NOT EXISTS NEMPLYRINFO (
  EMPLYR_ID varchar(20) NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  USER_NM varchar(60) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  OFCPS_NM varchar(60) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(20) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT NEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT NEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES NORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_group_id ON NEMPLYRINFO (GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_lettnempyrinfo_orgnzt_id ON NEMPLYRINFO (ORGNZT_ID);

-- NEMPLYRSCRTYESTBS
CREATE TABLE IF NOT EXISTS NEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(20) NOT NULL,
  MBER_TY_CODE varchar(15) DEFAULT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT NEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE)
);
CREATE INDEX IF NOT EXISTS idx_nemplyrscrtyestbs_author ON NEMPLYRSCRTYESTBS (AUTHOR_CODE);

-- NTMPLATINFO
CREATE TABLE IF NOT EXISTS NTMPLATINFO (
  TMPLAT_ID char(20) NOT NULL DEFAULT '',
  TMPLAT_NM varchar(255) DEFAULT NULL,
  TMPLAT_COURS varchar(2000) DEFAULT NULL,
  USE_AT char(1) DEFAULT NULL,
  TMPLAT_SE_CODE char(6) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (TMPLAT_ID)
);

-- NBBSMASTER
CREATE TABLE IF NOT EXISTS NBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_INTRCN varchar(2400) DEFAULT NULL,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) DEFAULT NULL,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);

-- NBBSUSE
CREATE TABLE IF NOT EXISTS NBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) NOT NULL DEFAULT '',
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT NBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
);

-- NBBS
CREATE TABLE IF NOT EXISTS NBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) DEFAULT NULL,
  NTT_SJ varchar(2000) DEFAULT NULL,
  NTT_CN text,
  ANSWER_AT char(1) DEFAULT NULL,
  PARNTSCTT_NO numeric(10,0) DEFAULT NULL,
  ANSWER_LC integer DEFAULT NULL,
  SORT_ORDR numeric(8,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) DEFAULT NULL,
  NTCE_ENDDE char(20) DEFAULT NULL,
  NTCR_ID varchar(20) DEFAULT NULL,
  NTCR_NM varchar(20) DEFAULT NULL,
  PASSWORD varchar(200) DEFAULT NULL,
  ATCH_FILE_ID char(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT NBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
);
CREATE INDEX IF NOT EXISTS idx_nbbs_bbs_id ON NBBS (BBS_ID);

-- CZIP
CREATE TABLE IF NOT EXISTS CZIP (
  ZIP varchar(6) NOT NULL,
  SN numeric(10,0) NOT NULL DEFAULT 0,
  CTPRVN_NM varchar(20) DEFAULT NULL,
  SIGNGU_NM varchar(20) DEFAULT NULL,
  EMD_NM varchar(60) DEFAULT NULL,
  LI_BULD_NM varchar(60) DEFAULT NULL,
  LNBR_DONG_HO varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
);

-- HEMPLYRINFOCHANGEDTLS
CREATE TABLE IF NOT EXISTS HEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar(20) NOT NULL,
  CHANGE_DE timestamp NOT NULL,
  ORGNZT_ID char(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  EMPL_NO varchar(20) DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  HOUSE_ADRES varchar(100) DEFAULT NULL,
  HOUSE_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFM_TELNO varchar(20) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  EMAIL_ADRES varchar(50) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  PSTINST_CODE char(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE varchar(15) DEFAULT NULL,
  ESNTL_ID char(20) DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
);

-- NBBSMASTEROPTN
CREATE TABLE IF NOT EXISTS NBBSMASTEROPTN (
  BBS_ID char(20) NOT NULL DEFAULT '',
  ANSWER_AT char(1) NOT NULL DEFAULT '',
  STSFDG_AT char(1) NOT NULL DEFAULT '',
  FRST_REGIST_PNTTM timestamp NOT NULL DEFAULT '1900-01-01 00:00:00',
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL DEFAULT '',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
);

-- NENTRPRSMBER
CREATE TABLE IF NOT EXISTS NENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL DEFAULT '',
  ENTRPRS_SE_CODE char(15) DEFAULT NULL,
  BIZRNO varchar(10) DEFAULT NULL,
  JURIRNO varchar(13) DEFAULT NULL,
  CMPNY_NM varchar(60) NOT NULL,
  CXFC varchar(50) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_MIDDLE_TELNO varchar(4) DEFAULT NULL,
  FXNUM varchar(20) DEFAULT NULL,
  INDUTY_CODE char(15) DEFAULT NULL,
  APPLCNT_NM varchar(50) DEFAULT NULL,
  APPLCNT_IHIDNUM varchar(200) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  ENTRPRS_MBER_STTUS varchar(15) DEFAULT NULL,
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  ENTRPRS_END_TELNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  APPLCNT_EMAIL_ADRES varchar(50) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT NENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nentrprsmber_group_id ON NENTRPRSMBER (GROUP_ID);

-- NFILE
CREATE TABLE IF NOT EXISTS NFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT timestamp NOT NULL,
  USE_AT char(1) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID)
);

-- NFILEDETAIL
CREATE TABLE IF NOT EXISTS NFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE numeric(8,0) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT NFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES NFILE (ATCH_FILE_ID)
);

-- NGNRLMBER
CREATE TABLE IF NOT EXISTS NGNRLMBER (
  MBER_ID varchar(20) NOT NULL DEFAULT '',
  PASSWORD varchar(200) NOT NULL,
  PASSWORD_HINT varchar(100) DEFAULT NULL,
  PASSWORD_CNSR varchar(100) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  MBER_NM varchar(50) NOT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MBER_STTUS varchar(15) DEFAULT NULL,
  DETAIL_ADRES varchar(100) DEFAULT NULL,
  END_TELNO varchar(4) DEFAULT NULL,
  MBTLNUM varchar(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  MBER_FXNUM varchar(20) DEFAULT NULL,
  MBER_EMAIL_ADRES varchar(50) DEFAULT NULL,
  MIDDLE_TELNO varchar(4) DEFAULT NULL,
  SBSCRB_DE timestamp DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (MBER_ID),
  CONSTRAINT NGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ngnrlmber_group_id ON NGNRLMBER (GROUP_ID);

-- NLOGINLOG
CREATE TABLE IF NOT EXISTS NLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  CREAT_DT timestamp DEFAULT NULL,
  PRIMARY KEY (LOG_ID)
);

-- NLOGINPOLICY
CREATE TABLE IF NOT EXISTS NLOGINPOLICY (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  IP_INFO varchar(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);

-- NPROGRMLIST
CREATE TABLE IF NOT EXISTS NPROGRMLIST (
  PROGRM_FILE_NM varchar(60) NOT NULL DEFAULT '',
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);

-- NMENUINFO
CREATE TABLE IF NOT EXISTS NMENUINFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) DEFAULT NULL,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO),
  CONSTRAINT NMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES NMENUINFO (MENU_NO),
  CONSTRAINT NMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES NPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nmenuinfo_progrm_file_nm ON NMENUINFO (PROGRM_FILE_NM);
CREATE INDEX IF NOT EXISTS idx_nmenuinfo_upper_menu_no ON NMENUINFO (UPPER_MENU_NO);

-- NMENUCREATDTLS
CREATE TABLE IF NOT EXISTS NMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT NMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT NMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES NMENUINFO (MENU_NO) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nmenucreatdtls_mapng ON NMENUCREATDTLS (MAPNG_CREAT_ID);
CREATE INDEX IF NOT EXISTS idx_nmenucreatdtls_author ON NMENUCREATDTLS (AUTHOR_CODE);

-- NUSERABSNCE
CREATE TABLE IF NOT EXISTS NUSERABSNCE (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM timestamp DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM timestamp DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
);

-- SSYSLOGSUMMARY
CREATE TABLE IF NOT EXISTS SSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO numeric(10,0) DEFAULT NULL,
  UPDT_CO numeric(10,0) DEFAULT NULL,
  RDCNT numeric(10,0) DEFAULT NULL,
  DELETE_CO numeric(10,0) DEFAULT NULL,
  OUTPT_CO numeric(10,0) DEFAULT NULL,
  ERROR_CO numeric(10,0) DEFAULT NULL,
  PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
);

-- View COMVNUSERMASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (
  ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID
) AS
        SELECT ESNTL_ID, MBER_ID AS USER_ID,PASSWORD,MBER_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,MBER_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'GNR' AS USER_SE, ' ' AS ORGNZT_ID
        FROM NGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID AS USER_ID,PASSWORD,USER_NM,ZIP AS USER_ZIP,HOUSE_ADRES AS USER_ADRES,EMAIL_ADRES AS USER_EMAIL,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM NEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID AS USER_ID,ENTRPRS_MBER_PASSWORD AS PASSWORD,CMPNY_NM AS USER_NM,ZIP AS USER_ZIP,ADRES AS USER_ADRES,APPLCNT_EMAIL_ADRES AS USER_EMAIL,' ' AS GROUP_ID,'ENT' AS USER_SE, ' ' AS ORGNZT_ID
        FROM NENTRPRSMBER
;


