CREATE TABLE CCMMNDETAILCODE
(
	CODE_ID               VARCHAR(6) NOT NULL,
	CODE                  VARCHAR(15) NOT NULL,
	CODE_NM               VARCHAR(60) NULL,
	CODE_DC               VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CODE_ID,CODE)
);

CREATE TABLE NBACKUPOPERT
(
	BACKUP_OPERT_ID       VARCHAR(20) NOT NULL,
	BACKUP_OPERT_NM       VARCHAR(60) NULL,
	BACKUP_ORGINL_DRCTRY  VARCHAR(255) NULL,
	BACKUP_STRE_DRCTRY    VARCHAR(255) NULL,
	CMPRS_SE              VARCHAR(2) NULL,
	EXECUT_CYCLE          VARCHAR(2) NULL,
	EXECUT_SCHDUL_DE      CHAR(20) NULL,
	EXECUT_SCHDUL_HOUR    CHAR(2) NULL,
	EXECUT_SCHDUL_MNT     CHAR(2) NULL,
	EXECUT_SCHDUL_SECND   CHAR(2) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NOT NULL,
	 PRIMARY KEY (BACKUP_OPERT_ID)
);

CREATE TABLE NBACKUPSCHDULDFK
(
	BACKUP_OPERT_ID       VARCHAR(20) NOT NULL,
	EXECUT_SCHDUL_DFK_SE  CHAR(1) NOT NULL,
	 PRIMARY KEY (BACKUP_OPERT_ID,EXECUT_SCHDUL_DFK_SE),
	FOREIGN KEY (BACKUP_OPERT_ID) REFERENCES NBACKUPOPERT(BACKUP_OPERT_ID)
);

