plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common-service')
    implementation project(':common-security')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    
    // JSP Support
    implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl'
    
    // MyBATIS Support
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    
    // Legacy Dependencies
    implementation 'com.ibm.icu:icu4j:75.1' // ChineseCalendar 등
    implementation 'commons-io:commons-io:2.17.0'
    implementation 'com.google.guava:guava:33.3.1-jre'
    runtimeOnly 'com.h2database:h2'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
