// Generated by scripts/generate-permissions.mjs. Do not edit.
export const PERMISSION_CODES = [
  "ABSENCE_READ",
  "ABSENCE_UPDATE",
  "ADBK_CREATE",
  "ADBK_DELETE",
  "ADBK_DELETE_ALL",
  "ADBK_READ",
  "ADBK_READ_ALL",
  "ADBK_UPDATE",
  "ADBK_UPDATE_ALL",
  "ADMCODE_CREATE",
  "ADMCODE_DELETE",
  "ADMCODE_READ",
  "ADMCODE_UPDATE",
  "APPROVAL_APPROVE",
  "APPROVAL_CANCEL",
  "APPROVAL_CREATE",
  "APPROVAL_READ",
  "AUTHRT_ASSIGN",
  "AUTHRT_AUDIT",
  "AUTHRT_CREATE",
  "AUTHRT_DELETE",
  "AUTHRT_GRANT",
  "AUTHRT_READ",
  "AUTHRT_UPDATE",
  "BANNER_ADMIN_READ",
  "BANNER_CREATE",
  "BANNER_DELETE",
  "BANNER_READ",
  "BANNER_UPDATE",
  "BBS_MST_CREATE",
  "BBS_MST_DELETE",
  "BBS_MST_READ",
  "BBS_MST_READ_ALL",
  "BBS_MST_UPDATE",
  "BOARD_CREATE",
  "BOARD_DELETE",
  "BOARD_DELETE_ALL",
  "BOARD_LIKE",
  "BOARD_READ",
  "BOARD_READ_ALL",
  "BOARD_UPDATE",
  "BOARD_UPDATE_ALL",
  "CLASS_GRP_CREATE",
  "CLASS_GRP_DELETE",
  "CLASS_GRP_READ",
  "CLASS_GRP_UPDATE",
  "CODE_CREATE",
  "CODE_DELETE",
  "CODE_READ",
  "CODE_UPDATE",
  "COMMENT_CREATE",
  "COMMENT_DELETE",
  "COMMENT_DELETE_ALL",
  "COMMENT_READ",
  "COMMENT_READ_ALL",
  "COMMENT_UPDATE",
  "COMMENT_UPDATE_ALL",
  "COMMUNITY_APPROVE",
  "COMMUNITY_CREATE_ALL",
  "COMMUNITY_DELETE_ALL",
  "COMMUNITY_JOIN",
  "COMMUNITY_READ",
  "COMMUNITY_READ_ALL",
  "COMMUNITY_REJECT",
  "COMMUNITY_UPDATE_ALL",
  "DASHBOARD_ADMIN_READ",
  "DASHBOARD_READ",
  "DEPT_BOX_CREATE",
  "DEPT_BOX_DELETE",
  "DEPT_BOX_READ",
  "DEPT_BOX_UPDATE",
  "DEPT_CREATE",
  "DEPT_DELETE",
  "DEPT_JOB_CREATE",
  "DEPT_JOB_DELETE",
  "DEPT_JOB_DELETE_ALL",
  "DEPT_JOB_READ",
  "DEPT_JOB_UPDATE",
  "DEPT_JOB_UPDATE_ALL",
  "DEPT_READ",
  "DEPT_UPDATE",
  "EVENT_CREATE",
  "EVENT_DELETE",
  "EVENT_DELETE_ALL",
  "EVENT_READ",
  "EVENT_UPDATE",
  "EVENT_UPDATE_ALL",
  "EXT_HR_CREATE",
  "EXT_HR_DELETE",
  "EXT_HR_DELETE_ALL",
  "EXT_HR_READ",
  "EXT_HR_UPDATE",
  "EXT_HR_UPDATE_ALL",
  "FILE_AUDIT",
  "FILE_DELETE",
  "FILE_DELETE_ALL",
  "FILE_DOWNLOAD",
  "FILE_DOWNLOAD_ALL",
  "FILE_READ",
  "FILE_READ_ALL",
  "FILE_UPLOAD",
  "FILE_UPLOAD_ALL",
  "HELP_CREATE",
  "HELP_DELETE",
  "HELP_DELETE_ALL",
  "HELP_READ",
  "HELP_UPDATE",
  "HELP_UPDATE_ALL",
  "INFORMAL_APPROVE",
  "INFORMAL_APPR_ADMIN",
  "INFORMAL_CREATE",
  "INFORMAL_CREATE_ALL",
  "INFORMAL_DELETE",
  "INFORMAL_DELETE_ALL",
  "INFORMAL_READ",
  "INFORMAL_READ_ALL",
  "INFORMAL_UPDATE",
  "INFORMAL_UPDATE_ALL",
  "INST_CODE_CREATE",
  "INST_CODE_DELETE",
  "INST_CODE_IMPORT",
  "INST_CODE_READ",
  "INST_CODE_UPDATE",
  "LOGIN_LOG_EXPORT",
  "LOGIN_LOG_READ",
  "LOGIN_POL_CREATE",
  "LOGIN_POL_DELETE",
  "LOGIN_POL_READ",
  "LOGIN_POL_UPDATE",
  "MAIL_DELETE",
  "MAIL_DELETE_ALL",
  "MAIL_READ",
  "MAIL_READ_ALL",
  "MAIL_SEND",
  "MEMO_RPT_CREATE",
  "MEMO_RPT_DELETE",
  "MEMO_RPT_DELETE_ALL",
  "MEMO_RPT_INSTRUCT",
  "MEMO_RPT_READ",
  "MEMO_RPT_READ_ALL",
  "MEMO_RPT_UPDATE",
  "MEMO_RPT_UPDATE_ALL",
  "MENU_CREATE",
  "MENU_DELETE",
  "MENU_READ",
  "MENU_UPDATE",
  "NETWORK_CREATE",
  "NETWORK_DELETE",
  "NETWORK_READ",
  "NETWORK_UPDATE",
  "NOTE_DELETE",
  "NOTE_READ",
  "NOTE_SEND",
  "NOTI_ACK",
  "NOTI_CREATE",
  "NOTI_DELETE",
  "NOTI_DISPATCH",
  "NOTI_READ",
  "OPS_READ",
  "POLICY_READ",
  "POLICY_UPDATE",
  "POLL_CREATE",
  "POLL_DELETE",
  "POLL_DELETE_ALL",
  "POLL_READ",
  "POLL_READ_ALL",
  "POLL_UPDATE",
  "POLL_UPDATE_ALL",
  "POLL_VOTE",
  "POPUP_ADMIN_READ",
  "POPUP_CREATE",
  "POPUP_DELETE",
  "POPUP_READ",
  "POPUP_UPDATE",
  "PRIVACY_EXPORT",
  "PRIVACY_READ",
  "PROGRAM_CREATE",
  "PROGRAM_DELETE",
  "PROGRAM_READ",
  "PROGRAM_UPDATE",
  "REWARD_CREATE",
  "REWARD_DELETE",
  "REWARD_DELETE_ALL",
  "REWARD_READ",
  "REWARD_UPDATE",
  "REWARD_UPDATE_ALL",
  "SATISFY_CREATE",
  "SATISFY_DELETE",
  "SATISFY_DELETE_ALL",
  "SATISFY_MODERATE",
  "SATISFY_READ",
  "SATISFY_UPDATE",
  "SATISFY_UPDATE_ALL",
  "SCHEDULE_CREATE",
  "SCHEDULE_DELETE",
  "SCHEDULE_DELETE_ALL",
  "SCHEDULE_READ",
  "SCHEDULE_READ_ALL",
  "SCHEDULE_UPDATE",
  "SCHEDULE_UPDATE_ALL",
  "SCRAP_CREATE",
  "SCRAP_DELETE",
  "SCRAP_DELETE_ALL",
  "SCRAP_READ",
  "SCRAP_READ_ALL",
  "SCRAP_UPDATE",
  "SCRAP_UPDATE_ALL",
  "SERVICE_CREATE",
  "SERVICE_DELETE",
  "SERVICE_READ",
  "SERVICE_UPDATE",
  "SMS_READ",
  "SMS_SEND",
  "STATS_ADMIN_READ",
  "STATS_READ",
  "SURVEY_CREATE_ALL",
  "SURVEY_DELETE_ALL",
  "SURVEY_READ",
  "SURVEY_READ_ALL",
  "SURVEY_RSP_DELETE",
  "SURVEY_RSP_READ",
  "SURVEY_SUBMIT",
  "SURVEY_UPDATE_ALL",
  "SYS_LOG_EXPORT",
  "SYS_LOG_READ",
  "TEMPLATE_CREATE",
  "TEMPLATE_DELETE",
  "TEMPLATE_READ",
  "TEMPLATE_UPDATE",
  "USER_CREATE",
  "USER_DELETE",
  "USER_DEPT",
  "USER_LOG_EXPORT",
  "USER_LOG_READ",
  "USER_PASSWORD",
  "USER_READ",
  "USER_STATUS",
  "USER_UPDATE",
  "WEB_LOG_EXPORT",
  "WEB_LOG_READ",
  "WORKFLOW_READ",
  "WORK_RPT_CREATE",
  "WORK_RPT_DELETE",
  "WORK_RPT_DELETE_ALL",
  "WORK_RPT_READ",
  "WORK_RPT_READ_ALL",
  "WORK_RPT_UPDATE",
  "WORK_RPT_UPDATE_ALL"
] as const;
export type PermissionCode = (typeof PERMISSION_CODES)[number];
export const PERMISSION_CATALOG_VERSION = "7905bb657127d40bea2df619093b24316651b1957ac9e26a902c7bd171473276";
export const PAGE_PERMISSIONS: Readonly<Record<string, readonly PermissionCode[]>> = {
  "/": [],
  "/admin": [
    "DASHBOARD_ADMIN_READ"
  ],
  "/admin/collaboration": [],
  "/admin/collaboration/address-book": [],
  "/admin/collaboration/address-book/insert-address-book": [],
  "/admin/collaboration/address-book/select-address-book-detail/[id]": [],
  "/admin/collaboration/address-book/select-address-book-list": [],
  "/admin/collaboration/mail-history": [],
  "/admin/collaboration/mail-send": [],
  "/admin/collaboration/scraps": [],
  "/admin/collaboration/scraps/insertScrap": [],
  "/admin/collaboration/scraps/selectScrapDetail/[id]": [],
  "/admin/collaboration/scraps/selectScrapList": [],
  "/admin/community": [],
  "/admin/community/[id]": [],
  "/admin/community/board": [],
  "/admin/community/boards": [],
  "/admin/community/boards/[id]": [],
  "/admin/community/boards/detail": [],
  "/admin/community/boards/insert-board-article": [],
  "/admin/community/boards/maker": [
    "BBS_MST_CREATE",
    "BBS_MST_UPDATE"
  ],
  "/admin/community/boards/master": [
    "BBS_MST_READ"
  ],
  "/admin/community/boards/select-board-list": [],
  "/admin/community/boards/write": [],
  "/admin/community/templates": [
    "TEMPLATE_READ"
  ],
  "/admin/help": [],
  "/admin/help/faq": [],
  "/admin/help/qna": [],
  "/admin/notifications": [
    "NOTI_DISPATCH"
  ],
  "/admin/observability": [
    "OPS_READ",
    "SYS_LOG_READ",
    "WEB_LOG_READ",
    "LOGIN_LOG_READ"
  ],
  "/admin/operation/events": [
    "EVENT_READ"
  ],
  "/admin/operation/external-hr": [
    "EXT_HR_READ"
  ],
  "/admin/operation/memo-reports": [
    "MEMO_RPT_READ_ALL"
  ],
  "/admin/operation/rewards": [
    "REWARD_READ"
  ],
  "/admin/operation/rough-map": [
    "EVENT_READ"
  ],
  "/admin/patterns": [
    "OPS_READ"
  ],
  "/admin/sanctn/forms": [
    "TEMPLATE_READ"
  ],
  "/admin/sanctn/workflow": [
    "WORKFLOW_READ"
  ],
  "/admin/security/audit": [
    "OPS_READ",
    "SYS_LOG_READ",
    "WEB_LOG_READ",
    "LOGIN_LOG_READ"
  ],
  "/admin/security/authority": [
    "AUTHRT_READ",
    "AUTHRT_AUDIT"
  ],
  "/admin/security/dept-authority": [
    "AUTHRT_READ"
  ],
  "/admin/security/group": [
    "CLASS_GRP_READ"
  ],
  "/admin/security/login-policy": [
    "LOGIN_POL_READ"
  ],
  "/admin/security/role": [
    "AUTHRT_READ"
  ],
  "/admin/stats": [
    "STATS_ADMIN_READ"
  ],
  "/admin/stats/board": [
    "STATS_ADMIN_READ"
  ],
  "/admin/stats/data-usage": [
    "STATS_ADMIN_READ"
  ],
  "/admin/stats/report": [
    "STATS_ADMIN_READ"
  ],
  "/admin/stats/screen": [
    "STATS_ADMIN_READ"
  ],
  "/admin/stats/user": [
    "STATS_ADMIN_READ"
  ],
  "/admin/survey": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/hub": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/items": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/manage": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/manage/[id]": [
    "SURVEY_READ_ALL"
  ],
  "/admin/survey/manage/create": [
    "SURVEY_CREATE_ALL"
  ],
  "/admin/survey/polls": [
    "POLL_READ_ALL"
  ],
  "/admin/survey/polls/manage": [
    "POLL_READ_ALL"
  ],
  "/admin/survey/polls/participate": [],
  "/admin/survey/questions": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/stats": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/survey/templates": [
    "SURVEY_READ_ALL",
    "SURVEY_RSP_READ"
  ],
  "/admin/system/audit": [
    "OPS_READ",
    "SYS_LOG_READ",
    "WEB_LOG_READ",
    "LOGIN_LOG_READ"
  ],
  "/admin/system/banner": [
    "BANNER_ADMIN_READ"
  ],
  "/admin/system/codes/administ": [
    "ADMCODE_READ"
  ],
  "/admin/system/codes/institution": [
    "INST_CODE_READ"
  ],
  "/admin/system/comments": [
    "COMMENT_READ_ALL"
  ],
  "/admin/system/common-code": [
    "CODE_READ"
  ],
  "/admin/system/common-code/codes": [
    "CODE_READ"
  ],
  "/admin/system/hpcm": [
    "HELP_READ"
  ],
  "/admin/system/isg": [
    "SERVICE_READ"
  ],
  "/admin/system/ism": [],
  "/admin/system/layout": [
    "MENU_READ"
  ],
  "/admin/system/logs": [
    "LOGIN_LOG_READ",
    "SYS_LOG_READ",
    "USER_LOG_READ",
    "WEB_LOG_READ"
  ],
  "/admin/system/logs/login": [
    "LOGIN_LOG_READ"
  ],
  "/admin/system/logs/privacy": [
    "PRIVACY_READ"
  ],
  "/admin/system/logs/system": [
    "SYS_LOG_READ"
  ],
  "/admin/system/logs/user": [
    "USER_LOG_READ"
  ],
  "/admin/system/logs/web": [
    "WEB_LOG_READ"
  ],
  "/admin/system/menus": [
    "MENU_READ"
  ],
  "/admin/system/menus/by-authority": [
    "AUTHRT_READ"
  ],
  "/admin/system/monitoring": [
    "OPS_READ",
    "SYS_LOG_READ",
    "WEB_LOG_READ",
    "LOGIN_LOG_READ"
  ],
  "/admin/system/monitoring/hub": [
    "OPS_READ",
    "SYS_LOG_READ",
    "WEB_LOG_READ",
    "LOGIN_LOG_READ"
  ],
  "/admin/system/network": [
    "NETWORK_READ"
  ],
  "/admin/system/policies": [
    "POLICY_READ"
  ],
  "/admin/system/programs": [
    "PROGRAM_READ"
  ],
  "/admin/user/absences": [
    "ABSENCE_READ"
  ],
  "/admin/user/departments": [
    "DEPT_READ"
  ],
  "/admin/user/indvdl-info-policy": [
    "LOGIN_POL_READ"
  ],
  "/admin/user/login-policy": [
    "LOGIN_POL_READ"
  ],
  "/admin/user/manage": [
    "USER_READ"
  ],
  "/admin/uss/ion/sms": [
    "SMS_READ"
  ],
  "/admin/uss/olh/online-manual": [
    "HELP_READ"
  ],
  "/admin/work-hub": [],
  "/admin/workflow": [
    "WORKFLOW_READ"
  ],
  "/approvals": [],
  "/approvals/draft": [],
  "/cop/cmy/selectCommunityDetail/[id]": [],
  "/cop/cmy/selectCommunityList": [],
  "/cop/sms/selectSmsList": [
    "SMS_READ"
  ],
  "/help": [],
  "/help/policies/[type]": [],
  "/login": [],
  "/note": [],
  "/search": [],
  "/smart-toolkit/dept-job": [],
  "/smart-toolkit/dept-job/[id]": [],
  "/smart-toolkit/dept-job/create": [],
  "/smart-toolkit/dept-job/insertDeptJob": [],
  "/smart-toolkit/dept-job/selectDeptJobDetail/[id]": [],
  "/smart-toolkit/dept-job/selectDeptJobList": [],
  "/smart-toolkit/schedule": [],
  "/smart-toolkit/schedule/dept": [],
  "/smart-toolkit/work-report": [],
  "/survey": [],
  "/survey/[id]": [],
  "/survey/response": [],
  "/survey/response/[id]": [],
  "/survey/stats": []
};
