// Generated by scripts/generate-screen-registry.mjs. Do not edit.
//
// 화면 목록 — 메뉴 편집기의 연결 화면, 권한 편집기의 화면별 권한 표, 화면 관리의 화면 목록이 읽는다.
// 원천: 화면 파일(frontend/src/app/**/page.tsx 중 라우팅이 page 인 것), 진입 권한(permission-catalog.json
// pagePermissions·pagePermissionModes), 라우트 원장(ui-route-capabilities.json shellAccess·visibleLabel),
// 메뉴 snapshot(project-composer-menus.json menu_nm), 쓰기 권한(operation-consumer census 축 3 계산).
//
// 권한 묶음 — 권한 작업대의 '권한 묶음 적용'이 읽는다. 원천은 config/governance/permission-bundles.json 이고, 묶음이
// 여는 화면(screens)과 관련 화면(relatedScreens)은 위 화면 목록에서 계산한다. screens 는 진입 권한을 이 묶음의 권한이
// 충족하는(ANY 하나 이상, ALL 전부) 화면의 라우트다. relatedScreens 는 진입 권한이 빈 화면(누구나 들어가는 화면 — 내
// 결재함·업무 쪽지함·일정 등) 가운데 이 묶음의 권한을 쓰기('write')로 쓰는 화면이다. 표시('display')만 하는 화면과 쓰기가
// 없는 화면(통합 검색·설문 참여 목록 등)은 relatedScreens 에 없고, 그 메뉴 표시는 묶음이 아니라 따로 배정한다. 두 목록은
// 겹치지 않는다. 묶음은 그룹이 아니다 — 적용은 그룹 권한 초안에 더할 뿐이고 저장·인가는 기존 '권한 변경 저장'이 한다.
// 카탈로그에서 어느 묶음에도 넣지 않은 권한은 원장 excluded 에 사유와 함께 있다(생성기가 전수 분류를 검사한다). protected 는
// 보호 권한(PROTECTED_PERMISSIONS)을 품는다는 뜻이다. 서버는 보호 권한을 그룹에 새로 더하거나 빼는 저장에만 권한 설정과 권한
// 배정 권한을 모두 요구한다 — 묶음의 보호 권한을 그룹이 이미 모두 가졌으면 그 저장에는 요구하지 않는다.
//
// 한계 — 이 목록을 인가로 쓰지 않는다(서버가 집행한다).
//   · 'write' 는 화면이 부르는 쓰기(GET 이 아닌) operation 의 권한이다. 조회(GET) 권한은 화면 진입('entry')과
//     canPermission 리터럴('display')로만 드러난다.
//   · 호출·import 는 이름으로 맞춘다 — 같은 이름의 모듈은 겹치고(타입만 가져오는 import 도 import 로 본다),
//     조립한 권한 코드(템플릿 문자열)는 보지 못한다.
//   · 'display' 는 리터럴로 적힌 canPermission 코드다. 리터럴을 언급하면 판정에 쓴 것으로 본다(어느 버튼에
//     걸었는지는 보지 않는다).
//   · 화면의 라우트 디렉터리 파일은 그 화면과, 그 파일을 import 하는(정적·동적) 다른 화면들에 귀속한다. 공용
//     컴포넌트·허브 클라이언트는 그것을 import 하는 화면들에 귀속하고, app/ 루트의 layout·헤더·전역 provider 는
//     어느 화면에도 귀속하지 않는다.
//   · 별칭(page-redirect·config-redirect)은 화면이 아니다. 목적지를 함께 적지만 링크하지 않는다. 화면 파일이 없는 앱
//     설정(next.config) 리다이렉트도 별칭이다 — 앱 설정은 화면 파일보다 먼저 넘기므로, 목록에 없으면 그 경로가 동적
//     형제(…/[id])로 풀린다.
//   · 재사용 투영본은 권한 생성물(PAGE_PERMISSIONS)만 다시 만든다. 그 산출물에서 빠진 화면·별칭은 아래에서
//     PAGE_PERMISSIONS 로 다시 거른다(모든 page 파일은 PAGE_PERMISSIONS 에 정확한 키가 있다). 앱 설정 별칭은 투영본에서도
//     앱 설정이 그대로 넘기므로, 화면 파일이 없거나 빠졌어도 넘어가는 화면(목적지 경로)이 투영본에 있으면 남는다.
//     묶음의 화면·관련 화면도 같이 거르고, 여는 화면(screens)이 하나도 남지 않은 묶음(그 투영본에 없는 업무의 묶음)은
//     내지 않는다 — 관련 화면만 남아도 내지 않는다(생성기가 여는 화면 하나 이상을 요구하는 것과 같은 기준).
import { PAGE_PERMISSIONS, type PermissionCode } from '@/types/generated-permissions';

export type ScreenPermissionSource = 'entry' | 'write' | 'display';
export interface ScreenPermission { code: PermissionCode; action: string; source: ScreenPermissionSource }
export interface ScreenRegistryEntry {
  route: string;
  label: string | null;
  labelSource: 'menu' | 'route-ledger' | null;
  shellAccess: string;
  dynamic: boolean;
  entry: { permissions: PermissionCode[]; mode: 'ANY' | 'ALL' };
  permissions: ScreenPermission[];
}
export interface ScreenAlias { route: string; target: string | null; kind: 'page-redirect' | 'config-redirect' }
export interface PermissionBundle {
  id: string;
  name: string;
  description: string;
  protected: boolean;
  /** 이 묶음이 그룹 초안에 더하는 기능권한(OPERATION), 코드 순. */
  permissions: PermissionCode[];
  /** 진입 권한을 이 묶음이 충족하는 화면의 라우트(진입 권한이 빈 화면 제외), 코드 포인트 순. SCREEN_REGISTRY 의 route 다. */
  screens: string[];
  /**
   * 관련 화면 — 진입 권한이 빈 화면(누구나 들어가는 화면) 가운데 이 묶음의 권한을 쓰기('write')로 쓰는 화면의 라우트,
   * 코드 포인트 순. screens 와 겹치지 않는다. 표시 리터럴('display')은 보지 않는다.
   */
  relatedScreens: string[];
}

const GENERATED_SCREENS: readonly ScreenRegistryEntry[] = [
  {
    "route": "/",
    "label": "업무 홈",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"NOTE_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/admin",
    "label": "관리자 업무 현황",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["DASHBOARD_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"DASHBOARD_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/collaboration",
    "label": "협업 및 네트워크 허브",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SCRAP_CREATE","action":"CREATE","source":"write"},
      {"code":"SCRAP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/collaboration/address-book/select-address-book-detail/[id]",
    "label": "주소록 상세",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"ADBK_DELETE","action":"DELETE","source":"write"},
      {"code":"ADBK_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/collaboration/address-book/select-address-book-list",
    "label": "통합 주소록 관리",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"ADBK_CREATE","action":"CREATE","source":"write"},
      {"code":"ADBK_DELETE","action":"DELETE","source":"write"}
    ]
  },
  {
    "route": "/admin/collaboration/mail-history",
    "label": "메일 발송 이력",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"MAIL_DELETE","action":"DELETE","source":"write"},
      {"code":"MAIL_SEND","action":"SEND","source":"write"}
    ]
  },
  {
    "route": "/admin/collaboration/mail-send",
    "label": "메일발송",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"MAIL_SEND","action":"SEND","source":"write"},
      {"code":"USER_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/admin/collaboration/scraps",
    "label": "내 스크랩",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SCRAP_CREATE","action":"CREATE","source":"write"},
      {"code":"SCRAP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/collaboration/scraps/selectScrapList",
    "label": "스크랩 목록",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SCRAP_CREATE","action":"CREATE","source":"write"},
      {"code":"SCRAP_DELETE","action":"DELETE","source":"write"},
      {"code":"SCRAP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/board",
    "label": "게시글 모아보기",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/admin/community/boards/detail",
    "label": "게시글 상세",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"BOARD_LIKE","action":"LIKE","source":"write"},
      {"code":"BOARD_UPDATE","action":"UPDATE","source":"write"},
      {"code":"COMMENT_CREATE","action":"CREATE","source":"write"},
      {"code":"COMMENT_DELETE","action":"DELETE","source":"write"},
      {"code":"COMMENT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"SATISFY_CREATE","action":"CREATE","source":"write"},
      {"code":"SATISFY_DELETE","action":"DELETE","source":"write"},
      {"code":"SATISFY_MODERATE","action":"MODERATE","source":"write"},
      {"code":"SATISFY_UPDATE","action":"UPDATE","source":"write"},
      {"code":"SCRAP_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/boards/insert-board-article",
    "label": "새 게시글 작성",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"BOARD_CREATE","action":"CREATE","source":"display"},
      {"code":"BOARD_UPDATE","action":"UPDATE","source":"display"},
      {"code":"BOARD_UPDATE_ALL","action":"UPDATE_ALL","source":"display"},
      {"code":"FILE_DELETE","action":"DELETE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/boards/maker",
    "label": "게시판 생성 마법사",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["BBS_MST_CREATE","BBS_MST_UPDATE"],"mode":"ANY"},
    "permissions": [
      {"code":"BBS_MST_CREATE","action":"CREATE","source":"entry"},
      {"code":"BBS_MST_UPDATE","action":"UPDATE","source":"entry"},
      {"code":"MENU_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/boards/master",
    "label": "통합 게시판 마스터 콘솔",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["BBS_MST_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"BBS_MST_CREATE","action":"CREATE","source":"display"},
      {"code":"BBS_MST_DELETE","action":"DELETE","source":"write"},
      {"code":"BBS_MST_READ","action":"READ","source":"entry"},
      {"code":"BBS_MST_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/boards/select-board-list",
    "label": "전체 게시글",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"BOARD_CREATE","action":"CREATE","source":"display"},
      {"code":"BOARD_LIKE","action":"LIKE","source":"write"}
    ]
  },
  {
    "route": "/admin/community/templates",
    "label": "템플릿관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["TEMPLATE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"TEMPLATE_CREATE","action":"CREATE","source":"write"},
      {"code":"TEMPLATE_DELETE","action":"DELETE","source":"write"},
      {"code":"TEMPLATE_READ","action":"READ","source":"entry"},
      {"code":"TEMPLATE_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/help",
    "label": "위키",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"COMMUNITY_APPROVE","action":"APPROVE","source":"write"},
      {"code":"COMMUNITY_CREATE_ALL","action":"CREATE_ALL","source":"write"},
      {"code":"COMMUNITY_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"COMMUNITY_READ_ALL","action":"READ_ALL","source":"display"},
      {"code":"COMMUNITY_REJECT","action":"REJECT","source":"write"},
      {"code":"COMMUNITY_UPDATE_ALL","action":"UPDATE_ALL","source":"write"}
    ]
  },
  {
    "route": "/admin/help/faq",
    "label": "자주 묻는 질문",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"COMMUNITY_APPROVE","action":"APPROVE","source":"write"},
      {"code":"COMMUNITY_CREATE_ALL","action":"CREATE_ALL","source":"write"},
      {"code":"COMMUNITY_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"COMMUNITY_READ_ALL","action":"READ_ALL","source":"display"},
      {"code":"COMMUNITY_REJECT","action":"REJECT","source":"write"},
      {"code":"COMMUNITY_UPDATE_ALL","action":"UPDATE_ALL","source":"write"}
    ]
  },
  {
    "route": "/admin/help/qna",
    "label": "질의응답(Q&A)",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"COMMUNITY_APPROVE","action":"APPROVE","source":"write"},
      {"code":"COMMUNITY_CREATE_ALL","action":"CREATE_ALL","source":"write"},
      {"code":"COMMUNITY_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"COMMUNITY_READ_ALL","action":"READ_ALL","source":"display"},
      {"code":"COMMUNITY_REJECT","action":"REJECT","source":"write"},
      {"code":"COMMUNITY_UPDATE_ALL","action":"UPDATE_ALL","source":"write"}
    ]
  },
  {
    "route": "/admin/notifications",
    "label": "알림 센터",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["NOTI_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"NOTI_DISPATCH","action":"DISPATCH","source":"write"},
      {"code":"NOTI_READ","action":"READ","source":"entry"},
      {"code":"USER_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/admin/operation/events",
    "label": "행사 정보 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["EVENT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"EVENT_CREATE","action":"CREATE","source":"write"},
      {"code":"EVENT_DELETE","action":"DELETE","source":"write"},
      {"code":"EVENT_READ","action":"READ","source":"entry"},
      {"code":"EVENT_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/operation/external-hr",
    "label": "행사 외부인사 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["EXT_HR_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"EXT_HR_CREATE","action":"CREATE","source":"write"},
      {"code":"EXT_HR_DELETE","action":"DELETE","source":"write"},
      {"code":"EXT_HR_READ","action":"READ","source":"entry"},
      {"code":"EXT_HR_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/operation/memo-reports",
    "label": "메모보고 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["MEMO_RPT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"MEMO_RPT_CREATE","action":"CREATE","source":"write"},
      {"code":"MEMO_RPT_DELETE","action":"DELETE","source":"write"},
      {"code":"MEMO_RPT_INSTRUCT","action":"INSTRUCT","source":"write"},
      {"code":"MEMO_RPT_READ","action":"READ","source":"entry"},
      {"code":"MEMO_RPT_READ_ALL","action":"READ_ALL","source":"display"},
      {"code":"MEMO_RPT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"MEMO_RPT_UPDATE_ALL","action":"UPDATE_ALL","source":"display"}
    ]
  },
  {
    "route": "/admin/operation/rewards",
    "label": "포상 기록 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["REWARD_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"REWARD_CREATE","action":"CREATE","source":"write"},
      {"code":"REWARD_DELETE","action":"DELETE","source":"write"},
      {"code":"REWARD_READ","action":"READ","source":"entry"},
      {"code":"REWARD_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/operation/rough-map",
    "label": "약도 및 거점 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["EVENT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"EVENT_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/patterns",
    "label": "업무 요청 목록",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["OPS_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"OPS_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/sanctn/forms",
    "label": "결재 양식 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["TEMPLATE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"TEMPLATE_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/security/authority",
    "label": "권한 그룹 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["AUTHRT_READ","AUTHRT_AUDIT"],"mode":"ANY"},
    "permissions": [
      {"code":"AUTHRT_ASSIGN","action":"ASSIGN","source":"write"},
      {"code":"AUTHRT_AUDIT","action":"AUDIT","source":"entry"},
      {"code":"AUTHRT_CREATE","action":"CREATE","source":"write"},
      {"code":"AUTHRT_DELETE","action":"DELETE","source":"write"},
      {"code":"AUTHRT_GRANT","action":"GRANT","source":"write"},
      {"code":"AUTHRT_READ","action":"READ","source":"entry"},
      {"code":"AUTHRT_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/security/dept-authority",
    "label": "부서별 그룹 배정",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["AUTHRT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"AUTHRT_ASSIGN","action":"ASSIGN","source":"write"},
      {"code":"AUTHRT_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/security/group",
    "label": "사용자 분류 그룹",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["CLASS_GRP_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"CLASS_GRP_CREATE","action":"CREATE","source":"write"},
      {"code":"CLASS_GRP_DELETE","action":"DELETE","source":"write"},
      {"code":"CLASS_GRP_READ","action":"READ","source":"entry"},
      {"code":"CLASS_GRP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/security/login-policy",
    "label": "로그인정책관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["LOGIN_POL_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"LOGIN_POL_CREATE","action":"CREATE","source":"write"},
      {"code":"LOGIN_POL_DELETE","action":"DELETE","source":"write"},
      {"code":"LOGIN_POL_READ","action":"READ","source":"entry"},
      {"code":"LOGIN_POL_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/stats",
    "label": "관리자 통계",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/stats/board",
    "label": "게시물통계",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/stats/data-usage",
    "label": "콘텐츠 사용량 통계",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/stats/report",
    "label": "보고서통계",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/stats/screen",
    "label": "화면통계",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/stats/user",
    "label": "사용자통계",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["STATS_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"STATS_ADMIN_READ","action":"ADMIN_READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/survey/hub",
    "label": "여론조사 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["SURVEY_READ_ALL","SURVEY_RSP_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"POLL_CREATE","action":"CREATE","source":"write"},
      {"code":"POLL_UPDATE","action":"UPDATE","source":"write"},
      {"code":"SURVEY_CREATE_ALL","action":"CREATE_ALL","source":"write"},
      {"code":"SURVEY_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"SURVEY_READ_ALL","action":"READ_ALL","source":"entry"},
      {"code":"SURVEY_RSP_READ","action":"READ","source":"entry"},
      {"code":"SURVEY_UPDATE_ALL","action":"UPDATE_ALL","source":"write"}
    ]
  },
  {
    "route": "/admin/survey/manage/[id]",
    "label": "설문 상세",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": true,
    "entry": {"permissions":["SURVEY_READ_ALL"],"mode":"ANY"},
    "permissions": [
      {"code":"POLL_CREATE","action":"CREATE","source":"write"},
      {"code":"POLL_DELETE","action":"DELETE","source":"write"},
      {"code":"POLL_UPDATE","action":"UPDATE","source":"write"},
      {"code":"SURVEY_READ_ALL","action":"READ_ALL","source":"entry"}
    ]
  },
  {
    "route": "/admin/survey/polls",
    "label": "투표 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["POLL_READ","POLL_READ_ALL"],"mode":"ALL"},
    "permissions": [
      {"code":"POLL_CREATE","action":"CREATE","source":"write"},
      {"code":"POLL_READ","action":"READ","source":"entry"},
      {"code":"POLL_READ_ALL","action":"READ_ALL","source":"entry"}
    ]
  },
  {
    "route": "/admin/survey/polls/manage",
    "label": "설문 여론조사 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["POLL_READ","POLL_READ_ALL"],"mode":"ALL"},
    "permissions": [
      {"code":"POLL_READ","action":"READ","source":"entry"},
      {"code":"POLL_READ_ALL","action":"READ_ALL","source":"entry"}
    ]
  },
  {
    "route": "/admin/survey/polls/participate",
    "label": "투표 참여",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"POLL_VOTE","action":"VOTE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/banner",
    "label": "배너 및 팝업 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["BANNER_ADMIN_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"BANNER_ADMIN_READ","action":"ADMIN_READ","source":"entry"},
      {"code":"BANNER_CREATE","action":"CREATE","source":"write"},
      {"code":"BANNER_DELETE","action":"DELETE","source":"write"},
      {"code":"BANNER_UPDATE","action":"UPDATE","source":"write"},
      {"code":"FILE_UPLOAD_ALL","action":"UPLOAD_ALL","source":"write"},
      {"code":"POPUP_CREATE","action":"CREATE","source":"write"},
      {"code":"POPUP_DELETE","action":"DELETE","source":"write"},
      {"code":"POPUP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/codes/administ",
    "label": "행정 표준코드 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["ADMCODE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ADMCODE_CREATE","action":"CREATE","source":"write"},
      {"code":"ADMCODE_DELETE","action":"DELETE","source":"write"},
      {"code":"ADMCODE_READ","action":"READ","source":"entry"},
      {"code":"ADMCODE_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/codes/institution",
    "label": "공공기관 코드 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["INST_CODE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"INST_CODE_IMPORT","action":"IMPORT","source":"write"},
      {"code":"INST_CODE_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/comments",
    "label": "댓글 및 평가 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["COMMENT_READ_ALL"],"mode":"ANY"},
    "permissions": [
      {"code":"COMMENT_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"COMMENT_READ_ALL","action":"READ_ALL","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/common-code",
    "label": "통합 코드 관리 허브",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["CODE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ADMCODE_CREATE","action":"CREATE","source":"write"},
      {"code":"ADMCODE_DELETE","action":"DELETE","source":"write"},
      {"code":"ADMCODE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"CODE_CREATE","action":"CREATE","source":"write"},
      {"code":"CODE_DELETE","action":"DELETE","source":"write"},
      {"code":"CODE_READ","action":"READ","source":"entry"},
      {"code":"CODE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"INST_CODE_IMPORT","action":"IMPORT","source":"write"}
    ]
  },
  {
    "route": "/admin/system/common-code/codes",
    "label": "공통코드 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["CODE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"CODE_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/durable-jobs",
    "label": "후속 작업 상태",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["DWORK_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"DWORK_READ","action":"READ","source":"entry"},
      {"code":"DWORK_RETRY","action":"RETRY","source":"write"}
    ]
  },
  {
    "route": "/admin/system/hpcm",
    "label": "도움말 콘텐츠 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["HELP_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"HELP_CREATE","action":"CREATE","source":"write"},
      {"code":"HELP_DELETE","action":"DELETE","source":"write"},
      {"code":"HELP_READ","action":"READ","source":"entry"},
      {"code":"HELP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/isg",
    "label": "인터넷 서비스 안내 관리",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["SERVICE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"SERVICE_CREATE","action":"CREATE","source":"write"},
      {"code":"SERVICE_DELETE","action":"DELETE","source":"write"},
      {"code":"SERVICE_READ","action":"READ","source":"entry"},
      {"code":"SERVICE_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/layout",
    "label": "화면 구성 예제",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["MENU_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"MENU_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs",
    "label": "로그 통합 대시보드",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["LOGIN_LOG_READ","SYS_LOG_READ","USER_LOG_READ","WEB_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"LOGIN_LOG_READ","action":"READ","source":"entry"},
      {"code":"SYS_LOG_READ","action":"READ","source":"entry"},
      {"code":"USER_LOG_READ","action":"READ","source":"entry"},
      {"code":"WEB_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/audit",
    "label": "민감 작업 감사 원장",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["ADT_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ADT_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/login",
    "label": "상세 접속 로그 (Login)",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["LOGIN_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"LOGIN_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/privacy",
    "label": "개인정보 조회 로그",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["PRIVACY_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"PRIVACY_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/system",
    "label": "상세 시스템 로그 (System)",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["SYS_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"SYS_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/user",
    "label": "상세 사용자 로그 (User)",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["USER_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"USER_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/logs/web",
    "label": "상세 웹 로그 (Web)",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["WEB_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"WEB_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/menus",
    "label": "메뉴 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["MENU_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"AUTHRT_GRANT","action":"GRANT","source":"display"},
      {"code":"AUTHRT_READ","action":"READ","source":"display"},
      {"code":"MENU_CREATE","action":"CREATE","source":"display"},
      {"code":"MENU_DELETE","action":"DELETE","source":"display"},
      {"code":"MENU_READ","action":"READ","source":"entry"},
      {"code":"MENU_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/menus/by-authority",
    "label": "그룹별 메뉴 현황",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["AUTHRT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"AUTHRT_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/monitoring/hub",
    "label": "보안 감사 로그",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["OPS_READ","SYS_LOG_READ","WEB_LOG_READ","LOGIN_LOG_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"COMMENT_DELETE_ALL","action":"DELETE_ALL","source":"write"},
      {"code":"LOGIN_LOG_READ","action":"READ","source":"entry"},
      {"code":"OPS_READ","action":"READ","source":"entry"},
      {"code":"SYS_LOG_READ","action":"READ","source":"entry"},
      {"code":"WEB_LOG_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/system/policies",
    "label": "개인정보처리방침·이용약관",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["POLICY_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"POLICY_READ","action":"READ","source":"entry"},
      {"code":"POLICY_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/system/programs",
    "label": "화면 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["MENU_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"MENU_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/admin/user/absences",
    "label": "부재 상태 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["ABSENCE_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ABSENCE_READ","action":"READ","source":"entry"},
      {"code":"ABSENCE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"AUTHRT_AUDIT","action":"AUDIT","source":"display"},
      {"code":"AUTHRT_READ","action":"READ","source":"display"},
      {"code":"DEPT_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"MFA_RECOVER","action":"RECOVER","source":"display"},
      {"code":"USER_CREATE","action":"CREATE","source":"write"},
      {"code":"USER_DELETE","action":"DELETE","source":"write"},
      {"code":"USER_DEPT","action":"DEPT","source":"write"},
      {"code":"USER_PASSWORD","action":"PASSWORD","source":"write"},
      {"code":"USER_STATUS","action":"STATUS","source":"write"},
      {"code":"USER_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/user/departments",
    "label": "부서 및 조직 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["DEPT_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ABSENCE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"AUTHRT_AUDIT","action":"AUDIT","source":"display"},
      {"code":"AUTHRT_READ","action":"READ","source":"display"},
      {"code":"DEPT_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_READ","action":"READ","source":"entry"},
      {"code":"DEPT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"MFA_RECOVER","action":"RECOVER","source":"display"},
      {"code":"USER_CREATE","action":"CREATE","source":"write"},
      {"code":"USER_DELETE","action":"DELETE","source":"write"},
      {"code":"USER_DEPT","action":"DEPT","source":"write"},
      {"code":"USER_PASSWORD","action":"PASSWORD","source":"write"},
      {"code":"USER_STATUS","action":"STATUS","source":"write"},
      {"code":"USER_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/user/indvdl-info-policy",
    "label": "조직 정책",
    "labelSource": "route-ledger",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["LOGIN_POL_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ABSENCE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"AUTHRT_AUDIT","action":"AUDIT","source":"display"},
      {"code":"AUTHRT_READ","action":"READ","source":"display"},
      {"code":"DEPT_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"LOGIN_POL_READ","action":"READ","source":"entry"},
      {"code":"MFA_RECOVER","action":"RECOVER","source":"display"},
      {"code":"USER_CREATE","action":"CREATE","source":"write"},
      {"code":"USER_DELETE","action":"DELETE","source":"write"},
      {"code":"USER_DEPT","action":"DEPT","source":"write"},
      {"code":"USER_PASSWORD","action":"PASSWORD","source":"write"},
      {"code":"USER_STATUS","action":"STATUS","source":"write"},
      {"code":"USER_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/user/manage",
    "label": "계정 및 사용자 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["USER_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"ABSENCE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"AUTHRT_AUDIT","action":"AUDIT","source":"display"},
      {"code":"AUTHRT_READ","action":"READ","source":"display"},
      {"code":"DEPT_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_UPDATE","action":"UPDATE","source":"write"},
      {"code":"MFA_RECOVER","action":"RECOVER","source":"display"},
      {"code":"USER_CREATE","action":"CREATE","source":"write"},
      {"code":"USER_DELETE","action":"DELETE","source":"write"},
      {"code":"USER_DEPT","action":"DEPT","source":"write"},
      {"code":"USER_PASSWORD","action":"PASSWORD","source":"write"},
      {"code":"USER_READ","action":"READ","source":"entry"},
      {"code":"USER_STATUS","action":"STATUS","source":"write"},
      {"code":"USER_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/uss/ion/sms",
    "label": "문자메시지",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["SMS_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"SMS_READ","action":"READ","source":"entry"},
      {"code":"SMS_SEND","action":"SEND","source":"write"},
      {"code":"USER_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/admin/uss/olh/online-manual",
    "label": "온라인 매뉴얼 관리",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["HELP_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"HELP_CREATE","action":"CREATE","source":"write"},
      {"code":"HELP_DELETE","action":"DELETE","source":"write"},
      {"code":"HELP_READ","action":"READ","source":"entry"},
      {"code":"HELP_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/work-hub",
    "label": "나의 업무",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_BOX_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_BOX_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_BOX_READ","action":"READ","source":"display"},
      {"code":"DEPT_BOX_UPDATE","action":"UPDATE","source":"write"},
      {"code":"DEPT_JOB_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_JOB_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"SCHEDULE_CREATE","action":"CREATE","source":"write"},
      {"code":"SCHEDULE_DELETE","action":"DELETE","source":"write"},
      {"code":"SCHEDULE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"WORK_RPT_CREATE","action":"CREATE","source":"write"},
      {"code":"WORK_RPT_DELETE","action":"DELETE","source":"write"},
      {"code":"WORK_RPT_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/admin/workflow",
    "label": "워크플로우 프로세스 설정",
    "labelSource": "menu",
    "shellAccess": "admin-system",
    "dynamic": false,
    "entry": {"permissions":["WORKFLOW_READ"],"mode":"ANY"},
    "permissions": [
      {"code":"WORKFLOW_READ","action":"READ","source":"entry"}
    ]
  },
  {
    "route": "/approvals",
    "label": "내 결재함",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"APPROVAL_APPROVE","action":"APPROVE","source":"write"},
      {"code":"APPROVAL_CANCEL","action":"CANCEL","source":"write"},
      {"code":"APPROVAL_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/approvals/draft",
    "label": "새 결재 기안",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"APPROVAL_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/cop/cmy/selectCommunityDetail/[id]",
    "label": "커뮤니티 상세",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"BOARD_READ_ALL","action":"READ_ALL","source":"display"},
      {"code":"COMMUNITY_JOIN","action":"JOIN","source":"write"}
    ]
  },
  {
    "route": "/cop/cmy/selectCommunityList",
    "label": "커뮤니티 목록",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/help",
    "label": "도움말 센터",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"BOARD_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/help/policies/[type]",
    "label": "약관 및 정책",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/login",
    "label": "엔터프라이즈",
    "labelSource": "route-ledger",
    "shellAccess": "public",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/note",
    "label": "업무 쪽지함",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"NOTE_DELETE","action":"DELETE","source":"write"},
      {"code":"NOTE_SEND","action":"SEND","source":"write"},
      {"code":"USER_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/search",
    "label": "통합 검색",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/smart-toolkit/dept-job",
    "label": "업무 관리",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_BOX_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_BOX_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_BOX_READ","action":"READ","source":"display"},
      {"code":"DEPT_BOX_UPDATE","action":"UPDATE","source":"write"},
      {"code":"DEPT_JOB_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_JOB_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_READ","action":"READ","source":"display"}
    ]
  },
  {
    "route": "/smart-toolkit/dept-job/[id]",
    "label": "부서 업무 상세",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_JOB_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_JOB_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/smart-toolkit/dept-job/create",
    "label": "부서 업무 등록",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_JOB_CREATE","action":"CREATE","source":"write"}
    ]
  },
  {
    "route": "/smart-toolkit/schedule",
    "label": "일정",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_BOX_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_BOX_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_BOX_READ","action":"READ","source":"display"},
      {"code":"DEPT_BOX_UPDATE","action":"UPDATE","source":"write"},
      {"code":"DEPT_JOB_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_JOB_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"SCHEDULE_CREATE","action":"CREATE","source":"write"},
      {"code":"SCHEDULE_DELETE","action":"DELETE","source":"write"},
      {"code":"SCHEDULE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"WORK_RPT_CREATE","action":"CREATE","source":"write"},
      {"code":"WORK_RPT_DELETE","action":"DELETE","source":"write"},
      {"code":"WORK_RPT_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/smart-toolkit/schedule/dept",
    "label": "부서 일정 관리",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SCHEDULE_CREATE","action":"CREATE","source":"write"},
      {"code":"SCHEDULE_DELETE","action":"DELETE","source":"write"},
      {"code":"SCHEDULE_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/smart-toolkit/work-report",
    "label": "업무 보고",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"DEPT_BOX_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_BOX_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_BOX_READ","action":"READ","source":"display"},
      {"code":"DEPT_BOX_UPDATE","action":"UPDATE","source":"write"},
      {"code":"DEPT_JOB_CREATE","action":"CREATE","source":"write"},
      {"code":"DEPT_JOB_DELETE","action":"DELETE","source":"write"},
      {"code":"DEPT_READ","action":"READ","source":"display"},
      {"code":"SCHEDULE_CREATE","action":"CREATE","source":"write"},
      {"code":"SCHEDULE_DELETE","action":"DELETE","source":"write"},
      {"code":"SCHEDULE_UPDATE","action":"UPDATE","source":"write"},
      {"code":"WORK_RPT_CREATE","action":"CREATE","source":"write"},
      {"code":"WORK_RPT_DELETE","action":"DELETE","source":"write"},
      {"code":"WORK_RPT_UPDATE","action":"UPDATE","source":"write"}
    ]
  },
  {
    "route": "/survey",
    "label": "설문 참여",
    "labelSource": "menu",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/survey/[id]",
    "label": "설문 응답",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SURVEY_SUBMIT","action":"SUBMIT","source":"write"}
    ]
  },
  {
    "route": "/survey/response",
    "label": "설문조사 응답 관리",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": [
      {"code":"SURVEY_RSP_DELETE","action":"DELETE","source":"display"}
    ]
  },
  {
    "route": "/survey/response/[id]",
    "label": "설문 응답 상세",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": true,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  },
  {
    "route": "/survey/stats",
    "label": "설문 결과 통계",
    "labelSource": "route-ledger",
    "shellAccess": "authenticated",
    "dynamic": false,
    "entry": {"permissions":[],"mode":"ANY"},
    "permissions": []
  }
];

const GENERATED_ALIASES: readonly ScreenAlias[] = [
  {"route":"/admin/collaboration/address-book","target":"/admin/collaboration/address-book/select-address-book-list","kind":"page-redirect"},
  {"route":"/admin/collaboration/address-book/insert-address-book","target":"/admin/collaboration/address-book/select-address-book-list","kind":"page-redirect"},
  {"route":"/admin/collaboration/scraps/insertScrap","target":"/admin/collaboration/scraps/selectScrapList","kind":"page-redirect"},
  {"route":"/admin/collaboration/scraps/selectScrapDetail/[id]","target":"/admin/collaboration/scraps/selectScrapList","kind":"page-redirect"},
  {"route":"/admin/community","target":"/admin/help?tab=COMMUNITY","kind":"page-redirect"},
  {"route":"/admin/community/[id]","target":"/cop/cmy/selectCommunityDetail/${id}","kind":"page-redirect"},
  {"route":"/admin/community/boards","target":"/admin/help?tab=COMMUNITY","kind":"page-redirect"},
  {"route":"/admin/community/boards/[id]","target":"/admin/community/boards/insert-board-article","kind":"page-redirect"},
  {"route":"/admin/community/boards/insertBoardArticle","target":"/admin/community/boards/insert-board-article","kind":"config-redirect"},
  {"route":"/admin/community/boards/selectBoardList","target":"/admin/community/boards/select-board-list","kind":"config-redirect"},
  {"route":"/admin/community/boards/write","target":"/admin/community/boards/insert-board-article","kind":"page-redirect"},
  {"route":"/admin/observability","target":"/admin/system/monitoring/hub?tab=observability","kind":"config-redirect"},
  {"route":"/admin/sanctn/workflow","target":"/admin/workflow","kind":"config-redirect"},
  {"route":"/admin/security/audit","target":"/admin/system/monitoring/hub?tab=security","kind":"config-redirect"},
  {"route":"/admin/security/role","target":"/admin/security/authority","kind":"page-redirect"},
  {"route":"/admin/survey","target":"/admin/survey/hub","kind":"page-redirect"},
  {"route":"/admin/survey/items","target":"/admin/survey/hub?tab=questions","kind":"config-redirect"},
  {"route":"/admin/survey/manage","target":"/admin/survey/hub?tab=manage","kind":"config-redirect"},
  {"route":"/admin/survey/manage/create","target":"/admin/survey/manage","kind":"page-redirect"},
  {"route":"/admin/survey/questions","target":"/admin/survey/hub?tab=questions","kind":"config-redirect"},
  {"route":"/admin/survey/stats","target":"/admin/survey/hub?tab=stats","kind":"config-redirect"},
  {"route":"/admin/survey/templates","target":"/admin/survey/hub?tab=templates","kind":"config-redirect"},
  {"route":"/admin/system/audit","target":"/admin/system/monitoring/hub?tab=system","kind":"config-redirect"},
  {"route":"/admin/system/ism","target":"/approvals","kind":"page-redirect"},
  {"route":"/admin/system/monitoring","target":"/admin/system/monitoring/hub","kind":"page-redirect"},
  {"route":"/admin/user/login-policy","target":"/admin/user/indvdl-info-policy","kind":"config-redirect"},
  {"route":"/cop/sms/selectSmsList","target":"/admin/uss/ion/sms","kind":"config-redirect"},
  {"route":"/smart-toolkit/dept-job/insertDeptJob","target":"/smart-toolkit/dept-job/create","kind":"page-redirect"},
  {"route":"/smart-toolkit/dept-job/selectDeptJobDetail/[id]","target":"/smart-toolkit/dept-job/${id}","kind":"page-redirect"},
  {"route":"/smart-toolkit/dept-job/selectDeptJobList","target":"/smart-toolkit/dept-job","kind":"page-redirect"}
];

const GENERATED_BUNDLES: readonly PermissionBundle[] = [
  {
    "id": "basic-work",
    "name": "기본 업무",
    "description": "일반 사용자 그룹(ROLE_USER)의 기본 권한과 같아, 모든 직원에게 결재·게시판·쪽지·메일·일정·업무 보고 같은 자기 업무를 맡깁니다.",
    "protected": false,
    "permissions": [
      "ADBK_CREATE",
      "ADBK_DELETE",
      "ADBK_READ",
      "ADBK_UPDATE",
      "APPROVAL_APPROVE",
      "APPROVAL_CANCEL",
      "APPROVAL_CREATE",
      "APPROVAL_READ",
      "BANNER_READ",
      "BOARD_CREATE",
      "BOARD_DELETE",
      "BOARD_LIKE",
      "BOARD_READ",
      "BOARD_UPDATE",
      "COMMENT_CREATE",
      "COMMENT_DELETE",
      "COMMENT_READ",
      "COMMENT_UPDATE",
      "COMMUNITY_JOIN",
      "COMMUNITY_READ",
      "DASHBOARD_READ",
      "DEPT_BOX_READ",
      "DEPT_JOB_CREATE",
      "DEPT_JOB_DELETE",
      "DEPT_JOB_READ",
      "DEPT_JOB_UPDATE",
      "FILE_DELETE",
      "FILE_DOWNLOAD",
      "FILE_READ",
      "FILE_UPLOAD",
      "INFORMAL_APPROVE",
      "INFORMAL_CREATE",
      "INFORMAL_DELETE",
      "INFORMAL_READ",
      "INFORMAL_UPDATE",
      "MAIL_DELETE",
      "MAIL_READ",
      "MAIL_SEND",
      "MEMO_RPT_CREATE",
      "MEMO_RPT_DELETE",
      "MEMO_RPT_INSTRUCT",
      "MEMO_RPT_READ",
      "MEMO_RPT_UPDATE",
      "NOTE_DELETE",
      "NOTE_READ",
      "NOTE_SEND",
      "NOTI_ACK",
      "NOTI_CREATE",
      "NOTI_DELETE",
      "NOTI_READ",
      "POLL_READ",
      "POLL_VOTE",
      "POPUP_READ",
      "SATISFY_CREATE",
      "SATISFY_DELETE",
      "SATISFY_READ",
      "SATISFY_UPDATE",
      "SCHEDULE_CREATE",
      "SCHEDULE_DELETE",
      "SCHEDULE_READ",
      "SCHEDULE_UPDATE",
      "SCRAP_CREATE",
      "SCRAP_DELETE",
      "SCRAP_READ",
      "SCRAP_UPDATE",
      "STATS_READ",
      "SURVEY_READ",
      "SURVEY_SUBMIT",
      "WORK_RPT_CREATE",
      "WORK_RPT_DELETE",
      "WORK_RPT_READ",
      "WORK_RPT_UPDATE"
    ],
    "screens": [
      "/admin/notifications",
      "/admin/operation/memo-reports"
    ],
    "relatedScreens": [
      "/admin/collaboration",
      "/admin/collaboration/address-book/select-address-book-detail/[id]",
      "/admin/collaboration/address-book/select-address-book-list",
      "/admin/collaboration/mail-history",
      "/admin/collaboration/mail-send",
      "/admin/collaboration/scraps",
      "/admin/collaboration/scraps/selectScrapList",
      "/admin/community/boards/detail",
      "/admin/community/boards/insert-board-article",
      "/admin/community/boards/select-board-list",
      "/admin/survey/polls/participate",
      "/admin/work-hub",
      "/approvals",
      "/approvals/draft",
      "/cop/cmy/selectCommunityDetail/[id]",
      "/help",
      "/note",
      "/smart-toolkit/dept-job",
      "/smart-toolkit/dept-job/[id]",
      "/smart-toolkit/dept-job/create",
      "/smart-toolkit/schedule",
      "/smart-toolkit/schedule/dept",
      "/smart-toolkit/work-report",
      "/survey/[id]"
    ]
  },
  {
    "id": "board-community-operations",
    "name": "게시판·커뮤니티 운영",
    "description": "게시판 담당자에게 게시판 만들기·설정과 템플릿, 모든 게시글·댓글·만족도 평가 관리, 공지·FAQ 편집, 커뮤니티 개설과 가입 승인을 맡깁니다.",
    "protected": false,
    "permissions": [
      "BBS_MST_CREATE",
      "BBS_MST_DELETE",
      "BBS_MST_READ",
      "BBS_MST_READ_ALL",
      "BBS_MST_UPDATE",
      "BOARD_CREATE",
      "BOARD_DELETE",
      "BOARD_DELETE_ALL",
      "BOARD_READ",
      "BOARD_READ_ALL",
      "BOARD_UPDATE",
      "BOARD_UPDATE_ALL",
      "COMMENT_DELETE",
      "COMMENT_DELETE_ALL",
      "COMMENT_READ",
      "COMMENT_READ_ALL",
      "COMMENT_UPDATE",
      "COMMENT_UPDATE_ALL",
      "COMMUNITY_APPROVE",
      "COMMUNITY_CREATE_ALL",
      "COMMUNITY_DELETE_ALL",
      "COMMUNITY_READ",
      "COMMUNITY_READ_ALL",
      "COMMUNITY_REJECT",
      "COMMUNITY_UPDATE_ALL",
      "FAQ_EDIT",
      "NOTICE_EDIT",
      "SATISFY_DELETE",
      "SATISFY_DELETE_ALL",
      "SATISFY_MODERATE",
      "SATISFY_READ",
      "SATISFY_UPDATE",
      "SATISFY_UPDATE_ALL",
      "TEMPLATE_CREATE",
      "TEMPLATE_DELETE",
      "TEMPLATE_READ",
      "TEMPLATE_UPDATE"
    ],
    "screens": [
      "/admin/community/boards/maker",
      "/admin/community/boards/master",
      "/admin/community/templates",
      "/admin/sanctn/forms",
      "/admin/system/comments"
    ],
    "relatedScreens": [
      "/admin/community/boards/detail",
      "/admin/help",
      "/admin/help/faq",
      "/admin/help/qna",
      "/help"
    ]
  },
  {
    "id": "survey-poll-operations",
    "name": "설문·투표 운영",
    "description": "설문 담당자에게 모든 설문·여론조사·투표의 등록·수정·삭제와 응답 조회·삭제를 맡깁니다.",
    "protected": false,
    "permissions": [
      "POLL_CREATE",
      "POLL_DELETE",
      "POLL_DELETE_ALL",
      "POLL_READ",
      "POLL_READ_ALL",
      "POLL_UPDATE",
      "POLL_UPDATE_ALL",
      "SURVEY_CREATE_ALL",
      "SURVEY_DELETE_ALL",
      "SURVEY_READ",
      "SURVEY_READ_ALL",
      "SURVEY_RSP_DELETE",
      "SURVEY_RSP_READ",
      "SURVEY_UPDATE_ALL"
    ],
    "screens": [
      "/admin/survey/hub",
      "/admin/survey/manage/[id]",
      "/admin/survey/polls",
      "/admin/survey/polls/manage"
    ],
    "relatedScreens": []
  },
  {
    "id": "event-reward-operations",
    "name": "행사·포상 운영",
    "description": "행사 담당자에게 다른 사람이 등록한 기록까지 포함한 행사 정보·외부인사·포상 기록의 조회와 등록·수정·삭제를 맡깁니다.",
    "protected": false,
    "permissions": [
      "EVENT_CREATE",
      "EVENT_DELETE",
      "EVENT_DELETE_ALL",
      "EVENT_READ",
      "EVENT_UPDATE",
      "EVENT_UPDATE_ALL",
      "EXT_HR_CREATE",
      "EXT_HR_DELETE",
      "EXT_HR_DELETE_ALL",
      "EXT_HR_READ",
      "EXT_HR_UPDATE",
      "EXT_HR_UPDATE_ALL",
      "REWARD_CREATE",
      "REWARD_DELETE",
      "REWARD_DELETE_ALL",
      "REWARD_READ",
      "REWARD_UPDATE",
      "REWARD_UPDATE_ALL"
    ],
    "screens": [
      "/admin/operation/events",
      "/admin/operation/external-hr",
      "/admin/operation/rewards",
      "/admin/operation/rough-map"
    ],
    "relatedScreens": []
  },
  {
    "id": "user-organization",
    "name": "사용자·조직 관리",
    "description": "인사 담당자에게 계정 등록·수정·삭제와 상태 변경, 부서·부재, 부서 업무함, 사용자 분류 그룹, 로그인 정책(접속 IP·허용 시간·접속 제한) 관리를 맡깁니다(비밀번호 초기화와 추가 인증 복구는 '계정 복구' 묶음에 있습니다).",
    "protected": false,
    "permissions": [
      "ABSENCE_READ",
      "ABSENCE_UPDATE",
      "CLASS_GRP_CREATE",
      "CLASS_GRP_DELETE",
      "CLASS_GRP_READ",
      "CLASS_GRP_UPDATE",
      "DEPT_BOX_CREATE",
      "DEPT_BOX_DELETE",
      "DEPT_BOX_READ",
      "DEPT_BOX_UPDATE",
      "DEPT_CREATE",
      "DEPT_DELETE",
      "DEPT_READ",
      "DEPT_UPDATE",
      "LOGIN_POL_CREATE",
      "LOGIN_POL_DELETE",
      "LOGIN_POL_READ",
      "LOGIN_POL_UPDATE",
      "USER_CREATE",
      "USER_DELETE",
      "USER_DEPT",
      "USER_READ",
      "USER_STATUS",
      "USER_UPDATE"
    ],
    "screens": [
      "/admin/security/group",
      "/admin/security/login-policy",
      "/admin/user/absences",
      "/admin/user/departments",
      "/admin/user/indvdl-info-policy",
      "/admin/user/manage"
    ],
    "relatedScreens": [
      "/admin/work-hub",
      "/smart-toolkit/dept-job",
      "/smart-toolkit/schedule",
      "/smart-toolkit/work-report"
    ]
  },
  {
    "id": "menu-code-settings",
    "name": "메뉴·코드 설정",
    "description": "시스템 담당자에게 메뉴와 화면 연결, 공통·행정·기관 코드, 인터넷 서비스 안내, 개인정보처리방침·이용약관 관리를 맡깁니다.",
    "protected": false,
    "permissions": [
      "ADMCODE_CREATE",
      "ADMCODE_DELETE",
      "ADMCODE_READ",
      "ADMCODE_UPDATE",
      "CODE_CREATE",
      "CODE_DELETE",
      "CODE_READ",
      "CODE_UPDATE",
      "INST_CODE_CREATE",
      "INST_CODE_DELETE",
      "INST_CODE_IMPORT",
      "INST_CODE_READ",
      "INST_CODE_UPDATE",
      "MENU_CREATE",
      "MENU_DELETE",
      "MENU_READ",
      "MENU_UPDATE",
      "POLICY_READ",
      "POLICY_UPDATE",
      "SERVICE_CREATE",
      "SERVICE_DELETE",
      "SERVICE_READ",
      "SERVICE_UPDATE"
    ],
    "screens": [
      "/admin/system/codes/administ",
      "/admin/system/codes/institution",
      "/admin/system/common-code",
      "/admin/system/common-code/codes",
      "/admin/system/isg",
      "/admin/system/layout",
      "/admin/system/menus",
      "/admin/system/policies",
      "/admin/system/programs"
    ],
    "relatedScreens": []
  },
  {
    "id": "banner-popup-help",
    "name": "배너·팝업·도움말 관리",
    "description": "홍보 담당자에게 배너·팝업과 그 이미지 올리기, 도움말 콘텐츠·온라인 매뉴얼 관리를 맡깁니다.",
    "protected": false,
    "permissions": [
      "BANNER_ADMIN_READ",
      "BANNER_CREATE",
      "BANNER_DELETE",
      "BANNER_READ",
      "BANNER_UPDATE",
      "FILE_UPLOAD",
      "FILE_UPLOAD_ALL",
      "HELP_CREATE",
      "HELP_DELETE",
      "HELP_DELETE_ALL",
      "HELP_READ",
      "HELP_UPDATE",
      "HELP_UPDATE_ALL",
      "POPUP_ADMIN_READ",
      "POPUP_CREATE",
      "POPUP_DELETE",
      "POPUP_READ",
      "POPUP_UPDATE"
    ],
    "screens": [
      "/admin/system/banner",
      "/admin/system/hpcm",
      "/admin/uss/olh/online-manual"
    ],
    "relatedScreens": []
  },
  {
    "id": "messaging-operations",
    "name": "메일·문자·알림 운영",
    "description": "연락 담당자에게 모든 사용자의 메일 발송 이력 조회·삭제와 문자 발송, 알림 발송을 맡깁니다.",
    "protected": false,
    "permissions": [
      "MAIL_DELETE",
      "MAIL_DELETE_ALL",
      "MAIL_READ",
      "MAIL_READ_ALL",
      "NOTI_DISPATCH",
      "NOTI_READ",
      "SMS_READ",
      "SMS_SEND"
    ],
    "screens": [
      "/admin/notifications",
      "/admin/uss/ion/sms"
    ],
    "relatedScreens": [
      "/admin/collaboration/mail-history"
    ]
  },
  {
    "id": "log-audit-viewer",
    "name": "로그·감사 열람",
    "description": "감사 담당자에게 접속·시스템·사용자·웹·개인정보 로그의 조회와 내보내기, 민감 작업 감사 원장과 권한 변경 이력 조회, 첨부 무결성 점검, 서버 운영 지표(운영 진단) 조회, 통계·관리자 업무 현황·후속 작업 상태 조회를 맡깁니다.",
    "protected": false,
    "permissions": [
      "ADT_LOG_READ",
      "AUTHRT_AUDIT",
      "DASHBOARD_ADMIN_READ",
      "DWORK_READ",
      "FILE_AUDIT",
      "LOGIN_LOG_EXPORT",
      "LOGIN_LOG_READ",
      "OPS_READ",
      "PRIVACY_EXPORT",
      "PRIVACY_READ",
      "STATS_ADMIN_READ",
      "STATS_READ",
      "SYS_LOG_EXPORT",
      "SYS_LOG_READ",
      "USER_LOG_EXPORT",
      "USER_LOG_READ",
      "WEB_LOG_EXPORT",
      "WEB_LOG_READ"
    ],
    "screens": [
      "/admin",
      "/admin/patterns",
      "/admin/security/authority",
      "/admin/stats",
      "/admin/stats/board",
      "/admin/stats/data-usage",
      "/admin/stats/report",
      "/admin/stats/screen",
      "/admin/stats/user",
      "/admin/system/durable-jobs",
      "/admin/system/logs",
      "/admin/system/logs/audit",
      "/admin/system/logs/login",
      "/admin/system/logs/privacy",
      "/admin/system/logs/system",
      "/admin/system/logs/user",
      "/admin/system/logs/web",
      "/admin/system/monitoring/hub"
    ],
    "relatedScreens": []
  },
  {
    "id": "others-work-data-proxy",
    "name": "다른 사람 업무 자료 대행",
    "description": "업무 지원 담당자에게 다른 사람의 주소록·일정·스크랩·부서 업무·업무 보고를 대신 조회하고 고치거나 지우는 일과, 다른 사람의 메모 보고를 대신 조회하고 지우는 일을 맡깁니다(메모 보고의 본문 수정과 지시는 맡기지 않습니다). 남의 메모 보고·업무 보고에 붙은 첨부파일은 작성자 개인 자료라 이 묶음으로도 열 수 없습니다. 작성자 본인이 아니어도 남의 자료를 바꾸거나 지울 수 있으므로 꼭 필요한 담당자에게만 주세요.",
    "protected": false,
    "permissions": [
      "ADBK_DELETE",
      "ADBK_DELETE_ALL",
      "ADBK_READ",
      "ADBK_READ_ALL",
      "ADBK_UPDATE",
      "ADBK_UPDATE_ALL",
      "DEPT_JOB_DELETE",
      "DEPT_JOB_DELETE_ALL",
      "DEPT_JOB_READ",
      "DEPT_JOB_UPDATE",
      "DEPT_JOB_UPDATE_ALL",
      "MEMO_RPT_DELETE",
      "MEMO_RPT_DELETE_ALL",
      "MEMO_RPT_READ",
      "MEMO_RPT_READ_ALL",
      "SCHEDULE_DELETE",
      "SCHEDULE_DELETE_ALL",
      "SCHEDULE_READ",
      "SCHEDULE_READ_ALL",
      "SCHEDULE_UPDATE",
      "SCHEDULE_UPDATE_ALL",
      "SCRAP_DELETE",
      "SCRAP_DELETE_ALL",
      "SCRAP_READ",
      "SCRAP_READ_ALL",
      "SCRAP_UPDATE",
      "SCRAP_UPDATE_ALL",
      "WORK_RPT_DELETE",
      "WORK_RPT_DELETE_ALL",
      "WORK_RPT_READ",
      "WORK_RPT_READ_ALL",
      "WORK_RPT_UPDATE",
      "WORK_RPT_UPDATE_ALL"
    ],
    "screens": [
      "/admin/operation/memo-reports"
    ],
    "relatedScreens": [
      "/admin/collaboration",
      "/admin/collaboration/address-book/select-address-book-detail/[id]",
      "/admin/collaboration/address-book/select-address-book-list",
      "/admin/collaboration/scraps",
      "/admin/collaboration/scraps/selectScrapList",
      "/admin/work-hub",
      "/smart-toolkit/dept-job",
      "/smart-toolkit/dept-job/[id]",
      "/smart-toolkit/schedule",
      "/smart-toolkit/schedule/dept",
      "/smart-toolkit/work-report"
    ]
  },
  {
    "id": "authority-management",
    "name": "권한 관리",
    "description": "보안 책임자에게 권한 그룹 만들기·수정·삭제, 기능권한·메뉴 표시 설정, 사용자·부서 배정과 변경 이력 조회를 맡깁니다.",
    "protected": true,
    "permissions": [
      "AUTHRT_ASSIGN",
      "AUTHRT_AUDIT",
      "AUTHRT_CREATE",
      "AUTHRT_DELETE",
      "AUTHRT_GRANT",
      "AUTHRT_READ",
      "AUTHRT_UPDATE"
    ],
    "screens": [
      "/admin/security/authority",
      "/admin/security/dept-authority",
      "/admin/system/menus/by-authority"
    ],
    "relatedScreens": []
  },
  {
    "id": "account-recovery",
    "name": "계정 복구",
    "description": "지원 담당자에게 사용자 조회, 계정 상태 변경·잠금 해제, 비밀번호 초기화와 추가 인증 복구를 맡깁니다.",
    "protected": true,
    "permissions": [
      "MFA_RECOVER",
      "USER_PASSWORD",
      "USER_READ",
      "USER_STATUS"
    ],
    "screens": [
      "/admin/user/manage"
    ],
    "relatedScreens": []
  }
];

const isProjected = (route: string): boolean => Object.hasOwn(PAGE_PERMISSIONS, route);
/** 경로부 — 쿼리·해시와 끝 슬래시를 뗀다. */
const pathOf = (route: string): string => route.split(/[?#]/)[0].replace(/\/+$/, '') || '/';
/**
 * 별칭의 투영 판정. 화면 파일이 넘기는 별칭은 그 파일이 투영본에 있을 때 남는다. 앱 설정(next.config)이 넘기는 별칭은
 * 투영본에서도 앱 설정이 그대로 넘기므로, 화면 파일이 없거나 빠졌어도 목적지 화면이 투영본에 있으면 남는다.
 */
const isProjectedAlias = (alias: ScreenAlias): boolean => isProjected(alias.route)
  || (alias.kind === 'config-redirect' && alias.target !== null && isProjected(pathOf(alias.target)));

export const SCREEN_REGISTRY: readonly ScreenRegistryEntry[] = GENERATED_SCREENS.filter(screen => isProjected(screen.route));
export const SCREEN_ALIASES: readonly ScreenAlias[] = GENERATED_ALIASES.filter(isProjectedAlias);
export const PERMISSION_BUNDLES: readonly PermissionBundle[] = GENERATED_BUNDLES
  .map(bundle => ({ ...bundle, screens: bundle.screens.filter(isProjected), relatedScreens: bundle.relatedScreens.filter(isProjected) }))
  .filter(bundle => bundle.screens.length > 0);

/**
 * 보호 권한 — 서버 SENSITIVE_ADMINISTRATION_PERMISSIONS 와 같은 집합이다(생성기 계약이 대조한다), 코드 순. 그룹에 새로
 * 더하거나 빼는 저장에는 권한 설정(AUTHRT_GRANT)과 권한 배정(AUTHRT_ASSIGN)이 모두 필요하다. 화면은 사본을 두지 않는다.
 */
export const PROTECTED_PERMISSIONS: readonly PermissionCode[] = ["AUTHRT_ASSIGN", "AUTHRT_GRANT", "MFA_RECOVER", "USER_PASSWORD"];

const DYNAMIC_SEGMENT = /^\[[^.[\]]+\]$/;

/**
 * 경로가 여는 화면. 쿼리·해시를 떼고, 세그먼트 수가 같은 화면·별칭 경로 중 리터럴 세그먼트가 가장 많이 맞는 것을
 * 고른다 — 정확한 경로가 먼저, 없으면 동적 형제다(page-authorization.ts 와 같은 순서, 정적 경로가 동적 경로를
 * 이긴다). 고른 경로가 별칭이면 화면이 아니다.
 */
export function findScreen(route: string): ScreenRegistryEntry | null {
  const pathOnly = route.split(/[?#]/)[0];
  // 라우트 없는 메뉴는 '' 로 저장된다 — 빈 경로를 업무 홈('/')으로 풀지 않는다.
  if (pathOnly.trim() === '') return null;
  const normalized = pathOnly.replace(/\/+$/, '') || '/';
  const segments = normalized.split('/');
  let best: { literals: number; screen: ScreenRegistryEntry | null } | null = null;
  const candidates: ReadonlyArray<{ route: string; screen: ScreenRegistryEntry | null }> = [
    ...SCREEN_REGISTRY.map(screen => ({ route: screen.route, screen })),
    ...SCREEN_ALIASES.map(alias => ({ route: alias.route, screen: null })),
  ];
  for (const candidate of candidates) {
    const parts = candidate.route.split('/');
    if (parts.length !== segments.length) continue;
    let literals = 0;
    const matches = parts.every((part, index) => {
      if (DYNAMIC_SEGMENT.test(part)) return segments[index].length > 0;
      literals += 1;
      return part === segments[index];
    });
    if (matches && (!best || literals > best.literals)) best = { literals, screen: candidate.screen };
  }
  return best?.screen ?? null;
}
