-- 생성 base의 최초 관리자 권한과 메뉴 초기화.
-- schema-only baseline에는 업무 데이터와 권한 부여가 없으므로, 구 6개 테이블이 없는
-- 빈 신규 base에만 코드 카탈로그의 명시 OPERATION + 관리자 NAVIGATION을 기록한다.
-- 기존 제품 DB 또는 변경 이력이 있는 DB에서 회수된 권한·메뉴·회원 배정을 재부여하지 않는다.
-- 구 모델 분기는 과거 Flyway target 검증만 지원하며 새 앱의 runtime 인가에는 사용하지 않는다.
-- 신규 base는 구 테이블을 DROP하지 않는다. 최초 초기화 감사는 schema barrier의 증거이고,
-- 운영 Contract의 writer 종료·백업·복원·승인을 대체하지 않는다.
-- 실행 순서: versioned 전체 → seed_demo → seed_framework → zz_seed_base_admin → dev 전용 credentials.
-- 표식 내부 OP 값은 scripts/generate-permissions.mjs가 defaultGroups에서 생성한다.
-- 검증: BaseAdminBootstrapSeedIntegrationTest, generate-reusable-base-db.mjs.

DO $$
DECLARE
    fresh_programs boolean;
    fresh_menus    boolean;
    fresh_authorization boolean;
    legacy_model boolean;
BEGIN
    legacy_model := to_regclass('public.tb_role_info') IS NOT NULL;
    fresh_authorization := false;
    IF to_regclass('public.tb_authrt_grnt_map') IS NOT NULL AND NOT legacy_model THEN
        SELECT NOT EXISTS (SELECT 1 FROM tb_authrt_grnt_map)
           AND NOT EXISTS (SELECT 1 FROM tb_authrt_chg_hstry WHERE dmnd_idntfr <> 'bootstrap:framework')
          INTO fresh_authorization;
    END IF;
    -- 예약 그룹 마스터. ON CONFLICT는 운영자가 바꾼 이름·설명을 덮어쓰지 않는다.
    INSERT INTO tb_authrt_info (authrt_cd, authrt_nm, crt_dt) VALUES
        ('ROLE_ADMIN',  '관리자 권한',  NOW()),
        ('ROLE_SYSTEM', '시스템 권한',  NOW()),
        ('ROLE_USER',   '사용자 권한',  NOW())
    ON CONFLICT (authrt_cd) DO NOTHING;

    IF legacy_model THEN
    -- R__seed_framework 는 ROLE_ADMIN/ROLE_USER 만 시드한다. ROLE_SYSTEM 은 V2_11 소유라
    -- 생성 base 에서 소실되므로 여기서 보증한다(tb_role_prgrm_map FK 대상).
    INSERT INTO tb_role_info (role_id, role_nm, role_expln, role_crt_ymd) VALUES
        ('ROLE_SYSTEM', '최상위 시스템', '시스템 최고 관리자 역할', CURRENT_DATE)
    ON CONFLICT (role_id) DO NOTHING;

    INSERT INTO tb_authrt_role_map (authrt_cd, role_cd, crt_dt, mdfcn_dt, frst_rgtr_id, last_mdfr_id) VALUES
        ('ROLE_ADMIN',  'ROLE_ADMIN',  NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
        ('ROLE_SYSTEM', 'ROLE_SYSTEM', NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
        ('ROLE_USER',   'ROLE_USER',   NOW(), NOW(), 'SYSTEM', 'SYSTEM')
    ON CONFLICT (authrt_cd, role_cd) DO NOTHING;

    -- tb_role_hierarchy 는 V2_3 에서 생성된다. 이른 target 으로 migrate 하는 스키마 검증이
    -- repeatable 을 실행해도 죽지 않도록 존재 확인 뒤에만 시드한다(미실행 분기는 plan 되지 않음).
    IF to_regclass('public.tb_role_hierarchy') IS NOT NULL THEN
        INSERT INTO tb_role_hierarchy (higher_authrt, lower_authrt, frst_rgtr_id) VALUES
            ('ROLE_SYSTEM', 'ROLE_ADMIN', 'SYSTEM'),
            ('ROLE_ADMIN',  'ROLE_USER',  'SYSTEM')
        ON CONFLICT (higher_authrt, lower_authrt) DO NOTHING;
    END IF;

    END IF;

    -- ── 2. URL 인가 anchor — 신규 base(tb_prgrm_lst 공백)에서만 ─────────────────────
    -- DbUrlAuthorizationManager 의 fail-closed 를 푸는 최소 매핑이다. V2_11 의
    -- ADMIN_ALL/ACTUATOR_ALL 과 동일 URL·동일 롤(ROLE_ADMIN/ROLE_SYSTEM)만 부여한다 —
    -- 별칭 경로(V2_84 에서 제거된 부류)는 재도입하지 않는다(H3: 최소 권한 보존).
    SELECT NOT EXISTS (SELECT 1 FROM tb_prgrm_lst) INTO fresh_programs;
    IF fresh_programs AND to_regclass('public.tb_role_prgrm_map') IS NOT NULL THEN
        INSERT INTO tb_prgrm_lst
            (prgrm_file_nm, prgrm_korn_nm, url, prgrm_strg_path, prgrm_expln, crt_dt, mdfcn_dt, frst_rgtr_id, last_mdfr_id)
        VALUES
            ('ADMIN_ALL',    '관리자 전체',    '/api/v1/admin/**', '/api/v1/admin', 'URL 인가: 관리자 전용 API 전체 (base bootstrap)', NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
            ('ACTUATOR_ALL', 'Actuator 전체', '/actuator/**',     '/actuator',     'URL 인가: 시스템 모니터링 전체 (base bootstrap)', NOW(), NOW(), 'SYSTEM', 'SYSTEM')
        ON CONFLICT (prgrm_file_nm) DO NOTHING;

        INSERT INTO tb_role_prgrm_map (role_id, prgrm_file_nm) VALUES
            ('ROLE_ADMIN',  'ADMIN_ALL'),
            ('ROLE_SYSTEM', 'ADMIN_ALL'),
            ('ROLE_ADMIN',  'ACTUATOR_ALL'),
            ('ROLE_SYSTEM', 'ACTUATOR_ALL')
        ON CONFLICT (role_id, prgrm_file_nm) DO NOTHING;
    END IF;

    -- ── 3. 최소 관리자 메뉴 트리 — 신규 base(tb_menu_info 공백)에서만 ────────────────
    -- 모든 modern_route 는 core pack 잔존 화면이다(백엔드: foundation/business-core 소유).
    SELECT NOT EXISTS (SELECT 1 FROM tb_menu_info) INTO fresh_menus;
    IF fresh_menus AND (legacy_model OR fresh_authorization) THEN
        INSERT INTO tb_menu_info
            (menu_sn, up_menu_sn, menu_ordr, menu_nm, prgrm_file_nm, menu_expln, modern_route, use_yn, del_yn, frst_rgtr_id, crt_dt)
        VALUES
            (910, NULL, 1,  '시스템 관리 센터',   NULL, 'base 부트스트랩 관리자 메뉴', '/admin/user/manage',               'Y', 'N', 'SYSTEM', NOW()),
            (911, 910,  1,  '사용자 관리',        NULL,  NULL,                          '/admin/user/manage',               'Y', 'N', 'SYSTEM', NOW()),
            (912, 910,  2,  '부서 및 조직 관리',  NULL,  NULL,                          '/admin/user/departments',          'Y', 'N', 'SYSTEM', NOW()),
            (913, 910,  3,  '권한(보안) 정책 관리', NULL, NULL,                         '/admin/security/authority',        'Y', 'N', 'SYSTEM', NOW()),
            (914, 910,  4,  '롤 관리',            NULL,  NULL,                          '/admin/security/role',             'Y', 'N', 'SYSTEM', NOW()),
            (915, 910,  5,  '그룹 관리',          NULL,  NULL,                          '/admin/security/group',            'Y', 'N', 'SYSTEM', NOW()),
            (916, 910,  6,  '메뉴 관리',          NULL,  NULL,                          '/admin/system/menus',              'Y', 'N', 'SYSTEM', NOW()),
            (917, 910,  7,  '권한별 메뉴 관리',    NULL,  NULL,                          '/admin/system/menus/by-authority', 'Y', 'N', 'SYSTEM', NOW()),
            (918, 910,  8,  '프로그램 관리',      NULL,  NULL,                          '/admin/system/programs',           'Y', 'N', 'SYSTEM', NOW()),
            (919, 910,  9,  '공통코드 관리',      NULL,  NULL,                          '/admin/system/common-code',        'Y', 'N', 'SYSTEM', NOW()),
            (920, 910,  10, '로그 및 감사',       NULL,  NULL,                          '/admin/system/logs',               'Y', 'N', 'SYSTEM', NOW())
        ON CONFLICT (menu_sn) DO NOTHING;

        IF legacy_model THEN
            INSERT INTO tb_menu_crt_dtl(menu_sn,authrt_cd,mapng_crt_id,crt_dt)
            SELECT menu_sn,'ROLE_ADMIN','SYSTEM',CURRENT_TIMESTAMP FROM tb_menu_info
             WHERE menu_sn BETWEEN 910 AND 920
            ON CONFLICT (menu_sn,authrt_cd) DO NOTHING;
        ELSIF fresh_authorization THEN
            -- 신규 base는 통합 권한 화면을 제공하므로 폐기된 두 관리 화면을 다시 노출하지 않는다.
            DELETE FROM tb_menu_info WHERE menu_sn IN (914,917);
            INSERT INTO tb_authrt_grnt_map(authrt_cd,authrt_type_cd,authrt_grnt_cd,frst_rgtr_id,crt_dt,last_mdfr_id,mdfcn_dt)
            SELECT 'ROLE_ADMIN','NAVIGATION',menu_sn::text,'SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP
              FROM tb_menu_info WHERE menu_sn BETWEEN 910 AND 920;
            INSERT INTO tb_authrt_grnt_map(authrt_cd,authrt_type_cd,authrt_grnt_cd,frst_rgtr_id,crt_dt,last_mdfr_id,mdfcn_dt)
            SELECT seed.group_code,'OPERATION',seed.permission_code,'SYSTEM',CURRENT_TIMESTAMP,'SYSTEM',CURRENT_TIMESTAMP
            FROM (VALUES
-- BEGIN GENERATED BASE OPERATION GRANTS
        ('ROLE_ADMIN', 'ABSENCE_READ'),
        ('ROLE_SYSTEM', 'ABSENCE_READ'),
        ('ROLE_ADMIN', 'ABSENCE_UPDATE'),
        ('ROLE_SYSTEM', 'ABSENCE_UPDATE'),
        ('ROLE_ADMIN', 'ADBK_CREATE'),
        ('ROLE_SYSTEM', 'ADBK_CREATE'),
        ('ROLE_USER', 'ADBK_CREATE'),
        ('ROLE_ADMIN', 'ADBK_DELETE'),
        ('ROLE_SYSTEM', 'ADBK_DELETE'),
        ('ROLE_USER', 'ADBK_DELETE'),
        ('ROLE_ADMIN', 'ADBK_DELETE_ALL'),
        ('ROLE_SYSTEM', 'ADBK_DELETE_ALL'),
        ('ROLE_ADMIN', 'ADBK_READ'),
        ('ROLE_SYSTEM', 'ADBK_READ'),
        ('ROLE_USER', 'ADBK_READ'),
        ('ROLE_ADMIN', 'ADBK_READ_ALL'),
        ('ROLE_SYSTEM', 'ADBK_READ_ALL'),
        ('ROLE_ADMIN', 'ADBK_UPDATE'),
        ('ROLE_SYSTEM', 'ADBK_UPDATE'),
        ('ROLE_USER', 'ADBK_UPDATE'),
        ('ROLE_ADMIN', 'ADBK_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'ADBK_UPDATE_ALL'),
        ('ROLE_ADMIN', 'ADMCODE_CREATE'),
        ('ROLE_SYSTEM', 'ADMCODE_CREATE'),
        ('ROLE_ADMIN', 'ADMCODE_DELETE'),
        ('ROLE_SYSTEM', 'ADMCODE_DELETE'),
        ('ROLE_ADMIN', 'ADMCODE_READ'),
        ('ROLE_SYSTEM', 'ADMCODE_READ'),
        ('ROLE_ADMIN', 'ADMCODE_UPDATE'),
        ('ROLE_SYSTEM', 'ADMCODE_UPDATE'),
        ('ROLE_ADMIN', 'APPROVAL_APPROVE'),
        ('ROLE_SYSTEM', 'APPROVAL_APPROVE'),
        ('ROLE_USER', 'APPROVAL_APPROVE'),
        ('ROLE_ADMIN', 'APPROVAL_CANCEL'),
        ('ROLE_SYSTEM', 'APPROVAL_CANCEL'),
        ('ROLE_USER', 'APPROVAL_CANCEL'),
        ('ROLE_ADMIN', 'APPROVAL_CREATE'),
        ('ROLE_SYSTEM', 'APPROVAL_CREATE'),
        ('ROLE_USER', 'APPROVAL_CREATE'),
        ('ROLE_ADMIN', 'APPROVAL_READ'),
        ('ROLE_SYSTEM', 'APPROVAL_READ'),
        ('ROLE_USER', 'APPROVAL_READ'),
        ('ROLE_ADMIN', 'AUTHRT_ASSIGN'),
        ('ROLE_SYSTEM', 'AUTHRT_ASSIGN'),
        ('ROLE_ADMIN', 'AUTHRT_AUDIT'),
        ('ROLE_SYSTEM', 'AUTHRT_AUDIT'),
        ('ROLE_ADMIN', 'AUTHRT_CREATE'),
        ('ROLE_SYSTEM', 'AUTHRT_CREATE'),
        ('ROLE_ADMIN', 'AUTHRT_DELETE'),
        ('ROLE_SYSTEM', 'AUTHRT_DELETE'),
        ('ROLE_ADMIN', 'AUTHRT_GRANT'),
        ('ROLE_SYSTEM', 'AUTHRT_GRANT'),
        ('ROLE_ADMIN', 'AUTHRT_READ'),
        ('ROLE_SYSTEM', 'AUTHRT_READ'),
        ('ROLE_ADMIN', 'AUTHRT_UPDATE'),
        ('ROLE_SYSTEM', 'AUTHRT_UPDATE'),
        ('ROLE_ADMIN', 'BANNER_ADMIN_READ'),
        ('ROLE_SYSTEM', 'BANNER_ADMIN_READ'),
        ('ROLE_ADMIN', 'BANNER_CREATE'),
        ('ROLE_SYSTEM', 'BANNER_CREATE'),
        ('ROLE_ADMIN', 'BANNER_DELETE'),
        ('ROLE_SYSTEM', 'BANNER_DELETE'),
        ('ROLE_ADMIN', 'BANNER_READ'),
        ('ROLE_SYSTEM', 'BANNER_READ'),
        ('ROLE_USER', 'BANNER_READ'),
        ('ROLE_ADMIN', 'BANNER_UPDATE'),
        ('ROLE_SYSTEM', 'BANNER_UPDATE'),
        ('ROLE_ADMIN', 'BBS_MST_CREATE'),
        ('ROLE_SYSTEM', 'BBS_MST_CREATE'),
        ('ROLE_ADMIN', 'BBS_MST_DELETE'),
        ('ROLE_SYSTEM', 'BBS_MST_DELETE'),
        ('ROLE_ADMIN', 'BBS_MST_READ'),
        ('ROLE_SYSTEM', 'BBS_MST_READ'),
        ('ROLE_ADMIN', 'BBS_MST_READ_ALL'),
        ('ROLE_SYSTEM', 'BBS_MST_READ_ALL'),
        ('ROLE_ADMIN', 'BBS_MST_UPDATE'),
        ('ROLE_SYSTEM', 'BBS_MST_UPDATE'),
        ('ROLE_ADMIN', 'BOARD_CREATE'),
        ('ROLE_SYSTEM', 'BOARD_CREATE'),
        ('ROLE_USER', 'BOARD_CREATE'),
        ('ROLE_ADMIN', 'BOARD_DELETE'),
        ('ROLE_SYSTEM', 'BOARD_DELETE'),
        ('ROLE_USER', 'BOARD_DELETE'),
        ('ROLE_ADMIN', 'BOARD_DELETE_ALL'),
        ('ROLE_SYSTEM', 'BOARD_DELETE_ALL'),
        ('ROLE_ADMIN', 'BOARD_LIKE'),
        ('ROLE_SYSTEM', 'BOARD_LIKE'),
        ('ROLE_USER', 'BOARD_LIKE'),
        ('ROLE_ADMIN', 'BOARD_READ'),
        ('ROLE_SYSTEM', 'BOARD_READ'),
        ('ROLE_USER', 'BOARD_READ'),
        ('ROLE_ADMIN', 'BOARD_READ_ALL'),
        ('ROLE_SYSTEM', 'BOARD_READ_ALL'),
        ('ROLE_ADMIN', 'BOARD_UPDATE'),
        ('ROLE_SYSTEM', 'BOARD_UPDATE'),
        ('ROLE_USER', 'BOARD_UPDATE'),
        ('ROLE_ADMIN', 'BOARD_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'BOARD_UPDATE_ALL'),
        ('ROLE_ADMIN', 'CLASS_GRP_CREATE'),
        ('ROLE_SYSTEM', 'CLASS_GRP_CREATE'),
        ('ROLE_ADMIN', 'CLASS_GRP_DELETE'),
        ('ROLE_SYSTEM', 'CLASS_GRP_DELETE'),
        ('ROLE_ADMIN', 'CLASS_GRP_READ'),
        ('ROLE_SYSTEM', 'CLASS_GRP_READ'),
        ('ROLE_ADMIN', 'CLASS_GRP_UPDATE'),
        ('ROLE_SYSTEM', 'CLASS_GRP_UPDATE'),
        ('ROLE_ADMIN', 'CODE_CREATE'),
        ('ROLE_SYSTEM', 'CODE_CREATE'),
        ('ROLE_ADMIN', 'CODE_DELETE'),
        ('ROLE_SYSTEM', 'CODE_DELETE'),
        ('ROLE_ADMIN', 'CODE_READ'),
        ('ROLE_SYSTEM', 'CODE_READ'),
        ('ROLE_ADMIN', 'CODE_UPDATE'),
        ('ROLE_SYSTEM', 'CODE_UPDATE'),
        ('ROLE_ADMIN', 'COMMENT_CREATE'),
        ('ROLE_SYSTEM', 'COMMENT_CREATE'),
        ('ROLE_USER', 'COMMENT_CREATE'),
        ('ROLE_ADMIN', 'COMMENT_DELETE'),
        ('ROLE_SYSTEM', 'COMMENT_DELETE'),
        ('ROLE_USER', 'COMMENT_DELETE'),
        ('ROLE_ADMIN', 'COMMENT_DELETE_ALL'),
        ('ROLE_SYSTEM', 'COMMENT_DELETE_ALL'),
        ('ROLE_ADMIN', 'COMMENT_READ'),
        ('ROLE_SYSTEM', 'COMMENT_READ'),
        ('ROLE_USER', 'COMMENT_READ'),
        ('ROLE_ADMIN', 'COMMENT_READ_ALL'),
        ('ROLE_SYSTEM', 'COMMENT_READ_ALL'),
        ('ROLE_ADMIN', 'COMMENT_UPDATE'),
        ('ROLE_SYSTEM', 'COMMENT_UPDATE'),
        ('ROLE_USER', 'COMMENT_UPDATE'),
        ('ROLE_ADMIN', 'COMMENT_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'COMMENT_UPDATE_ALL'),
        ('ROLE_ADMIN', 'COMMUNITY_APPROVE'),
        ('ROLE_SYSTEM', 'COMMUNITY_APPROVE'),
        ('ROLE_ADMIN', 'COMMUNITY_CREATE_ALL'),
        ('ROLE_SYSTEM', 'COMMUNITY_CREATE_ALL'),
        ('ROLE_ADMIN', 'COMMUNITY_DELETE_ALL'),
        ('ROLE_SYSTEM', 'COMMUNITY_DELETE_ALL'),
        ('ROLE_ADMIN', 'COMMUNITY_JOIN'),
        ('ROLE_SYSTEM', 'COMMUNITY_JOIN'),
        ('ROLE_USER', 'COMMUNITY_JOIN'),
        ('ROLE_ADMIN', 'COMMUNITY_READ'),
        ('ROLE_SYSTEM', 'COMMUNITY_READ'),
        ('ROLE_USER', 'COMMUNITY_READ'),
        ('ROLE_ADMIN', 'COMMUNITY_READ_ALL'),
        ('ROLE_SYSTEM', 'COMMUNITY_READ_ALL'),
        ('ROLE_ADMIN', 'COMMUNITY_REJECT'),
        ('ROLE_SYSTEM', 'COMMUNITY_REJECT'),
        ('ROLE_ADMIN', 'COMMUNITY_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'COMMUNITY_UPDATE_ALL'),
        ('ROLE_ADMIN', 'DASHBOARD_ADMIN_READ'),
        ('ROLE_SYSTEM', 'DASHBOARD_ADMIN_READ'),
        ('ROLE_ADMIN', 'DASHBOARD_READ'),
        ('ROLE_SYSTEM', 'DASHBOARD_READ'),
        ('ROLE_USER', 'DASHBOARD_READ'),
        ('ROLE_ADMIN', 'DEPT_BOX_CREATE'),
        ('ROLE_SYSTEM', 'DEPT_BOX_CREATE'),
        ('ROLE_ADMIN', 'DEPT_BOX_DELETE'),
        ('ROLE_SYSTEM', 'DEPT_BOX_DELETE'),
        ('ROLE_ADMIN', 'DEPT_BOX_READ'),
        ('ROLE_SYSTEM', 'DEPT_BOX_READ'),
        ('ROLE_USER', 'DEPT_BOX_READ'),
        ('ROLE_ADMIN', 'DEPT_BOX_UPDATE'),
        ('ROLE_SYSTEM', 'DEPT_BOX_UPDATE'),
        ('ROLE_ADMIN', 'DEPT_CREATE'),
        ('ROLE_SYSTEM', 'DEPT_CREATE'),
        ('ROLE_ADMIN', 'DEPT_DELETE'),
        ('ROLE_SYSTEM', 'DEPT_DELETE'),
        ('ROLE_ADMIN', 'DEPT_JOB_CREATE'),
        ('ROLE_SYSTEM', 'DEPT_JOB_CREATE'),
        ('ROLE_USER', 'DEPT_JOB_CREATE'),
        ('ROLE_ADMIN', 'DEPT_JOB_DELETE'),
        ('ROLE_SYSTEM', 'DEPT_JOB_DELETE'),
        ('ROLE_USER', 'DEPT_JOB_DELETE'),
        ('ROLE_ADMIN', 'DEPT_JOB_DELETE_ALL'),
        ('ROLE_SYSTEM', 'DEPT_JOB_DELETE_ALL'),
        ('ROLE_ADMIN', 'DEPT_JOB_READ'),
        ('ROLE_SYSTEM', 'DEPT_JOB_READ'),
        ('ROLE_USER', 'DEPT_JOB_READ'),
        ('ROLE_ADMIN', 'DEPT_JOB_UPDATE'),
        ('ROLE_SYSTEM', 'DEPT_JOB_UPDATE'),
        ('ROLE_USER', 'DEPT_JOB_UPDATE'),
        ('ROLE_ADMIN', 'DEPT_JOB_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'DEPT_JOB_UPDATE_ALL'),
        ('ROLE_ADMIN', 'DEPT_READ'),
        ('ROLE_SYSTEM', 'DEPT_READ'),
        ('ROLE_ADMIN', 'DEPT_UPDATE'),
        ('ROLE_SYSTEM', 'DEPT_UPDATE'),
        ('ROLE_ADMIN', 'EVENT_CREATE'),
        ('ROLE_SYSTEM', 'EVENT_CREATE'),
        ('ROLE_ADMIN', 'EVENT_DELETE'),
        ('ROLE_SYSTEM', 'EVENT_DELETE'),
        ('ROLE_ADMIN', 'EVENT_DELETE_ALL'),
        ('ROLE_SYSTEM', 'EVENT_DELETE_ALL'),
        ('ROLE_ADMIN', 'EVENT_READ'),
        ('ROLE_SYSTEM', 'EVENT_READ'),
        ('ROLE_ADMIN', 'EVENT_UPDATE'),
        ('ROLE_SYSTEM', 'EVENT_UPDATE'),
        ('ROLE_ADMIN', 'EVENT_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'EVENT_UPDATE_ALL'),
        ('ROLE_ADMIN', 'EXT_HR_CREATE'),
        ('ROLE_SYSTEM', 'EXT_HR_CREATE'),
        ('ROLE_ADMIN', 'EXT_HR_DELETE'),
        ('ROLE_SYSTEM', 'EXT_HR_DELETE'),
        ('ROLE_ADMIN', 'EXT_HR_DELETE_ALL'),
        ('ROLE_SYSTEM', 'EXT_HR_DELETE_ALL'),
        ('ROLE_ADMIN', 'EXT_HR_READ'),
        ('ROLE_SYSTEM', 'EXT_HR_READ'),
        ('ROLE_ADMIN', 'EXT_HR_UPDATE'),
        ('ROLE_SYSTEM', 'EXT_HR_UPDATE'),
        ('ROLE_ADMIN', 'EXT_HR_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'EXT_HR_UPDATE_ALL'),
        ('ROLE_ADMIN', 'FILE_AUDIT'),
        ('ROLE_SYSTEM', 'FILE_AUDIT'),
        ('ROLE_ADMIN', 'FILE_DELETE'),
        ('ROLE_SYSTEM', 'FILE_DELETE'),
        ('ROLE_USER', 'FILE_DELETE'),
        ('ROLE_ADMIN', 'FILE_DELETE_ALL'),
        ('ROLE_SYSTEM', 'FILE_DELETE_ALL'),
        ('ROLE_ADMIN', 'FILE_DOWNLOAD'),
        ('ROLE_SYSTEM', 'FILE_DOWNLOAD'),
        ('ROLE_USER', 'FILE_DOWNLOAD'),
        ('ROLE_ADMIN', 'FILE_DOWNLOAD_ALL'),
        ('ROLE_SYSTEM', 'FILE_DOWNLOAD_ALL'),
        ('ROLE_ADMIN', 'FILE_READ'),
        ('ROLE_SYSTEM', 'FILE_READ'),
        ('ROLE_USER', 'FILE_READ'),
        ('ROLE_ADMIN', 'FILE_READ_ALL'),
        ('ROLE_SYSTEM', 'FILE_READ_ALL'),
        ('ROLE_ADMIN', 'FILE_UPLOAD'),
        ('ROLE_SYSTEM', 'FILE_UPLOAD'),
        ('ROLE_USER', 'FILE_UPLOAD'),
        ('ROLE_ADMIN', 'FILE_UPLOAD_ALL'),
        ('ROLE_SYSTEM', 'FILE_UPLOAD_ALL'),
        ('ROLE_ADMIN', 'HELP_CREATE'),
        ('ROLE_SYSTEM', 'HELP_CREATE'),
        ('ROLE_ADMIN', 'HELP_DELETE'),
        ('ROLE_SYSTEM', 'HELP_DELETE'),
        ('ROLE_ADMIN', 'HELP_DELETE_ALL'),
        ('ROLE_SYSTEM', 'HELP_DELETE_ALL'),
        ('ROLE_ADMIN', 'HELP_READ'),
        ('ROLE_SYSTEM', 'HELP_READ'),
        ('ROLE_ADMIN', 'HELP_UPDATE'),
        ('ROLE_SYSTEM', 'HELP_UPDATE'),
        ('ROLE_ADMIN', 'HELP_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'HELP_UPDATE_ALL'),
        ('ROLE_ADMIN', 'INFORMAL_APPROVE'),
        ('ROLE_SYSTEM', 'INFORMAL_APPROVE'),
        ('ROLE_USER', 'INFORMAL_APPROVE'),
        ('ROLE_ADMIN', 'INFORMAL_APPR_ADMIN'),
        ('ROLE_SYSTEM', 'INFORMAL_APPR_ADMIN'),
        ('ROLE_ADMIN', 'INFORMAL_CREATE'),
        ('ROLE_SYSTEM', 'INFORMAL_CREATE'),
        ('ROLE_USER', 'INFORMAL_CREATE'),
        ('ROLE_ADMIN', 'INFORMAL_CREATE_ALL'),
        ('ROLE_SYSTEM', 'INFORMAL_CREATE_ALL'),
        ('ROLE_ADMIN', 'INFORMAL_DELETE'),
        ('ROLE_SYSTEM', 'INFORMAL_DELETE'),
        ('ROLE_USER', 'INFORMAL_DELETE'),
        ('ROLE_ADMIN', 'INFORMAL_DELETE_ALL'),
        ('ROLE_SYSTEM', 'INFORMAL_DELETE_ALL'),
        ('ROLE_ADMIN', 'INFORMAL_READ'),
        ('ROLE_SYSTEM', 'INFORMAL_READ'),
        ('ROLE_USER', 'INFORMAL_READ'),
        ('ROLE_ADMIN', 'INFORMAL_READ_ALL'),
        ('ROLE_SYSTEM', 'INFORMAL_READ_ALL'),
        ('ROLE_ADMIN', 'INFORMAL_UPDATE'),
        ('ROLE_SYSTEM', 'INFORMAL_UPDATE'),
        ('ROLE_USER', 'INFORMAL_UPDATE'),
        ('ROLE_ADMIN', 'INFORMAL_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'INFORMAL_UPDATE_ALL'),
        ('ROLE_ADMIN', 'INST_CODE_CREATE'),
        ('ROLE_SYSTEM', 'INST_CODE_CREATE'),
        ('ROLE_ADMIN', 'INST_CODE_DELETE'),
        ('ROLE_SYSTEM', 'INST_CODE_DELETE'),
        ('ROLE_ADMIN', 'INST_CODE_IMPORT'),
        ('ROLE_SYSTEM', 'INST_CODE_IMPORT'),
        ('ROLE_ADMIN', 'INST_CODE_READ'),
        ('ROLE_SYSTEM', 'INST_CODE_READ'),
        ('ROLE_ADMIN', 'INST_CODE_UPDATE'),
        ('ROLE_SYSTEM', 'INST_CODE_UPDATE'),
        ('ROLE_ADMIN', 'LOGIN_LOG_EXPORT'),
        ('ROLE_SYSTEM', 'LOGIN_LOG_EXPORT'),
        ('ROLE_ADMIN', 'LOGIN_LOG_READ'),
        ('ROLE_SYSTEM', 'LOGIN_LOG_READ'),
        ('ROLE_ADMIN', 'LOGIN_POL_CREATE'),
        ('ROLE_SYSTEM', 'LOGIN_POL_CREATE'),
        ('ROLE_ADMIN', 'LOGIN_POL_DELETE'),
        ('ROLE_SYSTEM', 'LOGIN_POL_DELETE'),
        ('ROLE_ADMIN', 'LOGIN_POL_READ'),
        ('ROLE_SYSTEM', 'LOGIN_POL_READ'),
        ('ROLE_ADMIN', 'LOGIN_POL_UPDATE'),
        ('ROLE_SYSTEM', 'LOGIN_POL_UPDATE'),
        ('ROLE_ADMIN', 'MAIL_DELETE'),
        ('ROLE_SYSTEM', 'MAIL_DELETE'),
        ('ROLE_USER', 'MAIL_DELETE'),
        ('ROLE_ADMIN', 'MAIL_DELETE_ALL'),
        ('ROLE_SYSTEM', 'MAIL_DELETE_ALL'),
        ('ROLE_ADMIN', 'MAIL_READ'),
        ('ROLE_SYSTEM', 'MAIL_READ'),
        ('ROLE_USER', 'MAIL_READ'),
        ('ROLE_ADMIN', 'MAIL_READ_ALL'),
        ('ROLE_SYSTEM', 'MAIL_READ_ALL'),
        ('ROLE_ADMIN', 'MAIL_SEND'),
        ('ROLE_SYSTEM', 'MAIL_SEND'),
        ('ROLE_USER', 'MAIL_SEND'),
        ('ROLE_ADMIN', 'MEMO_RPT_CREATE'),
        ('ROLE_SYSTEM', 'MEMO_RPT_CREATE'),
        ('ROLE_USER', 'MEMO_RPT_CREATE'),
        ('ROLE_ADMIN', 'MEMO_RPT_DELETE'),
        ('ROLE_SYSTEM', 'MEMO_RPT_DELETE'),
        ('ROLE_USER', 'MEMO_RPT_DELETE'),
        ('ROLE_ADMIN', 'MEMO_RPT_DELETE_ALL'),
        ('ROLE_SYSTEM', 'MEMO_RPT_DELETE_ALL'),
        ('ROLE_ADMIN', 'MEMO_RPT_INSTRUCT'),
        ('ROLE_SYSTEM', 'MEMO_RPT_INSTRUCT'),
        ('ROLE_USER', 'MEMO_RPT_INSTRUCT'),
        ('ROLE_ADMIN', 'MEMO_RPT_READ'),
        ('ROLE_SYSTEM', 'MEMO_RPT_READ'),
        ('ROLE_USER', 'MEMO_RPT_READ'),
        ('ROLE_ADMIN', 'MEMO_RPT_READ_ALL'),
        ('ROLE_SYSTEM', 'MEMO_RPT_READ_ALL'),
        ('ROLE_ADMIN', 'MEMO_RPT_UPDATE'),
        ('ROLE_SYSTEM', 'MEMO_RPT_UPDATE'),
        ('ROLE_USER', 'MEMO_RPT_UPDATE'),
        ('ROLE_ADMIN', 'MEMO_RPT_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'MEMO_RPT_UPDATE_ALL'),
        ('ROLE_ADMIN', 'MENU_CREATE'),
        ('ROLE_SYSTEM', 'MENU_CREATE'),
        ('ROLE_ADMIN', 'MENU_DELETE'),
        ('ROLE_SYSTEM', 'MENU_DELETE'),
        ('ROLE_ADMIN', 'MENU_READ'),
        ('ROLE_SYSTEM', 'MENU_READ'),
        ('ROLE_ADMIN', 'MENU_UPDATE'),
        ('ROLE_SYSTEM', 'MENU_UPDATE'),
        ('ROLE_ADMIN', 'NETWORK_CREATE'),
        ('ROLE_SYSTEM', 'NETWORK_CREATE'),
        ('ROLE_ADMIN', 'NETWORK_DELETE'),
        ('ROLE_SYSTEM', 'NETWORK_DELETE'),
        ('ROLE_ADMIN', 'NETWORK_READ'),
        ('ROLE_SYSTEM', 'NETWORK_READ'),
        ('ROLE_ADMIN', 'NETWORK_UPDATE'),
        ('ROLE_SYSTEM', 'NETWORK_UPDATE'),
        ('ROLE_ADMIN', 'NOTE_DELETE'),
        ('ROLE_SYSTEM', 'NOTE_DELETE'),
        ('ROLE_USER', 'NOTE_DELETE'),
        ('ROLE_ADMIN', 'NOTE_READ'),
        ('ROLE_SYSTEM', 'NOTE_READ'),
        ('ROLE_USER', 'NOTE_READ'),
        ('ROLE_ADMIN', 'NOTE_SEND'),
        ('ROLE_SYSTEM', 'NOTE_SEND'),
        ('ROLE_USER', 'NOTE_SEND'),
        ('ROLE_ADMIN', 'NOTI_ACK'),
        ('ROLE_SYSTEM', 'NOTI_ACK'),
        ('ROLE_USER', 'NOTI_ACK'),
        ('ROLE_ADMIN', 'NOTI_CREATE'),
        ('ROLE_SYSTEM', 'NOTI_CREATE'),
        ('ROLE_USER', 'NOTI_CREATE'),
        ('ROLE_ADMIN', 'NOTI_DELETE'),
        ('ROLE_SYSTEM', 'NOTI_DELETE'),
        ('ROLE_USER', 'NOTI_DELETE'),
        ('ROLE_ADMIN', 'NOTI_DISPATCH'),
        ('ROLE_SYSTEM', 'NOTI_DISPATCH'),
        ('ROLE_ADMIN', 'NOTI_READ'),
        ('ROLE_SYSTEM', 'NOTI_READ'),
        ('ROLE_USER', 'NOTI_READ'),
        ('ROLE_ADMIN', 'OPS_READ'),
        ('ROLE_SYSTEM', 'OPS_READ'),
        ('ROLE_ADMIN', 'POLICY_READ'),
        ('ROLE_SYSTEM', 'POLICY_READ'),
        ('ROLE_ADMIN', 'POLICY_UPDATE'),
        ('ROLE_SYSTEM', 'POLICY_UPDATE'),
        ('ROLE_ADMIN', 'POLL_CREATE'),
        ('ROLE_SYSTEM', 'POLL_CREATE'),
        ('ROLE_ADMIN', 'POLL_DELETE'),
        ('ROLE_SYSTEM', 'POLL_DELETE'),
        ('ROLE_ADMIN', 'POLL_DELETE_ALL'),
        ('ROLE_SYSTEM', 'POLL_DELETE_ALL'),
        ('ROLE_ADMIN', 'POLL_READ'),
        ('ROLE_SYSTEM', 'POLL_READ'),
        ('ROLE_USER', 'POLL_READ'),
        ('ROLE_ADMIN', 'POLL_READ_ALL'),
        ('ROLE_SYSTEM', 'POLL_READ_ALL'),
        ('ROLE_ADMIN', 'POLL_UPDATE'),
        ('ROLE_SYSTEM', 'POLL_UPDATE'),
        ('ROLE_ADMIN', 'POLL_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'POLL_UPDATE_ALL'),
        ('ROLE_ADMIN', 'POLL_VOTE'),
        ('ROLE_SYSTEM', 'POLL_VOTE'),
        ('ROLE_USER', 'POLL_VOTE'),
        ('ROLE_ADMIN', 'POPUP_ADMIN_READ'),
        ('ROLE_SYSTEM', 'POPUP_ADMIN_READ'),
        ('ROLE_ADMIN', 'POPUP_CREATE'),
        ('ROLE_SYSTEM', 'POPUP_CREATE'),
        ('ROLE_ADMIN', 'POPUP_DELETE'),
        ('ROLE_SYSTEM', 'POPUP_DELETE'),
        ('ROLE_ADMIN', 'POPUP_READ'),
        ('ROLE_SYSTEM', 'POPUP_READ'),
        ('ROLE_USER', 'POPUP_READ'),
        ('ROLE_ADMIN', 'POPUP_UPDATE'),
        ('ROLE_SYSTEM', 'POPUP_UPDATE'),
        ('ROLE_ADMIN', 'PRIVACY_EXPORT'),
        ('ROLE_ADMIN', 'PRIVACY_READ'),
        ('ROLE_ADMIN', 'PROGRAM_CREATE'),
        ('ROLE_SYSTEM', 'PROGRAM_CREATE'),
        ('ROLE_ADMIN', 'PROGRAM_DELETE'),
        ('ROLE_SYSTEM', 'PROGRAM_DELETE'),
        ('ROLE_ADMIN', 'PROGRAM_READ'),
        ('ROLE_SYSTEM', 'PROGRAM_READ'),
        ('ROLE_ADMIN', 'PROGRAM_UPDATE'),
        ('ROLE_SYSTEM', 'PROGRAM_UPDATE'),
        ('ROLE_ADMIN', 'REWARD_CREATE'),
        ('ROLE_SYSTEM', 'REWARD_CREATE'),
        ('ROLE_ADMIN', 'REWARD_DELETE'),
        ('ROLE_SYSTEM', 'REWARD_DELETE'),
        ('ROLE_ADMIN', 'REWARD_DELETE_ALL'),
        ('ROLE_SYSTEM', 'REWARD_DELETE_ALL'),
        ('ROLE_ADMIN', 'REWARD_READ'),
        ('ROLE_SYSTEM', 'REWARD_READ'),
        ('ROLE_ADMIN', 'REWARD_UPDATE'),
        ('ROLE_SYSTEM', 'REWARD_UPDATE'),
        ('ROLE_ADMIN', 'REWARD_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'REWARD_UPDATE_ALL'),
        ('ROLE_ADMIN', 'SATISFY_CREATE'),
        ('ROLE_SYSTEM', 'SATISFY_CREATE'),
        ('ROLE_USER', 'SATISFY_CREATE'),
        ('ROLE_ADMIN', 'SATISFY_DELETE'),
        ('ROLE_SYSTEM', 'SATISFY_DELETE'),
        ('ROLE_USER', 'SATISFY_DELETE'),
        ('ROLE_ADMIN', 'SATISFY_DELETE_ALL'),
        ('ROLE_SYSTEM', 'SATISFY_DELETE_ALL'),
        ('ROLE_ADMIN', 'SATISFY_MODERATE'),
        ('ROLE_SYSTEM', 'SATISFY_MODERATE'),
        ('ROLE_ADMIN', 'SATISFY_READ'),
        ('ROLE_SYSTEM', 'SATISFY_READ'),
        ('ROLE_USER', 'SATISFY_READ'),
        ('ROLE_ADMIN', 'SATISFY_UPDATE'),
        ('ROLE_SYSTEM', 'SATISFY_UPDATE'),
        ('ROLE_USER', 'SATISFY_UPDATE'),
        ('ROLE_ADMIN', 'SATISFY_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'SATISFY_UPDATE_ALL'),
        ('ROLE_ADMIN', 'SCHEDULE_CREATE'),
        ('ROLE_SYSTEM', 'SCHEDULE_CREATE'),
        ('ROLE_USER', 'SCHEDULE_CREATE'),
        ('ROLE_ADMIN', 'SCHEDULE_DELETE'),
        ('ROLE_SYSTEM', 'SCHEDULE_DELETE'),
        ('ROLE_USER', 'SCHEDULE_DELETE'),
        ('ROLE_ADMIN', 'SCHEDULE_DELETE_ALL'),
        ('ROLE_SYSTEM', 'SCHEDULE_DELETE_ALL'),
        ('ROLE_ADMIN', 'SCHEDULE_READ'),
        ('ROLE_SYSTEM', 'SCHEDULE_READ'),
        ('ROLE_USER', 'SCHEDULE_READ'),
        ('ROLE_ADMIN', 'SCHEDULE_READ_ALL'),
        ('ROLE_SYSTEM', 'SCHEDULE_READ_ALL'),
        ('ROLE_ADMIN', 'SCHEDULE_UPDATE'),
        ('ROLE_SYSTEM', 'SCHEDULE_UPDATE'),
        ('ROLE_USER', 'SCHEDULE_UPDATE'),
        ('ROLE_ADMIN', 'SCHEDULE_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'SCHEDULE_UPDATE_ALL'),
        ('ROLE_ADMIN', 'SCRAP_CREATE'),
        ('ROLE_SYSTEM', 'SCRAP_CREATE'),
        ('ROLE_USER', 'SCRAP_CREATE'),
        ('ROLE_ADMIN', 'SCRAP_DELETE'),
        ('ROLE_SYSTEM', 'SCRAP_DELETE'),
        ('ROLE_USER', 'SCRAP_DELETE'),
        ('ROLE_ADMIN', 'SCRAP_DELETE_ALL'),
        ('ROLE_SYSTEM', 'SCRAP_DELETE_ALL'),
        ('ROLE_ADMIN', 'SCRAP_READ'),
        ('ROLE_SYSTEM', 'SCRAP_READ'),
        ('ROLE_USER', 'SCRAP_READ'),
        ('ROLE_ADMIN', 'SCRAP_READ_ALL'),
        ('ROLE_SYSTEM', 'SCRAP_READ_ALL'),
        ('ROLE_ADMIN', 'SCRAP_UPDATE'),
        ('ROLE_SYSTEM', 'SCRAP_UPDATE'),
        ('ROLE_USER', 'SCRAP_UPDATE'),
        ('ROLE_ADMIN', 'SCRAP_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'SCRAP_UPDATE_ALL'),
        ('ROLE_ADMIN', 'SERVICE_CREATE'),
        ('ROLE_SYSTEM', 'SERVICE_CREATE'),
        ('ROLE_ADMIN', 'SERVICE_DELETE'),
        ('ROLE_SYSTEM', 'SERVICE_DELETE'),
        ('ROLE_ADMIN', 'SERVICE_READ'),
        ('ROLE_SYSTEM', 'SERVICE_READ'),
        ('ROLE_ADMIN', 'SERVICE_UPDATE'),
        ('ROLE_SYSTEM', 'SERVICE_UPDATE'),
        ('ROLE_ADMIN', 'SMS_READ'),
        ('ROLE_SYSTEM', 'SMS_READ'),
        ('ROLE_ADMIN', 'SMS_SEND'),
        ('ROLE_SYSTEM', 'SMS_SEND'),
        ('ROLE_ADMIN', 'STATS_ADMIN_READ'),
        ('ROLE_SYSTEM', 'STATS_ADMIN_READ'),
        ('ROLE_ADMIN', 'STATS_READ'),
        ('ROLE_SYSTEM', 'STATS_READ'),
        ('ROLE_USER', 'STATS_READ'),
        ('ROLE_ADMIN', 'SURVEY_CREATE_ALL'),
        ('ROLE_SYSTEM', 'SURVEY_CREATE_ALL'),
        ('ROLE_ADMIN', 'SURVEY_DELETE_ALL'),
        ('ROLE_SYSTEM', 'SURVEY_DELETE_ALL'),
        ('ROLE_ADMIN', 'SURVEY_READ'),
        ('ROLE_SYSTEM', 'SURVEY_READ'),
        ('ROLE_USER', 'SURVEY_READ'),
        ('ROLE_ADMIN', 'SURVEY_READ_ALL'),
        ('ROLE_SYSTEM', 'SURVEY_READ_ALL'),
        ('ROLE_ADMIN', 'SURVEY_RSP_DELETE'),
        ('ROLE_SYSTEM', 'SURVEY_RSP_DELETE'),
        ('ROLE_ADMIN', 'SURVEY_RSP_READ'),
        ('ROLE_SYSTEM', 'SURVEY_RSP_READ'),
        ('ROLE_ADMIN', 'SURVEY_SUBMIT'),
        ('ROLE_SYSTEM', 'SURVEY_SUBMIT'),
        ('ROLE_USER', 'SURVEY_SUBMIT'),
        ('ROLE_ADMIN', 'SURVEY_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'SURVEY_UPDATE_ALL'),
        ('ROLE_ADMIN', 'SYS_LOG_EXPORT'),
        ('ROLE_SYSTEM', 'SYS_LOG_EXPORT'),
        ('ROLE_ADMIN', 'SYS_LOG_READ'),
        ('ROLE_SYSTEM', 'SYS_LOG_READ'),
        ('ROLE_ADMIN', 'TEMPLATE_CREATE'),
        ('ROLE_SYSTEM', 'TEMPLATE_CREATE'),
        ('ROLE_ADMIN', 'TEMPLATE_DELETE'),
        ('ROLE_SYSTEM', 'TEMPLATE_DELETE'),
        ('ROLE_ADMIN', 'TEMPLATE_READ'),
        ('ROLE_SYSTEM', 'TEMPLATE_READ'),
        ('ROLE_ADMIN', 'TEMPLATE_UPDATE'),
        ('ROLE_SYSTEM', 'TEMPLATE_UPDATE'),
        ('ROLE_ADMIN', 'USER_CREATE'),
        ('ROLE_SYSTEM', 'USER_CREATE'),
        ('ROLE_ADMIN', 'USER_DELETE'),
        ('ROLE_SYSTEM', 'USER_DELETE'),
        ('ROLE_ADMIN', 'USER_DEPT'),
        ('ROLE_SYSTEM', 'USER_DEPT'),
        ('ROLE_ADMIN', 'USER_LOG_EXPORT'),
        ('ROLE_SYSTEM', 'USER_LOG_EXPORT'),
        ('ROLE_ADMIN', 'USER_LOG_READ'),
        ('ROLE_SYSTEM', 'USER_LOG_READ'),
        ('ROLE_ADMIN', 'USER_PASSWORD'),
        ('ROLE_SYSTEM', 'USER_PASSWORD'),
        ('ROLE_ADMIN', 'USER_READ'),
        ('ROLE_SYSTEM', 'USER_READ'),
        ('ROLE_ADMIN', 'USER_STATUS'),
        ('ROLE_SYSTEM', 'USER_STATUS'),
        ('ROLE_ADMIN', 'USER_UPDATE'),
        ('ROLE_SYSTEM', 'USER_UPDATE'),
        ('ROLE_ADMIN', 'WEB_LOG_EXPORT'),
        ('ROLE_SYSTEM', 'WEB_LOG_EXPORT'),
        ('ROLE_ADMIN', 'WEB_LOG_READ'),
        ('ROLE_SYSTEM', 'WEB_LOG_READ'),
        ('ROLE_ADMIN', 'WORKFLOW_READ'),
        ('ROLE_SYSTEM', 'WORKFLOW_READ'),
        ('ROLE_ADMIN', 'WORK_RPT_CREATE'),
        ('ROLE_SYSTEM', 'WORK_RPT_CREATE'),
        ('ROLE_USER', 'WORK_RPT_CREATE'),
        ('ROLE_ADMIN', 'WORK_RPT_DELETE'),
        ('ROLE_SYSTEM', 'WORK_RPT_DELETE'),
        ('ROLE_USER', 'WORK_RPT_DELETE'),
        ('ROLE_ADMIN', 'WORK_RPT_DELETE_ALL'),
        ('ROLE_SYSTEM', 'WORK_RPT_DELETE_ALL'),
        ('ROLE_ADMIN', 'WORK_RPT_READ'),
        ('ROLE_SYSTEM', 'WORK_RPT_READ'),
        ('ROLE_USER', 'WORK_RPT_READ'),
        ('ROLE_ADMIN', 'WORK_RPT_READ_ALL'),
        ('ROLE_SYSTEM', 'WORK_RPT_READ_ALL'),
        ('ROLE_ADMIN', 'WORK_RPT_UPDATE'),
        ('ROLE_SYSTEM', 'WORK_RPT_UPDATE'),
        ('ROLE_USER', 'WORK_RPT_UPDATE'),
        ('ROLE_ADMIN', 'WORK_RPT_UPDATE_ALL'),
        ('ROLE_SYSTEM', 'WORK_RPT_UPDATE_ALL')
-- END GENERATED BASE OPERATION GRANTS
            ) seed(group_code,permission_code);
            INSERT INTO tb_authrt_chg_hstry
                (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,authrt_type_cd,authrt_grnt_cd,
                 chg_artcl_nm,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
            SELECT 'bootstrap:base','bootstrap:base','GROUP_GRANT','MIGRATE',authrt_cd,authrt_type_cd,authrt_grnt_cd,
                   'initial_base_grant',authrt_grnt_cd,'schema-only base 최초 초기화; 기존 운영 권한 재부여 금지','SYSTEM',CURRENT_TIMESTAMP
              FROM tb_authrt_grnt_map;
            INSERT INTO tb_authrt_chg_hstry
                (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
                 chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
            VALUES ('bootstrap:base','bootstrap:base','GROUP','UPDATE','ROLE_ADMIN','legacy_authorization_contract',
                'schema-only baseline: legacy authorization tables absent',
                'tb_authrt_info,tb_authrt_user_map,tb_authrt_grnt_map,tb_authrt_chg_hstry',
                '빈 신규 base 최초 초기화; 구 테이블 DROP 없음; 운영 전환 승인을 대체하지 않음','SYSTEM',CURRENT_TIMESTAMP);
        END IF;

        -- 명시 번호 시드 뒤 IDENTITY 채번 충돌 방지 (V2_76 과 동일한 규율)
        PERFORM setval('sq_menu_sn', (SELECT max(menu_sn) FROM tb_menu_info), true);
    END IF;
END $$;
