-- User Search Indexes
CREATE INDEX IF NOT EXISTS IX_NEMPLYRINFO_USER_NM ON NEMPLYRINFO (USER_NM);
CREATE INDEX IF NOT EXISTS IX_NEMPLYRINFO_EMAIL ON NEMPLYRINFO (EMAIL_ADRES);
CREATE INDEX IF NOT EXISTS IX_NEMPLYRINFO_SBSCRB_DE ON NEMPLYRINFO (SBSCRB_DE);

-- Authority Search Index
-- CREATE INDEX IF NOT EXISTS IX_NUSER_AUTHORITY_ESNTL ON NUSER_AUTHORITY (ESNTL_ID);
