-- JWT Refresh Token Table
CREATE TABLE IF NOT EXISTS NREFRESH_TOKEN (
    USER_ID VARCHAR(20) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRY_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_NREFRESH_TOKEN PRIMARY KEY (USER_ID),
    CONSTRAINT UK_NREFRESH_TOKEN_TOKEN UNIQUE (TOKEN)
);

COMMENT ON TABLE NREFRESH_TOKEN IS 'JWT 리프레시 토큰 저장 테이블';
COMMENT ON COLUMN NREFRESH_TOKEN.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN NREFRESH_TOKEN.TOKEN IS '리프레시 토큰 값';
COMMENT ON COLUMN NREFRESH_TOKEN.EXPIRY_DATE IS '토큰 만료 일시';
