-- DEC-OPS-176(DIP B5 F11): 공통코드(분류·그룹·상세)의 등록·수정·삭제를 같은 트랜잭션에서 이력으로 남긴다.
--
-- 종전에는 코드 행에 최종 수정자·일시만 덮어써져, 누가 언제 코드 명칭을 바꾸거나 쓰지 않게 했는지 남는 곳이 없었다.
-- 권한 변경 이력(tb_authrt_chg_hstry, V2_98)과 같은 용어·형태를 쓴다. 이력은 고치지 않고 추가만 한다.
-- 대상 모양: 분류(CLSF)는 분류 코드, 그룹(CODE)은 그룹 ID, 상세(DTL)는 그룹 ID·상세 코드가 있어야 한다.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE tb_com_cd_chg_hstry (
    com_cd_chg_hstry_sn bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_com_cd_chg_hstry_sn),
    chg_trgt_type_cd varchar(12) NOT NULL,
    chg_type_cd varchar(12) NOT NULL,
    clsf_cd varchar(12),
    cd_id varchar(20),
    dtl_cd varchar(12),
    chg_artcl_nm varchar(100) NOT NULL,
    chg_bfr_cn varchar(4000),
    chg_aftr_cn varchar(4000),
    chg_user_idntfr varchar(20),
    frst_rgtr_id varchar(20) NOT NULL,
    crt_dt timestamp without time zone NOT NULL,
    CONSTRAINT pk_tb_com_cd_chg_hstry PRIMARY KEY (com_cd_chg_hstry_sn),
    CONSTRAINT ck_tb_com_cd_chg_hstry_chg_trgt_type_cd
        CHECK (chg_trgt_type_cd IN ('CLSF','CODE','DTL')),
    CONSTRAINT ck_tb_com_cd_chg_hstry_chg_type_cd
        CHECK (chg_type_cd IN ('ADD','UPDATE','REMOVE')),
    CONSTRAINT ck_tb_com_cd_chg_hstry_target_shape CHECK (
        (chg_trgt_type_cd='CLSF' AND clsf_cd IS NOT NULL AND dtl_cd IS NULL)
        OR (chg_trgt_type_cd='CODE' AND cd_id IS NOT NULL AND dtl_cd IS NULL)
        OR (chg_trgt_type_cd='DTL' AND cd_id IS NOT NULL AND dtl_cd IS NOT NULL)
    ),
    CONSTRAINT ck_tb_com_cd_chg_hstry_change_value CHECK (
        chg_bfr_cn IS NOT NULL OR chg_aftr_cn IS NOT NULL
    )
);
CREATE INDEX ix_tb_com_cd_chg_hstry_cd_id ON tb_com_cd_chg_hstry(cd_id,crt_dt,com_cd_chg_hstry_sn);
CREATE INDEX ix_tb_com_cd_chg_hstry_crt_dt ON tb_com_cd_chg_hstry(crt_dt,com_cd_chg_hstry_sn);

COMMENT ON TABLE tb_com_cd_chg_hstry IS '공통코드변경이력';
COMMENT ON COLUMN tb_com_cd_chg_hstry.com_cd_chg_hstry_sn IS '공통코드변경이력일련번호';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_trgt_type_cd IS '변경대상유형코드 (CLSF 분류·CODE 그룹·DTL 상세)';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_type_cd IS '변경유형코드 (ADD 등록·UPDATE 수정·REMOVE 삭제)';
COMMENT ON COLUMN tb_com_cd_chg_hstry.clsf_cd IS '분류코드';
COMMENT ON COLUMN tb_com_cd_chg_hstry.cd_id IS '코드ID (그룹)';
COMMENT ON COLUMN tb_com_cd_chg_hstry.dtl_cd IS '상세코드';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_artcl_nm IS '변경항목명';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_bfr_cn IS '변경전내용';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_aftr_cn IS '변경후내용';
COMMENT ON COLUMN tb_com_cd_chg_hstry.chg_user_idntfr IS '변경자 esntlId 감사 사본';
COMMENT ON COLUMN tb_com_cd_chg_hstry.frst_rgtr_id IS '공통 감사 loginId';
COMMENT ON COLUMN tb_com_cd_chg_hstry.crt_dt IS '생성일시';
