-- V2_122: 비공식결재(결재) 임시저장(2026-10-03 결재 동선 개선 D3, DEC-OPS-219).
-- 상신하지 않은 기안을 기안자 본인만 다시 여는 서버 임시저장이다. 결재 표에 상태를 더하지 않고 별도 표 두 개를 둔다 —
-- 대기함·알림·통계·결재선 제안의 질의는 결재 표(tb_ifml_atrz_*)만 읽으므로 임시저장이 구조적으로 섞이지 않는다.
-- 결재 표는 바꾸지 않는다(Expand 전용). 결재 첨부는 두지 않는다(GAP-DIP-001 ②, 첨부 원장 등재가 선행이다).
-- 신청자(aplcnt_id)와 결재선 사람(user_id)은 esntlId 이고, frst_rgtr_id·last_mdfr_id 는 공통 감사 계약대로 로그인 ID 다.
-- 보존: 만료 없음, 1인 20건(서비스가 사용자 행을 잠근 뒤 센다), 사용자 행이 지워지면 함께 지워진다
--   (ON DELETE CASCADE — 미상신 본문은 본인만 읽는 개인 데이터라 고아로 남기지 않는다, V2_112 선례). 관리자 열람 경로는 없다.
-- 결재선 사람(user_id)에는 FK 를 두지 않는다(tb_ifml_atrz_dtl 과 같다) — 남의 임시저장에 든 사람을 지울 때 막히거나
--   남의 임시저장이 조용히 바뀌지 않게 한다. 다시 열 때 지금 자격으로 판정한다.
-- 버전 컬럼은 결재 표(V2_0 tb_ifml_atrz_info.version)와 같은 비표준 `version integer` 다 — @Version 은 정수형만 받고,
--   표준 숫자 도메인은 NUMERIC 이라 쓸 수 없다(헌법 제9조 보고 대상, DEC-OPS-219).
-- H1: DOC_TTL 명V256·DOC_CN 내용V4000·ATRZ_SEQ 순서N10·ACRD_YN 여부C1·USER_ID 명V20·IFML_ATRZ_SN 일련번호N19 를 아래
--   DO 블록이 다시 확인한다. TASK_SE_CD·APLCNT_ID 는 V2_0 결재 표의 레거시 컬럼명을 그대로 쓴다.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- 표준 단어는 이미 등록돼 있다(V2_1). 새 복합 용어 하나만 등록한다(V2_78 형식).
DO $$
DECLARE
    expected RECORD;
BEGIN
    FOR expected IN SELECT * FROM (VALUES
        ('비공식','IFML'), ('결재','ATRZ'), ('임시','TMPR'), ('저장','STRG'), ('일련번호','SN')
    ) AS words(word_name,eng_abbr)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM meta_standard_words w
                       WHERE w.word_name=expected.word_name AND w.eng_abbr=expected.eng_abbr
                         AND w.rprs_yn='Y') THEN
            RAISE EXCEPTION 'Approval temporary draft standard word is missing or not representative: %',expected.eng_abbr;
        END IF;
    END LOOP;
END $$;

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('비공식결재임시저장일련번호', 'IFML_ATRZ_TMPR_STRG_SN',
        '상신하지 않은 비공식 결재 기안의 임시저장에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
DECLARE
    expected RECORD;
BEGIN
    FOR expected IN SELECT * FROM (VALUES
        ('IFML_ATRZ_TMPR_STRG_SN','비공식결재임시저장일련번호','일련번호N19'),
        ('IFML_ATRZ_SN','비공식결재일련번호','일련번호N19'),
        ('DOC_TTL','문서제목','명V256'), ('DOC_CN','문서내용','내용V4000'),
        ('ATRZ_SEQ','결재순서','순서N10'), ('ACRD_YN','합의여부','여부C1'),
        ('USER_ID','사용자아이디','명V20')
    ) AS terms(eng_abbr,term_name,domain_name)
    LOOP
        IF (SELECT count(*) FROM meta_standard_terms t
            WHERE t.eng_abbr=expected.eng_abbr AND t.term_name=expected.term_name
              AND t.domain_name=expected.domain_name) <> 1 THEN
            RAISE EXCEPTION 'Approval temporary draft standard term conflict: %',expected.eng_abbr;
        END IF;
    END LOOP;
END $$;

CREATE TABLE tb_ifml_atrz_tmpr_strg (
    ifml_atrz_tmpr_strg_sn bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_ifml_atrz_tmpr_strg_sn),
    aplcnt_id varchar(20) NOT NULL,
    task_se_cd varchar(12),
    doc_ttl varchar(256),
    doc_cn varchar(4000),
    version integer NOT NULL DEFAULT 0,
    frst_rgtr_id varchar(20),
    crt_dt timestamp without time zone NOT NULL,
    last_mdfr_id varchar(20),
    mdfcn_dt timestamp without time zone NOT NULL,
    CONSTRAINT pk_tb_ifml_atrz_tmpr_strg PRIMARY KEY (ifml_atrz_tmpr_strg_sn),
    CONSTRAINT fk_tb_ifml_atrz_tmpr_strg_tb_user_info FOREIGN KEY (aplcnt_id)
        REFERENCES tb_user_info (esntl_id) ON DELETE CASCADE,
    CONSTRAINT ck_tb_ifml_atrz_tmpr_strg_version CHECK (version >= 0)
);
CREATE INDEX ix_tb_ifml_atrz_tmpr_strg_aplcnt_id
    ON tb_ifml_atrz_tmpr_strg (aplcnt_id, mdfcn_dt, ifml_atrz_tmpr_strg_sn);

CREATE TABLE tb_ifml_atrz_tmpr_strg_dtl (
    ifml_atrz_tmpr_strg_sn bigint NOT NULL,
    atrz_seq numeric(10, 0) NOT NULL,
    user_id varchar(20) NOT NULL,
    acrd_yn varchar(1) NOT NULL DEFAULT 'N',
    frst_rgtr_id varchar(20),
    crt_dt timestamp without time zone NOT NULL,
    last_mdfr_id varchar(20),
    mdfcn_dt timestamp without time zone NOT NULL,
    CONSTRAINT pk_tb_ifml_atrz_tmpr_strg_dtl PRIMARY KEY (ifml_atrz_tmpr_strg_sn, atrz_seq, user_id),
    CONSTRAINT fk_tb_ifml_atrz_tmpr_strg_dtl_tb_ifml_atrz_tmpr_strg
        FOREIGN KEY (ifml_atrz_tmpr_strg_sn) REFERENCES tb_ifml_atrz_tmpr_strg (ifml_atrz_tmpr_strg_sn)
        ON DELETE CASCADE,
    CONSTRAINT ck_tb_ifml_atrz_tmpr_strg_dtl_atrz_seq CHECK (atrz_seq BETWEEN 1 AND 10),
    CONSTRAINT ck_tb_ifml_atrz_tmpr_strg_dtl_acrd_yn CHECK (acrd_yn IN ('N', 'Y'))
);

COMMENT ON TABLE tb_ifml_atrz_tmpr_strg IS '비공식결재임시저장 (상신 전 기안, 기안자 본인만 열람·수정)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.ifml_atrz_tmpr_strg_sn IS '비공식결재임시저장일련번호';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.aplcnt_id IS '신청자ID (기안자, esntlId; 사용자 행과 함께 지워진다)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.task_se_cd IS '업무구분코드 (공통코드 COM075, 비어 있을 수 있다)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.doc_ttl IS '문서제목';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.doc_cn IS '문서내용';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.version IS '버전 (낙관적 잠금, 저장할 때마다 오른다)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.frst_rgtr_id IS '최초등록자ID (공통 감사 loginId)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.crt_dt IS '생성일시';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.last_mdfr_id IS '최종수정자ID (공통 감사 loginId)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg.mdfcn_dt IS '수정일시';
COMMENT ON TABLE tb_ifml_atrz_tmpr_strg_dtl IS '비공식결재임시저장상세 (임시저장한 결재선, 단계마다 결재자 한 사람이 한 행)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.ifml_atrz_tmpr_strg_sn IS '비공식결재임시저장일련번호';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.atrz_seq IS '결재순서 (단계, 1부터)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.user_id IS '사용자아이디 (결재자, esntlId; 자격은 다시 열 때 판정한다)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.acrd_yn IS '합의여부 (Y 합의 단계, N 결재 단계)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.frst_rgtr_id IS '최초등록자ID (공통 감사 loginId)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.crt_dt IS '생성일시';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.last_mdfr_id IS '최종수정자ID (공통 감사 loginId)';
COMMENT ON COLUMN tb_ifml_atrz_tmpr_strg_dtl.mdfcn_dt IS '수정일시';
