-- 주소록 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 자동 내부키 표준화(2026-08-13).
-- 절차: Expand(신규 _sn) -> Sync(기존 문자열키 기준 백필) -> Redirect(동일 릴리스 앱) -> Contract(구 _id 제거).

INSERT INTO meta_standard_domains (domain_group, domain_name, data_type, data_length)
VALUES ('번호', '일련번호N19', 'BIGINT', 19)
ON CONFLICT (domain_name) DO NOTHING;

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES
    ('주소록일련번호', 'ADBK_SN', '주소록 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('주소록회원일련번호', 'ADBK_MBR_SN', '주소록 회원 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM meta_standard_domains
        WHERE domain_name = '일련번호N19' AND data_type = 'BIGINT' AND data_length = 19
    ) THEN
        RAISE EXCEPTION 'standard domain conflict: 일련번호N19 must be BIGINT(19)';
    END IF;
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE (eng_abbr = 'ADBK_SN' AND term_name = '주소록일련번호' AND domain_name = '일련번호N19')
           OR (eng_abbr = 'ADBK_MBR_SN' AND term_name = '주소록회원일련번호' AND domain_name = '일련번호N19')) <> 2 THEN
        RAISE EXCEPTION 'standard term conflict: ADBK_SN/ADBK_MBR_SN';
    END IF;
END $$;

-- Expand
ALTER TABLE tb_adbk_manage
    ADD COLUMN adbk_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_adbk_sn);

ALTER TABLE tb_adbk_info
    ADD COLUMN adbk_mbr_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_adbk_mbr_sn);

ALTER TABLE tb_adbk_info
    ADD COLUMN adbk_sn BIGINT;

-- Sync: 기존 문자열 FK를 신규 숫자 PK로 결정적으로 이관한다.
UPDATE tb_adbk_info i
SET adbk_sn = m.adbk_sn
FROM tb_adbk_manage m
WHERE i.adbk_id = m.adbk_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_adbk_manage WHERE adbk_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_adbk_manage.adbk_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_adbk_info WHERE adbk_mbr_sn IS NULL OR adbk_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_adbk_info bigint key backfill failed or orphan adbk_id exists';
    END IF;
END $$;

ALTER TABLE tb_adbk_manage ALTER COLUMN adbk_sn SET NOT NULL;
ALTER TABLE tb_adbk_info ALTER COLUMN adbk_mbr_sn SET NOT NULL;
ALTER TABLE tb_adbk_info ALTER COLUMN adbk_sn SET NOT NULL;

-- Redirect / Contract
ALTER TABLE tb_adbk_info DROP CONSTRAINT pk_tb_adbk_info;
ALTER TABLE tb_adbk_manage DROP CONSTRAINT pk_tb_adbk_manage;

ALTER TABLE tb_adbk_manage
    ADD CONSTRAINT pk_tb_adbk_manage PRIMARY KEY (adbk_sn);

ALTER TABLE tb_adbk_info
    ADD CONSTRAINT pk_tb_adbk_info PRIMARY KEY (adbk_mbr_sn);

ALTER TABLE tb_adbk_info
    ADD CONSTRAINT fk_tb_adbk_info_tb_adbk_manage
        FOREIGN KEY (adbk_sn) REFERENCES tb_adbk_manage (adbk_sn);

CREATE INDEX ix_tb_adbk_info_adbk_sn ON tb_adbk_info (adbk_sn);

ALTER TABLE tb_adbk_info DROP COLUMN adbk_constnt_id; -- linter:ignore contract: 주소록 회원 문자열 기술키 소비자 전환 완료
ALTER TABLE tb_adbk_info DROP COLUMN adbk_id; -- linter:ignore contract: 주소록 숫자 FK 백필·검증 완료
ALTER TABLE tb_adbk_manage DROP COLUMN adbk_id; -- linter:ignore contract: 주소록 숫자 PK 백필·검증 완료

COMMENT ON COLUMN tb_adbk_manage.adbk_sn IS '주소록일련번호 (adbk_sn)';
COMMENT ON COLUMN tb_adbk_info.adbk_mbr_sn IS '주소록회원일련번호 (adbk_mbr_sn)';
COMMENT ON COLUMN tb_adbk_info.adbk_sn IS '주소록일련번호 (adbk_sn)';
