-- 도움말 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).
-- 절차: Expand(신규 hlp_sn) -> Sync(identity 백필 검증) -> Redirect(동일 릴리스 앱) -> Contract(구 hlp_id 제거).

-- 공공 표준사전의 HLP_SN은 NUMERIC(22)로 매핑돼 있으나, 프로젝트 자동 내부키 표준인
-- BIGINT(19)에 맞춰 프로젝트 확장 도메인으로 명시적으로 재매핑한다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '도움말일련번호'
  AND eng_abbr = 'HLP_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '도움말일련번호'
          AND eng_abbr = 'HLP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: HLP_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_hlp_info
    ADD COLUMN hlp_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_hlp_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_hlp_info WHERE hlp_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_hlp_info.hlp_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_hlp_info ALTER COLUMN hlp_sn SET NOT NULL;

-- Redirect / Contract
ALTER TABLE tb_hlp_info DROP CONSTRAINT pk_tb_hlp_info;
ALTER TABLE tb_hlp_info
    ADD CONSTRAINT pk_tb_hlp_info PRIMARY KEY (hlp_sn);
ALTER TABLE tb_hlp_info DROP COLUMN hlp_id; -- linter:ignore contract: 도움말 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_hlp_info.hlp_sn IS '도움말일련번호 (hlp_sn)';
