-- 인터넷 서비스 안내 기술 PK를 문자열 수동 할당에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).
-- 신규 PK는 표준 단어 인터넷(ITNT)+서비스(SRVC)+일련번호(SN)를 사용한다.

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('인터넷서비스일련번호', 'ITNT_SRVC_SN',
        '인터넷 서비스 안내 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '인터넷서비스일련번호'
          AND eng_abbr = 'ITNT_SRVC_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: ITNT_SRVC_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_intrn_svc
    ADD COLUMN itnt_srvc_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_itnt_srvc_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_intrn_svc WHERE itnt_srvc_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_intrn_svc.itnt_srvc_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_intrn_svc ALTER COLUMN itnt_srvc_sn SET NOT NULL;

-- Redirect / Contract
ALTER TABLE tb_intrn_svc DROP CONSTRAINT pk_tb_intrn_svc;
ALTER TABLE tb_intrn_svc
    ADD CONSTRAINT pk_tb_intrn_svc PRIMARY KEY (itnt_srvc_sn);
ALTER TABLE tb_intrn_svc DROP COLUMN itnt_svc_id; -- linter:ignore contract: 인터넷 서비스 안내 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_intrn_svc.itnt_srvc_sn IS '인터넷서비스일련번호 (itnt_srvc_sn)';
