-- 팝업 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('팝업일련번호', 'POPUP_SN',
        '팝업 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '팝업일련번호'
          AND eng_abbr = 'POPUP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: POPUP_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_popup_info
    ADD COLUMN popup_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_popup_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_popup_info WHERE popup_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_popup_info.popup_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_popup_info ALTER COLUMN popup_sn SET NOT NULL;

-- Redirect / Contract
ALTER TABLE tb_popup_info DROP CONSTRAINT pk_tb_popup_info;
ALTER TABLE tb_popup_info
    ADD CONSTRAINT pk_tb_popup_info PRIMARY KEY (popup_sn);
ALTER TABLE tb_popup_info DROP COLUMN popup_id; -- linter:ignore contract: 팝업 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_popup_info.popup_sn IS '팝업일련번호 (popup_sn)';
