-- 온라인 매뉴얼 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('온라인매뉴얼일련번호', 'ONLN_MNL_SN',
        '온라인 매뉴얼 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '온라인매뉴얼일련번호'
          AND eng_abbr = 'ONLN_MNL_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: ONLN_MNL_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_onln_mnl_info
    ADD COLUMN onln_mnl_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_onln_mnl_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_onln_mnl_info WHERE onln_mnl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_mnl_info.onln_mnl_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_onln_mnl_info ALTER COLUMN onln_mnl_sn SET NOT NULL;

-- Redirect / Contract: 구 PK와 동일 컬럼의 중복 UNIQUE 제약을 함께 제거한다.
ALTER TABLE tb_onln_mnl_info DROP CONSTRAINT pk_tb_onln_mnl_info;
ALTER TABLE tb_onln_mnl_info DROP CONSTRAINT uk_tb_onln_mnl_info_onln_mnl_id;
ALTER TABLE tb_onln_mnl_info
    ADD CONSTRAINT pk_tb_onln_mnl_info PRIMARY KEY (onln_mnl_sn);
ALTER TABLE tb_onln_mnl_info DROP COLUMN onln_mnl_id; -- linter:ignore contract: 온라인 매뉴얼 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_onln_mnl_info.onln_mnl_sn IS '온라인매뉴얼일련번호 (onln_mnl_sn)';
