-- 부서업무함 기술 PK와 부서업무의 참조 FK를 BIGINT 일련번호로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('부서업무함일련번호', 'DEPT_TASK_BOX_SN',
        '부서업무함 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '부서업무함일련번호'
          AND eng_abbr = 'DEPT_TASK_BOX_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: DEPT_TASK_BOX_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 부모에는 identity, nullable 자식에는 같은 타입의 FK 후보 컬럼을 추가한다.
ALTER TABLE tb_dept_job_bx
    ADD COLUMN dept_task_box_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_dept_task_box_sn);

ALTER TABLE tb_dept_task_info
    ADD COLUMN dept_task_box_sn BIGINT;

-- Sync: 기존 문자열 FK를 부모의 신규 숫자 PK에 결정적으로 대응시킨다.
UPDATE tb_dept_task_info task
SET dept_task_box_sn = box.dept_task_box_sn
FROM tb_dept_job_bx box
WHERE task.dept_task_box_id = box.dept_task_box_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_dept_job_bx WHERE dept_task_box_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_dept_job_bx.dept_task_box_sn backfill failed';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_dept_task_info
        WHERE dept_task_box_id IS NOT NULL AND dept_task_box_sn IS NULL
    ) THEN
        RAISE EXCEPTION 'tb_dept_task_info.dept_task_box_sn backfill failed or orphan exists';
    END IF;
END $$;

ALTER TABLE tb_dept_job_bx ALTER COLUMN dept_task_box_sn SET NOT NULL;

-- Redirect / Contract: 기존 FK·PK를 신규 숫자 키로 재결속한다.
ALTER TABLE tb_dept_task_info DROP CONSTRAINT fk_tb_dept_task_info_tb_dept_job_bx;
ALTER TABLE tb_dept_job_bx DROP CONSTRAINT pk_tb_dept_job_bx;

ALTER TABLE tb_dept_job_bx
    ADD CONSTRAINT pk_tb_dept_job_bx PRIMARY KEY (dept_task_box_sn);

ALTER TABLE tb_dept_task_info
    ADD CONSTRAINT fk_tb_dept_task_info_tb_dept_job_bx
        FOREIGN KEY (dept_task_box_sn) REFERENCES tb_dept_job_bx (dept_task_box_sn) NOT VALID;
ALTER TABLE tb_dept_task_info
    VALIDATE CONSTRAINT fk_tb_dept_task_info_tb_dept_job_bx;

CREATE INDEX ix_tb_dept_task_info_dept_task_box_sn
    ON tb_dept_task_info (dept_task_box_sn);

ALTER TABLE tb_dept_task_info DROP COLUMN dept_task_box_id; -- linter:ignore contract: 부서업무함 숫자 FK 백필·검증 완료
ALTER TABLE tb_dept_job_bx DROP COLUMN dept_task_box_id; -- linter:ignore contract: 부서업무함 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_dept_job_bx.dept_task_box_sn IS '부서업무함일련번호 (dept_task_box_sn)';
COMMENT ON COLUMN tb_dept_task_info.dept_task_box_sn IS '부서업무함일련번호 (dept_task_box_sn)';
