-- 부서업무 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('부서업무일련번호', 'DEPT_TASK_SN',
        '부서업무 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '부서업무일련번호'
          AND eng_abbr = 'DEPT_TASK_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: DEPT_TASK_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_dept_task_info
    ADD COLUMN dept_task_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_dept_task_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_dept_task_info WHERE dept_task_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_dept_task_info.dept_task_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_dept_task_info ALTER COLUMN dept_task_sn SET NOT NULL;

-- Redirect / Contract: 이 PK를 참조하는 inbound FK는 없으며 기존 outbound FK는 영향받지 않는다.
ALTER TABLE tb_dept_task_info DROP CONSTRAINT pk_tb_dept_task_info;
ALTER TABLE tb_dept_task_info
    ADD CONSTRAINT pk_tb_dept_task_info PRIMARY KEY (dept_task_sn);
ALTER TABLE tb_dept_task_info DROP COLUMN dept_task_id; -- linter:ignore contract: 부서업무 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_dept_task_info.dept_task_sn IS '부서업무일련번호 (dept_task_sn)';
