-- 배너 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '배너일련번호'
  AND eng_abbr = 'BNR_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '배너일련번호'
          AND eng_abbr = 'BNR_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: BNR_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_bnr_info
    ADD COLUMN bnr_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_bnr_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_bnr_info WHERE bnr_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_bnr_info.bnr_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_bnr_info ALTER COLUMN bnr_sn SET NOT NULL;

ALTER TABLE tb_bnr_info DROP CONSTRAINT pk_tb_bnr_info;
ALTER TABLE tb_bnr_info
    ADD CONSTRAINT pk_tb_bnr_info PRIMARY KEY (bnr_sn);
ALTER TABLE tb_bnr_info DROP COLUMN bnr_id; -- linter:ignore contract: 배너 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_bnr_info.bnr_sn IS '배너일련번호 (bnr_sn)';
