-- 자료사용통계 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('자료사용통계일련번호', 'DTA_USE_STATS_SN',
        '자료 사용 통계 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '자료사용통계일련번호'
          AND eng_abbr = 'DTA_USE_STATS_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: DTA_USE_STATS_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_dta_use_stats
    ADD COLUMN dta_use_stats_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_dta_use_stats_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_dta_use_stats WHERE dta_use_stats_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_dta_use_stats.dta_use_stats_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_dta_use_stats ALTER COLUMN dta_use_stats_sn SET NOT NULL;
ALTER TABLE tb_dta_use_stats DROP CONSTRAINT pk_tb_dta_use_stats;
ALTER TABLE tb_dta_use_stats
    ADD CONSTRAINT pk_tb_dta_use_stats PRIMARY KEY (dta_use_stats_sn);
ALTER TABLE tb_dta_use_stats DROP COLUMN dta_use_stats_id; -- linter:ignore contract: 자료사용통계 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_dta_use_stats.dta_use_stats_sn IS '자료사용통계일련번호 (dta_use_stats_sn)';
