-- 쪽지 본문·발송·수신 기술 PK와 내부 FK 체인을 BIGINT IDENTITY로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES
    ('쪽지일련번호', 'NOTE_SN', '쪽지 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('쪽지발송일련번호', 'NOTE_SNDNG_SN', '쪽지 발송 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('쪽지수신일련번호', 'NOTE_RCPTN_SN', '쪽지 수신 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE (term_name, eng_abbr) IN (
            ('쪽지일련번호', 'NOTE_SN'),
            ('쪽지발송일련번호', 'NOTE_SNDNG_SN'),
            ('쪽지수신일련번호', 'NOTE_RCPTN_SN')
        ) AND domain_name = '일련번호N19') <> 3 THEN
        RAISE EXCEPTION 'standard term conflict: note family serial terms must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_note_info
    ADD COLUMN note_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_note_sn);

ALTER TABLE tb_note_sndng
    ADD COLUMN note_sndng_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_note_sndng_sn),
    ADD COLUMN note_sn BIGINT;

ALTER TABLE tb_note_rcptn
    ADD COLUMN note_rcptn_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_note_rcptn_sn),
    ADD COLUMN note_sn BIGINT,
    ADD COLUMN note_sndng_sn BIGINT;

UPDATE tb_note_sndng child
SET note_sn = parent.note_sn
FROM tb_note_info parent
WHERE child.note_id = parent.note_id;

UPDATE tb_note_rcptn child
SET note_sn = note_parent.note_sn
FROM tb_note_info note_parent
WHERE child.note_id = note_parent.note_id;

UPDATE tb_note_rcptn child
SET note_sndng_sn = sndng_parent.note_sndng_sn
FROM tb_note_sndng sndng_parent
WHERE child.note_sndng_id = sndng_parent.note_sndng_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_note_info WHERE note_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_info.note_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_note_sndng WHERE note_sndng_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_sndng.note_sndng_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_note_rcptn WHERE note_rcptn_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_rcptn.note_rcptn_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_note_sndng WHERE note_id IS NOT NULL AND note_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_sndng.note_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_note_rcptn WHERE note_id IS NOT NULL AND note_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_rcptn.note_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_note_rcptn WHERE note_sndng_id IS NOT NULL AND note_sndng_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_note_rcptn.note_sndng_sn relationship backfill failed';
    END IF;
END $$;

ALTER TABLE tb_note_info ALTER COLUMN note_sn SET NOT NULL;
ALTER TABLE tb_note_sndng ALTER COLUMN note_sndng_sn SET NOT NULL;
ALTER TABLE tb_note_rcptn ALTER COLUMN note_rcptn_sn SET NOT NULL;

ALTER TABLE tb_note_rcptn DROP CONSTRAINT fk_tb_note_rcptn_tb_note_sndng;
ALTER TABLE tb_note_rcptn DROP CONSTRAINT fk_tb_note_rcptn_tb_note_info;
ALTER TABLE tb_note_sndng DROP CONSTRAINT fk_tb_note_sndng_tb_note_info;

ALTER TABLE tb_note_rcptn DROP CONSTRAINT pk_tb_note_rcptn;
ALTER TABLE tb_note_sndng DROP CONSTRAINT pk_tb_note_sndng;
ALTER TABLE tb_note_info DROP CONSTRAINT pk_tb_note_info;

ALTER TABLE tb_note_info ADD CONSTRAINT pk_tb_note_info PRIMARY KEY (note_sn);
ALTER TABLE tb_note_sndng ADD CONSTRAINT pk_tb_note_sndng PRIMARY KEY (note_sndng_sn);
ALTER TABLE tb_note_rcptn ADD CONSTRAINT pk_tb_note_rcptn PRIMARY KEY (note_rcptn_sn);

ALTER TABLE tb_note_sndng
    ADD CONSTRAINT fk_tb_note_sndng_tb_note_info
        FOREIGN KEY (note_sn) REFERENCES tb_note_info (note_sn) NOT VALID;
ALTER TABLE tb_note_rcptn
    ADD CONSTRAINT fk_tb_note_rcptn_tb_note_info
        FOREIGN KEY (note_sn) REFERENCES tb_note_info (note_sn) NOT VALID;
ALTER TABLE tb_note_rcptn
    ADD CONSTRAINT fk_tb_note_rcptn_tb_note_sndng
        FOREIGN KEY (note_sndng_sn) REFERENCES tb_note_sndng (note_sndng_sn) NOT VALID;

ALTER TABLE tb_note_sndng VALIDATE CONSTRAINT fk_tb_note_sndng_tb_note_info;
ALTER TABLE tb_note_rcptn VALIDATE CONSTRAINT fk_tb_note_rcptn_tb_note_info;
ALTER TABLE tb_note_rcptn VALIDATE CONSTRAINT fk_tb_note_rcptn_tb_note_sndng;

ALTER TABLE tb_note_rcptn DROP COLUMN note_rcptn_id; -- linter:ignore contract: 쪽지 수신 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_note_rcptn DROP COLUMN note_id; -- linter:ignore contract: 쪽지 본문 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_note_rcptn DROP COLUMN note_sndng_id; -- linter:ignore contract: 쪽지 발송 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_note_sndng DROP COLUMN note_sndng_id; -- linter:ignore contract: 쪽지 발송 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_note_sndng DROP COLUMN note_id; -- linter:ignore contract: 쪽지 본문 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_note_info DROP COLUMN note_id; -- linter:ignore contract: 쪽지 본문 숫자 PK 백필·소비자 전환 완료

CREATE INDEX ix_tb_note_sndng_note_sn ON tb_note_sndng (note_sn);
CREATE INDEX ix_tb_note_rcptn_note_sn ON tb_note_rcptn (note_sn);
CREATE INDEX ix_tb_note_rcptn_note_sndng_sn ON tb_note_rcptn (note_sndng_sn);

COMMENT ON COLUMN tb_note_info.note_sn IS '쪽지일련번호 (note_sn)';
COMMENT ON COLUMN tb_note_sndng.note_sndng_sn IS '쪽지발송일련번호 (note_sndng_sn)';
COMMENT ON COLUMN tb_note_sndng.note_sn IS '쪽지일련번호 (note_sn)';
COMMENT ON COLUMN tb_note_rcptn.note_rcptn_sn IS '쪽지수신일련번호 (note_rcptn_sn)';
COMMENT ON COLUMN tb_note_rcptn.note_sn IS '쪽지일련번호 (note_sn)';
COMMENT ON COLUMN tb_note_rcptn.note_sndng_sn IS '쪽지발송일련번호 (note_sndng_sn)';
