-- 온라인 여론조사 관리·항목·결과 기술 PK와 내부 FK를 BIGINT IDENTITY로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES
    ('여론조사일련번호', 'POLL_SN', '여론조사 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('여론조사항목일련번호', 'POLL_ARTCL_SN', '여론조사 항목 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('여론조사결과일련번호', 'POLL_RSLT_SN', '여론조사 결과 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE (term_name, eng_abbr) IN (
            ('여론조사일련번호', 'POLL_SN'),
            ('여론조사항목일련번호', 'POLL_ARTCL_SN'),
            ('여론조사결과일련번호', 'POLL_RSLT_SN')
        ) AND domain_name = '일련번호N19') <> 3 THEN
        RAISE EXCEPTION 'standard term conflict: online poll serial terms must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_onln_poll_manage
    ADD COLUMN poll_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_poll_sn);

ALTER TABLE tb_onln_poll_artcl
    ADD COLUMN poll_artcl_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_poll_artcl_sn),
    ADD COLUMN poll_sn BIGINT;

ALTER TABLE tb_onln_poll_rslt
    ADD COLUMN poll_rslt_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_poll_rslt_sn),
    ADD COLUMN poll_sn BIGINT,
    ADD COLUMN poll_artcl_sn BIGINT;

UPDATE tb_onln_poll_artcl child
SET poll_sn = parent.poll_sn
FROM tb_onln_poll_manage parent
WHERE child.poll_id = parent.poll_id;

UPDATE tb_onln_poll_rslt child
SET poll_sn = parent.poll_sn
FROM tb_onln_poll_manage parent
WHERE child.poll_id = parent.poll_id;

UPDATE tb_onln_poll_rslt child
SET poll_artcl_sn = parent.poll_artcl_sn
FROM tb_onln_poll_artcl parent
WHERE child.poll_artcl_id = parent.poll_artcl_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_onln_poll_manage WHERE poll_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_manage.poll_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_onln_poll_artcl WHERE poll_artcl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_artcl.poll_artcl_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_onln_poll_rslt WHERE poll_rslt_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_rslt.poll_rslt_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_onln_poll_artcl WHERE poll_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_artcl.poll_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_onln_poll_rslt WHERE poll_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_rslt.poll_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_onln_poll_rslt WHERE poll_artcl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_onln_poll_rslt.poll_artcl_sn relationship backfill failed';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM tb_onln_poll_rslt result
        JOIN tb_onln_poll_artcl article ON article.poll_artcl_sn = result.poll_artcl_sn
        WHERE result.poll_sn <> article.poll_sn
    ) THEN
        RAISE EXCEPTION 'tb_onln_poll_rslt poll/article relationship mismatch';
    END IF;
END $$;

ALTER TABLE tb_onln_poll_manage ALTER COLUMN poll_sn SET NOT NULL;
ALTER TABLE tb_onln_poll_artcl ALTER COLUMN poll_artcl_sn SET NOT NULL;
ALTER TABLE tb_onln_poll_artcl ALTER COLUMN poll_sn SET NOT NULL;
ALTER TABLE tb_onln_poll_rslt ALTER COLUMN poll_rslt_sn SET NOT NULL;
ALTER TABLE tb_onln_poll_rslt ALTER COLUMN poll_sn SET NOT NULL;
ALTER TABLE tb_onln_poll_rslt ALTER COLUMN poll_artcl_sn SET NOT NULL;

ALTER TABLE tb_onln_poll_rslt DROP CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_artcl;
ALTER TABLE tb_onln_poll_rslt DROP CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_manage;
ALTER TABLE tb_onln_poll_artcl DROP CONSTRAINT fk_tb_onln_poll_artcl_tb_onln_poll_manage;
ALTER TABLE tb_onln_poll_rslt DROP CONSTRAINT uk_tb_onln_poll_rslt_poll_voter;

ALTER TABLE tb_onln_poll_rslt DROP CONSTRAINT pk_tb_onln_poll_rslt;
ALTER TABLE tb_onln_poll_artcl DROP CONSTRAINT pk_tb_onln_poll_artcl;
ALTER TABLE tb_onln_poll_manage DROP CONSTRAINT pk_tb_onln_poll_manage;

ALTER TABLE tb_onln_poll_manage ADD CONSTRAINT pk_tb_onln_poll_manage PRIMARY KEY (poll_sn);
ALTER TABLE tb_onln_poll_artcl ADD CONSTRAINT pk_tb_onln_poll_artcl PRIMARY KEY (poll_artcl_sn);
ALTER TABLE tb_onln_poll_rslt ADD CONSTRAINT pk_tb_onln_poll_rslt PRIMARY KEY (poll_rslt_sn);

ALTER TABLE tb_onln_poll_artcl
    ADD CONSTRAINT fk_tb_onln_poll_artcl_tb_onln_poll_manage
        FOREIGN KEY (poll_sn) REFERENCES tb_onln_poll_manage (poll_sn) NOT VALID;
ALTER TABLE tb_onln_poll_rslt
    ADD CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_manage
        FOREIGN KEY (poll_sn) REFERENCES tb_onln_poll_manage (poll_sn) NOT VALID;
ALTER TABLE tb_onln_poll_rslt
    ADD CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_artcl
        FOREIGN KEY (poll_artcl_sn) REFERENCES tb_onln_poll_artcl (poll_artcl_sn) NOT VALID;

ALTER TABLE tb_onln_poll_artcl VALIDATE CONSTRAINT fk_tb_onln_poll_artcl_tb_onln_poll_manage;
ALTER TABLE tb_onln_poll_rslt VALIDATE CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_manage;
ALTER TABLE tb_onln_poll_rslt VALIDATE CONSTRAINT fk_tb_onln_poll_rslt_tb_onln_poll_artcl;

ALTER TABLE tb_onln_poll_rslt
    ADD CONSTRAINT uk_tb_onln_poll_rslt_poll_voter UNIQUE (poll_sn, frst_rgtr_id);

ALTER TABLE tb_onln_poll_rslt DROP COLUMN poll_rslt_id; -- linter:ignore contract: 결과 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_onln_poll_rslt DROP COLUMN poll_id; -- linter:ignore contract: 관리 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_onln_poll_rslt DROP COLUMN poll_artcl_id; -- linter:ignore contract: 항목 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_onln_poll_artcl DROP COLUMN poll_artcl_id; -- linter:ignore contract: 항목 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_onln_poll_artcl DROP COLUMN poll_id; -- linter:ignore contract: 관리 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_onln_poll_manage DROP COLUMN poll_id; -- linter:ignore contract: 관리 숫자 PK 백필·소비자 전환 완료

CREATE INDEX ix_tb_onln_poll_artcl_poll_sn ON tb_onln_poll_artcl (poll_sn);
CREATE INDEX ix_tb_onln_poll_rslt_poll_artcl_sn ON tb_onln_poll_rslt (poll_artcl_sn);

COMMENT ON COLUMN tb_onln_poll_manage.poll_sn IS '여론조사일련번호 (poll_sn)';
COMMENT ON COLUMN tb_onln_poll_artcl.poll_artcl_sn IS '여론조사항목일련번호 (poll_artcl_sn)';
COMMENT ON COLUMN tb_onln_poll_artcl.poll_sn IS '여론조사일련번호 (poll_sn)';
COMMENT ON COLUMN tb_onln_poll_rslt.poll_rslt_sn IS '여론조사결과일련번호 (poll_rslt_sn)';
COMMENT ON COLUMN tb_onln_poll_rslt.poll_sn IS '여론조사일련번호 (poll_sn)';
COMMENT ON COLUMN tb_onln_poll_rslt.poll_artcl_sn IS '여론조사항목일련번호 (poll_artcl_sn)';
