-- 이메일 발신 이력 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- msg_id는 SMTP Message-ID가 아니라 애플리케이션 내부 발신 이력 키임을 코드·데이터로 확인했다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('이메일발신일련번호', 'EML_DSPTCH_SN',
        '이메일 발신 이력 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '이메일발신일련번호'
          AND eng_abbr = 'EML_DSPTCH_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: EML_DSPTCH_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_email_dsptch_manage
    ADD COLUMN eml_dsptch_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_eml_dsptch_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_email_dsptch_manage WHERE eml_dsptch_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_email_dsptch_manage.eml_dsptch_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_email_dsptch_manage ALTER COLUMN eml_dsptch_sn SET NOT NULL;
ALTER TABLE tb_email_dsptch_manage DROP CONSTRAINT pk_tb_email_dsptch_manage;
ALTER TABLE tb_email_dsptch_manage
    ADD CONSTRAINT pk_tb_email_dsptch_manage PRIMARY KEY (eml_dsptch_sn);
ALTER TABLE tb_email_dsptch_manage DROP COLUMN msg_id; -- linter:ignore contract: 이메일 발신 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_email_dsptch_manage.eml_dsptch_sn IS '이메일발신일련번호 (eml_dsptch_sn)';
