-- 설문 템플릿·설문·문항·항목·응답의 기술 PK와 전체 참조 폐포를 BIGINT IDENTITY로 전환한다.
-- 응답자 자체 식별자(srvy_rspdnt_id)는 유지하고, 물리 복합 PK의 설문/템플릿 참조만 BIGINT로 바꾼다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES
    ('설문일련번호', 'SRVY_SN', '설문 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('설문질문일련번호', 'SRVY_QSTN_SN', '설문 질문 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('설문항목일련번호', 'SRVY_ARTCL_SN', '설문 항목 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('설문응답일련번호', 'SRVY_RSPNS_SN', '설문 응답 내부 레코드에 연속되게 매긴 번호', '일련번호N19'),
    ('설문서식일련번호', 'SRVY_TMPLT_SN', '설문 서식 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE (term_name, eng_abbr) IN (
            ('설문일련번호', 'SRVY_SN'),
            ('설문질문일련번호', 'SRVY_QSTN_SN'),
            ('설문항목일련번호', 'SRVY_ARTCL_SN'),
            ('설문응답일련번호', 'SRVY_RSPNS_SN'),
            ('설문서식일련번호', 'SRVY_TMPLT_SN')
        ) AND domain_name = '일련번호N19') <> 5 THEN
        RAISE EXCEPTION 'standard term conflict: survey serial terms must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_srvy_tmplt
    ADD COLUMN srvy_tmplt_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_srvy_tmplt_sn);

ALTER TABLE tb_srvy_info
    ADD COLUMN srvy_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_srvy_sn),
    ADD COLUMN srvy_tmplt_sn BIGINT;

ALTER TABLE tb_srvy_qstn
    ADD COLUMN srvy_qstn_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_srvy_qstn_sn),
    ADD COLUMN srvy_sn BIGINT,
    ADD COLUMN srvy_tmplt_sn BIGINT;

ALTER TABLE tb_srvy_artcl
    ADD COLUMN srvy_artcl_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_srvy_artcl_sn),
    ADD COLUMN srvy_qstn_sn BIGINT,
    ADD COLUMN srvy_sn BIGINT,
    ADD COLUMN srvy_tmplt_sn BIGINT;

ALTER TABLE tb_srvy_rslt
    ADD COLUMN srvy_rspns_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_srvy_rspns_sn),
    ADD COLUMN srvy_sn BIGINT,
    ADD COLUMN srvy_tmplt_sn BIGINT,
    ADD COLUMN srvy_qstn_sn BIGINT,
    ADD COLUMN srvy_artcl_sn BIGINT;

ALTER TABLE tb_srvy_rspdnt
    ADD COLUMN srvy_tmplt_sn BIGINT,
    ADD COLUMN srvy_sn BIGINT;

UPDATE tb_srvy_info child
SET srvy_tmplt_sn = parent.srvy_tmplt_sn
FROM tb_srvy_tmplt parent
WHERE child.srvy_tmplt_id = parent.srvy_tmplt_id;

UPDATE tb_srvy_qstn child
SET srvy_sn = parent.srvy_sn
FROM tb_srvy_info parent
WHERE child.srvy_id = parent.srvy_id;
UPDATE tb_srvy_qstn child
SET srvy_tmplt_sn = parent.srvy_tmplt_sn
FROM tb_srvy_tmplt parent
WHERE child.srvy_tmplt_id = parent.srvy_tmplt_id;

UPDATE tb_srvy_artcl child
SET srvy_qstn_sn = parent.srvy_qstn_sn
FROM tb_srvy_qstn parent
WHERE child.srvy_qstn_id = parent.srvy_qstn_id;
UPDATE tb_srvy_artcl child
SET srvy_sn = parent.srvy_sn
FROM tb_srvy_info parent
WHERE child.srvy_id = parent.srvy_id;
UPDATE tb_srvy_artcl child
SET srvy_tmplt_sn = parent.srvy_tmplt_sn
FROM tb_srvy_tmplt parent
WHERE child.srvy_tmplt_id = parent.srvy_tmplt_id;

UPDATE tb_srvy_rslt child
SET srvy_sn = parent.srvy_sn
FROM tb_srvy_info parent
WHERE child.srvy_id = parent.srvy_id;
UPDATE tb_srvy_rslt child
SET srvy_tmplt_sn = parent.srvy_tmplt_sn
FROM tb_srvy_tmplt parent
WHERE child.srvy_tmplt_id = parent.srvy_tmplt_id;
UPDATE tb_srvy_rslt child
SET srvy_qstn_sn = parent.srvy_qstn_sn
FROM tb_srvy_qstn parent
WHERE child.srvy_qstn_id = parent.srvy_qstn_id;
UPDATE tb_srvy_rslt child
SET srvy_artcl_sn = parent.srvy_artcl_sn
FROM tb_srvy_artcl parent
WHERE child.srvy_artcl_id = parent.srvy_artcl_id;

UPDATE tb_srvy_rspdnt child
SET srvy_sn = parent.srvy_sn
FROM tb_srvy_info parent
WHERE child.srvy_id = parent.srvy_id;
UPDATE tb_srvy_rspdnt child
SET srvy_tmplt_sn = parent.srvy_tmplt_sn
FROM tb_srvy_tmplt parent
WHERE child.srvy_tmplt_id = parent.srvy_tmplt_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_srvy_tmplt WHERE srvy_tmplt_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_srvy_tmplt.srvy_tmplt_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_srvy_info WHERE srvy_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_srvy_info.srvy_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_srvy_qstn WHERE srvy_qstn_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_srvy_qstn.srvy_qstn_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_srvy_artcl WHERE srvy_artcl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_srvy_artcl.srvy_artcl_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_srvy_rslt WHERE srvy_rspns_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_srvy_rslt.srvy_rspns_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_srvy_info WHERE srvy_tmplt_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_srvy_qstn WHERE srvy_sn IS NULL OR srvy_tmplt_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_srvy_artcl
                   WHERE srvy_qstn_sn IS NULL OR srvy_sn IS NULL OR srvy_tmplt_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_srvy_rslt
                   WHERE srvy_sn IS NULL OR srvy_tmplt_sn IS NULL
                      OR srvy_qstn_sn IS NULL OR srvy_artcl_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_srvy_rspdnt WHERE srvy_sn IS NULL OR srvy_tmplt_sn IS NULL) THEN
        RAISE EXCEPTION 'survey relationship backfill failed';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_srvy_qstn q
        JOIN tb_srvy_info i ON i.srvy_sn = q.srvy_sn
        WHERE q.srvy_tmplt_sn <> i.srvy_tmplt_sn
    ) THEN
        RAISE EXCEPTION 'tb_srvy_qstn survey/template relationship mismatch';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_srvy_artcl a
        JOIN tb_srvy_qstn q ON q.srvy_qstn_sn = a.srvy_qstn_sn
        WHERE a.srvy_sn <> q.srvy_sn OR a.srvy_tmplt_sn <> q.srvy_tmplt_sn
    ) THEN
        RAISE EXCEPTION 'tb_srvy_artcl survey/question/template relationship mismatch';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_srvy_rslt r
        JOIN tb_srvy_qstn q ON q.srvy_qstn_sn = r.srvy_qstn_sn
        JOIN tb_srvy_artcl a ON a.srvy_artcl_sn = r.srvy_artcl_sn
        WHERE r.srvy_sn <> q.srvy_sn OR r.srvy_tmplt_sn <> q.srvy_tmplt_sn
           OR a.srvy_qstn_sn <> q.srvy_qstn_sn OR a.srvy_sn <> r.srvy_sn
           OR a.srvy_tmplt_sn <> r.srvy_tmplt_sn
    ) THEN
        RAISE EXCEPTION 'tb_srvy_rslt survey/question/article/template relationship mismatch';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_srvy_rspdnt r
        JOIN tb_srvy_info i ON i.srvy_sn = r.srvy_sn
        WHERE r.srvy_tmplt_sn <> i.srvy_tmplt_sn
    ) THEN
        RAISE EXCEPTION 'tb_srvy_rspdnt survey/template relationship mismatch';
    END IF;
END $$;

ALTER TABLE tb_srvy_tmplt ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_info ALTER COLUMN srvy_sn SET NOT NULL;
ALTER TABLE tb_srvy_info ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_qstn ALTER COLUMN srvy_qstn_sn SET NOT NULL;
ALTER TABLE tb_srvy_qstn ALTER COLUMN srvy_sn SET NOT NULL;
ALTER TABLE tb_srvy_qstn ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_artcl ALTER COLUMN srvy_artcl_sn SET NOT NULL;
ALTER TABLE tb_srvy_artcl ALTER COLUMN srvy_qstn_sn SET NOT NULL;
ALTER TABLE tb_srvy_artcl ALTER COLUMN srvy_sn SET NOT NULL;
ALTER TABLE tb_srvy_artcl ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_rslt ALTER COLUMN srvy_rspns_sn SET NOT NULL;
ALTER TABLE tb_srvy_rslt ALTER COLUMN srvy_sn SET NOT NULL;
ALTER TABLE tb_srvy_rslt ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_rslt ALTER COLUMN srvy_qstn_sn SET NOT NULL;
ALTER TABLE tb_srvy_rslt ALTER COLUMN srvy_artcl_sn SET NOT NULL;
ALTER TABLE tb_srvy_rspdnt ALTER COLUMN srvy_tmplt_sn SET NOT NULL;
ALTER TABLE tb_srvy_rspdnt ALTER COLUMN srvy_sn SET NOT NULL;

ALTER TABLE tb_srvy_rslt DROP CONSTRAINT fk_tb_srvy_rslt_tb_srvy_artcl;
ALTER TABLE tb_srvy_rslt DROP CONSTRAINT fk_tb_srvy_rslt_tb_srvy_qstn;
ALTER TABLE tb_srvy_rslt DROP CONSTRAINT fk_tb_srvy_rslt_tb_srvy_info;
ALTER TABLE tb_srvy_artcl DROP CONSTRAINT fk_tb_srvy_artcl_tb_srvy_qstn;
ALTER TABLE tb_srvy_artcl DROP CONSTRAINT fk_tb_srvy_artcl_tb_srvy_info;
ALTER TABLE tb_srvy_qstn DROP CONSTRAINT fk_tb_srvy_qstn_tb_srvy_info;
ALTER TABLE tb_srvy_rspdnt DROP CONSTRAINT fk_tb_srvy_rspdnt_tb_srvy_info;
ALTER TABLE tb_srvy_rslt DROP CONSTRAINT uk_tb_srvy_rslt_answer;

ALTER TABLE tb_srvy_rslt DROP CONSTRAINT pk_tb_srvy_rslt;
ALTER TABLE tb_srvy_artcl DROP CONSTRAINT pk_tb_srvy_artcl;
ALTER TABLE tb_srvy_qstn DROP CONSTRAINT pk_tb_srvy_qstn;
ALTER TABLE tb_srvy_rspdnt DROP CONSTRAINT pk_tb_srvy_rspdnt;
ALTER TABLE tb_srvy_info DROP CONSTRAINT pk_tb_srvy_info;
ALTER TABLE tb_srvy_tmplt DROP CONSTRAINT pk_tb_srvy_tmplt;

ALTER TABLE tb_srvy_tmplt ADD CONSTRAINT pk_tb_srvy_tmplt PRIMARY KEY (srvy_tmplt_sn);
ALTER TABLE tb_srvy_info ADD CONSTRAINT pk_tb_srvy_info PRIMARY KEY (srvy_sn);
ALTER TABLE tb_srvy_qstn ADD CONSTRAINT pk_tb_srvy_qstn PRIMARY KEY (srvy_qstn_sn);
ALTER TABLE tb_srvy_artcl ADD CONSTRAINT pk_tb_srvy_artcl PRIMARY KEY (srvy_artcl_sn);
ALTER TABLE tb_srvy_rslt ADD CONSTRAINT pk_tb_srvy_rslt PRIMARY KEY (srvy_rspns_sn);
ALTER TABLE tb_srvy_rspdnt
    ADD CONSTRAINT pk_tb_srvy_rspdnt PRIMARY KEY (srvy_tmplt_sn, srvy_sn, srvy_rspdnt_id);

ALTER TABLE tb_srvy_info
    ADD CONSTRAINT fk_tb_srvy_info_tb_srvy_tmplt
        FOREIGN KEY (srvy_tmplt_sn) REFERENCES tb_srvy_tmplt (srvy_tmplt_sn) NOT VALID;
ALTER TABLE tb_srvy_qstn
    ADD CONSTRAINT fk_tb_srvy_qstn_tb_srvy_info
        FOREIGN KEY (srvy_sn) REFERENCES tb_srvy_info (srvy_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_qstn_tb_srvy_tmplt
        FOREIGN KEY (srvy_tmplt_sn) REFERENCES tb_srvy_tmplt (srvy_tmplt_sn) NOT VALID;
ALTER TABLE tb_srvy_artcl
    ADD CONSTRAINT fk_tb_srvy_artcl_tb_srvy_info
        FOREIGN KEY (srvy_sn) REFERENCES tb_srvy_info (srvy_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_artcl_tb_srvy_qstn
        FOREIGN KEY (srvy_qstn_sn) REFERENCES tb_srvy_qstn (srvy_qstn_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_artcl_tb_srvy_tmplt
        FOREIGN KEY (srvy_tmplt_sn) REFERENCES tb_srvy_tmplt (srvy_tmplt_sn) NOT VALID;
ALTER TABLE tb_srvy_rslt
    ADD CONSTRAINT fk_tb_srvy_rslt_tb_srvy_info
        FOREIGN KEY (srvy_sn) REFERENCES tb_srvy_info (srvy_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_rslt_tb_srvy_qstn
        FOREIGN KEY (srvy_qstn_sn) REFERENCES tb_srvy_qstn (srvy_qstn_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_rslt_tb_srvy_artcl
        FOREIGN KEY (srvy_artcl_sn) REFERENCES tb_srvy_artcl (srvy_artcl_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_rslt_tb_srvy_tmplt
        FOREIGN KEY (srvy_tmplt_sn) REFERENCES tb_srvy_tmplt (srvy_tmplt_sn) NOT VALID;
ALTER TABLE tb_srvy_rspdnt
    ADD CONSTRAINT fk_tb_srvy_rspdnt_tb_srvy_info
        FOREIGN KEY (srvy_sn) REFERENCES tb_srvy_info (srvy_sn) NOT VALID,
    ADD CONSTRAINT fk_tb_srvy_rspdnt_tb_srvy_tmplt
        FOREIGN KEY (srvy_tmplt_sn) REFERENCES tb_srvy_tmplt (srvy_tmplt_sn) NOT VALID;

ALTER TABLE tb_srvy_info VALIDATE CONSTRAINT fk_tb_srvy_info_tb_srvy_tmplt;
ALTER TABLE tb_srvy_qstn VALIDATE CONSTRAINT fk_tb_srvy_qstn_tb_srvy_info;
ALTER TABLE tb_srvy_qstn VALIDATE CONSTRAINT fk_tb_srvy_qstn_tb_srvy_tmplt;
ALTER TABLE tb_srvy_artcl VALIDATE CONSTRAINT fk_tb_srvy_artcl_tb_srvy_info;
ALTER TABLE tb_srvy_artcl VALIDATE CONSTRAINT fk_tb_srvy_artcl_tb_srvy_qstn;
ALTER TABLE tb_srvy_artcl VALIDATE CONSTRAINT fk_tb_srvy_artcl_tb_srvy_tmplt;
ALTER TABLE tb_srvy_rslt VALIDATE CONSTRAINT fk_tb_srvy_rslt_tb_srvy_info;
ALTER TABLE tb_srvy_rslt VALIDATE CONSTRAINT fk_tb_srvy_rslt_tb_srvy_qstn;
ALTER TABLE tb_srvy_rslt VALIDATE CONSTRAINT fk_tb_srvy_rslt_tb_srvy_artcl;
ALTER TABLE tb_srvy_rslt VALIDATE CONSTRAINT fk_tb_srvy_rslt_tb_srvy_tmplt;
ALTER TABLE tb_srvy_rspdnt VALIDATE CONSTRAINT fk_tb_srvy_rspdnt_tb_srvy_info;
ALTER TABLE tb_srvy_rspdnt VALIDATE CONSTRAINT fk_tb_srvy_rspdnt_tb_srvy_tmplt;

ALTER TABLE tb_srvy_rslt
    ADD CONSTRAINT uk_tb_srvy_rslt_answer
        UNIQUE (srvy_sn, srvy_qstn_sn, srvy_artcl_sn, frst_rgtr_id);

ALTER TABLE tb_srvy_rslt DROP COLUMN srvy_rspns_id; -- linter:ignore contract: 응답 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rslt DROP COLUMN srvy_id; -- linter:ignore contract: 설문 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rslt DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rslt DROP COLUMN srvy_qstn_id; -- linter:ignore contract: 문항 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rslt DROP COLUMN srvy_artcl_id; -- linter:ignore contract: 항목 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_artcl DROP COLUMN srvy_artcl_id; -- linter:ignore contract: 항목 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_artcl DROP COLUMN srvy_qstn_id; -- linter:ignore contract: 문항 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_artcl DROP COLUMN srvy_id; -- linter:ignore contract: 설문 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_artcl DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_qstn DROP COLUMN srvy_qstn_id; -- linter:ignore contract: 문항 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_qstn DROP COLUMN srvy_id; -- linter:ignore contract: 설문 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_qstn DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rspdnt DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 복합키 백필·소비자 전환 완료
ALTER TABLE tb_srvy_rspdnt DROP COLUMN srvy_id; -- linter:ignore contract: 설문 숫자 복합키 백필·소비자 전환 완료
ALTER TABLE tb_srvy_info DROP COLUMN srvy_id; -- linter:ignore contract: 설문 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_info DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_srvy_tmplt DROP COLUMN srvy_tmplt_id; -- linter:ignore contract: 템플릿 숫자 PK 백필·소비자 전환 완료

CREATE INDEX ix_tb_srvy_info_srvy_tmplt_sn ON tb_srvy_info (srvy_tmplt_sn);
CREATE INDEX ix_tb_srvy_qstn_srvy_sn ON tb_srvy_qstn (srvy_sn);
CREATE INDEX ix_tb_srvy_qstn_srvy_tmplt_sn ON tb_srvy_qstn (srvy_tmplt_sn);
CREATE INDEX ix_tb_srvy_artcl_srvy_sn ON tb_srvy_artcl (srvy_sn);
CREATE INDEX ix_tb_srvy_artcl_srvy_qstn_sn ON tb_srvy_artcl (srvy_qstn_sn);
CREATE INDEX ix_tb_srvy_artcl_srvy_tmplt_sn ON tb_srvy_artcl (srvy_tmplt_sn);
CREATE INDEX ix_tb_srvy_rslt_srvy_sn ON tb_srvy_rslt (srvy_sn);
CREATE INDEX ix_tb_srvy_rslt_srvy_qstn_sn ON tb_srvy_rslt (srvy_qstn_sn);
CREATE INDEX ix_tb_srvy_rslt_srvy_artcl_sn ON tb_srvy_rslt (srvy_artcl_sn);
CREATE INDEX ix_tb_srvy_rslt_srvy_tmplt_sn ON tb_srvy_rslt (srvy_tmplt_sn);
CREATE INDEX ix_tb_srvy_rspdnt_srvy_sn_srvy_tmplt_sn ON tb_srvy_rspdnt (srvy_sn, srvy_tmplt_sn);

COMMENT ON COLUMN tb_srvy_tmplt.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_info.srvy_sn IS '설문일련번호 (srvy_sn)';
COMMENT ON COLUMN tb_srvy_info.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_qstn.srvy_qstn_sn IS '설문질문일련번호 (srvy_qstn_sn)';
COMMENT ON COLUMN tb_srvy_qstn.srvy_sn IS '설문일련번호 (srvy_sn)';
COMMENT ON COLUMN tb_srvy_qstn.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_artcl.srvy_artcl_sn IS '설문항목일련번호 (srvy_artcl_sn)';
COMMENT ON COLUMN tb_srvy_artcl.srvy_qstn_sn IS '설문질문일련번호 (srvy_qstn_sn)';
COMMENT ON COLUMN tb_srvy_artcl.srvy_sn IS '설문일련번호 (srvy_sn)';
COMMENT ON COLUMN tb_srvy_artcl.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_rslt.srvy_rspns_sn IS '설문응답일련번호 (srvy_rspns_sn)';
COMMENT ON COLUMN tb_srvy_rslt.srvy_sn IS '설문일련번호 (srvy_sn)';
COMMENT ON COLUMN tb_srvy_rslt.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_rslt.srvy_qstn_sn IS '설문질문일련번호 (srvy_qstn_sn)';
COMMENT ON COLUMN tb_srvy_rslt.srvy_artcl_sn IS '설문항목일련번호 (srvy_artcl_sn)';
COMMENT ON COLUMN tb_srvy_rspdnt.srvy_tmplt_sn IS '설문서식일련번호 (srvy_tmplt_sn)';
COMMENT ON COLUMN tb_srvy_rspdnt.srvy_sn IS '설문일련번호 (srvy_sn)';
