-- 스크랩 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('스크랩일련번호', 'SCRAP_SN',
        '스크랩 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '스크랩일련번호'
          AND eng_abbr = 'SCRAP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: SCRAP_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_bbs_scrap
    ADD COLUMN scrap_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_scrap_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_bbs_scrap WHERE scrap_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_bbs_scrap.scrap_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_bbs_scrap ALTER COLUMN scrap_sn SET NOT NULL;
ALTER TABLE tb_bbs_scrap DROP CONSTRAINT pk_tb_bbs_scrap;
ALTER TABLE tb_bbs_scrap ADD CONSTRAINT pk_tb_bbs_scrap PRIMARY KEY (scrap_sn);
ALTER TABLE tb_bbs_scrap DROP COLUMN scrap_id; -- linter:ignore contract: 스크랩 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_bbs_scrap.scrap_sn IS '스크랩일련번호 (scrap_sn)';
