-- 게시물 기술 PK와 댓글·스크랩·만족도·통계·답글 참조 폐포를 BIGINT IDENTITY로 전환한다.
-- 게시판 업무 식별자(bbs_id)는 고정 업무키이므로 보존한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('상위게시물일련번호', 'UP_PST_SN',
        '상위 게시물 내부 레코드에 연속되게 매긴 번호', '일련번호N22')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '게시물일련번호'
          AND eng_abbr = 'PST_SN'
          AND domain_name = '일련번호N22') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: PST_SN must map to 일련번호N22';
    END IF;
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '상위게시물일련번호'
          AND eng_abbr = 'UP_PST_SN'
          AND domain_name = '일련번호N22') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: UP_PST_SN must map to 일련번호N22';
    END IF;
END $$;

ALTER TABLE tb_bbs_item
    ADD COLUMN pst_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_pst_sn),
    ADD COLUMN up_pst_sn BIGINT;
ALTER TABLE tb_bbs_comment ADD COLUMN pst_sn BIGINT;
ALTER TABLE tb_bbs_scrap ADD COLUMN pst_sn BIGINT;
ALTER TABLE tb_dgstfn_info ADD COLUMN pst_sn BIGINT;
ALTER TABLE tb_dta_use_stats ADD COLUMN pst_sn BIGINT;

UPDATE tb_bbs_item child
SET up_pst_sn = parent.pst_sn
FROM tb_bbs_item parent
WHERE child.up_pst_id IS NOT NULL
  AND child.up_pst_id <> '0'
  AND child.up_pst_id = parent.pst_id;
UPDATE tb_bbs_comment child
SET pst_sn = parent.pst_sn
FROM tb_bbs_item parent
WHERE child.pst_id = parent.pst_id;
UPDATE tb_bbs_scrap child
SET pst_sn = parent.pst_sn
FROM tb_bbs_item parent
WHERE child.pst_id = parent.pst_id;
UPDATE tb_dgstfn_info child
SET pst_sn = parent.pst_sn
FROM tb_bbs_item parent
WHERE child.pst_id = parent.pst_id;
UPDATE tb_dta_use_stats child
SET pst_sn = parent.pst_sn
FROM tb_bbs_item parent
WHERE child.pst_id = parent.pst_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_bbs_item WHERE pst_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_bbs_item.pst_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_bbs_item
               WHERE up_pst_id IS NOT NULL AND up_pst_id <> '0' AND up_pst_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_bbs_item.up_pst_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_bbs_comment WHERE pst_id IS NOT NULL AND pst_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_bbs_scrap WHERE pst_id IS NOT NULL AND pst_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_dgstfn_info WHERE pst_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_dta_use_stats WHERE pst_id IS NOT NULL AND pst_sn IS NULL) THEN
        RAISE EXCEPTION 'board post inbound relationship backfill failed';
    END IF;
END $$;

ALTER TABLE tb_bbs_item ALTER COLUMN pst_sn SET NOT NULL;
ALTER TABLE tb_dgstfn_info ALTER COLUMN pst_sn SET NOT NULL;

ALTER TABLE tb_bbs_comment DROP CONSTRAINT fk_tb_bbs_comment_tb_bbs_item;
ALTER TABLE tb_bbs_scrap DROP CONSTRAINT fk_tb_bbs_scrap_tb_bbs_item;
ALTER TABLE tb_dgstfn_info DROP CONSTRAINT fk_tb_dgstfn_info_tb_bbs_item;
ALTER TABLE tb_bbs_item DROP CONSTRAINT pk_tb_bbs_item;

ALTER TABLE tb_bbs_item ADD CONSTRAINT pk_tb_bbs_item PRIMARY KEY (pst_sn);
ALTER TABLE tb_bbs_item
    ADD CONSTRAINT fk_tb_bbs_item_up_pst_sn
        FOREIGN KEY (up_pst_sn) REFERENCES tb_bbs_item (pst_sn) NOT VALID;
ALTER TABLE tb_bbs_comment
    ADD CONSTRAINT fk_tb_bbs_comment_tb_bbs_item
        FOREIGN KEY (pst_sn) REFERENCES tb_bbs_item (pst_sn) NOT VALID;
ALTER TABLE tb_bbs_scrap
    ADD CONSTRAINT fk_tb_bbs_scrap_tb_bbs_item
        FOREIGN KEY (pst_sn) REFERENCES tb_bbs_item (pst_sn) NOT VALID;
ALTER TABLE tb_dgstfn_info
    ADD CONSTRAINT fk_tb_dgstfn_info_tb_bbs_item
        FOREIGN KEY (pst_sn) REFERENCES tb_bbs_item (pst_sn) NOT VALID;
ALTER TABLE tb_dta_use_stats
    ADD CONSTRAINT fk_tb_dta_use_stats_tb_bbs_item
        FOREIGN KEY (pst_sn) REFERENCES tb_bbs_item (pst_sn) NOT VALID;

ALTER TABLE tb_bbs_item VALIDATE CONSTRAINT fk_tb_bbs_item_up_pst_sn;
ALTER TABLE tb_bbs_comment VALIDATE CONSTRAINT fk_tb_bbs_comment_tb_bbs_item;
ALTER TABLE tb_bbs_scrap VALIDATE CONSTRAINT fk_tb_bbs_scrap_tb_bbs_item;
ALTER TABLE tb_dgstfn_info VALIDATE CONSTRAINT fk_tb_dgstfn_info_tb_bbs_item;
ALTER TABLE tb_dta_use_stats VALIDATE CONSTRAINT fk_tb_dta_use_stats_tb_bbs_item;

ALTER TABLE tb_bbs_item DROP COLUMN pst_id; -- linter:ignore contract: 게시물 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_bbs_item DROP COLUMN up_pst_id; -- linter:ignore contract: 상위 게시물 숫자 FK 백필·센티널 NULL 정규화 완료
ALTER TABLE tb_bbs_comment DROP COLUMN pst_id; -- linter:ignore contract: 댓글 게시물 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_bbs_scrap DROP COLUMN pst_id; -- linter:ignore contract: 스크랩 게시물 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_dgstfn_info DROP COLUMN pst_id; -- linter:ignore contract: 만족도 게시물 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_dta_use_stats DROP COLUMN pst_id; -- linter:ignore contract: 통계 게시물 숫자 FK 백필·소비자 전환 완료
DROP SEQUENCE IF EXISTS sq_pst_id; -- linter:ignore contract: 서비스 수동 채번 제거·IDENTITY sq_pst_sn 전환 완료

CREATE INDEX ix_tb_bbs_item_up_pst_sn ON tb_bbs_item (up_pst_sn);
CREATE INDEX ix_tb_bbs_comment_pst_sn ON tb_bbs_comment (pst_sn);
CREATE INDEX ix_tb_bbs_scrap_pst_sn ON tb_bbs_scrap (pst_sn);
CREATE INDEX ix_tb_dgstfn_info_pst_sn ON tb_dgstfn_info (pst_sn);
CREATE INDEX ix_tb_dta_use_stats_pst_sn ON tb_dta_use_stats (pst_sn);

COMMENT ON COLUMN tb_bbs_item.pst_sn IS '게시물일련번호 (pst_sn)';
COMMENT ON COLUMN tb_bbs_item.up_pst_sn IS '상위게시물일련번호 (up_pst_sn)';
COMMENT ON COLUMN tb_bbs_comment.pst_sn IS '게시물일련번호 (pst_sn)';
COMMENT ON COLUMN tb_bbs_scrap.pst_sn IS '게시물일련번호 (pst_sn)';
COMMENT ON COLUMN tb_dgstfn_info.pst_sn IS '게시물일련번호 (pst_sn)';
COMMENT ON COLUMN tb_dta_use_stats.pst_sn IS '게시물일련번호 (pst_sn)';
