-- 업무보고 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 공공 표준사전의 RPTP_SN은 NUMERIC(22)로 매핑돼 있으나, 프로젝트 자동 내부키 표준인
-- BIGINT(19)에 맞춰 프로젝트 확장 도메인으로 명시적으로 재매핑한다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '보고서일련번호'
  AND eng_abbr = 'RPTP_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '보고서일련번호'
          AND eng_abbr = 'RPTP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: RPTP_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_rpt_info
    ADD COLUMN rptp_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_rptp_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_rpt_info WHERE rptp_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_rpt_info.rptp_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_rpt_info ALTER COLUMN rptp_sn SET NOT NULL;
ALTER TABLE tb_rpt_info DROP CONSTRAINT pk_tb_rpt_info;
ALTER TABLE tb_rpt_info ADD CONSTRAINT pk_tb_rpt_info PRIMARY KEY (rptp_sn);
ALTER TABLE tb_rpt_info DROP COLUMN rpt_id; -- linter:ignore contract: 업무보고 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_rpt_info.rptp_sn IS '보고서일련번호 (rptp_sn)';
