-- 일정 기술 PK와 업무일지의 논리 참조를 BIGINT로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('일정일련번호', 'SCHDL_SN',
        '일정 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '일정일련번호'
          AND eng_abbr = 'SCHDL_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: SCHDL_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_schdl_info
    ADD COLUMN schdl_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_schdl_sn);
ALTER TABLE tb_diary_info ADD COLUMN schdl_sn BIGINT;

UPDATE tb_diary_info d
SET schdl_sn = s.schdl_sn
FROM tb_schdl_info s
WHERE d.schdl_id = s.schdl_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_schdl_info WHERE schdl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_schdl_info.schdl_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_diary_info WHERE schdl_id IS NOT NULL AND schdl_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_diary_info.schdl_sn backfill failed: unresolved schedule reference';
    END IF;
END $$;

ALTER TABLE tb_schdl_info ALTER COLUMN schdl_sn SET NOT NULL;
ALTER TABLE tb_schdl_info DROP CONSTRAINT pk_tb_schdl_info;
ALTER TABLE tb_schdl_info ADD CONSTRAINT pk_tb_schdl_info PRIMARY KEY (schdl_sn);
ALTER TABLE tb_schdl_info DROP COLUMN schdl_id; -- linter:ignore contract: 일정 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_diary_info DROP COLUMN schdl_id; -- linter:ignore contract: 업무일지 일정 참조 숫자 백필·소비자 전환 완료

COMMENT ON COLUMN tb_schdl_info.schdl_sn IS '일정일련번호 (schdl_sn)';
COMMENT ON COLUMN tb_diary_info.schdl_sn IS '일정일련번호 (schdl_sn)';
