-- 메모보고 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('메모보고일련번호', 'MEMO_RPT_SN',
        '메모 보고 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '메모보고일련번호'
          AND eng_abbr = 'MEMO_RPT_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: MEMO_RPT_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_memo_rpt_info
    ADD COLUMN memo_rpt_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_memo_rpt_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_memo_rpt_info WHERE memo_rpt_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_memo_rpt_info.memo_rpt_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_memo_rpt_info ALTER COLUMN memo_rpt_sn SET NOT NULL;
ALTER TABLE tb_memo_rpt_info DROP CONSTRAINT pk_tb_memo_rpt_info;
ALTER TABLE tb_memo_rpt_info
    ADD CONSTRAINT pk_tb_memo_rpt_info PRIMARY KEY (memo_rpt_sn);
ALTER TABLE tb_memo_rpt_info DROP COLUMN rpt_id; -- linter:ignore contract: 메모보고 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_memo_rpt_info.memo_rpt_sn IS '메모보고일련번호 (memo_rpt_sn)';
