-- 보고서 통계의 수동 문자열 기술 PK를 표준 BIGINT 일련번호로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 기존 대표 표준 용어를 물리 BIGINT 타입과 일치시킨다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '보고서일련번호'
  AND eng_abbr = 'RPTP_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '보고서일련번호'
          AND eng_abbr = 'RPTP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: RPTP_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 기존 행에도 identity가 번호를 발급하므로 별도 문자열 파싱 없이 결정적으로 백필된다.
ALTER TABLE tb_rptp_stats
    ADD COLUMN rptp_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_rptp_stats_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_rptp_stats WHERE rptp_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_rptp_stats.rptp_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_rptp_stats ALTER COLUMN rptp_sn SET NOT NULL;

-- Redirect / Contract: 외부 FK가 없는 단독 기술키를 신규 일련번호로 교체한다.
ALTER TABLE tb_rptp_stats DROP CONSTRAINT pk_tb_rptp_stats;
ALTER TABLE tb_rptp_stats
    ADD CONSTRAINT pk_tb_rptp_stats PRIMARY KEY (rptp_sn);
ALTER TABLE tb_rptp_stats DROP COLUMN reprt_id; -- linter:ignore contract: 보고서 통계 숫자 PK 백필·검증 및 JPA 소비자 전환 완료

COMMENT ON COLUMN tb_rptp_stats.rptp_sn IS '보고서일련번호 (rptp_sn)';
