-- 시스템 로그의 요청 상관관계 ID는 보존하고, 별도 BIGINT IDENTITY를 내부 PK로 도입한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).
-- 절차: Expand(신규 sys_log_sn) -> Sync(identity 백필 검증) -> Redirect(PK 전환) -> Contract(dmnd_id UNIQUE 업무키 보존).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('시스템로그일련번호', 'SYS_LOG_SN', '시스템 로그 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '시스템로그일련번호'
          AND eng_abbr = 'SYS_LOG_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: SYS_LOG_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: 기존 12개 데모 행을 포함한 모든 행에 자동 내부키를 백필한다.
ALTER TABLE tb_sys_log
    ADD COLUMN sys_log_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_sys_log_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_sys_log WHERE sys_log_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_sys_log.sys_log_sn backfill failed';
    END IF;
END $$;

ALTER TABLE tb_sys_log ALTER COLUMN sys_log_sn SET NOT NULL;

-- Redirect / Contract: dmnd_id는 추적·표시용 요청 ID이므로 삭제하지 않고 유일 업무키로 유지한다.
ALTER TABLE tb_sys_log DROP CONSTRAINT pk_tb_sys_log;
ALTER TABLE tb_sys_log
    ADD CONSTRAINT pk_tb_sys_log PRIMARY KEY (sys_log_sn);
ALTER TABLE tb_sys_log
    ADD CONSTRAINT uk_tb_sys_log_dmnd_id UNIQUE (dmnd_id);

COMMENT ON COLUMN tb_sys_log.sys_log_sn IS '시스템로그일련번호 (sys_log_sn)';
COMMENT ON COLUMN tb_sys_log.dmnd_id IS '요청 상관관계 아이디 (dmnd_id)';
