-- 이미 BIGINT인 메뉴 PK에 DB IDENTITY 생성전략을 부여하고 레거시 수동 채번을 종료한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 메뉴 PK/FK의 물리 BIGINT와 표준 도메인을 일치시킨다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE (term_name = '메뉴일련번호' AND eng_abbr = 'MENU_SN')
   OR (term_name = '상위메뉴일련번호' AND eng_abbr = 'UP_MENU_SN');

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE domain_name = '일련번호N19'
          AND ((term_name = '메뉴일련번호' AND eng_abbr = 'MENU_SN')
            OR (term_name = '상위메뉴일련번호' AND eng_abbr = 'UP_MENU_SN'))) <> 2 THEN
        RAISE EXCEPTION 'standard term conflict: MENU_SN and UP_MENU_SN must map to 일련번호N19';
    END IF;
END $$;

-- V2_2의 8억 ROOT는 실제 자식이 없고 ROLE_ADMIN 매핑 1건만 남은 기술용 시드다.
-- 자동키가 전체 BIGINT 범위를 사용하도록 숫자 상한 필터를 제거하기 전에 이 숨은 센티널을 폐기한다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_menu_info WHERE up_menu_sn = 800000000) THEN
        RAISE EXCEPTION 'legacy ROOT menu still has children';
    END IF;
END $$;

-- 기존 PK/FK 값은 그대로 두고 생성전략만 추가한다. BY DEFAULT는 과거 시드의 명시 번호도 허용한다.
-- 자기참조 DEFERRABLE FK의 DELETE trigger가 대기 상태가 되기 전에 DDL을 먼저 수행해야 한다.
ALTER TABLE tb_menu_info
    ALTER COLUMN menu_sn ADD GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_menu_sn);

DELETE FROM tb_menu_crt_dtl WHERE menu_sn = 800000000;
DELETE FROM tb_menu_info
 WHERE menu_sn = 800000000
   AND menu_nm = 'ROOT'
   AND up_menu_sn IS NULL;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_menu_info WHERE menu_sn = 800000000) THEN
        RAISE EXCEPTION 'legacy ROOT menu retirement failed';
    END IF;
END $$;

-- 기존 명시 번호보다 큰 값부터 발급해 충돌을 차단한다. 빈 테이블이면 첫 nextval은 1이다.
SELECT setval('sq_menu_sn', COALESCE(max(menu_sn), 1), count(*) > 0)
  FROM tb_menu_info;

COMMENT ON COLUMN tb_menu_info.menu_sn IS '메뉴일련번호 (menu_sn) — DB IDENTITY 자동 생성';
