-- 비공식 결재 기술 PK와 포상관리의 논리 참조를 BIGINT PK/FK로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('비공식결재일련번호', 'IFML_ATRZ_SN',
        '비공식 결재 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '비공식결재일련번호'
          AND eng_abbr = 'IFML_ATRZ_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: IFML_ATRZ_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 결재에는 identity, 포상에는 같은 타입의 nullable FK 후보를 추가한다.
ALTER TABLE tb_ifml_atrz_info
    ADD COLUMN ifml_atrz_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_ifml_atrz_sn);
ALTER TABLE tb_rward_manage ADD COLUMN ifml_atrz_sn BIGINT;

-- Sync: 기존 문자열 논리참조를 신규 숫자 PK에 결정적으로 대응시킨다.
UPDATE tb_rward_manage reward
SET ifml_atrz_sn = sanction.ifml_atrz_sn
FROM tb_ifml_atrz_info sanction
WHERE reward.ifml_atrz_id = sanction.ifml_atrz_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_ifml_atrz_info WHERE ifml_atrz_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_ifml_atrz_info.ifml_atrz_sn backfill failed';
    END IF;
    IF EXISTS (
        SELECT 1 FROM tb_rward_manage
        WHERE ifml_atrz_id IS NOT NULL AND ifml_atrz_sn IS NULL
    ) THEN
        RAISE EXCEPTION 'tb_rward_manage.ifml_atrz_sn backfill failed or orphan exists';
    END IF;
END $$;

ALTER TABLE tb_ifml_atrz_info ALTER COLUMN ifml_atrz_sn SET NOT NULL;

-- Redirect / Contract: 숫자 PK로 교체하고 종전 논리참조를 검증된 FK로 승격한다.
ALTER TABLE tb_ifml_atrz_info DROP CONSTRAINT pk_tb_ifml_atrz_info;
ALTER TABLE tb_ifml_atrz_info
    ADD CONSTRAINT pk_tb_ifml_atrz_info PRIMARY KEY (ifml_atrz_sn);
ALTER TABLE tb_rward_manage
    ADD CONSTRAINT fk_tb_rward_manage_tb_ifml_atrz_info
        FOREIGN KEY (ifml_atrz_sn) REFERENCES tb_ifml_atrz_info (ifml_atrz_sn) NOT VALID;
ALTER TABLE tb_rward_manage
    VALIDATE CONSTRAINT fk_tb_rward_manage_tb_ifml_atrz_info;
CREATE INDEX ix_tb_rward_manage_ifml_atrz_sn ON tb_rward_manage (ifml_atrz_sn);

ALTER TABLE tb_rward_manage DROP COLUMN ifml_atrz_id; -- linter:ignore contract: 비공식결재 숫자 FK 백필·검증 및 소비자 전환 완료
ALTER TABLE tb_ifml_atrz_info DROP COLUMN ifml_atrz_id; -- linter:ignore contract: 비공식결재 숫자 PK 백필·검증 및 소비자 전환 완료

COMMENT ON COLUMN tb_ifml_atrz_info.ifml_atrz_sn IS '비공식결재일련번호 (ifml_atrz_sn)';
COMMENT ON COLUMN tb_rward_manage.ifml_atrz_sn IS '비공식결재일련번호 (ifml_atrz_sn)';
