-- 커뮤니티 기술 PK와 멤버십·게시판의 커뮤니티 참조 폐포를 BIGINT IDENTITY로 전환한다.
-- 사용자(user_id)·게시판(bbs_id)은 업무/보안 식별자이므로 문자열 키를 보존한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('커뮤니티일련번호', 'CMNTY_SN', '커뮤니티 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '커뮤니티일련번호'
          AND eng_abbr = 'CMNTY_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: CMNTY_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_cmnty_info
    ADD COLUMN cmnty_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_cmnty_sn);
ALTER TABLE tb_cmnty_user_map ADD COLUMN cmnty_sn BIGINT;
ALTER TABLE tb_bbs_master ADD COLUMN cmnty_sn BIGINT;

UPDATE tb_cmnty_user_map child
SET cmnty_sn = parent.cmnty_sn
FROM tb_cmnty_info parent
WHERE child.cmnty_id = parent.cmnty_id;
UPDATE tb_bbs_master child
SET cmnty_sn = parent.cmnty_sn
FROM tb_cmnty_info parent
WHERE child.cmnty_id = parent.cmnty_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_cmnty_info WHERE cmnty_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_cmnty_info.cmnty_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_cmnty_user_map WHERE cmnty_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_cmnty_user_map.cmnty_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_bbs_master WHERE cmnty_id IS NOT NULL AND cmnty_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_bbs_master.cmnty_sn logical relationship backfill failed';
    END IF;
END $$;

ALTER TABLE tb_cmnty_info ALTER COLUMN cmnty_sn SET NOT NULL;
ALTER TABLE tb_cmnty_user_map ALTER COLUMN cmnty_sn SET NOT NULL;

ALTER TABLE tb_cmnty_user_map DROP CONSTRAINT fk_tb_cmnty_user_map_tb_cmnty_info;
ALTER TABLE tb_cmnty_user_map DROP CONSTRAINT pk_tb_cmnty_user_map;
ALTER TABLE tb_cmnty_info DROP CONSTRAINT pk_tb_cmnty_info;

ALTER TABLE tb_cmnty_info ADD CONSTRAINT pk_tb_cmnty_info PRIMARY KEY (cmnty_sn);
ALTER TABLE tb_cmnty_user_map ADD CONSTRAINT pk_tb_cmnty_user_map PRIMARY KEY (cmnty_sn, user_id);
ALTER TABLE tb_cmnty_user_map
    ADD CONSTRAINT fk_tb_cmnty_user_map_tb_cmnty_info
        FOREIGN KEY (cmnty_sn) REFERENCES tb_cmnty_info (cmnty_sn) NOT VALID;
ALTER TABLE tb_cmnty_user_map VALIDATE CONSTRAINT fk_tb_cmnty_user_map_tb_cmnty_info;

ALTER TABLE tb_cmnty_info DROP COLUMN cmnty_id; -- linter:ignore contract: 커뮤니티 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_cmnty_user_map DROP COLUMN cmnty_id; -- linter:ignore contract: 멤버십 커뮤니티 숫자 복합키/FK 백필·소비자 전환 완료
ALTER TABLE tb_bbs_master DROP COLUMN cmnty_id; -- linter:ignore contract: 게시판 커뮤니티 숫자 논리 참조 백필·소비자 전환 완료

CREATE INDEX ix_tb_bbs_master_cmnty_sn ON tb_bbs_master (cmnty_sn);

COMMENT ON COLUMN tb_cmnty_info.cmnty_sn IS '커뮤니티일련번호 (cmnty_sn)';
COMMENT ON COLUMN tb_cmnty_user_map.cmnty_sn IS '커뮤니티일련번호 (cmnty_sn)';
COMMENT ON COLUMN tb_bbs_master.cmnty_sn IS '커뮤니티일련번호 (cmnty_sn)';
