-- 웹 로그의 잘린 UUID 수동 기술 PK를 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).
-- 절차: Expand(신규 web_log_sn) -> Sync(기존 4,003행 백필 검증) -> Redirect(PK 전환) -> Contract(구 dmnd_id 제거).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('웹로그일련번호', 'WEB_LOG_SN', '웹 로그 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '웹로그일련번호'
          AND eng_abbr = 'WEB_LOG_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: WEB_LOG_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: PostgreSQL identity가 기존 행에도 유일한 값을 채운다.
ALTER TABLE tb_web_log
    ADD COLUMN web_log_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_web_log_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_web_log WHERE web_log_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_web_log.web_log_sn backfill failed';
    END IF;
    IF (SELECT count(*) FROM tb_web_log) <> (SELECT count(DISTINCT web_log_sn) FROM tb_web_log) THEN
        RAISE EXCEPTION 'tb_web_log.web_log_sn uniqueness backfill failed';
    END IF;
END $$;

ALTER TABLE tb_web_log ALTER COLUMN web_log_sn SET NOT NULL;

-- Redirect / Contract: dmnd_id는 AuditEvent와 무관한 WLOG_ 잘린 UUID 기술키이므로 제거한다.
ALTER TABLE tb_web_log DROP CONSTRAINT pk_tb_web_log;
ALTER TABLE tb_web_log
    ADD CONSTRAINT pk_tb_web_log PRIMARY KEY (web_log_sn);
ALTER TABLE tb_web_log DROP COLUMN dmnd_id; -- linter:ignore contract: 웹 로그 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_web_log.web_log_sn IS '웹로그일련번호 (web_log_sn)';
