-- 개인정보 로그의 요청 ID는 상관관계 업무키로 보존하고 내부 PK만 BIGINT identity로 분리한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('개인정보로그일련번호', 'PRVC_LOG_SN',
        '개인정보 조회 로그 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '개인정보로그일련번호'
          AND eng_abbr = 'PRVC_LOG_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: PRVC_LOG_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_privacy_log
    ADD COLUMN prvc_log_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_prvc_log_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_privacy_log WHERE prvc_log_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_privacy_log.prvc_log_sn backfill failed';
    END IF;
    IF EXISTS (
        SELECT dmnd_id FROM tb_privacy_log GROUP BY dmnd_id HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'tb_privacy_log.dmnd_id duplicate business keys exist';
    END IF;
END $$;

ALTER TABLE tb_privacy_log DROP CONSTRAINT pk_tb_privacy_log;
ALTER TABLE tb_privacy_log
    ADD CONSTRAINT pk_tb_privacy_log PRIMARY KEY (prvc_log_sn);
ALTER TABLE tb_privacy_log
    ADD CONSTRAINT uk_tb_privacy_log_dmnd_id UNIQUE (dmnd_id);

COMMENT ON COLUMN tb_privacy_log.prvc_log_sn IS '개인정보로그일련번호 (prvc_log_sn)';
COMMENT ON COLUMN tb_privacy_log.dmnd_id IS '요청아이디 업무 상관관계 키 (dmnd_id)';
