-- 첨부파일 마스터 기술 PK와 상세·업무 참조 폐포를 BIGINT IDENTITY로 전환한다.
-- 파일 상세의 atch_file_seq는 마스터 안의 업무 순번이므로 그대로 보존한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 공공 표준사전의 ATCH_FILE_SN은 NUMERIC(10)으로 매핑돼 있으나, 프로젝트 자동 내부키 표준인
-- BIGINT(19)에 맞춰 프로젝트 확장 도메인으로 명시적으로 재매핑한다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '첨부파일일련번호'
  AND eng_abbr = 'ATCH_FILE_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '첨부파일일련번호'
          AND eng_abbr = 'ATCH_FILE_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: ATCH_FILE_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 마스터가 새 번호를 만들고, 모든 물리 참조원은 nullable BIGINT 그림자 컬럼을 받는다.
ALTER TABLE tb_file_master
    ADD COLUMN atch_file_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_atch_file_sn);
ALTER TABLE tb_file_detail ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_bbs_item ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_bnr_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_dept_task_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_diary_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_dta_use_stats ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_email_dsptch_manage ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_memo_rpt_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_note_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_rpt_info ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_rward_manage ADD COLUMN atch_file_sn BIGINT;
ALTER TABLE tb_schdl_info ADD COLUMN atch_file_sn BIGINT;

-- Sync: 문자열 FK를 마스터의 새 숫자 키로 보존한다.
UPDATE tb_file_detail child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_bbs_item child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_bnr_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_dept_task_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_diary_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_dta_use_stats child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_email_dsptch_manage child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_memo_rpt_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_note_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_rpt_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_rward_manage child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;
UPDATE tb_schdl_info child SET atch_file_sn = parent.atch_file_sn
FROM tb_file_master parent WHERE child.atch_file_id = parent.atch_file_id;

-- 팝업만 FK 컬럼 대신 URL 문자열로 첨부를 참조한다. 두 레거시 형태를 정규 숫자 경로로 수렴시킨다.
UPDATE tb_popup_info popup
SET file_url = '/api/v1/files/' || parent.atch_file_sn
FROM tb_file_master parent
WHERE popup.file_url = '/api/v1/files/' || parent.atch_file_id
   OR popup.file_url = '/api/v1/files/download?fileId=' || parent.atch_file_id;

-- Contract 전에 누락이 없음을 증명한다. nullable 업무 참조는 기존 값이 있을 때만 새 값이 필수다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_file_master WHERE atch_file_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_file_master.atch_file_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_file_detail WHERE atch_file_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_file_detail.atch_file_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_bbs_item WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_bnr_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_dept_task_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_diary_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_dta_use_stats WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_email_dsptch_manage WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_memo_rpt_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_note_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_rpt_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_rward_manage WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_schdl_info WHERE atch_file_id IS NOT NULL AND atch_file_sn IS NULL) THEN
        RAISE EXCEPTION 'attachment business relationship backfill failed';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM tb_popup_info
        WHERE file_url LIKE '/api/v1/files/download?fileId=%'
           OR (file_url LIKE '/api/v1/files/FILE\_%' ESCAPE '\')
    ) THEN
        RAISE EXCEPTION 'tb_popup_info.file_url attachment backfill failed';
    END IF;
END $$;

ALTER TABLE tb_file_master ALTER COLUMN atch_file_sn SET NOT NULL;
ALTER TABLE tb_file_detail ALTER COLUMN atch_file_sn SET NOT NULL;

-- Redirect: 기존 FK/UK/PK를 새 숫자 키 폐포로 교체한다.
ALTER TABLE tb_file_detail DROP CONSTRAINT fk_tb_file_detail_tb_file_master;
ALTER TABLE tb_bbs_item DROP CONSTRAINT fk_tb_bbs_item_tb_file_master;
ALTER TABLE tb_bnr_info DROP CONSTRAINT fk_tb_bnr_info_tb_file_master;
ALTER TABLE tb_dept_task_info DROP CONSTRAINT fk_tb_dept_task_info_tb_file_master;
ALTER TABLE tb_diary_info DROP CONSTRAINT fk_tb_diary_info_tb_file_master;
ALTER TABLE tb_dta_use_stats DROP CONSTRAINT fk_tb_dta_use_stats_tb_file_master;
ALTER TABLE tb_email_dsptch_manage DROP CONSTRAINT fk_tb_email_dsptch_manage_tb_file_master;
ALTER TABLE tb_memo_rpt_info DROP CONSTRAINT fk_tb_memo_rpt_info_tb_file_master;
ALTER TABLE tb_note_info DROP CONSTRAINT fk_tb_note_info_tb_file_master;
ALTER TABLE tb_rpt_info DROP CONSTRAINT fk_tb_rpt_info_tb_file_master;
ALTER TABLE tb_rward_manage DROP CONSTRAINT fk_tb_rward_manage_tb_file_master;
ALTER TABLE tb_schdl_info DROP CONSTRAINT fk_tb_schdl_info_tb_file_master;
ALTER TABLE tb_file_detail DROP CONSTRAINT uk_tb_file_detail_sn;
ALTER TABLE tb_file_master DROP CONSTRAINT pk_tb_file_master;

ALTER TABLE tb_file_master ADD CONSTRAINT pk_tb_file_master PRIMARY KEY (atch_file_sn);
ALTER TABLE tb_file_detail
    ADD CONSTRAINT uk_tb_file_detail_sn UNIQUE (atch_file_sn, atch_file_seq);

ALTER TABLE tb_file_detail ADD CONSTRAINT fk_tb_file_detail_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_bbs_item ADD CONSTRAINT fk_tb_bbs_item_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_bnr_info ADD CONSTRAINT fk_tb_bnr_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_dept_task_info ADD CONSTRAINT fk_tb_dept_task_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_diary_info ADD CONSTRAINT fk_tb_diary_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_dta_use_stats ADD CONSTRAINT fk_tb_dta_use_stats_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_email_dsptch_manage ADD CONSTRAINT fk_tb_email_dsptch_manage_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_memo_rpt_info ADD CONSTRAINT fk_tb_memo_rpt_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_note_info ADD CONSTRAINT fk_tb_note_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_rpt_info ADD CONSTRAINT fk_tb_rpt_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_rward_manage ADD CONSTRAINT fk_tb_rward_manage_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;
ALTER TABLE tb_schdl_info ADD CONSTRAINT fk_tb_schdl_info_tb_file_master
    FOREIGN KEY (atch_file_sn) REFERENCES tb_file_master (atch_file_sn) NOT VALID;

ALTER TABLE tb_file_detail VALIDATE CONSTRAINT fk_tb_file_detail_tb_file_master;
ALTER TABLE tb_bbs_item VALIDATE CONSTRAINT fk_tb_bbs_item_tb_file_master;
ALTER TABLE tb_bnr_info VALIDATE CONSTRAINT fk_tb_bnr_info_tb_file_master;
ALTER TABLE tb_dept_task_info VALIDATE CONSTRAINT fk_tb_dept_task_info_tb_file_master;
ALTER TABLE tb_diary_info VALIDATE CONSTRAINT fk_tb_diary_info_tb_file_master;
ALTER TABLE tb_dta_use_stats VALIDATE CONSTRAINT fk_tb_dta_use_stats_tb_file_master;
ALTER TABLE tb_email_dsptch_manage VALIDATE CONSTRAINT fk_tb_email_dsptch_manage_tb_file_master;
ALTER TABLE tb_memo_rpt_info VALIDATE CONSTRAINT fk_tb_memo_rpt_info_tb_file_master;
ALTER TABLE tb_note_info VALIDATE CONSTRAINT fk_tb_note_info_tb_file_master;
ALTER TABLE tb_rpt_info VALIDATE CONSTRAINT fk_tb_rpt_info_tb_file_master;
ALTER TABLE tb_rward_manage VALIDATE CONSTRAINT fk_tb_rward_manage_tb_file_master;
ALTER TABLE tb_schdl_info VALIDATE CONSTRAINT fk_tb_schdl_info_tb_file_master;

-- Contract: 동일 릴리스의 앱 소비자 전환을 전제로 문자열 키를 제거한다.
ALTER TABLE tb_file_master DROP COLUMN atch_file_id; -- linter:ignore contract: 첨부 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_file_detail DROP COLUMN atch_file_id; -- linter:ignore contract: 상세 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_bbs_item DROP COLUMN atch_file_id; -- linter:ignore contract: 게시물 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_bnr_info DROP COLUMN atch_file_id; -- linter:ignore contract: 배너 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_dept_task_info DROP COLUMN atch_file_id; -- linter:ignore contract: 부서업무 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_diary_info DROP COLUMN atch_file_id; -- linter:ignore contract: 업무일지 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_dta_use_stats DROP COLUMN atch_file_id; -- linter:ignore contract: 자료활용통계 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_email_dsptch_manage DROP COLUMN atch_file_id; -- linter:ignore contract: 발송메일 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_memo_rpt_info DROP COLUMN atch_file_id; -- linter:ignore contract: 메모보고 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_note_info DROP COLUMN atch_file_id; -- linter:ignore contract: 쪽지 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_rpt_info DROP COLUMN atch_file_id; -- linter:ignore contract: 업무보고 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_rward_manage DROP COLUMN atch_file_id; -- linter:ignore contract: 상벌 첨부 숫자 FK 백필·소비자 전환 완료
ALTER TABLE tb_schdl_info DROP COLUMN atch_file_id; -- linter:ignore contract: 일정 첨부 숫자 FK 백필·소비자 전환 완료

CREATE INDEX ix_tb_bbs_item_atch_file_sn ON tb_bbs_item (atch_file_sn);
CREATE INDEX ix_tb_bnr_info_atch_file_sn ON tb_bnr_info (atch_file_sn);
CREATE INDEX ix_tb_dept_task_info_atch_file_sn ON tb_dept_task_info (atch_file_sn);
CREATE INDEX ix_tb_diary_info_atch_file_sn ON tb_diary_info (atch_file_sn);
CREATE INDEX ix_tb_dta_use_stats_atch_file_sn ON tb_dta_use_stats (atch_file_sn);
CREATE INDEX ix_tb_email_dsptch_manage_atch_file_sn ON tb_email_dsptch_manage (atch_file_sn);
CREATE INDEX ix_tb_memo_rpt_info_atch_file_sn ON tb_memo_rpt_info (atch_file_sn);
CREATE INDEX ix_tb_note_info_atch_file_sn ON tb_note_info (atch_file_sn);
CREATE INDEX ix_tb_rpt_info_atch_file_sn ON tb_rpt_info (atch_file_sn);
CREATE INDEX ix_tb_rward_manage_atch_file_sn ON tb_rward_manage (atch_file_sn);
CREATE INDEX ix_tb_schdl_info_atch_file_sn ON tb_schdl_info (atch_file_sn);

COMMENT ON COLUMN tb_file_master.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_file_detail.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_bbs_item.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_bnr_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_dept_task_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_diary_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_dta_use_stats.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_email_dsptch_manage.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_memo_rpt_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_note_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_rpt_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_rward_manage.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
COMMENT ON COLUMN tb_schdl_info.atch_file_sn IS '첨부파일일련번호 (atch_file_sn)';
