-- 블로그 기술 PK와 멤버십·게시물·게시판의 블로그 참조 폐포를 BIGINT IDENTITY로 전환한다.
-- 게시판(bbs_id)·사용자(user_id)는 업무/보안 식별자이므로 문자열 키를 보존한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('블로그일련번호', 'BLOG_SN', '블로그 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '블로그일련번호'
          AND eng_abbr = 'BLOG_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: BLOG_SN must map to 일련번호N19';
    END IF;
END $$;

ALTER TABLE tb_blog_info
    ADD COLUMN blog_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_blog_sn);
ALTER TABLE tb_blog_user_map ADD COLUMN blog_sn BIGINT;
ALTER TABLE tb_bbs_item ADD COLUMN blog_sn BIGINT;
ALTER TABLE tb_bbs_master ADD COLUMN blog_sn BIGINT;

UPDATE tb_blog_user_map child
SET blog_sn = parent.blog_sn
FROM tb_blog_info parent
WHERE child.blog_id = parent.blog_id;
UPDATE tb_bbs_item child
SET blog_sn = parent.blog_sn
FROM tb_blog_info parent
WHERE child.blog_id = parent.blog_id;
UPDATE tb_bbs_master child
SET blog_sn = parent.blog_sn
FROM tb_blog_info parent
WHERE child.blog_id = parent.blog_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_blog_info WHERE blog_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_blog_info.blog_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_blog_user_map WHERE blog_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_blog_user_map.blog_sn relationship backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_bbs_item WHERE blog_id IS NOT NULL AND blog_sn IS NULL)
        OR EXISTS (SELECT 1 FROM tb_bbs_master WHERE blog_id IS NOT NULL AND blog_sn IS NULL) THEN
        RAISE EXCEPTION 'blog logical relationship backfill failed';
    END IF;
END $$;

ALTER TABLE tb_blog_info ALTER COLUMN blog_sn SET NOT NULL;
ALTER TABLE tb_blog_user_map ALTER COLUMN blog_sn SET NOT NULL;

ALTER TABLE tb_blog_user_map DROP CONSTRAINT fk_tb_blog_user_map_tb_blog_info;
ALTER TABLE tb_blog_user_map DROP CONSTRAINT pk_tb_blog_user_map;
ALTER TABLE tb_blog_info DROP CONSTRAINT pk_tb_blog_info;

ALTER TABLE tb_blog_info ADD CONSTRAINT pk_tb_blog_info PRIMARY KEY (blog_sn);
ALTER TABLE tb_blog_user_map ADD CONSTRAINT pk_tb_blog_user_map PRIMARY KEY (blog_sn, user_id);
ALTER TABLE tb_blog_user_map
    ADD CONSTRAINT fk_tb_blog_user_map_tb_blog_info
        FOREIGN KEY (blog_sn) REFERENCES tb_blog_info (blog_sn) NOT VALID;
ALTER TABLE tb_blog_user_map VALIDATE CONSTRAINT fk_tb_blog_user_map_tb_blog_info;

ALTER TABLE tb_blog_info DROP COLUMN blog_id; -- linter:ignore contract: 블로그 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_blog_user_map DROP COLUMN blog_id; -- linter:ignore contract: 멤버십 블로그 숫자 복합키/FK 백필·소비자 전환 완료
ALTER TABLE tb_bbs_item DROP COLUMN blog_id; -- linter:ignore contract: 게시물 블로그 숫자 논리 참조 백필·소비자 전환 완료
ALTER TABLE tb_bbs_master DROP COLUMN blog_id; -- linter:ignore contract: 게시판 블로그 숫자 논리 참조 백필·소비자 전환 완료

CREATE INDEX ix_tb_bbs_item_blog_sn ON tb_bbs_item (blog_sn);
CREATE INDEX ix_tb_bbs_master_blog_sn ON tb_bbs_master (blog_sn);

COMMENT ON COLUMN tb_blog_info.blog_sn IS '블로그일련번호 (blog_sn)';
COMMENT ON COLUMN tb_blog_user_map.blog_sn IS '블로그일련번호 (blog_sn)';
COMMENT ON COLUMN tb_bbs_item.blog_sn IS '블로그일련번호 (blog_sn)';
COMMENT ON COLUMN tb_bbs_master.blog_sn IS '블로그일련번호 (blog_sn)';
