-- 도장정보 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('도장일련번호', 'STMP_SN',
        '도장정보 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '도장일련번호'
          AND eng_abbr = 'STMP_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: STMP_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: identity 컬럼이 기존 행을 자동 백필한다.
ALTER TABLE tb_stmp_info
    ADD COLUMN stmp_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_stmp_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_stmp_info WHERE stmp_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_stmp_info.stmp_sn backfill failed';
    END IF;
END $$;

-- Redirect / Contract: 참조 FK가 없는 단일 테이블의 PK를 신규 숫자 키로 교체한다.
ALTER TABLE tb_stmp_info DROP CONSTRAINT pk_tb_stmp_info;
ALTER TABLE tb_stmp_info
    ADD CONSTRAINT pk_tb_stmp_info PRIMARY KEY (stmp_sn);
ALTER TABLE tb_stmp_info DROP COLUMN mpng_crt_id; -- linter:ignore contract: 도장 숫자 PK 백필·소비자 전환 완료

COMMENT ON COLUMN tb_stmp_info.stmp_sn IS '도장일련번호 (stmp_sn)';
