-- 사용자 알림 기술 PK를 문자열 수동 채번에서 BIGINT IDENTITY로 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 공공 표준사전의 NOTI_SN은 NUMERIC(22)로 매핑돼 있으나 프로젝트 자동 내부키 표준인
-- BIGINT(19)에 맞춰 프로젝트 확장 도메인으로 명시적으로 재매핑한다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = '알림일련번호'
  AND eng_abbr = 'NOTI_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '알림일련번호'
          AND eng_abbr = 'NOTI_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: NOTI_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand / Sync: 임시 숫자 컬럼에 identity가 기존 6행을 포함한 모든 행을 자동 백필한다.
ALTER TABLE tb_user_noti
    ADD COLUMN noti_sn_new BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_noti_sn);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_user_noti WHERE noti_sn_new IS NULL) THEN
        RAISE EXCEPTION 'tb_user_noti.noti_sn backfill failed';
    END IF;
END $$;

-- Redirect / Contract: 수신자 FK·인덱스·읽음 CHECK는 건드리지 않고 PK 컬럼만 교체한다.
ALTER TABLE tb_user_noti DROP CONSTRAINT pk_tb_user_noti;
ALTER TABLE tb_user_noti DROP COLUMN noti_sn; -- linter:ignore contract: 알림 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_user_noti RENAME COLUMN noti_sn_new TO noti_sn; -- linter:ignore contract: 알림 숫자 PK 백필·소비자 전환 완료
ALTER TABLE tb_user_noti
    ADD CONSTRAINT pk_tb_user_noti PRIMARY KEY (noti_sn);

COMMENT ON COLUMN tb_user_noti.noti_sn IS '알림일련번호 (noti_sn)';
