-- SMS 발송 기술 PK와 수신자의 식별 관계를 BIGINT PK/FK로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

-- 기존 공공표준 용어를 프로젝트의 물리 BIGINT 타입과 일치시킨다.
UPDATE meta_standard_terms
SET domain_name = '일련번호N19'
WHERE term_name = 'SMS전송일련번호'
  AND eng_abbr = 'SMS_TRSM_SN';

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = 'SMS전송일련번호'
          AND eng_abbr = 'SMS_TRSM_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: SMS_TRSM_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 발송에는 identity, 수신에는 같은 타입의 FK 후보를 추가한다.
ALTER TABLE tb_sms_info
    ADD COLUMN sms_trsm_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_sms_trsm_sn);
ALTER TABLE tb_sms_rcptn ADD COLUMN sms_trsm_sn BIGINT;

-- Sync: 기존 문자열 기술키를 신규 숫자 PK에 결정적으로 대응시킨다.
UPDATE tb_sms_rcptn recipient
SET sms_trsm_sn = sms.sms_trsm_sn
FROM tb_sms_info sms
WHERE recipient.sms_id = sms.sms_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_sms_info WHERE sms_trsm_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_sms_info.sms_trsm_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_sms_rcptn WHERE sms_trsm_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_sms_rcptn.sms_trsm_sn backfill failed or orphan exists';
    END IF;
END $$;

ALTER TABLE tb_sms_info ALTER COLUMN sms_trsm_sn SET NOT NULL;
ALTER TABLE tb_sms_rcptn ALTER COLUMN sms_trsm_sn SET NOT NULL;

-- Redirect / Contract: 기존 FK·복합 PK·조회 인덱스를 숫자 관계로 재결속한다.
ALTER TABLE tb_sms_rcptn DROP CONSTRAINT fk_tb_sms_rcptn_tb_sms_info;
ALTER TABLE tb_sms_rcptn DROP CONSTRAINT pk_tb_sms_rcptn;
ALTER TABLE tb_sms_info DROP CONSTRAINT pk_tb_sms_info;
DROP INDEX ix_tb_sms_rcptn_sms_id;

ALTER TABLE tb_sms_info
    ADD CONSTRAINT pk_tb_sms_info PRIMARY KEY (sms_trsm_sn);
ALTER TABLE tb_sms_rcptn
    ADD CONSTRAINT pk_tb_sms_rcptn PRIMARY KEY (rcptn_telno, sms_trsm_sn);
ALTER TABLE tb_sms_rcptn
    ADD CONSTRAINT fk_tb_sms_rcptn_tb_sms_info
        FOREIGN KEY (sms_trsm_sn) REFERENCES tb_sms_info (sms_trsm_sn) NOT VALID;
ALTER TABLE tb_sms_rcptn
    VALIDATE CONSTRAINT fk_tb_sms_rcptn_tb_sms_info;
CREATE INDEX ix_tb_sms_rcptn_sms_trsm_sn ON tb_sms_rcptn (sms_trsm_sn);

ALTER TABLE tb_sms_rcptn DROP COLUMN sms_id; -- linter:ignore contract: SMS 숫자 FK 백필·검증 및 소비자 전환 완료
ALTER TABLE tb_sms_info DROP COLUMN sms_id; -- linter:ignore contract: SMS 숫자 PK 백필·검증 및 소비자 전환 완료

COMMENT ON COLUMN tb_sms_info.sms_trsm_sn IS 'SMS전송일련번호 (sms_trsm_sn)';
COMMENT ON COLUMN tb_sms_rcptn.sms_trsm_sn IS 'SMS전송일련번호 (sms_trsm_sn)';
