-- 행사 기술 PK와 외부인사의 식별 관계를 BIGINT PK/FK로 함께 전환한다.
-- 사용자 승인: 비운영 시스템의 기존 데이터 일괄 변환 + 이번 PK 현대화에 한한 DB 헌법 예외(2026-08-13).

INSERT INTO meta_standard_terms (term_name, eng_abbr, description, domain_name)
VALUES ('행사일련번호', 'EVNT_SN',
        '행사 내부 레코드에 연속되게 매긴 번호', '일련번호N19')
ON CONFLICT (eng_abbr) DO NOTHING;

DO $$
BEGIN
    IF (SELECT count(*) FROM meta_standard_terms
        WHERE term_name = '행사일련번호'
          AND eng_abbr = 'EVNT_SN'
          AND domain_name = '일련번호N19') <> 1 THEN
        RAISE EXCEPTION 'standard term conflict: EVNT_SN must map to 일련번호N19';
    END IF;
END $$;

-- Expand: 행사에는 identity, 외부인사에는 같은 타입의 FK 후보를 추가한다.
ALTER TABLE tb_event_info
    ADD COLUMN evnt_sn BIGINT GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME sq_evnt_sn);
ALTER TABLE tb_extrl_hr_info ADD COLUMN evnt_sn BIGINT;

-- Sync: 기존 문자열 행사 식별자를 신규 숫자 PK에 결정적으로 대응시킨다.
UPDATE tb_extrl_hr_info external_hr
SET evnt_sn = event.evnt_sn
FROM tb_event_info event
WHERE external_hr.evnt_id = event.evnt_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_event_info WHERE evnt_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_event_info.evnt_sn backfill failed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_extrl_hr_info WHERE evnt_sn IS NULL) THEN
        RAISE EXCEPTION 'tb_extrl_hr_info.evnt_sn backfill failed or orphan exists';
    END IF;
END $$;

ALTER TABLE tb_event_info ALTER COLUMN evnt_sn SET NOT NULL;
ALTER TABLE tb_extrl_hr_info ALTER COLUMN evnt_sn SET NOT NULL;

-- Redirect / Contract: 자식 FK와 복합 PK를 먼저 해제한 뒤 숫자 관계로 재결속한다.
ALTER TABLE tb_extrl_hr_info DROP CONSTRAINT fk_tb_extrl_hr_info_tb_event_info;
ALTER TABLE tb_extrl_hr_info DROP CONSTRAINT pk_tb_extrl_hr_info;
ALTER TABLE tb_event_info DROP CONSTRAINT pk_tb_event_info;

ALTER TABLE tb_event_info
    ADD CONSTRAINT pk_tb_event_info PRIMARY KEY (evnt_sn);
ALTER TABLE tb_extrl_hr_info
    ADD CONSTRAINT pk_tb_extrl_hr_info PRIMARY KEY (evnt_sn, otsd_hr_id);
ALTER TABLE tb_extrl_hr_info
    ADD CONSTRAINT fk_tb_extrl_hr_info_tb_event_info
        FOREIGN KEY (evnt_sn) REFERENCES tb_event_info (evnt_sn) NOT VALID;
ALTER TABLE tb_extrl_hr_info
    VALIDATE CONSTRAINT fk_tb_extrl_hr_info_tb_event_info;

ALTER TABLE tb_extrl_hr_info DROP COLUMN evnt_id; -- linter:ignore contract: 행사 숫자 FK 백필·검증 및 소비자 전환 완료
ALTER TABLE tb_event_info DROP COLUMN evnt_id; -- linter:ignore contract: 행사 숫자 PK 백필·검증 및 소비자 전환 완료

COMMENT ON COLUMN tb_event_info.evnt_sn IS '행사일련번호 (evnt_sn)';
COMMENT ON COLUMN tb_extrl_hr_info.evnt_sn IS '행사일련번호 (evnt_sn)';
