-- V2_99: Explicit initial OPERATION grants from the approved source catalog.
-- Expand only: application startup remains fenced until the separate verified contract.
SET LOCAL lock_timeout = '5s';
-- Keep the validated legacy policy stable until its evidence snapshot is recorded.
LOCK TABLE tb_authrt_info, tb_user_authrt_map, tb_authrt_role_map,
    tb_role_hierarchy, tb_role_info, tb_role_prgrm_map, tb_prgrm_lst,
    tb_authrt_grnt_map, tb_authrt_chg_hstry IN SHARE MODE NOWAIT;
DO $$
BEGIN
    IF EXISTS (SELECT authrt_cd,role_cd FROM tb_authrt_role_map EXCEPT VALUES
        ('ROLE_ADMIN','ROLE_ADMIN'),('ROLE_SYSTEM','ROLE_SYSTEM'),('ROLE_USER','ROLE_USER'))
       OR (SELECT count(*) FROM tb_authrt_role_map) <> 3 THEN
        RAISE EXCEPTION 'Unreviewed legacy group role mapping; compare effective permissions before seeding';
    END IF;
    IF EXISTS (SELECT higher_authrt,lower_authrt FROM tb_role_hierarchy EXCEPT VALUES
        ('ROLE_SYSTEM','ROLE_ADMIN'),('ROLE_ADMIN','ROLE_USER'))
       OR (SELECT count(*) FROM tb_role_hierarchy) <> 2 THEN
        RAISE EXCEPTION 'Unreviewed legacy role hierarchy';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_user_authrt_map WHERE authrt_id NOT IN ('ROLE_ADMIN','ROLE_SYSTEM','ROLE_USER','ROLE_ANONYMOUS')) THEN
        RAISE EXCEPTION 'Unreviewed legacy user group; no implicit default is allowed';
    END IF;
    IF EXISTS (SELECT 1 FROM tb_authrt_grnt_map WHERE authrt_type_cd='OPERATION') THEN
        RAISE EXCEPTION 'Operation grants already exist before the initial reviewed seed';
    END IF;
END $$;

INSERT INTO tb_authrt_grnt_map(authrt_cd,authrt_type_cd,authrt_grnt_cd,crt_dt,mdfcn_dt,frst_rgtr_id,last_mdfr_id)
SELECT seed.group_code,'OPERATION',seed.permission_code,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SYSTEM','SYSTEM'
FROM (VALUES
    ('ROLE_ADMIN','ABSENCE_READ'),
    ('ROLE_ADMIN','ABSENCE_UPDATE'),
    ('ROLE_ADMIN','ADBK_CREATE'),
    ('ROLE_ADMIN','ADBK_DELETE'),
    ('ROLE_ADMIN','ADBK_DELETE_ALL'),
    ('ROLE_ADMIN','ADBK_READ'),
    ('ROLE_ADMIN','ADBK_READ_ALL'),
    ('ROLE_ADMIN','ADBK_UPDATE'),
    ('ROLE_ADMIN','ADBK_UPDATE_ALL'),
    ('ROLE_ADMIN','ADMCODE_CREATE'),
    ('ROLE_ADMIN','ADMCODE_DELETE'),
    ('ROLE_ADMIN','ADMCODE_READ'),
    ('ROLE_ADMIN','ADMCODE_UPDATE'),
    ('ROLE_ADMIN','APPROVAL_APPROVE'),
    ('ROLE_ADMIN','APPROVAL_CANCEL'),
    ('ROLE_ADMIN','APPROVAL_CREATE'),
    ('ROLE_ADMIN','APPROVAL_READ'),
    ('ROLE_ADMIN','AUTHRT_ASSIGN'),
    ('ROLE_ADMIN','AUTHRT_AUDIT'),
    ('ROLE_ADMIN','AUTHRT_CREATE'),
    ('ROLE_ADMIN','AUTHRT_DELETE'),
    ('ROLE_ADMIN','AUTHRT_GRANT'),
    ('ROLE_ADMIN','AUTHRT_READ'),
    ('ROLE_ADMIN','AUTHRT_UPDATE'),
    ('ROLE_ADMIN','BANNER_CREATE'),
    ('ROLE_ADMIN','BANNER_DELETE'),
    ('ROLE_ADMIN','BANNER_READ'),
    ('ROLE_ADMIN','BANNER_UPDATE'),
    ('ROLE_ADMIN','BBS_MST_CREATE'),
    ('ROLE_ADMIN','BBS_MST_DELETE'),
    ('ROLE_ADMIN','BBS_MST_READ'),
    ('ROLE_ADMIN','BBS_MST_READ_ALL'),
    ('ROLE_ADMIN','BBS_MST_UPDATE'),
    ('ROLE_ADMIN','BOARD_CREATE'),
    ('ROLE_ADMIN','BOARD_DELETE'),
    ('ROLE_ADMIN','BOARD_DELETE_ALL'),
    ('ROLE_ADMIN','BOARD_LIKE'),
    ('ROLE_ADMIN','BOARD_READ'),
    ('ROLE_ADMIN','BOARD_READ_ALL'),
    ('ROLE_ADMIN','BOARD_UPDATE'),
    ('ROLE_ADMIN','BOARD_UPDATE_ALL'),
    ('ROLE_ADMIN','CLASS_GRP_CREATE'),
    ('ROLE_ADMIN','CLASS_GRP_DELETE'),
    ('ROLE_ADMIN','CLASS_GRP_READ'),
    ('ROLE_ADMIN','CLASS_GRP_UPDATE'),
    ('ROLE_ADMIN','CODE_CREATE'),
    ('ROLE_ADMIN','CODE_DELETE'),
    ('ROLE_ADMIN','CODE_READ'),
    ('ROLE_ADMIN','CODE_UPDATE'),
    ('ROLE_ADMIN','COMMENT_CREATE'),
    ('ROLE_ADMIN','COMMENT_DELETE'),
    ('ROLE_ADMIN','COMMENT_DELETE_ALL'),
    ('ROLE_ADMIN','COMMENT_READ'),
    ('ROLE_ADMIN','COMMENT_READ_ALL'),
    ('ROLE_ADMIN','COMMENT_UPDATE'),
    ('ROLE_ADMIN','COMMENT_UPDATE_ALL'),
    ('ROLE_ADMIN','COMMUNITY_APPROVE'),
    ('ROLE_ADMIN','COMMUNITY_CREATE_ALL'),
    ('ROLE_ADMIN','COMMUNITY_DELETE_ALL'),
    ('ROLE_ADMIN','COMMUNITY_JOIN'),
    ('ROLE_ADMIN','COMMUNITY_READ'),
    ('ROLE_ADMIN','COMMUNITY_READ_ALL'),
    ('ROLE_ADMIN','COMMUNITY_REJECT'),
    ('ROLE_ADMIN','COMMUNITY_UPDATE_ALL'),
    ('ROLE_ADMIN','DASHBOARD_READ'),
    ('ROLE_ADMIN','DEPT_BOX_CREATE'),
    ('ROLE_ADMIN','DEPT_BOX_DELETE'),
    ('ROLE_ADMIN','DEPT_BOX_READ'),
    ('ROLE_ADMIN','DEPT_BOX_UPDATE'),
    ('ROLE_ADMIN','DEPT_CREATE'),
    ('ROLE_ADMIN','DEPT_DELETE'),
    ('ROLE_ADMIN','DEPT_JOB_CREATE'),
    ('ROLE_ADMIN','DEPT_JOB_DELETE'),
    ('ROLE_ADMIN','DEPT_JOB_DELETE_ALL'),
    ('ROLE_ADMIN','DEPT_JOB_READ'),
    ('ROLE_ADMIN','DEPT_JOB_UPDATE'),
    ('ROLE_ADMIN','DEPT_JOB_UPDATE_ALL'),
    ('ROLE_ADMIN','DEPT_READ'),
    ('ROLE_ADMIN','DEPT_UPDATE'),
    ('ROLE_ADMIN','EVENT_CREATE'),
    ('ROLE_ADMIN','EVENT_DELETE'),
    ('ROLE_ADMIN','EVENT_DELETE_ALL'),
    ('ROLE_ADMIN','EVENT_READ'),
    ('ROLE_ADMIN','EVENT_UPDATE'),
    ('ROLE_ADMIN','EVENT_UPDATE_ALL'),
    ('ROLE_ADMIN','EXT_HR_CREATE'),
    ('ROLE_ADMIN','EXT_HR_DELETE'),
    ('ROLE_ADMIN','EXT_HR_DELETE_ALL'),
    ('ROLE_ADMIN','EXT_HR_READ'),
    ('ROLE_ADMIN','EXT_HR_UPDATE'),
    ('ROLE_ADMIN','EXT_HR_UPDATE_ALL'),
    ('ROLE_ADMIN','FILE_AUDIT'),
    ('ROLE_ADMIN','FILE_DELETE'),
    ('ROLE_ADMIN','FILE_DELETE_ALL'),
    ('ROLE_ADMIN','FILE_DOWNLOAD'),
    ('ROLE_ADMIN','FILE_DOWNLOAD_ALL'),
    ('ROLE_ADMIN','FILE_READ'),
    ('ROLE_ADMIN','FILE_READ_ALL'),
    ('ROLE_ADMIN','FILE_UPLOAD'),
    ('ROLE_ADMIN','FILE_UPLOAD_ALL'),
    ('ROLE_ADMIN','HELP_CREATE'),
    ('ROLE_ADMIN','HELP_DELETE'),
    ('ROLE_ADMIN','HELP_DELETE_ALL'),
    ('ROLE_ADMIN','HELP_READ'),
    ('ROLE_ADMIN','HELP_UPDATE'),
    ('ROLE_ADMIN','HELP_UPDATE_ALL'),
    ('ROLE_ADMIN','INFORMAL_APPROVE'),
    ('ROLE_ADMIN','INFORMAL_CREATE'),
    ('ROLE_ADMIN','INFORMAL_CREATE_ALL'),
    ('ROLE_ADMIN','INFORMAL_DELETE'),
    ('ROLE_ADMIN','INFORMAL_DELETE_ALL'),
    ('ROLE_ADMIN','INFORMAL_READ'),
    ('ROLE_ADMIN','INFORMAL_READ_ALL'),
    ('ROLE_ADMIN','INFORMAL_UPDATE'),
    ('ROLE_ADMIN','INFORMAL_UPDATE_ALL'),
    ('ROLE_ADMIN','INST_CODE_CREATE'),
    ('ROLE_ADMIN','INST_CODE_DELETE'),
    ('ROLE_ADMIN','INST_CODE_IMPORT'),
    ('ROLE_ADMIN','INST_CODE_READ'),
    ('ROLE_ADMIN','INST_CODE_UPDATE'),
    ('ROLE_ADMIN','LOGIN_LOG_EXPORT'),
    ('ROLE_ADMIN','LOGIN_LOG_READ'),
    ('ROLE_ADMIN','LOGIN_POL_CREATE'),
    ('ROLE_ADMIN','LOGIN_POL_DELETE'),
    ('ROLE_ADMIN','LOGIN_POL_READ'),
    ('ROLE_ADMIN','LOGIN_POL_UPDATE'),
    ('ROLE_ADMIN','MAIL_DELETE'),
    ('ROLE_ADMIN','MAIL_DELETE_ALL'),
    ('ROLE_ADMIN','MAIL_READ'),
    ('ROLE_ADMIN','MAIL_READ_ALL'),
    ('ROLE_ADMIN','MAIL_SEND'),
    ('ROLE_ADMIN','MEMO_RPT_CREATE'),
    ('ROLE_ADMIN','MEMO_RPT_DELETE'),
    ('ROLE_ADMIN','MEMO_RPT_DELETE_ALL'),
    ('ROLE_ADMIN','MEMO_RPT_INSTRUCT'),
    ('ROLE_ADMIN','MEMO_RPT_READ'),
    ('ROLE_ADMIN','MEMO_RPT_READ_ALL'),
    ('ROLE_ADMIN','MEMO_RPT_UPDATE'),
    ('ROLE_ADMIN','MEMO_RPT_UPDATE_ALL'),
    ('ROLE_ADMIN','MENU_CREATE'),
    ('ROLE_ADMIN','MENU_DELETE'),
    ('ROLE_ADMIN','MENU_READ'),
    ('ROLE_ADMIN','MENU_UPDATE'),
    ('ROLE_ADMIN','NETWORK_CREATE'),
    ('ROLE_ADMIN','NETWORK_DELETE'),
    ('ROLE_ADMIN','NETWORK_READ'),
    ('ROLE_ADMIN','NETWORK_UPDATE'),
    ('ROLE_ADMIN','NOTE_DELETE'),
    ('ROLE_ADMIN','NOTE_READ'),
    ('ROLE_ADMIN','NOTE_SEND'),
    ('ROLE_ADMIN','NOTI_ACK'),
    ('ROLE_ADMIN','NOTI_CREATE'),
    ('ROLE_ADMIN','NOTI_DELETE'),
    ('ROLE_ADMIN','NOTI_DISPATCH'),
    ('ROLE_ADMIN','NOTI_READ'),
    ('ROLE_ADMIN','OPS_READ'),
    ('ROLE_ADMIN','POLICY_READ'),
    ('ROLE_ADMIN','POLICY_UPDATE'),
    ('ROLE_ADMIN','POLL_CREATE'),
    ('ROLE_ADMIN','POLL_DELETE'),
    ('ROLE_ADMIN','POLL_DELETE_ALL'),
    ('ROLE_ADMIN','POLL_READ'),
    ('ROLE_ADMIN','POLL_READ_ALL'),
    ('ROLE_ADMIN','POLL_UPDATE'),
    ('ROLE_ADMIN','POLL_UPDATE_ALL'),
    ('ROLE_ADMIN','POLL_VOTE'),
    ('ROLE_ADMIN','POPUP_CREATE'),
    ('ROLE_ADMIN','POPUP_DELETE'),
    ('ROLE_ADMIN','POPUP_READ'),
    ('ROLE_ADMIN','POPUP_UPDATE'),
    ('ROLE_ADMIN','PRIVACY_EXPORT'),
    ('ROLE_ADMIN','PRIVACY_READ'),
    ('ROLE_ADMIN','PROGRAM_CREATE'),
    ('ROLE_ADMIN','PROGRAM_DELETE'),
    ('ROLE_ADMIN','PROGRAM_READ'),
    ('ROLE_ADMIN','PROGRAM_UPDATE'),
    ('ROLE_ADMIN','REWARD_CREATE'),
    ('ROLE_ADMIN','REWARD_DELETE'),
    ('ROLE_ADMIN','REWARD_DELETE_ALL'),
    ('ROLE_ADMIN','REWARD_READ'),
    ('ROLE_ADMIN','REWARD_UPDATE'),
    ('ROLE_ADMIN','REWARD_UPDATE_ALL'),
    ('ROLE_ADMIN','SATISFY_CREATE'),
    ('ROLE_ADMIN','SATISFY_DELETE'),
    ('ROLE_ADMIN','SATISFY_DELETE_ALL'),
    ('ROLE_ADMIN','SATISFY_MODERATE'),
    ('ROLE_ADMIN','SATISFY_READ'),
    ('ROLE_ADMIN','SATISFY_UPDATE'),
    ('ROLE_ADMIN','SATISFY_UPDATE_ALL'),
    ('ROLE_ADMIN','SCHEDULE_CREATE'),
    ('ROLE_ADMIN','SCHEDULE_DELETE'),
    ('ROLE_ADMIN','SCHEDULE_DELETE_ALL'),
    ('ROLE_ADMIN','SCHEDULE_READ'),
    ('ROLE_ADMIN','SCHEDULE_READ_ALL'),
    ('ROLE_ADMIN','SCHEDULE_UPDATE'),
    ('ROLE_ADMIN','SCHEDULE_UPDATE_ALL'),
    ('ROLE_ADMIN','SCRAP_CREATE'),
    ('ROLE_ADMIN','SCRAP_DELETE'),
    ('ROLE_ADMIN','SCRAP_DELETE_ALL'),
    ('ROLE_ADMIN','SCRAP_READ'),
    ('ROLE_ADMIN','SCRAP_READ_ALL'),
    ('ROLE_ADMIN','SCRAP_UPDATE'),
    ('ROLE_ADMIN','SCRAP_UPDATE_ALL'),
    ('ROLE_ADMIN','SERVICE_CREATE'),
    ('ROLE_ADMIN','SERVICE_DELETE'),
    ('ROLE_ADMIN','SERVICE_READ'),
    ('ROLE_ADMIN','SERVICE_UPDATE'),
    ('ROLE_ADMIN','SMS_READ'),
    ('ROLE_ADMIN','SMS_SEND'),
    ('ROLE_ADMIN','STATS_READ'),
    ('ROLE_ADMIN','SURVEY_CREATE_ALL'),
    ('ROLE_ADMIN','SURVEY_DELETE_ALL'),
    ('ROLE_ADMIN','SURVEY_READ'),
    ('ROLE_ADMIN','SURVEY_READ_ALL'),
    ('ROLE_ADMIN','SURVEY_RSP_DELETE'),
    ('ROLE_ADMIN','SURVEY_RSP_READ'),
    ('ROLE_ADMIN','SURVEY_SUBMIT'),
    ('ROLE_ADMIN','SURVEY_UPDATE_ALL'),
    ('ROLE_ADMIN','SYS_LOG_EXPORT'),
    ('ROLE_ADMIN','SYS_LOG_READ'),
    ('ROLE_ADMIN','TEMPLATE_CREATE'),
    ('ROLE_ADMIN','TEMPLATE_DELETE'),
    ('ROLE_ADMIN','TEMPLATE_READ'),
    ('ROLE_ADMIN','TEMPLATE_UPDATE'),
    ('ROLE_ADMIN','USER_CREATE'),
    ('ROLE_ADMIN','USER_DELETE'),
    ('ROLE_ADMIN','USER_DEPT'),
    ('ROLE_ADMIN','USER_LOG_EXPORT'),
    ('ROLE_ADMIN','USER_LOG_READ'),
    ('ROLE_ADMIN','USER_PASSWORD'),
    ('ROLE_ADMIN','USER_READ'),
    ('ROLE_ADMIN','USER_STATUS'),
    ('ROLE_ADMIN','USER_UPDATE'),
    ('ROLE_ADMIN','WEB_LOG_EXPORT'),
    ('ROLE_ADMIN','WEB_LOG_READ'),
    ('ROLE_ADMIN','WORK_RPT_CREATE'),
    ('ROLE_ADMIN','WORK_RPT_DELETE'),
    ('ROLE_ADMIN','WORK_RPT_DELETE_ALL'),
    ('ROLE_ADMIN','WORK_RPT_READ'),
    ('ROLE_ADMIN','WORK_RPT_READ_ALL'),
    ('ROLE_ADMIN','WORK_RPT_UPDATE'),
    ('ROLE_ADMIN','WORK_RPT_UPDATE_ALL'),
    ('ROLE_SYSTEM','ABSENCE_READ'),
    ('ROLE_SYSTEM','ABSENCE_UPDATE'),
    ('ROLE_SYSTEM','ADBK_CREATE'),
    ('ROLE_SYSTEM','ADBK_DELETE'),
    ('ROLE_SYSTEM','ADBK_DELETE_ALL'),
    ('ROLE_SYSTEM','ADBK_READ'),
    ('ROLE_SYSTEM','ADBK_READ_ALL'),
    ('ROLE_SYSTEM','ADBK_UPDATE'),
    ('ROLE_SYSTEM','ADBK_UPDATE_ALL'),
    ('ROLE_SYSTEM','ADMCODE_CREATE'),
    ('ROLE_SYSTEM','ADMCODE_DELETE'),
    ('ROLE_SYSTEM','ADMCODE_READ'),
    ('ROLE_SYSTEM','ADMCODE_UPDATE'),
    ('ROLE_SYSTEM','APPROVAL_APPROVE'),
    ('ROLE_SYSTEM','APPROVAL_CANCEL'),
    ('ROLE_SYSTEM','APPROVAL_CREATE'),
    ('ROLE_SYSTEM','APPROVAL_READ'),
    ('ROLE_SYSTEM','AUTHRT_ASSIGN'),
    ('ROLE_SYSTEM','AUTHRT_AUDIT'),
    ('ROLE_SYSTEM','AUTHRT_CREATE'),
    ('ROLE_SYSTEM','AUTHRT_DELETE'),
    ('ROLE_SYSTEM','AUTHRT_GRANT'),
    ('ROLE_SYSTEM','AUTHRT_READ'),
    ('ROLE_SYSTEM','AUTHRT_UPDATE'),
    ('ROLE_SYSTEM','BANNER_CREATE'),
    ('ROLE_SYSTEM','BANNER_DELETE'),
    ('ROLE_SYSTEM','BANNER_READ'),
    ('ROLE_SYSTEM','BANNER_UPDATE'),
    ('ROLE_SYSTEM','BBS_MST_CREATE'),
    ('ROLE_SYSTEM','BBS_MST_DELETE'),
    ('ROLE_SYSTEM','BBS_MST_READ'),
    ('ROLE_SYSTEM','BBS_MST_READ_ALL'),
    ('ROLE_SYSTEM','BBS_MST_UPDATE'),
    ('ROLE_SYSTEM','BOARD_CREATE'),
    ('ROLE_SYSTEM','BOARD_DELETE'),
    ('ROLE_SYSTEM','BOARD_DELETE_ALL'),
    ('ROLE_SYSTEM','BOARD_LIKE'),
    ('ROLE_SYSTEM','BOARD_READ'),
    ('ROLE_SYSTEM','BOARD_READ_ALL'),
    ('ROLE_SYSTEM','BOARD_UPDATE'),
    ('ROLE_SYSTEM','BOARD_UPDATE_ALL'),
    ('ROLE_SYSTEM','CLASS_GRP_CREATE'),
    ('ROLE_SYSTEM','CLASS_GRP_DELETE'),
    ('ROLE_SYSTEM','CLASS_GRP_READ'),
    ('ROLE_SYSTEM','CLASS_GRP_UPDATE'),
    ('ROLE_SYSTEM','CODE_CREATE'),
    ('ROLE_SYSTEM','CODE_DELETE'),
    ('ROLE_SYSTEM','CODE_READ'),
    ('ROLE_SYSTEM','CODE_UPDATE'),
    ('ROLE_SYSTEM','COMMENT_CREATE'),
    ('ROLE_SYSTEM','COMMENT_DELETE'),
    ('ROLE_SYSTEM','COMMENT_DELETE_ALL'),
    ('ROLE_SYSTEM','COMMENT_READ'),
    ('ROLE_SYSTEM','COMMENT_READ_ALL'),
    ('ROLE_SYSTEM','COMMENT_UPDATE'),
    ('ROLE_SYSTEM','COMMENT_UPDATE_ALL'),
    ('ROLE_SYSTEM','COMMUNITY_APPROVE'),
    ('ROLE_SYSTEM','COMMUNITY_CREATE_ALL'),
    ('ROLE_SYSTEM','COMMUNITY_DELETE_ALL'),
    ('ROLE_SYSTEM','COMMUNITY_JOIN'),
    ('ROLE_SYSTEM','COMMUNITY_READ'),
    ('ROLE_SYSTEM','COMMUNITY_READ_ALL'),
    ('ROLE_SYSTEM','COMMUNITY_REJECT'),
    ('ROLE_SYSTEM','COMMUNITY_UPDATE_ALL'),
    ('ROLE_SYSTEM','DASHBOARD_READ'),
    ('ROLE_SYSTEM','DEPT_BOX_CREATE'),
    ('ROLE_SYSTEM','DEPT_BOX_DELETE'),
    ('ROLE_SYSTEM','DEPT_BOX_READ'),
    ('ROLE_SYSTEM','DEPT_BOX_UPDATE'),
    ('ROLE_SYSTEM','DEPT_CREATE'),
    ('ROLE_SYSTEM','DEPT_DELETE'),
    ('ROLE_SYSTEM','DEPT_JOB_CREATE'),
    ('ROLE_SYSTEM','DEPT_JOB_DELETE'),
    ('ROLE_SYSTEM','DEPT_JOB_DELETE_ALL'),
    ('ROLE_SYSTEM','DEPT_JOB_READ'),
    ('ROLE_SYSTEM','DEPT_JOB_UPDATE'),
    ('ROLE_SYSTEM','DEPT_JOB_UPDATE_ALL'),
    ('ROLE_SYSTEM','DEPT_READ'),
    ('ROLE_SYSTEM','DEPT_UPDATE'),
    ('ROLE_SYSTEM','EVENT_CREATE'),
    ('ROLE_SYSTEM','EVENT_DELETE'),
    ('ROLE_SYSTEM','EVENT_DELETE_ALL'),
    ('ROLE_SYSTEM','EVENT_READ'),
    ('ROLE_SYSTEM','EVENT_UPDATE'),
    ('ROLE_SYSTEM','EVENT_UPDATE_ALL'),
    ('ROLE_SYSTEM','EXT_HR_CREATE'),
    ('ROLE_SYSTEM','EXT_HR_DELETE'),
    ('ROLE_SYSTEM','EXT_HR_DELETE_ALL'),
    ('ROLE_SYSTEM','EXT_HR_READ'),
    ('ROLE_SYSTEM','EXT_HR_UPDATE'),
    ('ROLE_SYSTEM','EXT_HR_UPDATE_ALL'),
    ('ROLE_SYSTEM','FILE_AUDIT'),
    ('ROLE_SYSTEM','FILE_DELETE'),
    ('ROLE_SYSTEM','FILE_DELETE_ALL'),
    ('ROLE_SYSTEM','FILE_DOWNLOAD'),
    ('ROLE_SYSTEM','FILE_DOWNLOAD_ALL'),
    ('ROLE_SYSTEM','FILE_READ'),
    ('ROLE_SYSTEM','FILE_READ_ALL'),
    ('ROLE_SYSTEM','FILE_UPLOAD'),
    ('ROLE_SYSTEM','FILE_UPLOAD_ALL'),
    ('ROLE_SYSTEM','HELP_CREATE'),
    ('ROLE_SYSTEM','HELP_DELETE'),
    ('ROLE_SYSTEM','HELP_DELETE_ALL'),
    ('ROLE_SYSTEM','HELP_READ'),
    ('ROLE_SYSTEM','HELP_UPDATE'),
    ('ROLE_SYSTEM','HELP_UPDATE_ALL'),
    ('ROLE_SYSTEM','INFORMAL_APPROVE'),
    ('ROLE_SYSTEM','INFORMAL_CREATE'),
    ('ROLE_SYSTEM','INFORMAL_CREATE_ALL'),
    ('ROLE_SYSTEM','INFORMAL_DELETE'),
    ('ROLE_SYSTEM','INFORMAL_DELETE_ALL'),
    ('ROLE_SYSTEM','INFORMAL_READ'),
    ('ROLE_SYSTEM','INFORMAL_READ_ALL'),
    ('ROLE_SYSTEM','INFORMAL_UPDATE'),
    ('ROLE_SYSTEM','INFORMAL_UPDATE_ALL'),
    ('ROLE_SYSTEM','INST_CODE_CREATE'),
    ('ROLE_SYSTEM','INST_CODE_DELETE'),
    ('ROLE_SYSTEM','INST_CODE_IMPORT'),
    ('ROLE_SYSTEM','INST_CODE_READ'),
    ('ROLE_SYSTEM','INST_CODE_UPDATE'),
    ('ROLE_SYSTEM','LOGIN_LOG_EXPORT'),
    ('ROLE_SYSTEM','LOGIN_LOG_READ'),
    ('ROLE_SYSTEM','LOGIN_POL_CREATE'),
    ('ROLE_SYSTEM','LOGIN_POL_DELETE'),
    ('ROLE_SYSTEM','LOGIN_POL_READ'),
    ('ROLE_SYSTEM','LOGIN_POL_UPDATE'),
    ('ROLE_SYSTEM','MAIL_DELETE'),
    ('ROLE_SYSTEM','MAIL_DELETE_ALL'),
    ('ROLE_SYSTEM','MAIL_READ'),
    ('ROLE_SYSTEM','MAIL_READ_ALL'),
    ('ROLE_SYSTEM','MAIL_SEND'),
    ('ROLE_SYSTEM','MEMO_RPT_CREATE'),
    ('ROLE_SYSTEM','MEMO_RPT_DELETE'),
    ('ROLE_SYSTEM','MEMO_RPT_DELETE_ALL'),
    ('ROLE_SYSTEM','MEMO_RPT_INSTRUCT'),
    ('ROLE_SYSTEM','MEMO_RPT_READ'),
    ('ROLE_SYSTEM','MEMO_RPT_READ_ALL'),
    ('ROLE_SYSTEM','MEMO_RPT_UPDATE'),
    ('ROLE_SYSTEM','MEMO_RPT_UPDATE_ALL'),
    ('ROLE_SYSTEM','MENU_CREATE'),
    ('ROLE_SYSTEM','MENU_DELETE'),
    ('ROLE_SYSTEM','MENU_READ'),
    ('ROLE_SYSTEM','MENU_UPDATE'),
    ('ROLE_SYSTEM','NETWORK_CREATE'),
    ('ROLE_SYSTEM','NETWORK_DELETE'),
    ('ROLE_SYSTEM','NETWORK_READ'),
    ('ROLE_SYSTEM','NETWORK_UPDATE'),
    ('ROLE_SYSTEM','NOTE_DELETE'),
    ('ROLE_SYSTEM','NOTE_READ'),
    ('ROLE_SYSTEM','NOTE_SEND'),
    ('ROLE_SYSTEM','NOTI_ACK'),
    ('ROLE_SYSTEM','NOTI_CREATE'),
    ('ROLE_SYSTEM','NOTI_DELETE'),
    ('ROLE_SYSTEM','NOTI_DISPATCH'),
    ('ROLE_SYSTEM','NOTI_READ'),
    ('ROLE_SYSTEM','OPS_READ'),
    ('ROLE_SYSTEM','POLICY_READ'),
    ('ROLE_SYSTEM','POLICY_UPDATE'),
    ('ROLE_SYSTEM','POLL_CREATE'),
    ('ROLE_SYSTEM','POLL_DELETE'),
    ('ROLE_SYSTEM','POLL_DELETE_ALL'),
    ('ROLE_SYSTEM','POLL_READ'),
    ('ROLE_SYSTEM','POLL_READ_ALL'),
    ('ROLE_SYSTEM','POLL_UPDATE'),
    ('ROLE_SYSTEM','POLL_UPDATE_ALL'),
    ('ROLE_SYSTEM','POLL_VOTE'),
    ('ROLE_SYSTEM','POPUP_CREATE'),
    ('ROLE_SYSTEM','POPUP_DELETE'),
    ('ROLE_SYSTEM','POPUP_READ'),
    ('ROLE_SYSTEM','POPUP_UPDATE'),
    ('ROLE_SYSTEM','PROGRAM_CREATE'),
    ('ROLE_SYSTEM','PROGRAM_DELETE'),
    ('ROLE_SYSTEM','PROGRAM_READ'),
    ('ROLE_SYSTEM','PROGRAM_UPDATE'),
    ('ROLE_SYSTEM','REWARD_CREATE'),
    ('ROLE_SYSTEM','REWARD_DELETE'),
    ('ROLE_SYSTEM','REWARD_DELETE_ALL'),
    ('ROLE_SYSTEM','REWARD_READ'),
    ('ROLE_SYSTEM','REWARD_UPDATE'),
    ('ROLE_SYSTEM','REWARD_UPDATE_ALL'),
    ('ROLE_SYSTEM','SATISFY_CREATE'),
    ('ROLE_SYSTEM','SATISFY_DELETE'),
    ('ROLE_SYSTEM','SATISFY_DELETE_ALL'),
    ('ROLE_SYSTEM','SATISFY_MODERATE'),
    ('ROLE_SYSTEM','SATISFY_READ'),
    ('ROLE_SYSTEM','SATISFY_UPDATE'),
    ('ROLE_SYSTEM','SATISFY_UPDATE_ALL'),
    ('ROLE_SYSTEM','SCHEDULE_CREATE'),
    ('ROLE_SYSTEM','SCHEDULE_DELETE'),
    ('ROLE_SYSTEM','SCHEDULE_DELETE_ALL'),
    ('ROLE_SYSTEM','SCHEDULE_READ'),
    ('ROLE_SYSTEM','SCHEDULE_READ_ALL'),
    ('ROLE_SYSTEM','SCHEDULE_UPDATE'),
    ('ROLE_SYSTEM','SCHEDULE_UPDATE_ALL'),
    ('ROLE_SYSTEM','SCRAP_CREATE'),
    ('ROLE_SYSTEM','SCRAP_DELETE'),
    ('ROLE_SYSTEM','SCRAP_DELETE_ALL'),
    ('ROLE_SYSTEM','SCRAP_READ'),
    ('ROLE_SYSTEM','SCRAP_READ_ALL'),
    ('ROLE_SYSTEM','SCRAP_UPDATE'),
    ('ROLE_SYSTEM','SCRAP_UPDATE_ALL'),
    ('ROLE_SYSTEM','SERVICE_CREATE'),
    ('ROLE_SYSTEM','SERVICE_DELETE'),
    ('ROLE_SYSTEM','SERVICE_READ'),
    ('ROLE_SYSTEM','SERVICE_UPDATE'),
    ('ROLE_SYSTEM','SMS_READ'),
    ('ROLE_SYSTEM','SMS_SEND'),
    ('ROLE_SYSTEM','STATS_READ'),
    ('ROLE_SYSTEM','SURVEY_CREATE_ALL'),
    ('ROLE_SYSTEM','SURVEY_DELETE_ALL'),
    ('ROLE_SYSTEM','SURVEY_READ'),
    ('ROLE_SYSTEM','SURVEY_READ_ALL'),
    ('ROLE_SYSTEM','SURVEY_RSP_DELETE'),
    ('ROLE_SYSTEM','SURVEY_RSP_READ'),
    ('ROLE_SYSTEM','SURVEY_SUBMIT'),
    ('ROLE_SYSTEM','SURVEY_UPDATE_ALL'),
    ('ROLE_SYSTEM','SYS_LOG_EXPORT'),
    ('ROLE_SYSTEM','SYS_LOG_READ'),
    ('ROLE_SYSTEM','TEMPLATE_CREATE'),
    ('ROLE_SYSTEM','TEMPLATE_DELETE'),
    ('ROLE_SYSTEM','TEMPLATE_READ'),
    ('ROLE_SYSTEM','TEMPLATE_UPDATE'),
    ('ROLE_SYSTEM','USER_CREATE'),
    ('ROLE_SYSTEM','USER_DELETE'),
    ('ROLE_SYSTEM','USER_DEPT'),
    ('ROLE_SYSTEM','USER_LOG_EXPORT'),
    ('ROLE_SYSTEM','USER_LOG_READ'),
    ('ROLE_SYSTEM','USER_PASSWORD'),
    ('ROLE_SYSTEM','USER_READ'),
    ('ROLE_SYSTEM','USER_STATUS'),
    ('ROLE_SYSTEM','USER_UPDATE'),
    ('ROLE_SYSTEM','WEB_LOG_EXPORT'),
    ('ROLE_SYSTEM','WEB_LOG_READ'),
    ('ROLE_SYSTEM','WORK_RPT_CREATE'),
    ('ROLE_SYSTEM','WORK_RPT_DELETE'),
    ('ROLE_SYSTEM','WORK_RPT_DELETE_ALL'),
    ('ROLE_SYSTEM','WORK_RPT_READ'),
    ('ROLE_SYSTEM','WORK_RPT_READ_ALL'),
    ('ROLE_SYSTEM','WORK_RPT_UPDATE'),
    ('ROLE_SYSTEM','WORK_RPT_UPDATE_ALL'),
    ('ROLE_USER','ADBK_CREATE'),
    ('ROLE_USER','ADBK_DELETE'),
    ('ROLE_USER','ADBK_READ'),
    ('ROLE_USER','ADBK_UPDATE'),
    ('ROLE_USER','APPROVAL_APPROVE'),
    ('ROLE_USER','APPROVAL_CANCEL'),
    ('ROLE_USER','APPROVAL_CREATE'),
    ('ROLE_USER','APPROVAL_READ'),
    ('ROLE_USER','BANNER_READ'),
    ('ROLE_USER','BOARD_CREATE'),
    ('ROLE_USER','BOARD_DELETE'),
    ('ROLE_USER','BOARD_LIKE'),
    ('ROLE_USER','BOARD_READ'),
    ('ROLE_USER','BOARD_UPDATE'),
    ('ROLE_USER','COMMENT_CREATE'),
    ('ROLE_USER','COMMENT_DELETE'),
    ('ROLE_USER','COMMENT_READ'),
    ('ROLE_USER','COMMENT_UPDATE'),
    ('ROLE_USER','COMMUNITY_JOIN'),
    ('ROLE_USER','COMMUNITY_READ'),
    ('ROLE_USER','DASHBOARD_READ'),
    ('ROLE_USER','DEPT_BOX_READ'),
    ('ROLE_USER','DEPT_JOB_CREATE'),
    ('ROLE_USER','DEPT_JOB_DELETE'),
    ('ROLE_USER','DEPT_JOB_READ'),
    ('ROLE_USER','DEPT_JOB_UPDATE'),
    ('ROLE_USER','FILE_DELETE'),
    ('ROLE_USER','FILE_DOWNLOAD'),
    ('ROLE_USER','FILE_READ'),
    ('ROLE_USER','FILE_UPLOAD'),
    ('ROLE_USER','INFORMAL_APPROVE'),
    ('ROLE_USER','INFORMAL_CREATE'),
    ('ROLE_USER','INFORMAL_DELETE'),
    ('ROLE_USER','INFORMAL_READ'),
    ('ROLE_USER','INFORMAL_UPDATE'),
    ('ROLE_USER','MAIL_DELETE'),
    ('ROLE_USER','MAIL_READ'),
    ('ROLE_USER','MAIL_SEND'),
    ('ROLE_USER','MEMO_RPT_CREATE'),
    ('ROLE_USER','MEMO_RPT_DELETE'),
    ('ROLE_USER','MEMO_RPT_INSTRUCT'),
    ('ROLE_USER','MEMO_RPT_READ'),
    ('ROLE_USER','MEMO_RPT_UPDATE'),
    ('ROLE_USER','NOTE_DELETE'),
    ('ROLE_USER','NOTE_READ'),
    ('ROLE_USER','NOTE_SEND'),
    ('ROLE_USER','NOTI_ACK'),
    ('ROLE_USER','NOTI_CREATE'),
    ('ROLE_USER','NOTI_DELETE'),
    ('ROLE_USER','NOTI_READ'),
    ('ROLE_USER','POLL_CREATE'),
    ('ROLE_USER','POLL_DELETE'),
    ('ROLE_USER','POLL_READ'),
    ('ROLE_USER','POLL_UPDATE'),
    ('ROLE_USER','POLL_VOTE'),
    ('ROLE_USER','POPUP_READ'),
    ('ROLE_USER','SATISFY_CREATE'),
    ('ROLE_USER','SATISFY_DELETE'),
    ('ROLE_USER','SATISFY_READ'),
    ('ROLE_USER','SATISFY_UPDATE'),
    ('ROLE_USER','SCHEDULE_CREATE'),
    ('ROLE_USER','SCHEDULE_DELETE'),
    ('ROLE_USER','SCHEDULE_READ'),
    ('ROLE_USER','SCHEDULE_UPDATE'),
    ('ROLE_USER','SCRAP_CREATE'),
    ('ROLE_USER','SCRAP_DELETE'),
    ('ROLE_USER','SCRAP_READ'),
    ('ROLE_USER','SCRAP_UPDATE'),
    ('ROLE_USER','STATS_READ'),
    ('ROLE_USER','SURVEY_READ'),
    ('ROLE_USER','SURVEY_SUBMIT'),
    ('ROLE_USER','WORK_RPT_CREATE'),
    ('ROLE_USER','WORK_RPT_DELETE'),
    ('ROLE_USER','WORK_RPT_READ'),
    ('ROLE_USER','WORK_RPT_UPDATE')
) AS seed(group_code,permission_code);

INSERT INTO tb_authrt_chg_hstry(dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,
    authrt_type_cd,authrt_grnt_cd,chg_artcl_nm,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP_GRANT','MIGRATE',authrt_cd,
    'OPERATION',authrt_grnt_cd,'initial_operation_grant',authrt_grnt_cd,
    '승인한 기능 카탈로그의 초기 그룹 권한을 명시적으로 배정','SYSTEM',CURRENT_TIMESTAMP
FROM tb_authrt_grnt_map WHERE authrt_type_cd='OPERATION';

-- Reviewed from V2_11, retirement V2_23/V2_40/V2_41, survey alias V2_84,
-- and OCI read-only measurement on 2026-09-10: 17 programs, 34 ADMIN/SYSTEM mappings.
DO $$
BEGIN
    IF (SELECT count(*) FROM tb_role_prgrm_map) <> 34
       OR EXISTS (
           SELECT role_id,prgrm_file_nm FROM tb_role_prgrm_map
           EXCEPT
           SELECT role_id,prgrm_file_nm FROM (VALUES ('ROLE_ADMIN'),('ROLE_SYSTEM')) roles(role_id)
           CROSS JOIN (VALUES
        ('ACTUATOR_ALL','/actuator/**'),
        ('ADMIN_ALL','/api/v1/admin/**'),
        ('ADMIN_DEPT_ALL','/api/v1/admin/system/departments/**'),
        ('ADMIN_DEPT_AUTH_ALL','/api/v1/admin/system/dept-authorities/**'),
        ('ADMIN_HELP_ALIAS','/api/v1/help/**'),
        ('ADMIN_HELP_ALL','/api/v1/admin/help/**'),
        ('ADMIN_SURVEY_ALL','/api/v1/admin/system/surveys/**'),
        ('ADMIN_USER_BULK_DEL','/api/v1/admin/system/users'),
        ('ADMIN_USER_CREATE','/api/v1/admin/system/users'),
        ('ADMIN_USER_DELETE','/api/v1/admin/system/users/{userId}'),
        ('ADMIN_USER_DEPT','/api/v1/admin/system/users/dept'),
        ('ADMIN_USER_DETAIL','/api/v1/admin/system/users/{userId}'),
        ('ADMIN_USER_LIST','/api/v1/admin/system/users'),
        ('ADMIN_USER_PWD','/api/v1/admin/system/users/{userId}/password'),
        ('ADMIN_USER_ROLE','/api/v1/admin/system/users/role'),
        ('ADMIN_USER_STATUS','/api/v1/admin/system/users/status'),
        ('ADMIN_USER_UPDATE','/api/v1/admin/system/users/{userId}')
           ) programs(prgrm_file_nm,url)
       ) THEN
        RAISE EXCEPTION 'Unreviewed legacy role program mapping; compare effective permissions before seeding';
    END IF;
    IF EXISTS (
        SELECT 1 FROM (VALUES
        ('ACTUATOR_ALL','/actuator/**'),
        ('ADMIN_ALL','/api/v1/admin/**'),
        ('ADMIN_DEPT_ALL','/api/v1/admin/system/departments/**'),
        ('ADMIN_DEPT_AUTH_ALL','/api/v1/admin/system/dept-authorities/**'),
        ('ADMIN_HELP_ALIAS','/api/v1/help/**'),
        ('ADMIN_HELP_ALL','/api/v1/admin/help/**'),
        ('ADMIN_SURVEY_ALL','/api/v1/admin/system/surveys/**'),
        ('ADMIN_USER_BULK_DEL','/api/v1/admin/system/users'),
        ('ADMIN_USER_CREATE','/api/v1/admin/system/users'),
        ('ADMIN_USER_DELETE','/api/v1/admin/system/users/{userId}'),
        ('ADMIN_USER_DEPT','/api/v1/admin/system/users/dept'),
        ('ADMIN_USER_DETAIL','/api/v1/admin/system/users/{userId}'),
        ('ADMIN_USER_LIST','/api/v1/admin/system/users'),
        ('ADMIN_USER_PWD','/api/v1/admin/system/users/{userId}/password'),
        ('ADMIN_USER_ROLE','/api/v1/admin/system/users/role'),
        ('ADMIN_USER_STATUS','/api/v1/admin/system/users/status'),
        ('ADMIN_USER_UPDATE','/api/v1/admin/system/users/{userId}')
        ) expected(prgrm_file_nm,url)
        LEFT JOIN tb_prgrm_lst actual USING(prgrm_file_nm)
        WHERE actual.prgrm_file_nm IS NULL OR actual.url IS DISTINCT FROM expected.url
    ) THEN
        RAISE EXCEPTION 'Unreviewed legacy program URL; compare effective permissions before seeding';
    END IF;
END $$;

-- Include in V2_99 before the OPERATION grant seed, in the same Flyway transaction.
-- Replace c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359 with the reviewed catalog SHA-256 literal.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_role_info legacy WHERE char_length(to_jsonb(legacy)::text)>4000) THEN
        RAISE EXCEPTION 'Legacy authorization policy snapshot exceeds 4000 characters: tb_role_info';
    END IF;
END $$;
INSERT INTO tb_authrt_chg_hstry
    (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
     chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP','MIGRATE','ROLE_ADMIN',
       'legacy_policy:tb_role_info',to_jsonb(legacy)::text,to_jsonb(legacy)::text,
       '구 인가 정책 원본 행의 전환 직전 비교용 스냅샷; 운영 백업을 대체하지 않음','SYSTEM',CURRENT_TIMESTAMP
FROM tb_role_info legacy;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_authrt_role_map legacy WHERE char_length(to_jsonb(legacy)::text)>4000) THEN
        RAISE EXCEPTION 'Legacy authorization policy snapshot exceeds 4000 characters: tb_authrt_role_map';
    END IF;
END $$;
INSERT INTO tb_authrt_chg_hstry
    (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
     chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP','MIGRATE','ROLE_ADMIN',
       'legacy_policy:tb_authrt_role_map',to_jsonb(legacy)::text,to_jsonb(legacy)::text,
       '구 인가 정책 원본 행의 전환 직전 비교용 스냅샷; 운영 백업을 대체하지 않음','SYSTEM',CURRENT_TIMESTAMP
FROM tb_authrt_role_map legacy;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_role_prgrm_map legacy WHERE char_length(to_jsonb(legacy)::text)>4000) THEN
        RAISE EXCEPTION 'Legacy authorization policy snapshot exceeds 4000 characters: tb_role_prgrm_map';
    END IF;
END $$;
INSERT INTO tb_authrt_chg_hstry
    (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
     chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP','MIGRATE','ROLE_ADMIN',
       'legacy_policy:tb_role_prgrm_map',to_jsonb(legacy)::text,to_jsonb(legacy)::text,
       '구 인가 정책 원본 행의 전환 직전 비교용 스냅샷; 운영 백업을 대체하지 않음','SYSTEM',CURRENT_TIMESTAMP
FROM tb_role_prgrm_map legacy;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tb_role_hierarchy legacy WHERE char_length(to_jsonb(legacy)::text)>4000) THEN
        RAISE EXCEPTION 'Legacy authorization policy snapshot exceeds 4000 characters: tb_role_hierarchy';
    END IF;
END $$;
INSERT INTO tb_authrt_chg_hstry
    (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
     chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP','MIGRATE','ROLE_ADMIN',
       'legacy_policy:tb_role_hierarchy',to_jsonb(legacy)::text,to_jsonb(legacy)::text,
       '구 인가 정책 원본 행의 전환 직전 비교용 스냅샷; 운영 백업을 대체하지 않음','SYSTEM',CURRENT_TIMESTAMP
FROM tb_role_hierarchy legacy;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM (
            SELECT DISTINCT program.prgrm_file_nm,program.url FROM tb_prgrm_lst program
            JOIN tb_role_prgrm_map mapping USING(prgrm_file_nm)
        ) legacy WHERE char_length(to_jsonb(legacy)::text)>4000
    ) THEN
        RAISE EXCEPTION 'Legacy authorization program URL snapshot exceeds 4000 characters';
    END IF;
END $$;
INSERT INTO tb_authrt_chg_hstry
    (dmnd_idntfr,plcy_ver_no,chg_trgt_type_cd,chg_type_cd,authrt_cd,chg_artcl_nm,
     chg_bfr_cn,chg_aftr_cn,chg_rsn,frst_rgtr_id,crt_dt)
SELECT 'migration:2.99','c811a0a4d24432c0eb1e28c7b3e61985b2750bcbb5155a20a7d7d7d5cdc44359','GROUP','MIGRATE','ROLE_ADMIN','legacy_policy:program_url',
       to_jsonb(legacy)::text,to_jsonb(legacy)::text,
       '연결 프로그램의 구 URL 인가 입력 보존; 프로그램 업무 메타데이터는 유지','SYSTEM',CURRENT_TIMESTAMP
FROM (
    SELECT DISTINCT program.prgrm_file_nm,program.url FROM tb_prgrm_lst program
    JOIN tb_role_prgrm_map mapping USING(prgrm_file_nm)
) legacy;
