
-- Password Reset Script
-- Target Password: "1"
-- Hashing Algorithm: SHA-256(id + password)

-- 1. Update 'webmaster' (NEMPLYRINFO)
-- Hash: lR9HSaayoa3L47nbYGT0XbRvrYp2Ldo4g54am6/pS2w=
UPDATE NEMPLYRINFO 
SET PASSWORD = 'lR9HSaayoa3L47nbYGT0XbRvrYp2Ldo4g54am6/pS2w=' 
WHERE EMPLYR_ID = 'webmaster';

-- 2. Update 'TEST1' (NEMPLYRINFO)
-- Hash: yfHoVdC88xaHuSkJSJYdLcw3athlaHO9oUzEvD/EwFI=
UPDATE NEMPLYRINFO 
SET PASSWORD = 'yfHoVdC88xaHuSkJSJYdLcw3athlaHO9oUzEvD/EwFI=' 
WHERE EMPLYR_ID = 'TEST1';

-- 3. Update 'USER' (NGNRLMBER)
-- Hash: p9ddPCJCWPhbI8pHFSs3VFoL/M4kkGa0owIFCGd136M=
UPDATE NGNRLMBER 
SET PASSWORD = 'p9ddPCJCWPhbI8pHFSs3VFoL/M4kkGa0owIFCGd136M=' 
WHERE MBER_ID = 'USER';

-- 4. Update 'ENTERPRISE' (NENTRPRSMBER)
-- Hash: c3OjO3zLDnA7H76K6HT9HGgMLhLpazgLihL5jcwt48s=
UPDATE NENTRPRSMBER 
SET ENTRPRS_MBER_PASSWORD = 'c3OjO3zLDnA7H76K6HT9HGgMLhLpazgLihL5jcwt48s=' 
WHERE ENTRPRS_MBER_ID = 'ENTERPRISE';

COMMIT;
