package nuri.migration.postgres;

import com.fasterxml.jackson.databind.ObjectMapper;
import nuri.migration.artifact.ArtifactRedactionGuard;
import nuri.migration.identity.IdentityValueType;
import nuri.migration.identity.TargetIdentityPolicy;
import nuri.migration.model.MappingSpec;
import nuri.migration.model.MappingSpec.ColumnMapping;
import nuri.migration.model.MappingSpec.CompositeForeignKey;
import nuri.migration.model.MappingSpec.IdentityComponentSpec;
import nuri.migration.model.MappingSpec.IdentityStrategy;
import nuri.migration.model.MappingSpec.TableMapping;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("PostgreSQL target schema canonical fingerprint - H2 PostgreSQL mode")
class PostgresTargetSchemaFingerprinterTest {

    private Connection connection;
    private PostgresTargetSchemaFingerprinter fingerprinter;

    @BeforeEach
    void setUp() throws SQLException {
        connection = DriverManager.getConnection(
                "jdbc:h2:mem:target_fingerprint;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "migration_user",
                "target-test-password");
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP ALL OBJECTS");
            statement.execute("CREATE SCHEMA IF NOT EXISTS public");
            statement.execute("""
                    CREATE TABLE public.tb_user_info (
                        tenant_id varchar(20) NOT NULL,
                        user_id varchar(40) NOT NULL,
                        user_nm varchar(100) NOT NULL,
                        login_count bigint DEFAULT 0,
                        CONSTRAINT pk_tb_user_info PRIMARY KEY (tenant_id, user_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE public.tb_ognz_info (
                        ognz_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ognz_nm varchar(100) NOT NULL
                    )
                    """);
        }
        fingerprinter = new PostgresTargetSchemaFingerprinter();
    }

    @AfterEach
    void tearDown() throws SQLException {
        connection.close();
    }

    @Test
    @DisplayName("MappingSpec 요청 순서와 metadata 컬렉션 순서에 관계없이 digest가 같다")
    void digestIsIndependentOfRequestAndMetadataOrder() throws SQLException {
        MappingSpec forward = mapping(List.of(
                table("legacy_user", "public.tb_user_info", List.of("tenant_id", "user_id", "user_nm")),
                table("legacy_org", "public.tb_ognz_info", List.of("ognz_id", "ognz_nm"))));
        MappingSpec reversed = mapping(List.of(
                table("legacy_org", "public.tb_ognz_info", List.of("ognz_nm", "ognz_id")),
                table("legacy_user", "public.tb_user_info", List.of("user_nm", "user_id", "tenant_id"))));

        TargetSchemaFingerprint left = fingerprinter.fingerprint(connection, forward);
        TargetSchemaFingerprint right = fingerprinter.fingerprint(connection, reversed);
        List<TargetSchemaFingerprint.TableMetadata> shuffled = new ArrayList<>(left.tables());
        Collections.reverse(shuffled);
        TargetSchemaFingerprint recanonicalized = TargetSchemaFingerprint.create(
                left.databaseProduct(), left.databaseVersion(), shuffled);

        assertThat(right.digest()).isEqualTo(left.digest());
        assertThat(recanonicalized.digest()).isEqualTo(left.digest());
        assertThat(left.tables()).extracting(TargetSchemaFingerprint.TableMetadata::name)
                .containsExactly("tb_ognz_info", "tb_user_info");
        assertThat(left.tables().stream()
                .filter(table -> table.name().equals("tb_user_info"))
                .findFirst().orElseThrow().primaryKey().columns())
                .extracting(TargetSchemaFingerprint.PrimaryKeyColumn::name)
                .containsExactly("tenant_id", "user_id");
    }

    @Test
    @DisplayName("매핑 컬럼의 타입/길이가 바뀌면 target schema digest가 바뀐다")
    void mappedSchemaChangeChangesDigest() throws SQLException {
        MappingSpec mapping = mapping(List.of(
                table("legacy_user", "public.tb_user_info", List.of("tenant_id", "user_id", "user_nm"))));
        TargetSchemaFingerprint before = fingerprinter.fingerprint(connection, mapping);

        try (Statement statement = connection.createStatement()) {
            statement.execute("ALTER TABLE public.tb_user_info ALTER COLUMN user_nm varchar(200)");
        }
        TargetSchemaFingerprint after = fingerprinter.fingerprint(connection, mapping);

        assertThat(after.digest()).isNotEqualTo(before.digest());
        assertThat(after.tables().getFirst().columns())
                .filteredOn(column -> column.name().equals("user_nm"))
                .singleElement()
                .extracting(TargetSchemaFingerprint.ColumnMetadata::size)
                .isEqualTo(200);
    }

    @Test
    @DisplayName("typed identity/FK target 컬럼과 매핑 테이블의 전체 컬럼을 fingerprint한다")
    void includesTypedIdentityForeignKeyAndAllMappedTableColumns() throws SQLException {
        IdentityStrategy identity = new IdentityStrategy(
                TargetIdentityPolicy.PRESERVE,
                List.of(component("TENANT_ID", IdentityValueType.TEXT),
                        component("USER_ID", IdentityValueType.TEXT)),
                List.of(component("tenant_id", IdentityValueType.TEXT),
                        component("user_id", IdentityValueType.TEXT)));
        CompositeForeignKey foreignKey = new CompositeForeignKey(
                "legacy_counter",
                List.of(component("LOGIN_COUNT", IdentityValueType.SIGNED_INTEGER)),
                List.of(component("login_count", IdentityValueType.SIGNED_INTEGER)));
        TableMapping typed = new TableMapping(
                "legacy_user", "public.tb_user_info", null, null,
                List.of("TENANT_ID", "USER_ID"), null, List.of(), null, identity, List.of(foreignKey));

        TargetSchemaFingerprint fingerprint = fingerprinter.fingerprint(
                connection, mapping(List.of(typed)));

        assertThat(fingerprint.tables().getFirst().columns())
                .extracting(TargetSchemaFingerprint.ColumnMetadata::name)
                .containsExactlyInAnyOrder("tenant_id", "user_id", "user_nm", "login_count");
    }

    @Test
    @DisplayName("MappingSpec의 target table 또는 column이 실제 DB에 없으면 fail-closed한다")
    void missingTableOrColumnFailsClosed() {
        MappingSpec missingTable = mapping(List.of(
                table("legacy_missing", "public.tb_missing", List.of("id"))));
        MappingSpec missingColumn = mapping(List.of(
                table("legacy_user", "public.tb_user_info", List.of("tenant_id", "missing_column"))));

        assertThatThrownBy(() -> fingerprinter.fingerprint(connection, missingTable))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("target table", "tb_missing");
        assertThatThrownBy(() -> fingerprinter.fingerprint(connection, missingColumn))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("target column", "missing_column");
    }

    @Test
    @DisplayName("fingerprint에는 JDBC URL·username·password가 포함되지 않는다")
    void fingerprintContainsNoCredentials() throws Exception {
        TargetSchemaFingerprint fingerprint = fingerprinter.fingerprint(connection, mapping(List.of(
                table("legacy_user", "public.tb_user_info", List.of("tenant_id", "user_id")))));
        String json = new ObjectMapper().writeValueAsString(fingerprint);

        ArtifactRedactionGuard.assertSafe(new ObjectMapper().readTree(json));
        assertThat(json)
                .doesNotContain("jdbc:h2")
                .doesNotContain("migration_user")
                .doesNotContain("target-test-password");
    }

    private static MappingSpec mapping(List<TableMapping> tables) {
        return new MappingSpec(null, null, tables, Map.of());
    }

    private static TableMapping table(String source, String target, List<String> targetColumns) {
        List<ColumnMapping> columns = targetColumns.stream()
                .map(column -> new ColumnMapping(column, column, null, null, null, null, null))
                .toList();
        return new TableMapping(source, target, null, columns, null);
    }

    private static IdentityComponentSpec component(String column, IdentityValueType type) {
        return new IdentityComponentSpec(column, type);
    }
}
