package nuri.business.security.authorization;

/** Generated by scripts/generate-permissions.mjs. */
public final class PermissionCodes {
    private PermissionCodes() {}
    public static final String CATALOG_VERSION = "7905bb657127d40bea2df619093b24316651b1957ac9e26a902c7bd171473276";
    public static final String ABSENCE_READ = "ABSENCE_READ";
    public static final String ABSENCE_UPDATE = "ABSENCE_UPDATE";
    public static final String ADBK_CREATE = "ADBK_CREATE";
    public static final String ADBK_DELETE = "ADBK_DELETE";
    public static final String ADBK_DELETE_ALL = "ADBK_DELETE_ALL";
    public static final String ADBK_READ = "ADBK_READ";
    public static final String ADBK_READ_ALL = "ADBK_READ_ALL";
    public static final String ADBK_UPDATE = "ADBK_UPDATE";
    public static final String ADBK_UPDATE_ALL = "ADBK_UPDATE_ALL";
    public static final String ADMCODE_CREATE = "ADMCODE_CREATE";
    public static final String ADMCODE_DELETE = "ADMCODE_DELETE";
    public static final String ADMCODE_READ = "ADMCODE_READ";
    public static final String ADMCODE_UPDATE = "ADMCODE_UPDATE";
    public static final String APPROVAL_APPROVE = "APPROVAL_APPROVE";
    public static final String APPROVAL_CANCEL = "APPROVAL_CANCEL";
    public static final String APPROVAL_CREATE = "APPROVAL_CREATE";
    public static final String APPROVAL_READ = "APPROVAL_READ";
    public static final String AUTHRT_ASSIGN = "AUTHRT_ASSIGN";
    public static final String AUTHRT_AUDIT = "AUTHRT_AUDIT";
    public static final String AUTHRT_CREATE = "AUTHRT_CREATE";
    public static final String AUTHRT_DELETE = "AUTHRT_DELETE";
    public static final String AUTHRT_GRANT = "AUTHRT_GRANT";
    public static final String AUTHRT_READ = "AUTHRT_READ";
    public static final String AUTHRT_UPDATE = "AUTHRT_UPDATE";
    public static final String BANNER_ADMIN_READ = "BANNER_ADMIN_READ";
    public static final String BANNER_CREATE = "BANNER_CREATE";
    public static final String BANNER_DELETE = "BANNER_DELETE";
    public static final String BANNER_READ = "BANNER_READ";
    public static final String BANNER_UPDATE = "BANNER_UPDATE";
    public static final String BBS_MST_CREATE = "BBS_MST_CREATE";
    public static final String BBS_MST_DELETE = "BBS_MST_DELETE";
    public static final String BBS_MST_READ = "BBS_MST_READ";
    public static final String BBS_MST_READ_ALL = "BBS_MST_READ_ALL";
    public static final String BBS_MST_UPDATE = "BBS_MST_UPDATE";
    public static final String BOARD_CREATE = "BOARD_CREATE";
    public static final String BOARD_DELETE = "BOARD_DELETE";
    public static final String BOARD_DELETE_ALL = "BOARD_DELETE_ALL";
    public static final String BOARD_LIKE = "BOARD_LIKE";
    public static final String BOARD_READ = "BOARD_READ";
    public static final String BOARD_READ_ALL = "BOARD_READ_ALL";
    public static final String BOARD_UPDATE = "BOARD_UPDATE";
    public static final String BOARD_UPDATE_ALL = "BOARD_UPDATE_ALL";
    public static final String CLASS_GRP_CREATE = "CLASS_GRP_CREATE";
    public static final String CLASS_GRP_DELETE = "CLASS_GRP_DELETE";
    public static final String CLASS_GRP_READ = "CLASS_GRP_READ";
    public static final String CLASS_GRP_UPDATE = "CLASS_GRP_UPDATE";
    public static final String CODE_CREATE = "CODE_CREATE";
    public static final String CODE_DELETE = "CODE_DELETE";
    public static final String CODE_READ = "CODE_READ";
    public static final String CODE_UPDATE = "CODE_UPDATE";
    public static final String COMMENT_CREATE = "COMMENT_CREATE";
    public static final String COMMENT_DELETE = "COMMENT_DELETE";
    public static final String COMMENT_DELETE_ALL = "COMMENT_DELETE_ALL";
    public static final String COMMENT_READ = "COMMENT_READ";
    public static final String COMMENT_READ_ALL = "COMMENT_READ_ALL";
    public static final String COMMENT_UPDATE = "COMMENT_UPDATE";
    public static final String COMMENT_UPDATE_ALL = "COMMENT_UPDATE_ALL";
    public static final String COMMUNITY_APPROVE = "COMMUNITY_APPROVE";
    public static final String COMMUNITY_CREATE_ALL = "COMMUNITY_CREATE_ALL";
    public static final String COMMUNITY_DELETE_ALL = "COMMUNITY_DELETE_ALL";
    public static final String COMMUNITY_JOIN = "COMMUNITY_JOIN";
    public static final String COMMUNITY_READ = "COMMUNITY_READ";
    public static final String COMMUNITY_READ_ALL = "COMMUNITY_READ_ALL";
    public static final String COMMUNITY_REJECT = "COMMUNITY_REJECT";
    public static final String COMMUNITY_UPDATE_ALL = "COMMUNITY_UPDATE_ALL";
    public static final String DASHBOARD_ADMIN_READ = "DASHBOARD_ADMIN_READ";
    public static final String DASHBOARD_READ = "DASHBOARD_READ";
    public static final String DEPT_BOX_CREATE = "DEPT_BOX_CREATE";
    public static final String DEPT_BOX_DELETE = "DEPT_BOX_DELETE";
    public static final String DEPT_BOX_READ = "DEPT_BOX_READ";
    public static final String DEPT_BOX_UPDATE = "DEPT_BOX_UPDATE";
    public static final String DEPT_CREATE = "DEPT_CREATE";
    public static final String DEPT_DELETE = "DEPT_DELETE";
    public static final String DEPT_JOB_CREATE = "DEPT_JOB_CREATE";
    public static final String DEPT_JOB_DELETE = "DEPT_JOB_DELETE";
    public static final String DEPT_JOB_DELETE_ALL = "DEPT_JOB_DELETE_ALL";
    public static final String DEPT_JOB_READ = "DEPT_JOB_READ";
    public static final String DEPT_JOB_UPDATE = "DEPT_JOB_UPDATE";
    public static final String DEPT_JOB_UPDATE_ALL = "DEPT_JOB_UPDATE_ALL";
    public static final String DEPT_READ = "DEPT_READ";
    public static final String DEPT_UPDATE = "DEPT_UPDATE";
    public static final String EVENT_CREATE = "EVENT_CREATE";
    public static final String EVENT_DELETE = "EVENT_DELETE";
    public static final String EVENT_DELETE_ALL = "EVENT_DELETE_ALL";
    public static final String EVENT_READ = "EVENT_READ";
    public static final String EVENT_UPDATE = "EVENT_UPDATE";
    public static final String EVENT_UPDATE_ALL = "EVENT_UPDATE_ALL";
    public static final String EXT_HR_CREATE = "EXT_HR_CREATE";
    public static final String EXT_HR_DELETE = "EXT_HR_DELETE";
    public static final String EXT_HR_DELETE_ALL = "EXT_HR_DELETE_ALL";
    public static final String EXT_HR_READ = "EXT_HR_READ";
    public static final String EXT_HR_UPDATE = "EXT_HR_UPDATE";
    public static final String EXT_HR_UPDATE_ALL = "EXT_HR_UPDATE_ALL";
    public static final String FILE_AUDIT = "FILE_AUDIT";
    public static final String FILE_DELETE = "FILE_DELETE";
    public static final String FILE_DELETE_ALL = "FILE_DELETE_ALL";
    public static final String FILE_DOWNLOAD = "FILE_DOWNLOAD";
    public static final String FILE_DOWNLOAD_ALL = "FILE_DOWNLOAD_ALL";
    public static final String FILE_READ = "FILE_READ";
    public static final String FILE_READ_ALL = "FILE_READ_ALL";
    public static final String FILE_UPLOAD = "FILE_UPLOAD";
    public static final String FILE_UPLOAD_ALL = "FILE_UPLOAD_ALL";
    public static final String HELP_CREATE = "HELP_CREATE";
    public static final String HELP_DELETE = "HELP_DELETE";
    public static final String HELP_DELETE_ALL = "HELP_DELETE_ALL";
    public static final String HELP_READ = "HELP_READ";
    public static final String HELP_UPDATE = "HELP_UPDATE";
    public static final String HELP_UPDATE_ALL = "HELP_UPDATE_ALL";
    public static final String INFORMAL_APPROVE = "INFORMAL_APPROVE";
    public static final String INFORMAL_APPR_ADMIN = "INFORMAL_APPR_ADMIN";
    public static final String INFORMAL_CREATE = "INFORMAL_CREATE";
    public static final String INFORMAL_CREATE_ALL = "INFORMAL_CREATE_ALL";
    public static final String INFORMAL_DELETE = "INFORMAL_DELETE";
    public static final String INFORMAL_DELETE_ALL = "INFORMAL_DELETE_ALL";
    public static final String INFORMAL_READ = "INFORMAL_READ";
    public static final String INFORMAL_READ_ALL = "INFORMAL_READ_ALL";
    public static final String INFORMAL_UPDATE = "INFORMAL_UPDATE";
    public static final String INFORMAL_UPDATE_ALL = "INFORMAL_UPDATE_ALL";
    public static final String INST_CODE_CREATE = "INST_CODE_CREATE";
    public static final String INST_CODE_DELETE = "INST_CODE_DELETE";
    public static final String INST_CODE_IMPORT = "INST_CODE_IMPORT";
    public static final String INST_CODE_READ = "INST_CODE_READ";
    public static final String INST_CODE_UPDATE = "INST_CODE_UPDATE";
    public static final String LOGIN_LOG_EXPORT = "LOGIN_LOG_EXPORT";
    public static final String LOGIN_LOG_READ = "LOGIN_LOG_READ";
    public static final String LOGIN_POL_CREATE = "LOGIN_POL_CREATE";
    public static final String LOGIN_POL_DELETE = "LOGIN_POL_DELETE";
    public static final String LOGIN_POL_READ = "LOGIN_POL_READ";
    public static final String LOGIN_POL_UPDATE = "LOGIN_POL_UPDATE";
    public static final String MAIL_DELETE = "MAIL_DELETE";
    public static final String MAIL_DELETE_ALL = "MAIL_DELETE_ALL";
    public static final String MAIL_READ = "MAIL_READ";
    public static final String MAIL_READ_ALL = "MAIL_READ_ALL";
    public static final String MAIL_SEND = "MAIL_SEND";
    public static final String MEMO_RPT_CREATE = "MEMO_RPT_CREATE";
    public static final String MEMO_RPT_DELETE = "MEMO_RPT_DELETE";
    public static final String MEMO_RPT_DELETE_ALL = "MEMO_RPT_DELETE_ALL";
    public static final String MEMO_RPT_INSTRUCT = "MEMO_RPT_INSTRUCT";
    public static final String MEMO_RPT_READ = "MEMO_RPT_READ";
    public static final String MEMO_RPT_READ_ALL = "MEMO_RPT_READ_ALL";
    public static final String MEMO_RPT_UPDATE = "MEMO_RPT_UPDATE";
    public static final String MEMO_RPT_UPDATE_ALL = "MEMO_RPT_UPDATE_ALL";
    public static final String MENU_CREATE = "MENU_CREATE";
    public static final String MENU_DELETE = "MENU_DELETE";
    public static final String MENU_READ = "MENU_READ";
    public static final String MENU_UPDATE = "MENU_UPDATE";
    public static final String NETWORK_CREATE = "NETWORK_CREATE";
    public static final String NETWORK_DELETE = "NETWORK_DELETE";
    public static final String NETWORK_READ = "NETWORK_READ";
    public static final String NETWORK_UPDATE = "NETWORK_UPDATE";
    public static final String NOTE_DELETE = "NOTE_DELETE";
    public static final String NOTE_READ = "NOTE_READ";
    public static final String NOTE_SEND = "NOTE_SEND";
    public static final String NOTI_ACK = "NOTI_ACK";
    public static final String NOTI_CREATE = "NOTI_CREATE";
    public static final String NOTI_DELETE = "NOTI_DELETE";
    public static final String NOTI_DISPATCH = "NOTI_DISPATCH";
    public static final String NOTI_READ = "NOTI_READ";
    public static final String OPS_READ = "OPS_READ";
    public static final String POLICY_READ = "POLICY_READ";
    public static final String POLICY_UPDATE = "POLICY_UPDATE";
    public static final String POLL_CREATE = "POLL_CREATE";
    public static final String POLL_DELETE = "POLL_DELETE";
    public static final String POLL_DELETE_ALL = "POLL_DELETE_ALL";
    public static final String POLL_READ = "POLL_READ";
    public static final String POLL_READ_ALL = "POLL_READ_ALL";
    public static final String POLL_UPDATE = "POLL_UPDATE";
    public static final String POLL_UPDATE_ALL = "POLL_UPDATE_ALL";
    public static final String POLL_VOTE = "POLL_VOTE";
    public static final String POPUP_ADMIN_READ = "POPUP_ADMIN_READ";
    public static final String POPUP_CREATE = "POPUP_CREATE";
    public static final String POPUP_DELETE = "POPUP_DELETE";
    public static final String POPUP_READ = "POPUP_READ";
    public static final String POPUP_UPDATE = "POPUP_UPDATE";
    public static final String PRIVACY_EXPORT = "PRIVACY_EXPORT";
    public static final String PRIVACY_READ = "PRIVACY_READ";
    public static final String PROGRAM_CREATE = "PROGRAM_CREATE";
    public static final String PROGRAM_DELETE = "PROGRAM_DELETE";
    public static final String PROGRAM_READ = "PROGRAM_READ";
    public static final String PROGRAM_UPDATE = "PROGRAM_UPDATE";
    public static final String REWARD_CREATE = "REWARD_CREATE";
    public static final String REWARD_DELETE = "REWARD_DELETE";
    public static final String REWARD_DELETE_ALL = "REWARD_DELETE_ALL";
    public static final String REWARD_READ = "REWARD_READ";
    public static final String REWARD_UPDATE = "REWARD_UPDATE";
    public static final String REWARD_UPDATE_ALL = "REWARD_UPDATE_ALL";
    public static final String SATISFY_CREATE = "SATISFY_CREATE";
    public static final String SATISFY_DELETE = "SATISFY_DELETE";
    public static final String SATISFY_DELETE_ALL = "SATISFY_DELETE_ALL";
    public static final String SATISFY_MODERATE = "SATISFY_MODERATE";
    public static final String SATISFY_READ = "SATISFY_READ";
    public static final String SATISFY_UPDATE = "SATISFY_UPDATE";
    public static final String SATISFY_UPDATE_ALL = "SATISFY_UPDATE_ALL";
    public static final String SCHEDULE_CREATE = "SCHEDULE_CREATE";
    public static final String SCHEDULE_DELETE = "SCHEDULE_DELETE";
    public static final String SCHEDULE_DELETE_ALL = "SCHEDULE_DELETE_ALL";
    public static final String SCHEDULE_READ = "SCHEDULE_READ";
    public static final String SCHEDULE_READ_ALL = "SCHEDULE_READ_ALL";
    public static final String SCHEDULE_UPDATE = "SCHEDULE_UPDATE";
    public static final String SCHEDULE_UPDATE_ALL = "SCHEDULE_UPDATE_ALL";
    public static final String SCRAP_CREATE = "SCRAP_CREATE";
    public static final String SCRAP_DELETE = "SCRAP_DELETE";
    public static final String SCRAP_DELETE_ALL = "SCRAP_DELETE_ALL";
    public static final String SCRAP_READ = "SCRAP_READ";
    public static final String SCRAP_READ_ALL = "SCRAP_READ_ALL";
    public static final String SCRAP_UPDATE = "SCRAP_UPDATE";
    public static final String SCRAP_UPDATE_ALL = "SCRAP_UPDATE_ALL";
    public static final String SERVICE_CREATE = "SERVICE_CREATE";
    public static final String SERVICE_DELETE = "SERVICE_DELETE";
    public static final String SERVICE_READ = "SERVICE_READ";
    public static final String SERVICE_UPDATE = "SERVICE_UPDATE";
    public static final String SMS_READ = "SMS_READ";
    public static final String SMS_SEND = "SMS_SEND";
    public static final String STATS_ADMIN_READ = "STATS_ADMIN_READ";
    public static final String STATS_READ = "STATS_READ";
    public static final String SURVEY_CREATE_ALL = "SURVEY_CREATE_ALL";
    public static final String SURVEY_DELETE_ALL = "SURVEY_DELETE_ALL";
    public static final String SURVEY_READ = "SURVEY_READ";
    public static final String SURVEY_READ_ALL = "SURVEY_READ_ALL";
    public static final String SURVEY_RSP_DELETE = "SURVEY_RSP_DELETE";
    public static final String SURVEY_RSP_READ = "SURVEY_RSP_READ";
    public static final String SURVEY_SUBMIT = "SURVEY_SUBMIT";
    public static final String SURVEY_UPDATE_ALL = "SURVEY_UPDATE_ALL";
    public static final String SYS_LOG_EXPORT = "SYS_LOG_EXPORT";
    public static final String SYS_LOG_READ = "SYS_LOG_READ";
    public static final String TEMPLATE_CREATE = "TEMPLATE_CREATE";
    public static final String TEMPLATE_DELETE = "TEMPLATE_DELETE";
    public static final String TEMPLATE_READ = "TEMPLATE_READ";
    public static final String TEMPLATE_UPDATE = "TEMPLATE_UPDATE";
    public static final String USER_CREATE = "USER_CREATE";
    public static final String USER_DELETE = "USER_DELETE";
    public static final String USER_DEPT = "USER_DEPT";
    public static final String USER_LOG_EXPORT = "USER_LOG_EXPORT";
    public static final String USER_LOG_READ = "USER_LOG_READ";
    public static final String USER_PASSWORD = "USER_PASSWORD";
    public static final String USER_READ = "USER_READ";
    public static final String USER_STATUS = "USER_STATUS";
    public static final String USER_UPDATE = "USER_UPDATE";
    public static final String WEB_LOG_EXPORT = "WEB_LOG_EXPORT";
    public static final String WEB_LOG_READ = "WEB_LOG_READ";
    public static final String WORKFLOW_READ = "WORKFLOW_READ";
    public static final String WORK_RPT_CREATE = "WORK_RPT_CREATE";
    public static final String WORK_RPT_DELETE = "WORK_RPT_DELETE";
    public static final String WORK_RPT_DELETE_ALL = "WORK_RPT_DELETE_ALL";
    public static final String WORK_RPT_READ = "WORK_RPT_READ";
    public static final String WORK_RPT_READ_ALL = "WORK_RPT_READ_ALL";
    public static final String WORK_RPT_UPDATE = "WORK_RPT_UPDATE";
    public static final String WORK_RPT_UPDATE_ALL = "WORK_RPT_UPDATE_ALL";
    public static final java.util.Set<String> ALL = java.util.Set.of(
            ABSENCE_READ,
            ABSENCE_UPDATE,
            ADBK_CREATE,
            ADBK_DELETE,
            ADBK_DELETE_ALL,
            ADBK_READ,
            ADBK_READ_ALL,
            ADBK_UPDATE,
            ADBK_UPDATE_ALL,
            ADMCODE_CREATE,
            ADMCODE_DELETE,
            ADMCODE_READ,
            ADMCODE_UPDATE,
            APPROVAL_APPROVE,
            APPROVAL_CANCEL,
            APPROVAL_CREATE,
            APPROVAL_READ,
            AUTHRT_ASSIGN,
            AUTHRT_AUDIT,
            AUTHRT_CREATE,
            AUTHRT_DELETE,
            AUTHRT_GRANT,
            AUTHRT_READ,
            AUTHRT_UPDATE,
            BANNER_ADMIN_READ,
            BANNER_CREATE,
            BANNER_DELETE,
            BANNER_READ,
            BANNER_UPDATE,
            BBS_MST_CREATE,
            BBS_MST_DELETE,
            BBS_MST_READ,
            BBS_MST_READ_ALL,
            BBS_MST_UPDATE,
            BOARD_CREATE,
            BOARD_DELETE,
            BOARD_DELETE_ALL,
            BOARD_LIKE,
            BOARD_READ,
            BOARD_READ_ALL,
            BOARD_UPDATE,
            BOARD_UPDATE_ALL,
            CLASS_GRP_CREATE,
            CLASS_GRP_DELETE,
            CLASS_GRP_READ,
            CLASS_GRP_UPDATE,
            CODE_CREATE,
            CODE_DELETE,
            CODE_READ,
            CODE_UPDATE,
            COMMENT_CREATE,
            COMMENT_DELETE,
            COMMENT_DELETE_ALL,
            COMMENT_READ,
            COMMENT_READ_ALL,
            COMMENT_UPDATE,
            COMMENT_UPDATE_ALL,
            COMMUNITY_APPROVE,
            COMMUNITY_CREATE_ALL,
            COMMUNITY_DELETE_ALL,
            COMMUNITY_JOIN,
            COMMUNITY_READ,
            COMMUNITY_READ_ALL,
            COMMUNITY_REJECT,
            COMMUNITY_UPDATE_ALL,
            DASHBOARD_ADMIN_READ,
            DASHBOARD_READ,
            DEPT_BOX_CREATE,
            DEPT_BOX_DELETE,
            DEPT_BOX_READ,
            DEPT_BOX_UPDATE,
            DEPT_CREATE,
            DEPT_DELETE,
            DEPT_JOB_CREATE,
            DEPT_JOB_DELETE,
            DEPT_JOB_DELETE_ALL,
            DEPT_JOB_READ,
            DEPT_JOB_UPDATE,
            DEPT_JOB_UPDATE_ALL,
            DEPT_READ,
            DEPT_UPDATE,
            EVENT_CREATE,
            EVENT_DELETE,
            EVENT_DELETE_ALL,
            EVENT_READ,
            EVENT_UPDATE,
            EVENT_UPDATE_ALL,
            EXT_HR_CREATE,
            EXT_HR_DELETE,
            EXT_HR_DELETE_ALL,
            EXT_HR_READ,
            EXT_HR_UPDATE,
            EXT_HR_UPDATE_ALL,
            FILE_AUDIT,
            FILE_DELETE,
            FILE_DELETE_ALL,
            FILE_DOWNLOAD,
            FILE_DOWNLOAD_ALL,
            FILE_READ,
            FILE_READ_ALL,
            FILE_UPLOAD,
            FILE_UPLOAD_ALL,
            HELP_CREATE,
            HELP_DELETE,
            HELP_DELETE_ALL,
            HELP_READ,
            HELP_UPDATE,
            HELP_UPDATE_ALL,
            INFORMAL_APPROVE,
            INFORMAL_APPR_ADMIN,
            INFORMAL_CREATE,
            INFORMAL_CREATE_ALL,
            INFORMAL_DELETE,
            INFORMAL_DELETE_ALL,
            INFORMAL_READ,
            INFORMAL_READ_ALL,
            INFORMAL_UPDATE,
            INFORMAL_UPDATE_ALL,
            INST_CODE_CREATE,
            INST_CODE_DELETE,
            INST_CODE_IMPORT,
            INST_CODE_READ,
            INST_CODE_UPDATE,
            LOGIN_LOG_EXPORT,
            LOGIN_LOG_READ,
            LOGIN_POL_CREATE,
            LOGIN_POL_DELETE,
            LOGIN_POL_READ,
            LOGIN_POL_UPDATE,
            MAIL_DELETE,
            MAIL_DELETE_ALL,
            MAIL_READ,
            MAIL_READ_ALL,
            MAIL_SEND,
            MEMO_RPT_CREATE,
            MEMO_RPT_DELETE,
            MEMO_RPT_DELETE_ALL,
            MEMO_RPT_INSTRUCT,
            MEMO_RPT_READ,
            MEMO_RPT_READ_ALL,
            MEMO_RPT_UPDATE,
            MEMO_RPT_UPDATE_ALL,
            MENU_CREATE,
            MENU_DELETE,
            MENU_READ,
            MENU_UPDATE,
            NETWORK_CREATE,
            NETWORK_DELETE,
            NETWORK_READ,
            NETWORK_UPDATE,
            NOTE_DELETE,
            NOTE_READ,
            NOTE_SEND,
            NOTI_ACK,
            NOTI_CREATE,
            NOTI_DELETE,
            NOTI_DISPATCH,
            NOTI_READ,
            OPS_READ,
            POLICY_READ,
            POLICY_UPDATE,
            POLL_CREATE,
            POLL_DELETE,
            POLL_DELETE_ALL,
            POLL_READ,
            POLL_READ_ALL,
            POLL_UPDATE,
            POLL_UPDATE_ALL,
            POLL_VOTE,
            POPUP_ADMIN_READ,
            POPUP_CREATE,
            POPUP_DELETE,
            POPUP_READ,
            POPUP_UPDATE,
            PRIVACY_EXPORT,
            PRIVACY_READ,
            PROGRAM_CREATE,
            PROGRAM_DELETE,
            PROGRAM_READ,
            PROGRAM_UPDATE,
            REWARD_CREATE,
            REWARD_DELETE,
            REWARD_DELETE_ALL,
            REWARD_READ,
            REWARD_UPDATE,
            REWARD_UPDATE_ALL,
            SATISFY_CREATE,
            SATISFY_DELETE,
            SATISFY_DELETE_ALL,
            SATISFY_MODERATE,
            SATISFY_READ,
            SATISFY_UPDATE,
            SATISFY_UPDATE_ALL,
            SCHEDULE_CREATE,
            SCHEDULE_DELETE,
            SCHEDULE_DELETE_ALL,
            SCHEDULE_READ,
            SCHEDULE_READ_ALL,
            SCHEDULE_UPDATE,
            SCHEDULE_UPDATE_ALL,
            SCRAP_CREATE,
            SCRAP_DELETE,
            SCRAP_DELETE_ALL,
            SCRAP_READ,
            SCRAP_READ_ALL,
            SCRAP_UPDATE,
            SCRAP_UPDATE_ALL,
            SERVICE_CREATE,
            SERVICE_DELETE,
            SERVICE_READ,
            SERVICE_UPDATE,
            SMS_READ,
            SMS_SEND,
            STATS_ADMIN_READ,
            STATS_READ,
            SURVEY_CREATE_ALL,
            SURVEY_DELETE_ALL,
            SURVEY_READ,
            SURVEY_READ_ALL,
            SURVEY_RSP_DELETE,
            SURVEY_RSP_READ,
            SURVEY_SUBMIT,
            SURVEY_UPDATE_ALL,
            SYS_LOG_EXPORT,
            SYS_LOG_READ,
            TEMPLATE_CREATE,
            TEMPLATE_DELETE,
            TEMPLATE_READ,
            TEMPLATE_UPDATE,
            USER_CREATE,
            USER_DELETE,
            USER_DEPT,
            USER_LOG_EXPORT,
            USER_LOG_READ,
            USER_PASSWORD,
            USER_READ,
            USER_STATUS,
            USER_UPDATE,
            WEB_LOG_EXPORT,
            WEB_LOG_READ,
            WORKFLOW_READ,
            WORK_RPT_CREATE,
            WORK_RPT_DELETE,
            WORK_RPT_DELETE_ALL,
            WORK_RPT_READ,
            WORK_RPT_READ_ALL,
            WORK_RPT_UPDATE,
            WORK_RPT_UPDATE_ALL);
}
