plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-security'
    
    api libs.egovframe.rte.fdl.cmmn
    api libs.egovframe.rte.fdl.crypto
    api libs.egovframe.rte.fdl.access
    api libs.egovframe.rte.fdl.idgnr
    
    api libs.icu4j
    api 'jakarta.servlet:jakarta.servlet-api'
    api 'org.apache.commons:commons-lang3'
    api 'commons-io:commons-io:2.11.0'
    api 'com.google.guava:guava:33.3.1-jre'
    api 'com.fasterxml.jackson.core:jackson-databind'
}