CREATE TABLE TB_ADMDST_CD (
    ADMDST_CD VARCHAR(12) NOT NULL PRIMARY KEY,
    UP_ADMDST_CD VARCHAR(12),
    ADMDST_SE_CD VARCHAR(12),
    USE_YN CHAR(1),
    CRT_YMD CHAR(8),
    ABL_YMD CHAR(8),
    ADMDST_ZONE_NM VARCHAR(100),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_AUTHRT_INFO (
    AUTHRT_CD VARCHAR(30) NOT NULL PRIMARY KEY,
    AUTHRT_NM VARCHAR(300) NOT NULL,
    AUTHRT_EXPLN VARCHAR(4000),
    AUTHRT_CRT_YMD CHAR(8),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

INSERT INTO TB_AUTHRT_INFO (AUTHRT_CD, AUTHRT_NM, AUTHRT_EXPLN, AUTHRT_CRT_YMD) VALUES 
('ROLE_ADMIN', '시스템 관리자', '전체 시스템 관리 권한', '20260518'),
('ROLE_USER', '일반 사용자', '일반 업무 사용자 권한', '20260518'),
('ROLE_ANONYMOUS', '익명 사용자', '비로그인 사용자 권한', '20260518');

CREATE TABLE TB_AUTHRT_GROUP_INFO (
    GROUP_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    GROUP_NM VARCHAR(100),
    GROUP_EXPLN VARCHAR(4000),
    GROUP_CRT_YMD CHAR(8),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_AUTHRT_ROLE_MAP (
    AUTHRT_CD VARCHAR(30) NOT NULL,
    ROLE_CD VARCHAR(12) NOT NULL,
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20),
    PRIMARY KEY (AUTHRT_CD, ROLE_CD)
);

CREATE TABLE TB_ROLE_LYR (
    PRNT_ROLE_ID VARCHAR(30) NOT NULL,
    CHLD_ROLE_ID VARCHAR(30) NOT NULL,
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20),
    PRIMARY KEY (PRNT_ROLE_ID, CHLD_ROLE_ID)
);

CREATE TABLE TB_MENU_CRT_DTL (
    MENU_SN BIGINT NOT NULL,
    AUTHRT_CD VARCHAR(12) NOT NULL,
    MAPNG_CRT_ID VARCHAR(20),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20),
    PRIMARY KEY (MENU_SN, AUTHRT_CD)
);

CREATE TABLE TB_PRGRM_LST (
    PRGRM_FILE_NM VARCHAR(100) NOT NULL PRIMARY KEY,
    PRGRM_KORN_NM VARCHAR(100),
    PRGRM_STRG_PATH VARCHAR(1000),
    URL VARCHAR(1000),
    PRGRM_EXPLN VARCHAR(4000),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_INDV_PG (
    PAGE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    PAGE_TTL VARCHAR(300) NOT NULL,
    PAGE_EXPLN VARCHAR(4000),
    USER_ID VARCHAR(30) NOT NULL,
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_INDV_PG_CONTS (
    CNTNTS_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CNTNTS_NM VARCHAR(100),
    CNTC_URL VARCHAR(255),
    CNTNTS_USE_YN CHAR(1),
    CNTNTS_LINK_URL VARCHAR(255),
    CNTNTS_DC VARCHAR(255),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_INDV_PG_SET (
    TTL_BAR_CLR VARCHAR(12),
    SORT_MTHD VARCHAR(12),
    SORT_COUNT BIGINT,
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_INTRN_SVC (
    ITNT_SVC_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ITNT_SVC_NM VARCHAR(100),
    ITNT_SVC_EXPLN VARCHAR(4000),
    RFLT_YN CHAR(1),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);

CREATE TABLE TB_STMP_INFO (
    MPNG_CRT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CRTR_ID VARCHAR(20),
    MPNG_FILE_NM VARCHAR(100),
    MPNG_FILE_PATH VARCHAR(1000),
    CRT_DT TIMESTAMP,
    MDFCN_DT TIMESTAMP,
    FRST_RGTR_ID VARCHAR(20),
    LAST_MDFR_ID VARCHAR(20)
);
