const fs = require('fs');
const path = require('path');

// 경로 설정
const projectRoot = path.join(__dirname, '..', '..');
const apiDocsPath = path.join(projectRoot, 'api-docs.json');
const outputPath = path.join(projectRoot, 'frontend', 'src', 'types', 'generated-zod.ts');

console.log('Loading api-docs.json...');
if (!fs.existsSync(apiDocsPath)) {
  console.error(`Error: api-docs.json not found at ${apiDocsPath}`);
  process.exit(1);
}

const apiDocs = JSON.parse(fs.readFileSync(apiDocsPath, 'utf8'));
const schemas = apiDocs.components?.schemas || {};
const schemaNames = Object.keys(schemas);

console.log(`Found ${schemaNames.length} schemas in api-docs.json.`);

// 헬퍼 함수: $ref에서 스키마 이름 추출
function getSchemaNameFromRef(ref) {
  if (!ref) return null;
  const parts = ref.split('/');
  return parts[parts.length - 1];
}

// 헬퍼 함수: 개별 프로퍼티를 Zod 코드로 변환
function convertPropertyToZod(propName, prop, requiredList = []) {
  let zodChain = '';
  const isRequired = requiredList.includes(propName);

  // $ref가 직접 정의된 경우
  if (prop.$ref) {
    const refSchema = getSchemaNameFromRef(prop.$ref);
    zodChain = `z.lazy(() => ${refSchema}Schema)`;
  } else {
    switch (prop.type) {
      case 'string':
        zodChain = 'z.string()';
        if (prop.minLength !== undefined) {
          zodChain += `.min(${prop.minLength})`;
        }
        if (prop.maxLength !== undefined) {
          zodChain += `.max(${prop.maxLength})`;
        }
        if (prop.pattern !== undefined) {
          // 이스케이프 보호를 위해 JSON.stringify를 활용해 new RegExp 문자열 생성
          const safePattern = JSON.stringify(prop.pattern);
          zodChain += `.regex(new RegExp(${safePattern}))`;
        }
        break;
      case 'integer':
      case 'number':
        zodChain = 'z.number()';
        if (prop.minimum !== undefined) {
          zodChain += `.min(${prop.minimum})`;
        }
        if (prop.maximum !== undefined) {
          zodChain += `.max(${prop.maximum})`;
        }
        break;
      case 'boolean':
        zodChain = 'z.boolean()';
        break;
      case 'array':
        if (prop.items) {
          if (prop.items.$ref) {
            const refSchema = getSchemaNameFromRef(prop.items.$ref);
            zodChain = `z.array(z.lazy(() => ${refSchema}Schema))`;
          } else {
            const itemType = convertPropertyToZod('', prop.items, []);
            zodChain = `z.array(${itemType})`;
          }
        } else {
          zodChain = 'z.array(z.any())';
        }
        break;
      case 'object':
        if (prop.properties) {
          const nestedProps = [];
          const nestedRequired = prop.required || [];
          for (const [subName, subProp] of Object.entries(prop.properties)) {
            nestedProps.push(`  ${subName}: ${convertPropertyToZod(subName, subProp, nestedRequired)}`);
          }
          zodChain = `z.object({\n  ${nestedProps.join(',\n  ')}\n})`;
        } else {
          zodChain = 'z.record(z.any())';
        }
        break;
      default:
        zodChain = 'z.any()';
    }
  }

  // 필수 값이 아니면 optional 처리
  if (!isRequired) {
    zodChain += '.optional()';
  }

  // nullable인 경우 처리
  if (prop.nullable) {
    zodChain += '.nullable()';
  }

  return zodChain;
}

// Zod 스키마 코드 빌드
let codeLines = [
  '// ==========================================================================',
  '// ⚠️ WARNING: Auto-generated file. Do not edit this file manually.',
  '// This file is generated by codegen-zod.js using api-docs.json.',
  '// ==========================================================================',
  '',
  "import { z } from 'zod';",
  ''
];

// 각 스키마의 Zod Object를 문자열로 빌드
for (const schemaName of schemaNames) {
  const schema = schemas[schemaName];
  
  codeLines.push(`// ==========================================================================`);
  codeLines.push(`// ${schemaName} Schema`);
  codeLines.push(`// ==========================================================================`);
  
  if (schema.type === 'object' && schema.properties) {
    const requiredList = schema.required || [];
    codeLines.push(`export const ${schemaName}Schema = z.object({`);
    
    for (const [propName, prop] of Object.entries(schema.properties)) {
      const zodProp = convertPropertyToZod(propName, prop, requiredList);
      codeLines.push(`  ${propName}: ${zodProp},`);
    }
    
    codeLines.push(`});`);
    codeLines.push(`export type ${schemaName} = z.infer<typeof ${schemaName}Schema>;`);
  } else if (schema.type === 'array' && schema.items) {
    if (schema.items.$ref) {
      const refSchema = getSchemaNameFromRef(schema.items.$ref);
      codeLines.push(`export const ${schemaName}Schema = z.array(z.lazy(() => ${refSchema}Schema));`);
    } else {
      codeLines.push(`export const ${schemaName}Schema = z.array(z.any());`);
    }
    codeLines.push(`export type ${schemaName} = z.infer<typeof ${schemaName}Schema>;`);
  } else {
    // 그 외 단선 타입이거나 맵 형식 등
    codeLines.push(`export const ${schemaName}Schema = z.any();`);
    codeLines.push(`export type ${schemaName} = any;`);
  }
  codeLines.push('');
}

// 디렉토리 존재 확인 및 생성
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// 파일 쓰기
fs.writeFileSync(outputPath, codeLines.join('\n'), 'utf8');
console.log(`\nSuccessfully compiled and generated Zod schemas to ${outputPath}!`);
console.log(`Generated file size: ${(fs.statSync(outputPath).size / 1024).toFixed(2)} KB.`);
