const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
const { readDbConfig } = require('./db-bridge');

/**
 * Full Database Dump Tool for PostgreSQL (Antigravity Edition)
 * Includes: Sequences, Tables, Data, Comments, Views, Functions, Constraints, Indices
 */

const client = new Client(readDbConfig());
const dumpDir = path.join(process.cwd(), 'database', 'dumps');
if (!fs.existsSync(dumpDir)) {
    fs.mkdirSync(dumpDir, { recursive: true });
}
const outputFilePath = path.join(dumpDir, `db_full_dump_${new Date().toISOString().replace(/[:.]/g, '-')}.sql`);
const stream = fs.createWriteStream(outputFilePath);

async function dump() {
    console.log(`>>> Starting full database dump to: ${outputFilePath}`);
    await client.connect();

    try {
        await client.query('BEGIN TRANSACTION READ ONLY');
        await client.query("SET LOCAL statement_timeout = '30s'");
        stream.write('-- Full Database Dump generated by Antigravity\n');
        stream.write(`-- Date: ${new Date().toLocaleString()}\n\n`);

        // 1. Sequences
        console.log('>>> Dumping sequences...');
        const seqRes = await client.query(`
            SELECT sequence_name, data_type, start_value, minimum_value, maximum_value, increment, cycle_option 
            FROM information_schema.sequences 
            WHERE sequence_schema = 'public'
        `);
        for (const seq of seqRes.rows) {
            stream.write(`CREATE SEQUENCE IF NOT EXISTS ${seq.sequence_name} 
                START WITH ${seq.start_value} 
                INCREMENT BY ${seq.increment} 
                MINVALUE ${seq.minimum_value} 
                MAXVALUE ${seq.maximum_value} 
                ${seq.cycle_option === 'YES' ? 'CYCLE' : 'NO CYCLE'};\n`);
        }
        stream.write('\n');

        // 2. Tables and Columns
        console.log('>>> Dumping tables and comments...');
        const tablesRes = await client.query(`
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
            ORDER BY table_name
        `);

        for (const table of tablesRes.rows) {
            const tableName = table.table_name;
            console.log(`  - Table: ${tableName}`);

            // Get Table Comment
            const tableCommentRes = await client.query(`
                SELECT obj_description(pg_class.oid, 'pg_class') as comment
                FROM pg_class
                JOIN pg_namespace ON pg_class.relnamespace = pg_namespace.oid
                WHERE pg_class.relname = $1 AND pg_namespace.nspname = 'public'
            `, [tableName]);
            if (tableCommentRes.rows[0]?.comment) {
                stream.write(`COMMENT ON TABLE ${tableName} IS '${tableCommentRes.rows[0].comment.replace(/'/g, "''")}';\n`);
            }

            // Get Column Definitions
            const colsRes = await client.query(`
                SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
                FROM information_schema.columns
                WHERE table_name = $1 AND table_schema = 'public'
                ORDER BY ordinal_position
            `, [tableName]);

            stream.write(`CREATE TABLE IF NOT EXISTS ${tableName} (\n`);
            const colDefs = colsRes.rows.map(col => {
                let def = `    ${col.column_name} ${col.data_type}`;
                if (col.character_maximum_length) def += `(${col.character_maximum_length})`;
                if (col.is_nullable === 'NO') def += ' NOT NULL';
                if (col.column_default) def += ` DEFAULT ${col.column_default}`;
                return def;
            });
            stream.write(colDefs.join(',\n') + '\n);\n');

            // Get Column Comments
            for (const col of colsRes.rows) {
                const colCommentRes = await client.query(`
                    SELECT col_description(pg_class.oid, pg_attribute.attnum) as comment
                    FROM pg_class
                    JOIN pg_attribute ON pg_class.oid = pg_attribute.attrelid
                    JOIN pg_namespace ON pg_class.relnamespace = pg_namespace.oid
                    WHERE pg_class.relname = $1 AND pg_attribute.attname = $2 AND pg_namespace.nspname = 'public'
                `, [tableName, col.column_name]);
                if (colCommentRes.rows[0]?.comment) {
                    stream.write(`COMMENT ON COLUMN ${tableName}.${col.column_name} IS '${colCommentRes.rows[0].comment.replace(/'/g, "''")}';\n`);
                }
            }

            // 3. Data (INSERTs)
            const dataRes = await client.query(`SELECT * FROM ${tableName}`);
            for (const row of dataRes.rows) {
                const keys = Object.keys(row);
                const values = Object.values(row).map(val => {
                    if (val === null) return 'NULL';
                    if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
                    if (val instanceof Date) return `'${val.toISOString()}'`;
                    return val;
                });
                stream.write(`INSERT INTO ${tableName} (${keys.join(', ')}) VALUES (${values.join(', ')});\n`);
            }
            stream.write('\n');
        }

        // 4. Views
        console.log('>>> Dumping views...');
        const viewsRes = await client.query(`
            SELECT table_name, view_definition 
            FROM information_schema.views 
            WHERE table_schema = 'public'
        `);
        for (const view of viewsRes.rows) {
            stream.write(`CREATE OR REPLACE VIEW ${view.table_name} AS\n${view.view_definition};\n\n`);
        }

        // 5. Functions
        console.log('>>> Dumping functions...');
        const funcRes = await client.query(`
            SELECT n.nspname as schema, p.proname as name, pg_get_functiondef(p.oid) as definition
            FROM pg_proc p
            JOIN pg_namespace n ON p.pronamespace = n.oid
            WHERE n.nspname = 'public'
        `);
        for (const func of funcRes.rows) {
            stream.write(`${func.definition};\n\n`);
        }

        // 6. Constraints and Indices
        console.log('>>> Dumping constraints and indices...');
        const constraintsRes = await client.query(`
            SELECT conname, pg_get_constraintdef(c.oid) as definition, relname as table_name
            FROM pg_constraint c
            JOIN pg_class r ON c.conrelid = r.oid
            JOIN pg_namespace n ON r.relnamespace = n.oid
            WHERE n.nspname = 'public'
        `);
        for (const con of constraintsRes.rows) {
            stream.write(`ALTER TABLE ${con.table_name} ADD CONSTRAINT ${con.conname} ${con.definition};\n`);
        }

        const indicesRes = await client.query(`
            SELECT indexname, indexdef
            FROM pg_indexes
            WHERE schemaname = 'public' AND indexname NOT IN (SELECT conname FROM pg_constraint)
        `);
        for (const idx of indicesRes.rows) {
            stream.write(`${idx.indexdef};\n`);
        }

        console.log(`>>> Dump completed successfully! File: ${outputFilePath}`);
    } catch (err) {
        console.error('>>> Dump Error:', err.message);
        process.exitCode = 1;
    } finally {
        try {
            await client.query('ROLLBACK');
        } catch {
            // Preserve the original dump error and close the connection below.
        }
        await client.end();
        stream.end();
    }
}

dump();
