import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { buildAtlasCatalog } from './atlas-catalog.mjs';

export const ATLAS_OUTPUT = 'frontend/public/governance_harness_atlas.html';
export const ATLAS_INPUTS = [
  'frontend/atlas/atlas.template.html',
  'frontend/atlas/atlas.css',
  'frontend/atlas/atlas-runtime.js',
  'scripts/atlas-catalog.mjs',
  'scripts/build-atlas.mjs',
];
const defaultRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const normalize = value => value.replace(/\r\n/g, '\n');
const digest = value => createHash('sha256').update(value).digest('hex');
const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[char]);

function replaceMarker(template, marker, content) {
  if (template.split(marker).length !== 2) throw new Error('Atlas marker must occur once: ' + marker);
  return template.replace(marker, () => content);
}

/** Portable, deterministic HTML. No network, timestamp, or generated-output self hash. */
export function renderAtlas(repoRoot = defaultRoot, suppliedCatalog) {
  const inputs = Object.fromEntries(ATLAS_INPUTS.map(file => [
    file, normalize(fs.readFileSync(path.join(repoRoot, file), 'utf8')),
  ]));
  const catalog = suppliedCatalog ?? buildAtlasCatalog(repoRoot);
  const presentationSources = ATLAS_INPUTS.map(file => ({ path: file, digest: digest(inputs[file]) }));
  const data = {
    ...catalog,
    presentationSources,
    sourceDigest: digest(JSON.stringify([catalog.sources, presentationSources])),
  };
  let html = inputs[ATLAS_INPUTS[0]];
  html = replaceMarker(html, '<!-- ATLAS_STYLE -->', '<style id="atlas-style">\n' + inputs[ATLAS_INPUTS[1]] + '\n</style>');
  const json = JSON.stringify(data).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  html = replaceMarker(html, '<!-- ATLAS_DATA -->', '<script id="atlas-catalog-data" type="application/json">' + json + '</script>');
  html = replaceMarker(html, '<!-- ATLAS_RUNTIME -->', '<script id="atlas-runtime">\n' + inputs[ATLAS_INPUTS[2]] + '\n</script>');
  html = html.replace(/(<span\b[^>]*\bdata-fact="([^"]+)"[^>]*>)[\s\S]*?<\/span>/g, (_, start, key) => {
    if (!Object.hasOwn(data.facts, key)) throw new Error('Unknown Atlas fact: ' + key);
    return start + escapeHtml(data.facts[key]) + '</span>';
  });
  return '<!-- Generated by npm run atlas:build. Edit frontend/atlas and source catalogs. -->\n' + html.trim() + '\n';
}

export function checkAtlas(repoRoot = defaultRoot) {
  const expected = renderAtlas(repoRoot);
  const output = path.join(repoRoot, ATLAS_OUTPUT);
  return fs.existsSync(output) && normalize(fs.readFileSync(output, 'utf8')) === expected;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== '--check')) throw new Error('Usage: node scripts/build-atlas.mjs [--check]');
  if (args.includes('--check')) {
    if (!checkAtlas()) {
      console.error('Atlas generated output is stale. Run npm run atlas:build and review the diff.');
      process.exitCode = 1;
    } else console.log('Atlas source/catalog/output agreement: PASS');
  } else {
    fs.writeFileSync(path.join(defaultRoot, ATLAS_OUTPUT), renderAtlas(defaultRoot), 'utf8');
    console.log('Generated ' + ATLAS_OUTPUT);
  }
}
