import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { census, comparison, hasUseClientDirective, MEASUREMENT_VERSION } from './code-census.mjs';

test('only the initial directive prologue marks a client file', () => {
  for (const source of [
    "'use client'; export const view = 1;",
    '\uFEFF/* heading */ "use client"\nexport const view = 1;',
    "'use strict'; // compatibility\n'use client';",
    "'use client' /* comment\n*/ export const view = 1;",
    "'use client'\n!function(){}();",
    "'use client'\n++count;",
    "'use client'\n--count;",
    "'legacy\\x20directive'; 'use client';",
  ]) assert.equal(hasUseClientDirective(source), true, source);
  for (const source of [
    '// \'use client\'\nexport const view = 1;',
    '/* "use client" */ export const view = 1;',
    "const note = 'use client';",
    "export {}; 'use client';",
    "'use client' + suffix;",
    "'use client'\n(() => 1)();",
    "'use client'\n['field'];",
    "'use client'\n.includes('client');",
    "'use client'\nin object;",
    "'use\\x20client';",
    "/* unfinished 'use client';",
  ]) assert.equal(hasUseClientDirective(source), false, source);
});

test('production metrics exclude tests and generators while retaining handwritten generated transports', () => {
  const root = mkdtempSync(join(tmpdir(), 'egov-code-census-'));
  const write = (file, source) => {
    const path = join(root, file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, source);
  };
  try {
    write('foundation/src/main/java/Library.java', 'class Library {}\n');
    write('foundation/src/main/java/Permissions.java', 'package nuri.foundation;\n/** Generated by script. */\nclass Permissions {}\n');
    write('foundation/src/test/java/LibraryTest.java', 'class LibraryTest {}\n');
    write('frontend/src/page.tsx', '"use client";\nexport default function Page() {}\n');
    write('frontend/src/lib/api/generated-api-client.ts', 'export const transport = 1;\n');
    write('frontend/src/lib/api/generated-operation.ts', 'export const descriptor = 1;\n');
    write('frontend/src/example.ts', 'export const example = "@generated";\n');
    write('frontend/src/types/generated-screen-registry.ts', '// generated registry\n'.repeat(650));
    write('frontend/src/__tests__/page.test.tsx', "'use client';\n".repeat(650));
    write('frontend/src/mocks/handlers.ts', 'export const handlers = [];\n');
    const current = census(root);
    assert.equal(current.measurementVersion, MEASUREMENT_VERSION);
    assert.equal(current.scale.beMain.files, 1);
    assert.equal(current.scale.beTest.files, 1);
    assert.equal(current.scale.beGenerated.files, 1);
    assert.equal(current.scale.frontend.files, 4);
    assert.equal(current.scale.frontend.loc, 5);
    assert.equal(current.scale.frontend.clientFiles, 1);
    assert.equal(current.scale.frontendTest.files, 2);
    assert.equal(current.scale.frontendGenerated.files, 1);
    assert.equal(current.targets.clientRatio, 40);
    assert.equal(current.targets.oversizedFe, 0);
    assert.deepEqual(current.oversizedFiles, []);
    assert.deepEqual(comparison(current, current), []);
    assert.throws(() => comparison({ ...current, measurementVersion: 1 }, current), /측정 정의/);
    assert.throws(() => comparison({ ...current, definitions: {} }, current), /측정 정의/);
    assert.throws(() => comparison({ ...current, scale: {} }, current), /측정 항목/);
  } finally {
    assert.ok(root.startsWith(join(tmpdir(), 'egov-code-census-')));
    rmSync(root, { recursive: true, force: true });
  }
});

test('empty populations have finite metrics without implying a successful quality gate', () => {
  const root = mkdtempSync(join(tmpdir(), 'egov-code-census-'));
  try {
    const current = census(root);
    assert.equal(current.scale.totalLoc, 0);
    assert.equal(current.targets.clientRatio, 0);
  } finally {
    assert.ok(root.startsWith(join(tmpdir(), 'egov-code-census-')));
    rmSync(root, { recursive: true, force: true });
  }
});
