#!/usr/bin/env bash
#
# Regenerate the e2e ephemeral-DB seed from an OCI dev DB dump.
#
#   Usage: scripts/gen-e2e-seed.sh <path-to-oci-dump.sql>
#   Output: dump/e2e_full_dump.sql   (mounted into the e2e Postgres container's
#           /docker-entrypoint-initdb.d/ by docker-compose.yml)
#
# What it produces, and WHY it is safe to commit:
#   1. Schema  = every non-INSERT statement (CREATE/ALTER/SEQUENCE) — contains no PII.
#   2. Seed    = INSERTs from config/lookup tables that provably contain NO email,
#                phone, or bcrypt hash, PLUS the single `webmaster` test-admin row
#                (a documented test account, user_id/pw = webmaster/1).
#                User / authority / address-book / email / sms / board tables are
#                excluded, and any residual phone-like string is masked.
#   3. A hard PII audit fails the script if any email/phone/extra-user row survives.
#
# Regenerate whenever the OCI dev schema changes: dump the OCI dev DB, then run this.
set -euo pipefail

D="${1:?usage: scripts/gen-e2e-seed.sh <oci-dump.sql>}"
OUT="dump/e2e_full_dump.sql"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
mkdir -p dump

# 1) Schema (PII-free). Strip DB-level FK constraints: the app uses JPA NO_CONSTRAINT
#    and the seed is partial, so FKs would fail on init against excluded referenced rows.
grep -vE '^INSERT INTO' "$D" | grep -vE 'ADD CONSTRAINT .* FOREIGN KEY' > "$T/schema.sql"

# 2) Whitelist config tables that have zero email/phone/bcrypt anywhere; then drop
#    any user/authority/address-book/log table by name as an extra guard.
grep -oE '^INSERT INTO [a-z_]+' "$D" | awk '{print $3}' | sort -u | while read -r t; do
  if grep -E "^INSERT INTO $t " "$D" | grep -qE '@[a-zA-Z0-9.-]+\.[a-z]{2,}|01[0-9]-?[0-9]{3,4}-?[0-9]{4}|\$2[aby]\$'; then :; else echo "$t"; fi
done | grep -vE 'user|authrt|nemplyr|mber|adbk|role|absnc|log' > "$T/tables.txt"
sed 's|^|^INSERT INTO |; s|$| |' "$T/tables.txt" > "$T/pat.txt"

# 3) Seed = clean config data + the single webmaster row; mask any residual phone
grep -E '^INSERT INTO' "$D" | grep -Ef "$T/pat.txt" > "$T/seed.sql"
grep -E "^INSERT INTO tb_user_info " "$D" | grep -E "VALUES \('[^']*', 'webmaster'," >> "$T/seed.sql"
sed -i -E 's/01[0-9]-?[0-9]{3,4}-?[0-9]{4}/010-0000-0000/g' "$T/seed.sql"

# 4) Assemble
{
  echo "-- e2e ephemeral DB seed (PostgreSQL). Schema + PII-scrubbed config seed + 'webmaster' test admin."
  echo "-- Generated by scripts/gen-e2e-seed.sh. NO real-user PII. Mounted at /docker-entrypoint-initdb.d/."
  echo ""
  cat "$T/schema.sql"
  echo ""
  echo "-- ===== seed data (config + webmaster admin) ====="
  cat "$T/seed.sql"
} > "$OUT"

# 5) Hard PII audit — refuse to produce a leaky seed
E=$(grep -cE '@[a-z0-9.-]+\.[a-z]{2,}' "$OUT" || true)
P=$(grep -cE '01[1-9]-?[0-9]{3,4}-?[0-9]{4}' "$OUT" || true)
U=$(grep -cE '^INSERT INTO tb_user_info ' "$OUT" || true)
echo "PII audit -> emails=$E phones=$P user_rows=$U (expected 0 / 0 / 1)"
if [ "$E" != "0" ] || [ "$P" != "0" ] || [ "$U" != "1" ]; then
  echo "!! PII AUDIT FAILED — not committing $OUT" >&2
  exit 1
fi
echo "OK: wrote $OUT ($(grep -cE '^CREATE TABLE' "$OUT") tables, $(grep -cE '^INSERT INTO' "$OUT") rows)"
