DROP TABLE IDS CASCADE CONSTRAINTS;
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE CCMMNCLCODE CASCADE CONSTRAINTS;
CREATE TABLE CCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar2(60) ,
  CL_CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT CCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;
DROP TABLE CCMMNCODE CASCADE CONSTRAINTS;
CREATE TABLE CCMMNCODE (
  CODE_ID varchar2(6) NOT NULL,
  CODE_ID_NM varchar2(60) ,
  CODE_ID_DC varchar2(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT CCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT CCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES CCMMNCLCODE (CL_CODE)
) ;
DROP TABLE CCMMNDETAILCODE CASCADE CONSTRAINTS;
CREATE TABLE CCMMNDETAILCODE (
  CODE_ID varchar2(6) NOT NULL,
  CODE varchar2(15) NOT NULL,
  CODE_NM varchar2(60) ,
  CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT CCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT CCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES CCMMNCODE (CODE_ID)
) ;
DROP TABLE NORGNZTINFO CASCADE CONSTRAINTS;
CREATE TABLE NORGNZTINFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar2(20) NOT NULL,
  ORGNZT_DC varchar2(100) ,
  CONSTRAINT NORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
DROP TABLE NAUTHORGROUPINFO CASCADE CONSTRAINTS;
CREATE TABLE NAUTHORGROUPINFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar2(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar2(100) ,
  CONSTRAINT NAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;
DROP TABLE NAUTHORINFO CASCADE CONSTRAINTS;
CREATE TABLE NAUTHORINFO (
  AUTHOR_CODE varchar2(30) DEFAULT '' NOT NULL,
  AUTHOR_NM varchar2(60) NOT NULL,
  AUTHOR_DC varchar2(200) ,
  AUTHOR_CREAT_DE char(20) NOT NULL,
  CONSTRAINT NAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;
DROP TABLE NROLES_HIERARCHY CASCADE CONSTRAINTS;
CREATE TABLE NROLES_HIERARCHY (
  PARNTS_ROLE varchar2(30) NOT NULL,
  CHLDRN_ROLE varchar2(30) NOT NULL,
  CONSTRAINT NROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT NROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT NROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE NROLEINFO CASCADE CONSTRAINTS;
CREATE TABLE NROLEINFO (
  ROLE_CODE varchar2(50) DEFAULT '' NOT NULL,
  ROLE_NM varchar2(60) NOT NULL,
  ROLE_PTTRN varchar2(300) ,
  ROLE_DC varchar2(200) ,
  ROLE_TY varchar2(80) ,
  ROLE_SORT varchar2(10) ,
  ROLE_CREAT_DE char(20) NOT NULL,
  CONSTRAINT NROLEINFO_PK PRIMARY KEY (ROLE_CODE)
) ;
DROP TABLE NAUTHORROLERELATE CASCADE CONSTRAINTS;
CREATE TABLE NAUTHORROLERELATE (
  AUTHOR_CODE varchar2(30) NOT NULL,
  ROLE_CODE varchar2(50) NOT NULL,
  CREAT_DT DATE ,
  CONSTRAINT NAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT NAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES NROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT NAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE NEMPLYRINFO CASCADE CONSTRAINTS;
CREATE TABLE NEMPLYRINFO (
  EMPLYR_ID varchar2(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar2(60) NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  EMPL_NO varchar2(20) ,
  IHIDNUM varchar2(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar2(20) ,
  HOUSE_ADRES varchar2(100) ,
  PASSWORD_HINT varchar2(100) NOT NULL,
  PASSWORD_CNSR varchar2(100) NOT NULL,
  HOUSE_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  DETAIL_ADRES varchar2(100) ,
  ZIP varchar2(6) ,
  OFFM_TELNO varchar2(20) ,
  MBTLNUM varchar2(20) ,
  EMAIL_ADRES varchar2(50) ,
  OFCPS_NM varchar2(60) ,
  HOUSE_MIDDLE_TELNO varchar2(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar2(20) ,
  SBSCRB_DE DATE ,
  CONSTRAINT NEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT NEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT NEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES NORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;
DROP TABLE NEMPLYRSCRTYESTBS CASCADE CONSTRAINTS;
CREATE TABLE NEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar2(20) NOT NULL,
  MBER_TY_CODE varchar2(15) ,
  AUTHOR_CODE varchar2(30) NOT NULL,
  CONSTRAINT NEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT NEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE)
) ;
DROP TABLE NTMPLATINFO CASCADE CONSTRAINTS;
CREATE TABLE NTMPLATINFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar2(255) ,
  TMPLAT_COURS varchar2(2000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT NTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
DROP TABLE NBBSMASTER CASCADE CONSTRAINTS;
CREATE TABLE NBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar2(255) NOT NULL,
  BBS_INTRCN varchar2(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER number(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE number(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT NBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE NBBSUSE CASCADE CONSTRAINTS;
CREATE TABLE NBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT NBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT NBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
) ;
DROP TABLE NBBS CASCADE CONSTRAINTS;
CREATE TABLE NBBS (
  NTT_ID number(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO number(20,0) ,
  NTT_SJ varchar2(2000) ,
  NTT_CN CLOB,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO number(10,0) ,
  ANSWER_LC number(11) ,
  SORT_ORDR number(8,0) ,
  RDCNT number(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar2(20) ,
  NTCR_NM varchar2(20) ,
  PASSWORD varchar2(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT NBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT NBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES NBBSMASTER (BBS_ID)
) ;
DROP TABLE CZIP CASCADE CONSTRAINTS;
CREATE TABLE CZIP (
  ZIP varchar2(6) NOT NULL,
  SN number(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar2(20) ,
  SIGNGU_NM varchar2(20) ,
  EMD_NM varchar2(60) ,
  LI_BULD_NM varchar2(60) ,
  LNBR_DONG_HO varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT CZIP_PK PRIMARY KEY (ZIP,SN)
) ;
DROP TABLE HEMPLYRINFOCHANGEDTLS CASCADE CONSTRAINTS;
CREATE TABLE HEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID varchar2(20) NOT NULL,
  CHANGE_DE char(20) DEFAULT '' NOT NULL,
  ORGNZT_ID char(20) ,
  GROUP_ID char(20) ,
  EMPL_NO varchar2(20) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar2(20) ,
  HOUSE_ADRES varchar2(100),
  HOUSE_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  DETAIL_ADRES varchar2(100),
  ZIP varchar2(6),
  OFFM_TELNO varchar2(20) ,
  MBTLNUM varchar2(20) ,
  EMAIL_ADRES varchar2(50) ,
  HOUSE_MIDDLE_TELNO varchar2(4) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar2(15),
  ESNTL_ID char(20) ,
  CONSTRAINT HEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
) ;
DROP TABLE NBBSMASTEROPTN CASCADE CONSTRAINTS;
CREATE TABLE NBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT NBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE NENTRPRSMBER CASCADE CONSTRAINTS;
CREATE TABLE NENTRPRSMBER (
  ENTRPRS_MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar2(10) ,
  JURIRNO varchar2(13) ,
  CMPNY_NM varchar2(60) NOT NULL,
  CXFC varchar2(50) ,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  ENTRPRS_MIDDLE_TELNO varchar2(4) ,
  FXNUM varchar2(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar2(50) ,
  APPLCNT_IHIDNUM varchar2(200) ,
  SBSCRB_DE DATE ,
  ENTRPRS_MBER_STTUS varchar2(15) ,
  ENTRPRS_MBER_PASSWORD varchar2(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar2(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar2(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar2(100) ,
  ENTRPRS_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  APPLCNT_EMAIL_ADRES varchar2(50) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT NENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT NENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE NFILE CASCADE CONSTRAINTS;
CREATE TABLE NFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT NFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
DROP TABLE NFILEDETAIL CASCADE CONSTRAINTS;
CREATE TABLE NFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN number(10,0) NOT NULL,
  FILE_STRE_COURS varchar2(2000) NOT NULL,
  STRE_FILE_NM varchar2(255) NOT NULL,
  ORIGNL_FILE_NM varchar2(255) ,
  FILE_EXTSN varchar2(20) NOT NULL,
  FILE_CN CLOB,
  FILE_SIZE number(8,0) ,
  CONSTRAINT NFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT NFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES NFILE (ATCH_FILE_ID)
) ;
DROP TABLE NGNRLMBER CASCADE CONSTRAINTS;
CREATE TABLE NGNRLMBER (
  MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  PASSWORD_HINT varchar2(100) ,
  PASSWORD_CNSR varchar2(100) ,
  IHIDNUM varchar2(200) ,
  MBER_NM varchar2(50) NOT NULL,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  AREA_NO varchar2(4) ,
  MBER_STTUS varchar2(15) ,
  DETAIL_ADRES varchar2(100) ,
  END_TELNO varchar2(4) ,
  MBTLNUM varchar2(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar2(20) ,
  MBER_EMAIL_ADRES varchar2(50) ,
  MIDDLE_TELNO varchar2(4) ,
  SBSCRB_DE DATE ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT NGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT NGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES NAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE NLOGINLOG CASCADE CONSTRAINTS;
CREATE TABLE NLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar2(20) ,
  CONECT_IP varchar2(23) ,
  CONECT_MTHD char(4) ,
  ERROR_OCCRRNC_AT char(1) ,
  ERROR_CODE char(3) ,
  CREAT_DT DATE ,
  CONSTRAINT NLOGINLOG_PK PRIMARY KEY (LOG_ID)
) ;
DROP TABLE NLOGINPOLICY CASCADE CONSTRAINTS;
CREATE TABLE NLOGINPOLICY (
  EMPLYR_ID varchar2(20) DEFAULT '' NOT NULL,
  IP_INFO varchar2(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT NLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID)
) ;
DROP TABLE NPROGRMLIST CASCADE CONSTRAINTS;
CREATE TABLE NPROGRMLIST (
  PROGRM_FILE_NM varchar2(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar2(100) NOT NULL,
  PROGRM_KOREAN_NM varchar2(60) ,
  PROGRM_DC varchar2(200) ,
  URL varchar2(100) NOT NULL,
  CONSTRAINT NPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;
DROP TABLE NMENUINFO CASCADE CONSTRAINTS;
CREATE TABLE NMENUINFO (
  MENU_NM varchar2(60) NOT NULL,
  PROGRM_FILE_NM varchar2(60) NOT NULL,
  MENU_NO number(20,0) NOT NULL,
  UPPER_MENU_NO number(20,0) ,
  MENU_ORDR number(5,0) NOT NULL,
  MENU_DC varchar2(250) ,
  RELATE_IMAGE_PATH varchar2(100) ,
  RELATE_IMAGE_NM varchar2(60) ,
  CONSTRAINT NMENUINFO_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT NMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES NMENUINFO (MENU_NO),
  CONSTRAINT NMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES NPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;
DROP TABLE NMENUCREATDTLS CASCADE CONSTRAINTS;
CREATE TABLE NMENUCREATDTLS (
  MENU_NO number(20,0) NOT NULL,
  AUTHOR_CODE varchar2(30) NOT NULL,
  MAPNG_CREAT_ID varchar2(30) ,
  CONSTRAINT NMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT NMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES NAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT NMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES NMENUINFO (MENU_NO) ON DELETE CASCADE
) ;
DROP TABLE NUSERABSNCE CASCADE CONSTRAINTS;
CREATE TABLE NUSERABSNCE (
  EMPLYR_ID varchar2(20) DEFAULT '' NOT NULL,
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT NUSERABSNCE_PK PRIMARY KEY (EMPLYR_ID)
) ;
DROP TABLE SSYSLOGSUMMARY CASCADE CONSTRAINTS;
CREATE TABLE SSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar2(255) NOT NULL,
  METHOD_NM varchar2(60) NOT NULL,
  CREAT_CO number(10,0) ,
  UPDT_CO number(10,0) ,
  RDCNT number(10,0) ,
  DELETE_CO number(10,0) ,
  OUTPT_CO number(10,0) ,
  ERROR_CO number(10,0) ,
  CONSTRAINT SSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM NGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM NEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM NENTRPRSMBER 
;