#!/usr/bin/env node
/** Rebuild static utilities after HTML/JS class changes; the server needs no frontend packages. */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const directory = dirname(fileURLToPath(import.meta.url));
const tailwind = resolve(directory, '../../frontend/node_modules/tailwindcss');
const { compile } = await import(pathToFileURL(resolve(tailwind, 'dist/lib.mjs')).href);
const input = await readFile(resolve(directory, 'styles.input.css'), 'utf8');
const contents = await Promise.all(['index.html', 'app.js'].map(file => readFile(resolve(directory, 'public', file), 'utf8')));
// Tailwind candidates are tokens, including quoted class lists assembled by the small local UI.
const candidates = [...new Set(contents.flatMap(source => source.split(/[\s"'`<>;=]+/)).filter(Boolean))];
const compiler = await compile(input, { loadStylesheet: async id => {
  if (!['tailwindcss/theme.css', 'tailwindcss/preflight.css'].includes(id)) throw new Error('unsupported stylesheet');
  return { path: id, base: directory, content: await readFile(resolve(tailwind, id.slice('tailwindcss/'.length)), 'utf8') };
} });
const output = `/* Generated by node tools/project-composer/build-styles.mjs. Edit styles.input.css and public HTML/JS. */\n${compiler.build(candidates).trimEnd()}\n`;
const destination = resolve(directory, 'public/styles.css');
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== output) throw new Error('Project composer stylesheet is stale; rebuild with node tools/project-composer/build-styles.mjs');
} else await writeFile(destination, output, 'utf8');
