server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
spring:
  main:
    allow-circular-references: true
    lazy-initialization: false
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/egovdb?currentSchema=public
    jdbc-url: jdbc:postgresql://localhost:5433/egovdb?currentSchema=public
    username: egov
    password: egov123
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5433/egovdb?currentSchema=public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapper/com/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.company.project: debug
    egovframework: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.web.servlet.DispatcherServlet: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
